kmp_flag_32 Class Reference
#include <kmp_wait_release.h>
Public Member Functions
kmp_flag_32 (volatile kmp_uint32 *p)
kmp_flag_32 (volatile kmp_uint32 *p, kmp_info_t *thr)
kmp_flag_32 (volatile kmp_uint32 *p, kmp_uint32 c)
void suspend (int th_gtid)
void resume (int th_gtid)
int execute_tasks (kmp_info_t *this_thr, kmp_int32 gtid, int final_spin, int *thread_finished USE_ITT_BUILD_ARG(void *itt_sync_obj), kmp_int32 is_constrained)
void wait (kmp_info_t *this_thr, int final_spin USE_ITT_BUILD_ARG(void *itt_sync_obj))
void release ()
flag_type get_ptr_type ()
Additional Inherited Members
Detailed Description
Definition at line 425 of file kmp_wait_release.h.
Constructor & Destructor Documentation
kmp_flag_32::kmp_flag_32 (volatile kmp_uint32 * p) [inline]
Definition at line 427 of file kmp_wait_release.h.
: kmp_basic_flag<kmp_uint32>(p) {}
kmp_flag_32::kmp_flag_32 (volatile kmp_uint32 * p, kmp_info_t * thr) [inline]
Definition at line 428 of file kmp_wait_release.h.
: kmp_basic_flag<kmp_uint32>(p, thr) {}
kmp_flag_32::kmp_flag_32 (volatile kmp_uint32 * p, kmp_uint32 c) [inline]
Definition at line 429 of file kmp_wait_release.h.
: kmp_basic_flag<kmp_uint32>(p, c) {}
Member Function Documentation
int kmp_flag_32::execute_tasks (kmp_info_t * this_thr, kmp_int32 gtid, int final_spin, int *thread_finished USE_ITT_BUILD_ARGvoid *itt_sync_obj, kmp_int32 is_constrained) [inline]
Definition at line 432 of file kmp_wait_release.h.
Referenced by __kmp_tasking_barrier(), __kmpc_end_taskgroup(), __kmpc_omp_taskwait(), and __kmpc_omp_wait_deps().
                                                                                        {
        return __kmp_execute_tasks_32(this_thr, gtid, this, final_spin,
      thread_finished
                                      USE_ITT_BUILD_ARG(itt_sync_obj), is_constrained);
    }
flag_type kmp_flag_32::get_ptr_type () [inline]
Definition at line 443 of file kmp_wait_release.h.
{ return flag32; }
void kmp_flag_32::release () [inline]
Definition at line 442 of file kmp_wait_release.h.
{ __kmp_release_template(this); }
void kmp_flag_32::resume (int th_gtid) [inline]
Definition at line 431 of file kmp_wait_release.h.
{ __kmp_resume_32(th_gtid, this); }
void kmp_flag_32::suspend (int th_gtid) [inline]
Definition at line 430 of file kmp_wait_release.h.
{ __kmp_suspend_32(th_gtid, this); }
void kmp_flag_32::wait (kmp_info_t * this_thr, int final_spin USE_ITT_BUILD_ARGvoid *itt_sync_obj) [inline]
Definition at line 437 of file kmp_wait_release.h.
Referenced by __kmp_task_team_wait().
                                                      {
        __kmp_wait_template(this_thr, this, final_spin
                            USE_ITT_BUILD_ARG(itt_sync_obj));
    }
The documentation for this class was generated from the following file:
kmp_wait_release.h