StringTable Class Reference
Public Member Functions
StringTable (rstream &f)
StringTable (const set< string > &strings)
~StringTable ()
__int64 encode (const string &str)
string decode (__int64 x) const
void write (ostream &os)
Private Member Functions
void makeDirectory (void)
void init (const char *_data)
Private Attributes
map< string, unsigned > directory
size_t length
char * data
Detailed Description
Definition at line 113 of file extractExternal.cpp.
Constructor & Destructor Documentation
StringTable::StringTable (rstream & f) [inline]
Definition at line 147 of file extractExternal.cpp.
                            {
        /* Construct string table by reading from f.
         */
        streampos s;
        unsigned strSize;
        char *strData;
        s = f.tellg();
        f>>strSize;
        if(strSize < sizeof(unsigned))
            stop("StringTable: Invalid string table");
        strData = new char[strSize];
        *(unsigned*)strData = strSize;
        // read the raw data into <strData>
        f.read(strData + sizeof(unsigned), strSize - sizeof(unsigned));
        s = f.tellg() - s;
        if(s < strSize)
            stop("StringTable: Unexpected EOF");
        init(strData);
        delete[]strData;
    }
StringTable::StringTable (const set< string > & strings) [inline]
Definition at line 168 of file extractExternal.cpp.
                                            {
        /* Construct string table from given strings.
         */
        char *p;
        set<string>::const_iterator it;
        size_t s;
        // count required size for data
        for(length = sizeof(unsigned), it = strings.begin(); it != strings.end(); ++it) {
            size_t l = (*it).size();
            if(l > (unsigned) 0xFFFFFFFF)
                stop("StringTable: String too long");
            if(l > 8) {
                length += l + 1;
                if(length > (unsigned) 0xFFFFFFFF)
                    stop("StringTable: Symbol table too long");
            }
        }
        data = new char[length];
        *(unsigned*)data = length;
        // populate data and directory
        for(p = data + sizeof(unsigned), it = strings.begin(); it != strings.end(); ++it) {
            const string &str = *it;
            size_t l = str.size();
            if(l > 8) {
                directory.insert(make_pair(str, p - data));
                KMP_MEMCPY(p, str.c_str(), l);
                p[l] = 0;
                p += l + 1;
            }
        }
    }
StringTable::~StringTable () [inline]
Definition at line 201 of file extractExternal.cpp.
                   {
        delete[] data;
    }
Member Function Documentation
string StringTable::decode (__int64 x) const [inline]
Definition at line 230 of file extractExternal.cpp.
Referenced by computeExternalSymbols(), and hideSymbols().
                                   {
        if(*(unsigned*)&x == 0) {
            // represented as index into table
            unsigned &p = ((unsigned*)&x)[1];
            if(p >= length)
                stop("StringTable::decode: Invalid string table lookup");
            return string(data + p);
        } else {
            // encoded directly
            char *p = (char*)&x;
            int i;
            for(i = 0; i < 8 && p[i]; ++i);
            return string(p, i);
        }
    }
__int64 StringTable::encode (const string & str) [inline]
Definition at line 208 of file extractExternal.cpp.
Referenced by hideSymbols().
                                      {
        __int64 r;
        if(str.size() <= 8) {
            // encoded directly
            ((char*)&r)[7] = 0;
            KMP_STRNCPY_S((char*)&r, sizeof(r), str.c_str(), 8);
            return r;
        } else {
            // represented as index into table
            map<string,unsigned>::const_iterator it = directory.find(
      str);
            if(it == directory.end())
                stop("StringTable::encode: String now found in string table");
            ((unsigned*)&r)[0] = 0;
            ((unsigned*)&r)[1] = (*it).second;
            return r;
        }
    }
void StringTable::init (const char * _data) [inline], [private]
Definition at line 129 of file extractExternal.cpp.
                                 {
        unsigned _length = *(unsigned*)_data;
        if(_length < sizeof(unsigned) || _length != *(unsigned*)_data)
            stop("StringTable.init: Invalid symbol table");
        if(_data[_length - 1]) {
            // to prevent runaway strings, make sure the data ends with a zero
            data = new char[length = _length + 1];
            data[_length] = 0;
        } else {
            data = new char[length = _length];
        }
        *(unsigned*)data = length;
        KMP_MEMCPY(data + sizeof(unsigned), _data + sizeof(unsigned),
                   length - sizeof(unsigned));
        makeDirectory();
    }
void StringTable::makeDirectory (void) [inline], [private]
Definition at line 120 of file extractExternal.cpp.
                             {
        unsigned i = 4;
        while(i < length) {
            string s = string(data + i);
            directory.insert(make_pair(s, i));
            i += s.size() + 1;
        }
    }
void StringTable::write (ostream & os) [inline]
Definition at line 246 of file extractExternal.cpp.
Referenced by hideSymbols().
                            {
        os.write(data, length);
    }
Member Data Documentation
char* StringTable::data [private]
Definition at line 117 of file extractExternal.cpp.
map<string, unsigned> StringTable::directory [private]
Definition at line 115 of file extractExternal.cpp.
size_t StringTable::length [private]
Definition at line 116 of file extractExternal.cpp.
The documentation for this class was generated from the following file:
extractExternal.cpp