kmp_stats_event Class Reference
#include <kmp_stats.h>
Public Member Functions
kmp_stats_event ()
kmp_stats_event (uint64_t strt, uint64_t stp, int nst, timer_e nme)
uint64_t getStart () const
uint64_t getStop () const
int getNestLevel () const
timer_e getTimerName () const
Private Attributes
uint64_t start
uint64_t stop
int nest_level
timer_e timer_name
Detailed Description
Definition at line 367 of file kmp_stats.h.
Constructor & Destructor Documentation
kmp_stats_event::kmp_stats_event () [inline]
Definition at line 373 of file kmp_stats.h.
: start(0), stop(0), nest_level(0), timer_name(TIMER_LAST) {}
kmp_stats_event::kmp_stats_event (uint64_t strt, uint64_t stp, int nst, timer_e nme) [inline]
Definition at line 374 of file kmp_stats.h.
: start(strt), stop(stp), nest_level(nst), timer_name(nme) {}
Member Function Documentation
int kmp_stats_event::getNestLevel () const [inline]
Definition at line 377 of file kmp_stats.h.
Referenced by kmp_stats_output_module::printEvents().
{ return nest_level; }
uint64_t kmp_stats_event::getStart () const [inline]
Definition at line 375 of file kmp_stats.h.
Referenced by compare_two_events(), and kmp_stats_output_module::printEvents().
{ return start; }
uint64_t kmp_stats_event::getStop () const [inline]
Definition at line 376 of file kmp_stats.h.
Referenced by kmp_stats_output_module::printEvents().
{ return stop; }
timer_e kmp_stats_event::getTimerName () const [inline]
Definition at line 378 of file kmp_stats.h.
Referenced by kmp_stats_output_module::printEvents().
{ return timer_name; }
Member Data Documentation
int kmp_stats_event::nest_level [private]
Definition at line 370 of file kmp_stats.h.
Referenced by getNestLevel().
uint64_t kmp_stats_event::start [private]
Definition at line 368 of file kmp_stats.h.
Referenced by getStart().
uint64_t kmp_stats_event::stop [private]
Definition at line 369 of file kmp_stats.h.
Referenced by getStop().
timer_e kmp_stats_event::timer_name [private]
Definition at line 371 of file kmp_stats.h.
Referenced by getTimerName().
The documentation for this class was generated from the following file:
kmp_stats.h