kmp_flag_64 Class Reference
#include <kmp_wait_release.h>
Public Member Functions
kmp_flag_64 (volatile kmp_uint64 *p)
kmp_flag_64 (volatile kmp_uint64 *p, kmp_info_t *thr)
kmp_flag_64 (volatile kmp_uint64 *p, kmp_uint64 c)
void suspend (int th_gtid)
void resume (int th_gtid)
int execute_tasks (kmp_info_t *this_thr, kmp_int32 gtid, int final_spin, int *thread_finished USE_ITT_BUILD_ARG(void *itt_sync_obj), kmp_int32 is_constrained)
void wait (kmp_info_t *this_thr, int final_spin USE_ITT_BUILD_ARG(void *itt_sync_obj))
void release ()
flag_type get_ptr_type ()
Additional Inherited Members
Detailed Description
Definition at line 446 of file kmp_wait_release.h.
Constructor & Destructor Documentation
kmp_flag_64::kmp_flag_64 (volatile kmp_uint64 * p) [inline]
Definition at line 448 of file kmp_wait_release.h.
: kmp_basic_flag<kmp_uint64>(p) {}
kmp_flag_64::kmp_flag_64 (volatile kmp_uint64 * p, kmp_info_t * thr) [inline]
Definition at line 449 of file kmp_wait_release.h.
: kmp_basic_flag<kmp_uint64>(p, thr) {}
kmp_flag_64::kmp_flag_64 (volatile kmp_uint64 * p, kmp_uint64 c) [inline]
Definition at line 450 of file kmp_wait_release.h.
: kmp_basic_flag<kmp_uint64>(p, c) {}
Member Function Documentation
int kmp_flag_64::execute_tasks (kmp_info_t * this_thr, kmp_int32 gtid, int final_spin, int *thread_finished USE_ITT_BUILD_ARGvoid *itt_sync_obj, kmp_int32 is_constrained) [inline]
Definition at line 453 of file kmp_wait_release.h.
                                                                                        {
        return __kmp_execute_tasks_64(this_thr, gtid, this, final_spin,
      thread_finished
                                      USE_ITT_BUILD_ARG(itt_sync_obj), is_constrained);
    }
flag_type kmp_flag_64::get_ptr_type () [inline]
Definition at line 464 of file kmp_wait_release.h.
{ return flag64; }
void kmp_flag_64::release () [inline]
Definition at line 463 of file kmp_wait_release.h.
Referenced by __kmp_hierarchical_barrier_gather(), __kmp_hierarchical_barrier_release(), __kmp_hyper_barrier_gather(), __kmp_hyper_barrier_release(), __kmp_linear_barrier_gather(), __kmp_linear_barrier_release(), __kmp_tree_barrier_gather(), and __kmp_tree_barrier_release().
{ __kmp_release_template(this); }
void kmp_flag_64::resume (int th_gtid) [inline]
Definition at line 452 of file kmp_wait_release.h.
{ __kmp_resume_64(th_gtid, this); }
void kmp_flag_64::suspend (int th_gtid) [inline]
Definition at line 451 of file kmp_wait_release.h.
{ __kmp_suspend_64(th_gtid, this); }
void kmp_flag_64::wait (kmp_info_t * this_thr, int final_spin USE_ITT_BUILD_ARGvoid *itt_sync_obj) [inline]
Definition at line 458 of file kmp_wait_release.h.
Referenced by __kmp_hierarchical_barrier_gather(), __kmp_hierarchical_barrier_release(), __kmp_hyper_barrier_gather(), __kmp_hyper_barrier_release(), __kmp_linear_barrier_gather(), __kmp_linear_barrier_release(), __kmp_tree_barrier_gather(), and __kmp_tree_barrier_release().
                                                      {
        __kmp_wait_template(this_thr, this, final_spin
                            USE_ITT_BUILD_ARG(itt_sync_obj));
    }
The documentation for this class was generated from the following file:
kmp_wait_release.h