extractExternal.cpp File Reference
#include <stdlib.h>
*
#include <iostream>
*
#include <strstream>
*
#include <fstream>
*
#include <string>
*
#include <set>
*
#include <map>
*
Classes
class Symbol
class _rstream
class rstream
class StringTable
Functions
void stop (char *errorMsg)
void computeExternalSymbols (const char *fileName, set< string > *defined, set< string > *undefined)
void hideSymbols (char *fileName, const set< string > &hide)
template<class T >
bool isDisjoint (const set< T > &a, const set< T > &b)
set< int > * findRequiredExternal (int nExternal, int nTotal, set< string > *defined, set< string > *undefined)
int main (int argc, char **argv)
Function Documentation
void computeExternalSymbols (const char * fileName, set< string > * defined, set< string > * undefined)
Definition at line 254 of file extractExternal.cpp.
Referenced by main().
                                                                                               {
    streampos fileSize;
    size_t strTabStart;
    unsigned symTabStart, symNEntries;
    rstream f(fileName);
    f.seekg(0,ios::end);
    fileSize = f.tellg();
    f.seekg(8);
    f >> symTabStart >> symNEntries;
    // seek to the string table
    f.seekg(strTabStart = symTabStart + 18 * (size_t)symNEntries);
    if(f.eof()) {
        printf("computeExternalSymbols: fileName='%s', fileSize = %lu, symTabStart = %u, symNEntries = %u\n
      ",
               fileName, (unsigned long) fileSize, symTabStart, symNEntries);
        stop("computeExternalSymbols: Unexpected EOF 1");
    }
    StringTable stringTable(f); // read the string table
    if(f.tellg() != fileSize)
        stop("computeExternalSymbols: Unexpected data after string table");
    f.clear();
    f.seekg(symTabStart); // seek to the symbol table
    defined->clear(); undefined->clear();
    for(int i = 0; i < symNEntries; ++i) {
        // process each entry
        Symbol e;
        if(f.eof())
            stop("computeExternalSymbols: Unexpected EOF 2");
        f>>e;
        if(f.fail())
            stop("computeExternalSymbols: File read error");
        if(e.nAux) { // auxiliary entry: skip
            f.seekg(e.nAux * 18, ios::cur);
            i += e.nAux;
        }
        // if symbol is extern and defined in the current file, insert it
        if(e.storageClass == 2)
            if(e.sectionNum)
                defined->insert(stringTable.decode(e.name));
            else
                undefined->insert(stringTable.decode(e.name));
    }
}
set<int>* findRequiredExternal (int nExternal, int nTotal, set< string > * defined, set< string > * undefined)
Definition at line 417 of file extractExternal.cpp.
Referenced by main().
                                                                                                        {
    set<int> *required = new set<int>;
    set<int> fresh[2];
    int i, cur = 0;
    bool changed;
    for(i = nTotal - 1; i >= nExternal; --i)
        fresh[cur].insert(i);
    do {
        changed = false;
        for(set<int>::iterator it = fresh[cur].begin(); it != fresh[cur].end(); ++it) {
            set<string> &s = undefined[*it];
            for(i = 0; i < nExternal; ++i) {
                if(required->find(i) == required->end()) {
                    if(!isDisjoint(defined[i], s)) {
                        // found a new qualifying element
                        required->insert(i);
                        fresh[1 - cur].insert(i);
                        changed = true;
                    }
                }
            }
        }
        fresh[cur].clear();
        cur = 1 - cur;
    } while(changed);
    return required;
}
void hideSymbols (char * fileName, const set< string > & hide)
Definition at line 306 of file extractExternal.cpp.
Referenced by main().
                                                          {
    static const string prefix("__kmp_external_");
    set<string> strings; // set of all occurring symbols, appropriately prefixed
    streampos fileSize;
    size_t strTabStart;
    unsigned symTabStart, symNEntries;
    int i;
    rstream in(fileName);
    in.seekg(0,ios::end);
    fileSize = in.tellg();
    in.seekg(8);
    in >> symTabStart >> symNEntries;
    in.seekg(strTabStart = symTabStart + 18 * (size_t)symNEntries);
    if(in.eof())
        stop("hideSymbols: Unexpected EOF");
    StringTable stringTableOld(in); // read original string table
    if(in.tellg() != fileSize)
        stop("hideSymbols: Unexpected data after string table");
    // compute set of occurring strings with prefix added
    for(i = 0; i < symNEntries; ++i) {
        Symbol e;
        in.seekg(symTabStart + i * 18);
        if(in.eof())
            stop("hideSymbols: Unexpected EOF");
        in >> e;
        if(in.fail())
            stop("hideSymbols: File read error");
        if(e.nAux)
            i += e.nAux;
        const string &s = stringTableOld.decode(e.name);
        // if symbol is extern and found in <hide>, prefix and insert into strings,
        // otherwise, just insert into strings without prefix
        strings.insert((e.storageClass == 2 && hide.find(s) != hide.end()) ?
                        prefix + s : s);
    }
    ofstream out(fileName, ios::trunc | ios::out | ios::binary);
    if(!out.is_open())
        stop("hideSymbols: Error opening output file");
    // make new string table from string set
    StringTable stringTableNew = StringTable(strings);
    // copy input file to output file up to just before the symbol table
    in.seekg(0);
    char *buf = new char[symTabStart];
    in.read(buf, symTabStart);
    out.write(buf, symTabStart);
    delete []buf;
    // copy input symbol table to output symbol table with name translation
    for(i = 0; i < symNEntries; ++i) {
        Symbol e;
        in.seekg(symTabStart + i*18);
        if(in.eof())
            stop("hideSymbols: Unexpected EOF");
        in >> e;
        if(in.fail())
            stop("hideSymbols: File read error");
        const string &s = stringTableOld.decode(e.name);
        out.seekp(symTabStart + i*18);
        e.name = stringTableNew.encode((e.storageClass == 2 && hide.find(s) != hide.end()) ?
                                        prefix + s : s);
        out.write((char*)&e, 18);
        if(out.fail())
            stop("hideSymbols: File write error");
        if(e.nAux) {
            // copy auxiliary symbol table entries
            int nAux = e.nAux;
            for(int j = 1; j <= nAux; ++j) {
                in >> e;
                out.seekp(symTabStart + (i + j) * 18);
                out.write((char*)&e, 18);
            }
            i += nAux;
        }
    }
    // output string table
    stringTableNew.write(out);
}
template<class T > bool isDisjoint (const set< T > & a, const set< T > & b)
Definition at line 395 of file extractExternal.cpp.
Referenced by findRequiredExternal().
                                                  {
    set<T>::const_iterator ita, itb;
    for(ita = a.begin(), itb = b.begin(); ita != a.end() && itb != b.end();) {
        const T &ta = *ita, &tb = *itb;
        if(ta < tb)
            ++ita;
        else if (tb < ta)
            ++itb;
        else
            return false;
    }
    return true;
}
int main (int argc, char ** argv)
Definition at line 447 of file extractExternal.cpp.
                                {
    int nExternal, nInternal, i;
    set<string> *defined, *undefined;
    set<int>::iterator it;
    if(argc < 3)
        stop("Please specify a positive integer followed by a list of object filenames");
    nExternal = atoi(argv[1]);
    if(nExternal <= 0)
        stop("Please specify a positive integer followed by a list of object filenames");
    if(nExternal + 2 > argc)
        stop("Too few external objects");
    nInternal = argc - nExternal - 2;
    defined = new set<string>[argc - 2];
    undefined = new set<string>[argc - 2];
    // determine the set of defined and undefined external symbols
    for(i = 2; i < argc; ++i)
        computeExternalSymbols(argv[i], defined + i - 2, undefined + i - 2);
    // determine the set of required external files
    set<int> *requiredExternal = findRequiredExternal(nExternal, argc - 2, defined,
      undefined);
    set<string> hide;
    /* determine the set of symbols to hide--namely defined external symbols of the
       required external files
    */
    for(it = requiredExternal->begin(); it != requiredExternal->end(); ++it) {
        int idx = *it;
        set<string>::iterator it2;
        /* We have to insert one element at a time instead of inserting a range because
           the insert member function taking a range doesn't exist on Windows* OS, at least
           at the time of this writing.
        */
        for(it2 = defined[idx].begin(); it2 != defined[idx].end(); ++it2)
            hide.insert(*it2);
    }
    /* process the external files--removing those that are not required and hiding
       the appropriate symbols in the others
    */
    for(i = 0; i < nExternal; ++i)
        if(requiredExternal->find(i) != requiredExternal->end())
            hideSymbols(argv[2 + i], hide);
        else
            remove(argv[2 + i]);
    // hide the appropriate symbols in the internal files
    for(i = nExternal + 2; i < argc; ++i)
        hideSymbols(argv[i], hide);
    return 0;
}
void stop (char * errorMsg)
Definition at line 39 of file extractExternal.cpp.
Referenced by computeExternalSymbols(), StringTable::decode(), StringTable::encode(), rstream::getBuf(), hideSymbols(), StringTable::init(), main(), and StringTable::StringTable().
                          {
    printf("%s\n", errorMsg);
    exit(1);
}