Synchronization
Functions
void __kmpc_flush (ident_t *loc)
void __kmpc_barrier (ident_t *loc, kmp_int32 global_tid)
kmp_int32 __kmpc_barrier_master (ident_t *loc, kmp_int32 global_tid)
void __kmpc_end_barrier_master (ident_t *loc, kmp_int32 global_tid)
kmp_int32 __kmpc_barrier_master_nowait (ident_t *loc, kmp_int32 global_tid)
kmp_int32 __kmpc_reduce_nowait (ident_t *loc, kmp_int32 global_tid, kmp_int32 num_vars, size_t reduce_size, void *reduce_data, void(*reduce_func)(void *lhs_data, void *rhs_data), kmp_critical_name *lck)
void __kmpc_end_reduce_nowait (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *lck)
kmp_int32 __kmpc_reduce (ident_t *loc, kmp_int32 global_tid, kmp_int32 num_vars, size_t reduce_size, void *reduce_data, void(*reduce_func)(void *lhs_data, void *rhs_data), kmp_critical_name *lck)
void __kmpc_end_reduce (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *lck)
Detailed Description
These functions are used for implementing barriers.
Function Documentation
void __kmpc_barrier (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information
global_tid thread id.
Execute a barrier.
Definition at line 697 of file kmp_csupport.c.
Referenced by __kmpc_cancel_barrier(), and KMP_API_NAME_GOMP_BARRIER().
{
    KMP_COUNT_BLOCK(OMP_BARRIER);
    KMP_TIME_BLOCK(OMP_barrier);
    KC_TRACE(10, ("__kmpc_barrier: called T#%d\n", global_tid));
    if (! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
    if (__kmp_env_consistency_check) {
        if (loc == 0) {
            KMP_WARNING(ConstructIdentInvalid); // ??? What does it mean for the user?
        }; // if
        __kmp_check_barrier(global_tid, ct_barrier, loc);
    }
    __kmp_threads[ global_tid ]->th.th_ident = loc;
    // TODO: explicit barrier_wait_id:
    // this function is called when 'barrier' directive is present or
    // implicit barrier at the end of a worksharing construct.
    // 1) better to add a per-thread barrier counter to a thread data structure
    // 2) set to 0 when a new team is created
    // 4) no sync is required
    __kmp_barrier(bs_plain_barrier, global_tid,
      FALSE, 0, NULL, NULL);
}
kmp_int32 __kmpc_barrier_master (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information
global_tid thread id.
Returns
one if the thread should execute the master block, zero otherwise
Start execution of a combined barrier and master. The barrier is executed inside this function.
Definition at line 1377 of file kmp_csupport.c.
{
    int status;
    KC_TRACE(10, ("__kmpc_barrier_master: called T#%d\n", global_tid));
    if (! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
    if (__kmp_env_consistency_check)
        __kmp_check_barrier(global_tid, ct_barrier, loc);
#if USE_ITT_NOTIFY
    __kmp_threads[global_tid]->th.th_ident = loc;
#endif
    status = __kmp_barrier(bs_plain_barrier, global_tid,
      TRUE, 0, NULL, NULL);
    return (status != 0) ? 0 : 1;
}
kmp_int32 __kmpc_barrier_master_nowait (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information
global_tid thread id.
Returns
one if the thread should execute the master block, zero otherwise
Start execution of a combined barrier and master(nowait) construct. The barrier is executed inside this function. There is no equivalent `end` function, since the
Definition at line 1425 of file kmp_csupport.c.
{
    kmp_int32 ret;
    KC_TRACE(10, ("__kmpc_barrier_master_nowait: called T#%d\n", global_tid));
    if (! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
    if (__kmp_env_consistency_check) {
        if (loc == 0) {
            KMP_WARNING(ConstructIdentInvalid); // ??? What does it mean for the user?
        }
        __kmp_check_barrier(global_tid, ct_barrier, loc);
    }
#if USE_ITT_NOTIFY
    __kmp_threads[global_tid]->th.th_ident = loc;
#endif
    __kmp_barrier(bs_plain_barrier, global_tid,
      FALSE, 0, NULL, NULL);
    ret = __kmpc_master (loc, global_tid);
    if (__kmp_env_consistency_check) {
        /* there's no __kmpc_end_master called; so the (stats) */
        /* actions of __kmpc_end_master are done here */
        if (global_tid < 0) {
            KMP_WARNING(ThreadIdentInvalid);
        }
        if (ret) {
            /* only one thread should do the pop since only */
            /* one did the push (see __kmpc_master()) */
            __kmp_pop_sync(global_tid, ct_master, loc);
        }
    }
    return (ret);
}
void __kmpc_end_barrier_master (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information
global_tid thread id.
Complete the execution of a combined barrier and master. This function should only be called at the completion of the master code. Other threads will still be waiting at the barrier and this call releases them.
Definition at line 1407 of file kmp_csupport.c.
Referenced by __kmp_enqueue_task().
{
    KC_TRACE(10, ("__kmpc_end_barrier_master: called T#%d\n", global_tid));
    __kmp_end_split_barrier (bs_plain_barrier, global_tid);
}
void __kmpc_end_reduce (ident_t * loc, kmp_int32 global_tid, kmp_critical_name * lck)
Parameters
loc source location information
global_tid global thread id.
lck pointer to the unique lock data structure
Finish the execution of a blocking reduce. The lck pointer must be the same as that used in the corresponding start function.
Definition at line 2947 of file kmp_csupport.c.
                                                                                {
    PACKED_REDUCTION_METHOD_T packed_reduction_method;
    KA_TRACE(10, ("__kmpc_end_reduce() enter: called T#%d\n", global_tid));
    packed_reduction_method = __KMP_GET_REDUCTION_METHOD(global_tid);
    // this barrier should be visible to a customer and to the threading profile tool
    // (it's a terminating barrier on constructs if NOWAIT not specified)
    if(packed_reduction_method == critical_reduce_block) {
        __kmp_end_critical_section_reduce_block(loc, global_tid,
      lck);
        // TODO: implicit barrier: should be exposed
#if USE_ITT_NOTIFY
        __kmp_threads[global_tid]->th.th_ident = loc;
#endif
        __kmp_barrier(bs_plain_barrier, global_tid,
      FALSE, 0, NULL, NULL);
    } else if(packed_reduction_method == empty_reduce_block) {
        // usage: if team size == 1, no synchronization is required (Intel platforms only)
        // TODO: implicit barrier: should be exposed
#if USE_ITT_NOTIFY
        __kmp_threads[global_tid]->th.th_ident = loc;
#endif
        __kmp_barrier(bs_plain_barrier, global_tid,
      FALSE, 0, NULL, NULL);
    } else if(packed_reduction_method == atomic_reduce_block) {
        // TODO: implicit barrier: should be exposed
#if USE_ITT_NOTIFY
        __kmp_threads[global_tid]->th.th_ident = loc;
#endif
        __kmp_barrier(bs_plain_barrier, global_tid,
      FALSE, 0, NULL, NULL);
    } else if(TEST_REDUCTION_METHOD(packed_reduction_method,
      tree_reduce_block)) {
        // only master executes here (master releases all other workers)
        __kmp_end_split_barrier(UNPACK_REDUCTION_BARRIER(
      packed_reduction_method), global_tid);
    } else {
        // should never reach this block
        KMP_ASSERT(0); // "unexpected method"
    }
    if (__kmp_env_consistency_check)
        __kmp_pop_sync(global_tid, ct_reduce, loc);
    KA_TRACE(10, ("__kmpc_end_reduce() exit: called T#%d: method %08x\n", global_tid,
      packed_reduction_method));
    return;
}
void __kmpc_end_reduce_nowait (ident_t * loc, kmp_int32 global_tid, kmp_critical_name * lck)
Parameters
loc source location information
global_tid global thread id.
lck pointer to the unique lock data structure
Finish the execution of a reduce nowait.
Definition at line 2802 of file kmp_csupport.c.
                                                                                       {
    PACKED_REDUCTION_METHOD_T packed_reduction_method;
    KA_TRACE(10, ("__kmpc_end_reduce_nowait() enter: called T#%d\n", global_tid));
    packed_reduction_method = __KMP_GET_REDUCTION_METHOD(global_tid);
    if(packed_reduction_method == critical_reduce_block) {
        __kmp_end_critical_section_reduce_block(loc, global_tid,
      lck);
    } else if(packed_reduction_method == empty_reduce_block) {
        // usage: if team size == 1, no synchronization is required (on Intel platforms only)
    } else if(packed_reduction_method == atomic_reduce_block) {
        // neither master nor other workers should get here
        // (code gen does not generate this call in case 2: atomic reduce block)
        // actually it's better to remove this elseif at all;
        // after removal this value will checked by the 'else' and will assert
    } else if(TEST_REDUCTION_METHOD(packed_reduction_method,
      tree_reduce_block)) {
        // only master gets here
    } else {
        // should never reach this block
        KMP_ASSERT(0); // "unexpected method"
    }
    if (__kmp_env_consistency_check)
        __kmp_pop_sync(global_tid, ct_reduce, loc);
    KA_TRACE(10, ("__kmpc_end_reduce_nowait() exit: called T#%d: method %08x\n", global_tid,
      packed_reduction_method));
    return;
}
void __kmpc_flush (ident_t * loc)
Parameters
loc source location information.
Execute flush. This is implemented as a full memory fence. (Though depending on the memory ordering convention obeyed by the compiler even that may not be necessary).
Definition at line 631 of file kmp_csupport.c.
{
    KC_TRACE(10, ("__kmpc_flush: called\n"));
    /* need explicit __mf() here since use volatile instead in library */
    KMP_MB(); /* Flush all pending memory write invalidates. */
    #if (KMP_ARCH_X86 || KMP_ARCH_X86_64)
        #if KMP_MIC
            // fence-style instructions do not exist, but lock; xaddl $0,(%rsp) can be used.
            // We shouldn't need it, though, since the ABI rules require that
            // * If the compiler generates NGO stores it also generates the fence
            // * If users hand-code NGO stores they should insert the fence
            // therefore no incomplete unordered stores should be visible.
        #else
            // C74404
            // This is to address non-temporal store instructions (sfence needed).
            // The clflush instruction is addressed either (mfence needed).
            // Probably the non-temporal load monvtdqa instruction should also be addressed.
            // mfence is a SSE2 instruction. Do not execute it if CPU is not SSE2.
            if (! __kmp_cpuinfo.initialized) {
                __kmp_query_cpuid(& __kmp_cpuinfo);
            }; // if
            if (! __kmp_cpuinfo.sse2) {
                // CPU cannot execute SSE2 instructions.
            } else {
                #if KMP_COMPILER_ICC || KMP_COMPILER_MSVC
                _mm_mfence();
                #else
                __sync_synchronize();
                #endif // KMP_COMPILER_ICC
            }; // if
        #endif // KMP_MIC
    #elif (KMP_ARCH_ARM || KMP_ARCH_AARCH64)
        // Nothing to see here move along
    #elif KMP_ARCH_PPC64
        // Nothing needed here (we have a real MB above).
        #if KMP_OS_CNK
        // The flushing thread needs to yield here; this prevents a
       // busy-waiting thread from saturating the pipeline. flush is
          // often used in loops like this:
           // while (!flag) {
           // #pragma omp flush(flag)
           // }
       // and adding the yield here is good for at least a 10x speedup
          // when running >2 threads per core (on the NAS LU benchmark).
            __kmp_yield(TRUE);
        #endif
    #else
        #error Unknown or unsupported architecture
    #endif
}
kmp_int32 __kmpc_reduce (ident_t * loc, kmp_int32 global_tid, kmp_int32 num_vars, size_t reduce_size, void * reduce_data, void(*)(void *lhs_data, void *rhs_data) reduce_func, kmp_critical_name * lck)
Parameters
loc source location information
global_tid global thread number
num_vars number of items (variables) to be reduced
reduce_size size of data in bytes to be reduced
reduce_data pointer to data to be reduced
reduce_func callback function providing reduction operation on two operands and returning result of reduction in lhs_data
lck pointer to the unique lock data structure
Returns
1 for the master thread, 0 for all other team threads, 2 for all team threads if atomic reduction needed
A blocking reduce that includes an implicit barrier.
Definition at line 2860 of file kmp_csupport.c.
{
    KMP_COUNT_BLOCK(REDUCE_wait);
    int retval = 0;
    PACKED_REDUCTION_METHOD_T packed_reduction_method;
    KA_TRACE(10, ("__kmpc_reduce() enter: called T#%d\n", global_tid));
    // why do we need this initialization here at all?
    // Reduction clause can not be a stand-alone directive.
    // do not call __kmp_serial_initialize(), it will be called by __kmp_parallel_initialize() if needed
    // possible detection of false-positive race by the threadchecker ???
    if(! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
    // check correctness of reduce block nesting
#if KMP_USE_DYNAMIC_LOCK
    if (__kmp_env_consistency_check)
        __kmp_push_sync(global_tid, ct_reduce, loc, NULL, 0);
#else
    if (__kmp_env_consistency_check)
        __kmp_push_sync(global_tid, ct_reduce, loc, NULL);
#endif
    packed_reduction_method = __kmp_determine_reduction_method(loc,
      global_tid, num_vars, reduce_size, reduce_data, reduce_func, lck);
    __KMP_SET_REDUCTION_METHOD(global_tid, packed_reduction_method);
    if(packed_reduction_method == critical_reduce_block) {
        __kmp_enter_critical_section_reduce_block(loc, global_tid
      , lck);
        retval = 1;
    } else if(packed_reduction_method == empty_reduce_block) {
        // usage: if team size == 1, no synchronization is required (Intel platforms only)
        retval = 1;
    } else if(packed_reduction_method == atomic_reduce_block) {
        retval = 2;
    } else if(TEST_REDUCTION_METHOD(packed_reduction_method,
      tree_reduce_block)) {
        //case tree_reduce_block:
        // this barrier should be visible to a customer and to the threading profile tool
        // (it's a terminating barrier on constructs if NOWAIT not specified)
#if USE_ITT_NOTIFY
        __kmp_threads[global_tid]->th.th_ident = loc; // needed for correct notification of
       frames
#endif
        retval = __kmp_barrier(UNPACK_REDUCTION_BARRIER(
      packed_reduction_method), global_tid, TRUE, reduce_size, reduce_data, reduce_func);
        retval = (retval != 0) ? (0) : (1);
        // all other workers except master should do this pop here
        // (none of other workers except master will enter __kmpc_end_reduce())
        if (__kmp_env_consistency_check) {
            if(retval == 0) { // 0: all other workers; 1: master
                __kmp_pop_sync(global_tid, ct_reduce, loc);
            }
        }
    } else {
        // should never reach this block
        KMP_ASSERT(0); // "unexpected method"
    }
    KA_TRACE(10, ("__kmpc_reduce() exit: called T#%d: method %08x, returns %08x\n", global_tid,
      packed_reduction_method, retval));
    return retval;
}
kmp_int32 __kmpc_reduce_nowait (ident_t * loc, kmp_int32 global_tid, kmp_int32 num_vars, size_t reduce_size, void * reduce_data, void(*)(void *lhs_data, void *rhs_data) reduce_func, kmp_critical_name * lck)
Parameters
loc source location information
global_tid global thread number
num_vars number of items (variables) to be reduced
reduce_size size of data in bytes to be reduced
reduce_data pointer to data to be reduced
reduce_func callback function providing reduction operation on two operands and returning result of reduction in lhs_data
lck pointer to the unique lock data structure
Returns
1 for the master thread, 0 for all other team threads, 2 for all team threads if atomic reduction needed
The nowait version is used for a reduce clause with the nowait argument.
Definition at line 2663 of file kmp_csupport.c.
                             {
    KMP_COUNT_BLOCK(REDUCE_nowait);
    int retval = 0;
    PACKED_REDUCTION_METHOD_T packed_reduction_method;
#if OMP_40_ENABLED
    kmp_team_t *team;
    kmp_info_t *th;
    int teams_swapped = 0, task_state;
#endif
    KA_TRACE(10, ("__kmpc_reduce_nowait() enter: called T#%d\n", global_tid));
    // why do we need this initialization here at all?
    // Reduction clause can not be used as a stand-alone directive.
    // do not call __kmp_serial_initialize(), it will be called by __kmp_parallel_initialize() if needed
    // possible detection of false-positive race by the threadchecker ???
    if(! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
    // check correctness of reduce block nesting
#if KMP_USE_DYNAMIC_LOCK
    if (__kmp_env_consistency_check)
        __kmp_push_sync(global_tid, ct_reduce, loc, NULL, 0);
#else
    if (__kmp_env_consistency_check)
        __kmp_push_sync(global_tid, ct_reduce, loc, NULL);
#endif
#if OMP_40_ENABLED
    th = __kmp_thread_from_gtid(global_tid);
    if(th->th.th_teams_microtask) { // AC: check if we are inside the teams construct?
        team = th->th.th_team;
        if(team->t.t_level == th->th.th_teams_level) {
            // this is reduction at teams construct
            KMP_DEBUG_ASSERT(!th->th.th_info.ds.ds_tid); // AC: check that tid == 0
            // Let's swap teams temporarily for the reduction barrier
            teams_swapped = 1;
            th->th.th_info.ds.ds_tid = team->t.t_master_tid;
            th->th.th_team = team->t.t_parent;
            th->th.th_team_nproc = th->th.th_team->t.t_nproc;
            th->th.th_task_team = th->th.th_team->t.t_task_team[0];
            task_state = th->th.th_task_state;
            th->th.th_task_state = 0;
        }
    }
#endif // OMP_40_ENABLED
    // packed_reduction_method value will be reused by __kmp_end_reduce* function, the value should be kept
       in a variable
    // the variable should be either a construct-specific or thread-specific property, not a team specific
       property
    // (a thread can reach the next reduce block on the next construct, reduce method may differ on the
       next construct)
    // an ident_t "loc" parameter could be used as a construct-specific property (what if loc == 0?)
    // (if both construct-specific and team-specific variables were shared, then unness extra syncs
       should be needed)
    // a thread-specific variable is better regarding two issues above (next construct and extra syncs)
    // a thread-specific "th_local.reduction_method" variable is used currently
    // each thread executes 'determine' and 'set' lines (no need to execute by one thread, to avoid unness
       extra syncs)
    packed_reduction_method = __kmp_determine_reduction_method(loc,
      global_tid, num_vars, reduce_size, reduce_data, reduce_func, lck);
    __KMP_SET_REDUCTION_METHOD(global_tid, packed_reduction_method);
    if(packed_reduction_method == critical_reduce_block) {
        __kmp_enter_critical_section_reduce_block(loc, global_tid
      , lck);
        retval = 1;
    } else if(packed_reduction_method == empty_reduce_block) {
        // usage: if team size == 1, no synchronization is required (Intel platforms only)
        retval = 1;
    } else if(packed_reduction_method == atomic_reduce_block) {
        retval = 2;
        // all threads should do this pop here (because __kmpc_end_reduce_nowait() won't be called by the
       code gen)
        // (it's not quite good, because the checking block has been closed by this 'pop',
        // but atomic operation has not been executed yet, will be executed slightly later, literally
       on next instruction)
        if (__kmp_env_consistency_check)
            __kmp_pop_sync(global_tid, ct_reduce, loc);
    } else if(TEST_REDUCTION_METHOD(packed_reduction_method,
      tree_reduce_block)) {
        //AT: performance issue: a real barrier here
        //AT: (if master goes slow, other threads are blocked here waiting for the master to come and
       release them)
        //AT: (it's not what a customer might expect specifying NOWAIT clause)
        //AT: (specifying NOWAIT won't result in improvement of performance, it'll be confusing to a
       customer)
        //AT: another implementation of *barrier_gather*nowait() (or some other design) might go faster
        // and be more in line with sense of NOWAIT
        //AT: TO DO: do epcc test and compare times
        // this barrier should be invisible to a customer and to the threading profile tool
        // (it's neither a terminating barrier nor customer's code, it's used for an internal
       purpose)
#if USE_ITT_NOTIFY
        __kmp_threads[global_tid]->th.th_ident = loc;
#endif
        retval = __kmp_barrier(UNPACK_REDUCTION_BARRIER(
      packed_reduction_method), global_tid, FALSE, reduce_size, reduce_data, reduce_func);
        retval = (retval != 0) ? (0) : (1);
        // all other workers except master should do this pop here
        // (none of other workers will get to __kmpc_end_reduce_nowait())
        if (__kmp_env_consistency_check) {
            if(retval == 0) {
                __kmp_pop_sync(global_tid, ct_reduce, loc);
            }
        }
    } else {
        // should never reach this block
        KMP_ASSERT(0); // "unexpected method"
    }
#if OMP_40_ENABLED
    if(teams_swapped) {
        // Restore thread structure
        th->th.th_info.ds.ds_tid = 0;
        th->th.th_team = team;
        th->th.th_team_nproc = team->t.t_nproc;
        th->th.th_task_team = team->t.t_task_team[task_state];
        th->th.th_task_state = task_state;
    }
#endif
    KA_TRACE(10, ("__kmpc_reduce_nowait() exit: called T#%d: method %08x, returns %08x\n",
      global_tid, packed_reduction_method, retval));
    return retval;
}