kmp_environment.c File Reference
#include `kmp_environment.h`
*
#include `kmp_os.h`
*
#include `kmp.h`
*
#include `kmp_str.h`
*
#include `kmp_i18n.h`
*
Functions
static void * allocate (size_t size)
char * __kmp_env_get (char const *name)
void __kmp_env_free (char const **value)
int __kmp_env_exists (char const *name)
void __kmp_env_set (char const *name, char const *value, int overwrite)
void __kmp_env_unset (char const *name)
static void ___kmp_env_blk_parse_string (kmp_env_blk_t *block, char const *env)
static void ___kmp_env_blk_parse_unix (kmp_env_blk_t *block, char **env)
void __kmp_env_blk_init (kmp_env_blk_t *block, char const *bulk)
static int ___kmp_env_var_cmp (kmp_env_var_t const *lhs, kmp_env_var_t const *rhs)
void __kmp_env_blk_sort (kmp_env_blk_t *block)
void __kmp_env_blk_free (kmp_env_blk_t *block)
char const * __kmp_env_blk_var (kmp_env_blk_t *block, char const *name)
Function Documentation
static void ___kmp_env_blk_parse_string (kmp_env_blk_t * block, char const * env) [static]
Definition at line 300 of file kmp_environment.c.
Referenced by __kmp_env_blk_init().
  {
    char const chr_delimiter = '|';
    char const str_delimiter[] = { chr_delimiter, 0 };
    char * bulk = NULL;
    kmp_env_var_t * vars = NULL;
    int count = 0; // Number of used elements in vars array.
    int delimiters = 0; // Number of delimiters in input string.
    // Copy original string, we will modify the copy.
    bulk = __kmp_str_format("%s", env);
    // Loop thru all the vars in environment block. Count delimiters (maximum number of variables
    // is number of delimiters plus one).
    {
        char const * ptr = bulk;
        for (; ;) {
            ptr = strchr(ptr, chr_delimiter);
            if (ptr == NULL) {
                break;
            }; // if
            ++ delimiters;
            ptr += 1;
        }; // forever
    }
    // Allocate vars array.
    vars = (kmp_env_var_t *) allocate((delimiters + 1) * sizeof(
      kmp_env_var_t));
    // Loop thru all the variables.
    {
        char * var; // Pointer to variable (both name and value).
        char * name; // Pointer to name of variable.
        char * value; // Pointer to value.
        char * buf; // Buffer for __kmp_str_token() function.
        var = __kmp_str_token(bulk, str_delimiter, & buf); // Get the first var.
        while (var != NULL) {
            // Save found variable in vars array.
            __kmp_str_split(var, '=', & name, & value);
            KMP_DEBUG_ASSERT(count < delimiters + 1);
            vars[ count ].name = name;
            vars[ count ].value = value;
            ++ count;
            // Get the next var.
            var = __kmp_str_token(NULL, str_delimiter, & buf);
        }; // while
    }
    // Fill out result.
    block->bulk = bulk;
    block->vars = vars;
    block->count = count;
}; // ___kmp_env_blk_parse_string
static void ___kmp_env_blk_parse_unix (kmp_env_blk_t * block, char ** env) [static]
Definition at line 449 of file kmp_environment.c.
Referenced by __kmp_env_blk_init().
  {
    char * bulk = NULL;
    kmp_env_var_t * vars = NULL;
    int count = 0;
    int size = 0; // Size of bulk.
    // Count number of variables and length of required bulk.
    {
        count = 0;
        size = 0;
        while (env[ count ] != NULL) {
            size += KMP_STRLEN(env[ count ]) + 1;
            ++ count;
        }; // while
    }
    // Allocate memory.
    bulk = (char *) allocate(size);
    vars = (kmp_env_var_t *) allocate(count * sizeof(
      kmp_env_var_t));
    // Loop thru all the vars.
    {
        char * var; // Pointer to beginning of var.
        char * name; // Pointer to name of variable.
        char * value; // Pointer to value.
        int len; // Length of variable.
        int i;
        var = bulk;
        for (i = 0; i < count; ++ i) {
            // Copy variable to bulk.
            len = KMP_STRLEN(env[ i ]);
            KMP_MEMCPY_S(var, size, env[ i ], len + 1);
            // Save found variable in vars array.
            __kmp_str_split(var, '=', & name, & value);
            vars[ i ].name = name;
            vars[ i ].value = value;
            // Move pointer.
            var += len + 1;
        }; // for
    }
    // Fill out result.
    block->bulk = bulk;
    block->vars = vars;
    block->count = count;
}; // ___kmp_env_blk_parse_unix
static int ___kmp_env_var_cmp (kmp_env_var_t const * lhs, kmp_env_var_t const * rhs) [static]
Definition at line 540 of file kmp_environment.c.
Referenced by __kmp_env_blk_sort().
  {
    return strcmp(lhs->name, rhs->name);
}
void __kmp_env_blk_free (kmp_env_blk_t * block)
Definition at line 564 of file kmp_environment.c.
Referenced by __kmp_env_initialize(), __kmp_env_print(), and __kmp_env_print_2().
  {
    KMP_INTERNAL_FREE((void *) block->vars);
    KMP_INTERNAL_FREE((void *) block->bulk);
    block->count = 0;
    block->vars = NULL;
    block->bulk = NULL;
} // __kmp_env_blk_free
void __kmp_env_blk_init (kmp_env_blk_t * block, char const * bulk)
Definition at line 504 of file kmp_environment.c.
Referenced by __kmp_env_initialize(), __kmp_env_print(), and __kmp_env_print_2().
  {
    if (bulk != NULL) {
        ___kmp_env_blk_parse_string(block, bulk);
    } else {
        #if KMP_OS_UNIX
            ___kmp_env_blk_parse_unix(block, environ);
        #elif KMP_OS_WINDOWS
            {
                char * mem = GetEnvironmentStrings();
                if (mem == NULL) {
                    DWORD error = GetLastError();
                    __kmp_msg(
                        kmp_ms_fatal,
                        KMP_MSG(CantGetEnvironment),
                        KMP_ERR(error),
                        __kmp_msg_null
                    );
                }; // if
                ___kmp_env_blk_parse_windows(block, mem);
                FreeEnvironmentStrings(mem);
            }
        #else
            #error Unknown or unsupported OS.
        #endif
    }; // if
} // __kmp_env_blk_init
void __kmp_env_blk_sort (kmp_env_blk_t * block)
Definition at line 548 of file kmp_environment.c.
Referenced by __kmp_env_print(), and __kmp_env_print_2().
  {
    qsort(
        (void *) block->vars,
        block->count,
        sizeof(kmp_env_var_t),
        (int (*)(void const *, void const *)) & ___kmp_env_var_cmp
    );
} // __kmp_env_block_sort
char const* __kmp_env_blk_var (kmp_env_blk_t * block, char const * name)
Definition at line 580 of file kmp_environment.c.
Referenced by __kmp_aux_env_initialize(), and __kmp_env_initialize().
  {
    int i;
    for (i = 0; i < block->count; ++ i) {
        if (strcmp(block->vars[ i ].name, name) == 0) {
            return block->vars[ i ].value;
        }; // if
    }; // for
    return NULL;
} // __kmp_env_block_var
int __kmp_env_exists (char const * name)
Definition at line 179 of file kmp_environment.c.
                                      {
    #if KMP_OS_UNIX
        char const * value = getenv(name);
        return ((value == NULL) ? (0) : (1));
    #elif KMP_OS_WINDOWS
        DWORD rc;
        rc = GetEnvironmentVariable(name, NULL, 0);
        if (rc == 0) {
            DWORD error = GetLastError();
            if (error != ERROR_ENVVAR_NOT_FOUND) {
                __kmp_msg(
                    kmp_ms_fatal,
                    KMP_MSG(CantGetEnvVar, name),
                    KMP_ERR(error),
                    __kmp_msg_null
                );
            }; // if
            return 0;
        }; // if
        return 1;
    #else
        #error Unknown or unsupported OS.
    #endif
} // func __kmp_env_exists
void __kmp_env_free (char const ** value)
Definition at line 168 of file kmp_environment.c.
Referenced by __kmp_do_serial_initialize().
                                       {
    KMP_DEBUG_ASSERT(value != NULL);
    KMP_INTERNAL_FREE((void *) * value);
    * value = NULL;
} // func __kmp_env_free
char* __kmp_env_get (char const * name)
Definition at line 96 of file kmp_environment.c.
Referenced by __kmp_do_serial_initialize(), __kmp_register_library_startup(), and __kmp_unregister_library().
                                   {
    char * result = NULL;
    #if KMP_OS_UNIX
        char const * value = getenv(name);
        if (value != NULL) {
            size_t len = KMP_STRLEN(value) + 1;
            result = (char *) KMP_INTERNAL_MALLOC(len);
            if (result == NULL) {
                KMP_FATAL(MemoryAllocFailed);
            }; // if
            KMP_STRNCPY_S(result, len, value, len);
        }; // if
    #elif KMP_OS_WINDOWS
        /*
            We use GetEnvironmentVariable for Windows* OS instead of getenv because the act of
            loading a DLL on Windows* OS makes any user-set environment variables (i.e. with putenv())
            unavailable. getenv() apparently gets a clean copy of the env variables as they existed
            at the start of the run.
            JH 12/23/2002
        */
        DWORD rc;
        rc = GetEnvironmentVariable(name, NULL, 0);
        if (! rc) {
            DWORD error = GetLastError();
            if (error != ERROR_ENVVAR_NOT_FOUND) {
                __kmp_msg(
                    kmp_ms_fatal,
                    KMP_MSG(CantGetEnvVar, name),
                    KMP_ERR(error),
                    __kmp_msg_null
                );
            }; // if
            // Variable is not found, it's ok, just continue.
        } else {
            DWORD len = rc;
            result = (char *) KMP_INTERNAL_MALLOC(len);
            if (result == NULL) {
                KMP_FATAL(MemoryAllocFailed);
            }; // if
            rc = GetEnvironmentVariable(name, result, len);
            if (! rc) {
                // GetEnvironmentVariable() may return 0 if variable is empty.
                // In such a case GetLastError() returns ERROR_SUCCESS.
                DWORD error = GetLastError();
                if (error != ERROR_SUCCESS) {
                    // Unexpected error. The variable should be in the environment,
                    // and buffer should be large enough.
                    __kmp_msg(
                        kmp_ms_fatal,
                        KMP_MSG(CantGetEnvVar, name),
                        KMP_ERR(error),
                        __kmp_msg_null
                    );
                    KMP_INTERNAL_FREE((void *) result);
                    result = NULL;
                }; // if
            }; // if
        }; // if
    #else
        #error Unknown or unsupported OS.
    #endif
    return result;
} // func __kmp_env_get
void __kmp_env_set (char const * name, char const * value, int overwrite)
Definition at line 209 of file kmp_environment.c.
Referenced by __kmp_register_library_startup().
                                                                      {
    #if KMP_OS_UNIX
        int rc = setenv(name, value, overwrite);
        if (rc != 0) {
            // Dead code. I tried to put too many variables into Linux* OS
            // environment on IA-32 architecture. When application consumes
            // more than ~2.5 GB of memory, entire system feels bad. Sometimes
            // application is killed (by OS?), sometimes system stops
            // responding... But this error message never appears. --ln
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(CantSetEnvVar, name),
                KMP_HNT(NotEnoughMemory),
                __kmp_msg_null
            );
        }; // if
    #elif KMP_OS_WINDOWS
        BOOL rc;
        if (! overwrite) {
            rc = GetEnvironmentVariable(name, NULL, 0);
            if (rc) {
                // Variable exists, do not overwrite.
                return;
            }; // if
            DWORD error = GetLastError();
            if (error != ERROR_ENVVAR_NOT_FOUND) {
                __kmp_msg(
                    kmp_ms_fatal,
                    KMP_MSG(CantGetEnvVar, name),
                    KMP_ERR(error),
                    __kmp_msg_null
                );
            }; // if
        }; // if
        rc = SetEnvironmentVariable(name, value);
        if (! rc) {
            DWORD error = GetLastError();
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(CantSetEnvVar, name),
                KMP_ERR(error),
                __kmp_msg_null
            );
        }; // if
    #else
        #error Unknown or unsupported OS.
    #endif
} // func __kmp_env_set
void __kmp_env_unset (char const * name)
Definition at line 263 of file kmp_environment.c.
Referenced by __kmp_register_library_startup(), and __kmp_unregister_library().
                                     {
    #if KMP_OS_UNIX
        unsetenv(name);
    #elif KMP_OS_WINDOWS
        BOOL rc = SetEnvironmentVariable(name, NULL);
        if (! rc) {
            DWORD error = GetLastError();
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(CantSetEnvVar, name),
                KMP_ERR(error),
                __kmp_msg_null
            );
        }; // if
    #else
        #error Unknown or unsupported OS.
    #endif
} // func __kmp_env_unset
static void* allocate (size_t size) [inline], [static]
Definition at line 84 of file kmp_environment.c.
Referenced by ___kmp_env_blk_parse_string(), and ___kmp_env_blk_parse_unix().
  {
    void * ptr = KMP_INTERNAL_MALLOC(size);
    if (ptr == NULL) {
        KMP_FATAL(MemoryAllocFailed);
    }; // if
    return ptr;
} // allocate