kmp_taskdeps.cpp File Reference
#include `kmp.h`
*
#include `kmp_io.h`
*
#include `kmp_wait_release.h`
*
Macros
#define KMP_ACQUIRE_DEPNODE(gtid, n) __kmp_acquire_lock(&(n)->dn.lock,(gtid))
#define KMP_RELEASE_DEPNODE(gtid, n) __kmp_release_lock(&(n)->dn.lock,(gtid))
#define NO_DEP_BARRIER (false)
#define DEP_BARRIER (true)
Enumerations
enum { KMP_DEPHASH_OTHER_SIZE = 97,
KMP_DEPHASH_MASTER_SIZE = 997
 }
Functions
static void __kmp_init_node (kmp_depnode_t *node)
static kmp_depnode_t * __kmp_node_ref (kmp_depnode_t *node)
static void __kmp_node_deref (kmp_info_t *thread, kmp_depnode_t *node)
static void __kmp_depnode_list_free (kmp_info_t *thread, kmp_depnode_list *list)
static kmp_int32 __kmp_dephash_hash (kmp_intptr_t addr, size_t hsize)
static kmp_dephash_t * __kmp_dephash_create (kmp_info_t *thread, kmp_taskdata_t *current_task)
static void __kmp_dephash_free (kmp_info_t *thread, kmp_dephash_t *h)
static kmp_dephash_entry * __kmp_dephash_find (kmp_info_t *thread, kmp_dephash_t *h, kmp_intptr_t addr)
static kmp_depnode_list_t * __kmp_add_node (kmp_info_t *thread, kmp_depnode_list_t *list, kmp_depnode_t *node)
static void __kmp_track_dependence (kmp_depnode_t *source, kmp_depnode_t *sink, kmp_task_t *sink_task)
template<bool filter>
static kmp_int32 __kmp_process_deps (kmp_int32 gtid, kmp_depnode_t *node, kmp_dephash_t *hash, bool dep_barrier, kmp_int32 ndeps, kmp_depend_info_t *dep_list, kmp_task_t *task)
static bool __kmp_check_deps (kmp_int32 gtid, kmp_depnode_t *node, kmp_task_t *task, kmp_dephash_t *hash, bool dep_barrier, kmp_int32 ndeps, kmp_depend_info_t *dep_list, kmp_int32 ndeps_noalias, kmp_depend_info_t *noalias_dep_list)
void __kmp_release_deps (kmp_int32 gtid, kmp_taskdata_t *task)
kmp_int32 __kmpc_omp_task_with_deps (ident_t *loc_ref, kmp_int32 gtid, kmp_task_t *new_task, kmp_int32 ndeps, kmp_depend_info_t *dep_list, kmp_int32 ndeps_noalias, kmp_depend_info_t *noalias_dep_list)
void __kmpc_omp_wait_deps (ident_t *loc_ref, kmp_int32 gtid, kmp_int32 ndeps, kmp_depend_info_t *dep_list, kmp_int32 ndeps_noalias, kmp_depend_info_t *noalias_dep_list)
Macro Definition Documentation
#define DEP_BARRIER (true)
Definition at line 308 of file kmp_taskdeps.cpp.
Referenced by __kmpc_omp_wait_deps().
#define KMP_ACQUIRE_DEPNODE(gtid, n) __kmp_acquire_lock(&(n)->dn.lock,(gtid))
Definition at line 70 of file kmp_taskdeps.cpp.
Referenced by __kmp_process_deps(), and __kmp_release_deps().
#define KMP_RELEASE_DEPNODE(gtid, n) __kmp_release_lock(&(n)->dn.lock,(gtid))
Definition at line 71 of file kmp_taskdeps.cpp.
Referenced by __kmp_process_deps(), and __kmp_release_deps().
#define NO_DEP_BARRIER (false)
Definition at line 307 of file kmp_taskdeps.cpp.
Referenced by __kmpc_omp_task_with_deps().
Enumeration Type Documentation
anonymous enum
Enumerator
KMP_DEPHASH_OTHER_SIZE
KMP_DEPHASH_MASTER_SIZE
Definition at line 76 of file kmp_taskdeps.cpp.
     {
    KMP_DEPHASH_OTHER_SIZE = 97,
    KMP_DEPHASH_MASTER_SIZE = 997
};
Function Documentation
static kmp_depnode_list_t* __kmp_add_node (kmp_info_t * thread, kmp_depnode_list_t * list, kmp_depnode_t * node) [static]
Definition at line 176 of file kmp_taskdeps.cpp.
Referenced by __kmp_process_deps().
{
    kmp_depnode_list_t *new_head;
#if USE_FAST_MEMORY
    new_head = (kmp_depnode_list_t *) __kmp_fast_allocate(thread,
      sizeof(kmp_depnode_list_t));
#else
    new_head = (kmp_depnode_list_t *) __kmp_thread_malloc(thread,
      sizeof(kmp_depnode_list_t));
#endif
    new_head->node = __kmp_node_ref(node);
    new_head->next = list;
    return new_head;
}
static bool __kmp_check_deps (kmp_int32 gtid, kmp_depnode_t * node, kmp_task_t * task, kmp_dephash_t * hash, bool dep_barrier, kmp_int32 ndeps, kmp_depend_info_t * dep_list, kmp_int32 ndeps_noalias, kmp_depend_info_t * noalias_dep_list) [static]
Definition at line 312 of file kmp_taskdeps.cpp.
Referenced by __kmpc_omp_task_with_deps(), and __kmpc_omp_wait_deps().
{
    int i;
#if KMP_DEBUG
    kmp_taskdata_t * taskdata = KMP_TASK_TO_TASKDATA(task);
#endif
    KA_TRACE(20, ("__kmp_check_deps: T#%d checking dependencies for task %p : %d possibly aliased
       dependencies, %d non-aliased depedencies : dep_barrier=%d .\n", gtid, taskdata, ndeps, ndeps_noalias,
      dep_barrier));
    // Filter deps in dep_list
    // TODO: Different algorithm for large dep_list (> 10 ?)
    for (i = 0; i < ndeps; i ++) {
        if (dep_list[i].base_addr != 0)
            for (int j = i+1; j < ndeps; j++)
                if (dep_list[i].base_addr == dep_list[j].base_addr) {
                    dep_list[i].flags.in |= dep_list[j].flags.in;
                    dep_list[i].flags.out |= dep_list[j].flags.out;
                    dep_list[j].base_addr = 0; // Mark j element as void
                }
    }
    // doesn't need to be atomic as no other thread is going to be accessing this node just yet
    // npredecessors is set -1 to ensure that none of the releasing tasks queues this task before we have
       finished processing all the dependencies
    node->dn.npredecessors = -1;
    // used to pack all npredecessors additions into a single atomic operation at the end
    int npredecessors;
    npredecessors = __kmp_process_deps<true>(gtid, node, hash, dep_barrier,
      ndeps, dep_list, task);
    npredecessors += __kmp_process_deps<false>(gtid, node, hash, dep_barrier,
      ndeps_noalias, noalias_dep_list, task);
    node->dn.task = task;
    KMP_MB();
    // Account for our initial fake value
    npredecessors++;
    // Update predecessors and obtain current value to check if there are still any outstandig dependences
       (some tasks may have finished while we processed the dependences)
    npredecessors = KMP_TEST_THEN_ADD32(&node->dn.npredecessors, npredecessors) +
      npredecessors;
    KA_TRACE(20, ("__kmp_check_deps: T#%d found %d predecessors for task %p \n", gtid,
      npredecessors, taskdata));
    // beyond this point the task could be queued (and executed) by a releasing task...
    return npredecessors > 0 ? true : false;
}
static kmp_dephash_t* __kmp_dephash_create (kmp_info_t * thread, kmp_taskdata_t * current_task) [static]
Definition at line 89 of file kmp_taskdeps.cpp.
Referenced by __kmpc_omp_task_with_deps().
{
    kmp_dephash_t *h;
    size_t h_size;
    if (current_task->td_flags.tasktype == TASK_IMPLICIT)
        h_size = KMP_DEPHASH_MASTER_SIZE;
    else
        h_size = KMP_DEPHASH_OTHER_SIZE;
    kmp_int32 size = h_size * sizeof(kmp_dephash_entry_t) + sizeof(
      kmp_dephash_t);
#if USE_FAST_MEMORY
    h = (kmp_dephash_t *) __kmp_fast_allocate(thread, size);
#else
    h = (kmp_dephash_t *) __kmp_thread_malloc(thread, size);
#endif
    h->size = h_size;
#ifdef KMP_DEBUG
    h->nelements = 0;
    h->nconflicts = 0;
#endif
    h->buckets = (kmp_dephash_entry **)(h+1);
    for (size_t i = 0; i < h_size; i++)
        h->buckets[i] = 0;
    return h;
}
static kmp_dephash_entry* __kmp_dephash_find (kmp_info_t * thread, kmp_dephash_t * h, kmp_intptr_t addr) [static]
Definition at line 147 of file kmp_taskdeps.cpp.
Referenced by __kmp_process_deps().
{
    kmp_int32 bucket = __kmp_dephash_hash(addr,h->size);
    kmp_dephash_entry_t *entry;
    for (entry = h->buckets[bucket]; entry; entry = entry->
      next_in_bucket)
        if (entry->addr == addr) break;
    if (entry == NULL) {
        // create entry. This is only done by one thread so no locking required
#if USE_FAST_MEMORY
        entry = (kmp_dephash_entry_t *) __kmp_fast_allocate(thread,
      sizeof(kmp_dephash_entry_t));
#else
        entry = (kmp_dephash_entry_t *) __kmp_thread_malloc(thread,
      sizeof(kmp_dephash_entry_t));
#endif
        entry->addr = addr;
        entry->last_out = NULL;
        entry->last_ins = NULL;
        entry->next_in_bucket = h->buckets[bucket];
        h->buckets[bucket] = entry;
#ifdef KMP_DEBUG
        h->nelements++;
        if (entry->next_in_bucket) h->nconflicts++;
#endif
    }
    return entry;
}
static void __kmp_dephash_free (kmp_info_t * thread, kmp_dephash_t * h) [static]
Definition at line 122 of file kmp_taskdeps.cpp.
Referenced by __kmp_release_deps().
{
    for (size_t i=0; i < h->size; i++) {
        if (h->buckets[i]) {
            kmp_dephash_entry_t *next;
            for (kmp_dephash_entry_t *entry = h->buckets[
      i]; entry; entry = next) {
                next = entry->next_in_bucket;
                __kmp_depnode_list_free(thread,entry->last_ins);
                __kmp_node_deref(thread,entry->last_out);
#if USE_FAST_MEMORY
                __kmp_fast_free(thread,entry);
#else
                __kmp_thread_free(thread,entry);
#endif
            }
        }
    }
#if USE_FAST_MEMORY
    __kmp_fast_free(thread,h);
#else
    __kmp_thread_free(thread,h);
#endif
}
static kmp_int32 __kmp_dephash_hash (kmp_intptr_t addr, size_t hsize) [inline], [static]
Definition at line 82 of file kmp_taskdeps.cpp.
Referenced by __kmp_dephash_find().
{
    //TODO alternate to try: set = (((Addr64)(addrUsefulBits * 9.618)) % m_num_sets);
    return ((addr >> 6) ^ (addr >> 2)) % hsize;
}
static void __kmp_depnode_list_free (kmp_info_t * thread, kmp_depnode_list * list) [static]
Definition at line 193 of file kmp_taskdeps.cpp.
Referenced by __kmp_dephash_free(), and __kmp_process_deps().
{
    kmp_depnode_list *next;
    for (; list ; list = next) {
        next = list->next;
        __kmp_node_deref(thread,list->node);
#if USE_FAST_MEMORY
        __kmp_fast_free(thread,list);
#else
        __kmp_thread_free(thread,list);
#endif
    }
}
static void __kmp_init_node (kmp_depnode_t * node) [static]
Definition at line 36 of file kmp_taskdeps.cpp.
Referenced by __kmpc_omp_task_with_deps(), and __kmpc_omp_wait_deps().
{
    node->dn.task = NULL; // set to null initially, it will point to the right task once dependences
       have been processed
    node->dn.successors = NULL;
    __kmp_init_lock(&node->dn.lock);
    node->dn.nrefs = 1; // init creates the first reference to the node
#ifdef KMP_SUPPORT_GRAPH_OUTPUT
    node->dn.id = KMP_TEST_THEN_INC32(&kmp_node_id_seed);
#endif
}
static void __kmp_node_deref (kmp_info_t * thread, kmp_depnode_t * node) [inline], [static]
Definition at line 55 of file kmp_taskdeps.cpp.
Referenced by __kmp_dephash_free(), __kmp_depnode_list_free(), __kmp_process_deps(), and __kmp_release_deps().
{
    if (!node) return;
    kmp_int32 n = KMP_TEST_THEN_DEC32(&node->dn.nrefs) - 1;
    if (n == 0) {
        KMP_ASSERT(node->dn.nrefs == 0);
#if USE_FAST_MEMORY
        __kmp_fast_free(thread,node);
#else
        __kmp_thread_free(thread,node);
#endif
    }
}
static kmp_depnode_t* __kmp_node_ref (kmp_depnode_t * node) [inline], [static]
Definition at line 48 of file kmp_taskdeps.cpp.
Referenced by __kmp_add_node(), and __kmp_process_deps().
{
    KMP_TEST_THEN_INC32(&node->dn.nrefs);
    return node;
}
template<bool filter> static kmp_int32 __kmp_process_deps (kmp_int32 gtid, kmp_depnode_t * node, kmp_dephash_t * hash, bool dep_barrier, kmp_int32 ndeps, kmp_depend_info_t * dep_list, kmp_task_t * task) [inline], [static]
Definition at line 237 of file kmp_taskdeps.cpp.
{
    KA_TRACE(30, ("__kmp_process_deps<%d>: T#%d processing %d depencies : dep_barrier = %d\n",
      filter, gtid, ndeps, dep_barrier));
    
    kmp_info_t *thread = __kmp_threads[ gtid ];
    kmp_int32 npredecessors=0;
    for (kmp_int32 i = 0; i < ndeps ; i++) {
        const kmp_depend_info_t * dep = &dep_list[i];
        KMP_DEBUG_ASSERT(dep->flags.in);
        if (filter && dep->base_addr == 0) continue; // skip filtered entries
        kmp_dephash_entry_t *info = __kmp_dephash_find(thread,hash,dep
      ->base_addr);
        kmp_depnode_t *last_out = info->last_out;
        if (dep->flags.out && info->last_ins) {
            for (kmp_depnode_list_t * p = info->last_ins;
      p; p = p->next) {
                kmp_depnode_t * indep = p->node;
                if (indep->dn.task) {
                    KMP_ACQUIRE_DEPNODE(gtid,indep);
                    if (indep->dn.task) {
                        __kmp_track_dependence(indep,node,task);
                        indep->dn.successors = __kmp_add_node(thread, indep->
      dn.successors, node);
                        KA_TRACE(40,("__kmp_process_deps<%d>: T#%d adding dependence from %p to %p
      \n",
                                 filter,gtid, KMP_TASK_TO_TASKDATA(indep->
      dn.task), KMP_TASK_TO_TASKDATA(node->dn.task)));
                        npredecessors++;
                    }
                    KMP_RELEASE_DEPNODE(gtid,indep);
                }
            }
            __kmp_depnode_list_free(thread,info->last_ins);
            info->last_ins = NULL;
        } else if (last_out && last_out->dn.task) {
            KMP_ACQUIRE_DEPNODE(gtid,last_out);
            if (last_out->dn.task) {
                __kmp_track_dependence(last_out,node,task);
                last_out->dn.successors = __kmp_add_node(thread, last_out->
      dn.successors, node);
                KA_TRACE(40,("__kmp_process_deps<%d>: T#%d adding dependence from %p to %p\n",
                             filter,gtid, KMP_TASK_TO_TASKDATA(last_out->
      dn.task), KMP_TASK_TO_TASKDATA(node->dn.task)));
                
                npredecessors++;
            }
            KMP_RELEASE_DEPNODE(gtid,last_out);
        }
        if (dep_barrier) {
            // if this is a sync point in the serial sequence, then the previous outputs are guaranteed to
       be completed after
            // the execution of this task so the previous output nodes can be cleared.
            __kmp_node_deref(thread,last_out);
            info->last_out = NULL;
        } else {
            if (dep->flags.out) {
                __kmp_node_deref(thread,last_out);
                info->last_out = __kmp_node_ref(node);
            } else
                info->last_ins = __kmp_add_node(thread, info->
      last_ins, node);
        }
    }
    KA_TRACE(30, ("__kmp_process_deps<%d>: T#%d found %d predecessors\n", filter, gtid,
      npredecessors));
    return npredecessors;
}
void __kmp_release_deps (kmp_int32 gtid, kmp_taskdata_t * task)
Definition at line 363 of file kmp_taskdeps.cpp.
Referenced by __kmp_task_finish().
{
    kmp_info_t *thread = __kmp_threads[ gtid ];
    kmp_depnode_t *node = task->td_depnode;
    if (task->td_dephash) {
        KA_TRACE(40, ("__kmp_realease_deps: T#%d freeing dependencies hash of task %p.\n", gtid,
      task));
        __kmp_dephash_free(thread,task->td_dephash);
    }
    if (!node) return;
    KA_TRACE(20, ("__kmp_realease_deps: T#%d notifying succesors of task %p.\n", gtid, task));
    
    KMP_ACQUIRE_DEPNODE(gtid,node);
    node->dn.task = NULL; // mark this task as finished, so no new dependencies are generated
    KMP_RELEASE_DEPNODE(gtid,node);
    kmp_depnode_list_t *next;
    for (kmp_depnode_list_t *p = node->dn.successors;
      p; p = next) {
        kmp_depnode_t *successor = p->node;
        kmp_int32 npredecessors = KMP_TEST_THEN_DEC32(&successor->
      dn.npredecessors) - 1;
        // successor task can be NULL for wait_depends or because deps are still being processed
        if (npredecessors == 0) {
            KMP_MB();
            if (successor->dn.task) {
                KA_TRACE(20, ("__kmp_realease_deps: T#%d successor %p of %p scheduled for
       execution.\n", gtid, successor->dn.task, task));
                __kmp_omp_task(gtid,successor->dn.task,false);
            }
        }
        next = p->next;
        __kmp_node_deref(thread,p->node);
#if USE_FAST_MEMORY
        __kmp_fast_free(thread,p);
#else
        __kmp_thread_free(thread,p);
#endif
    }
    __kmp_node_deref(thread,node);
    KA_TRACE(20, ("__kmp_realease_deps: T#%d all successors of %p notified of completation\n", gtid
      , task));
}
static void __kmp_track_dependence (kmp_depnode_t * source, kmp_depnode_t * sink, kmp_task_t * sink_task) [inline], [static]
Definition at line 210 of file kmp_taskdeps.cpp.
Referenced by __kmp_process_deps().
{
#ifdef KMP_SUPPORT_GRAPH_OUTPUT
    kmp_taskdata_t * task_source = KMP_TASK_TO_TASKDATA(source->
      dn.task);
    kmp_taskdata_t * task_sink = KMP_TASK_TO_TASKDATA(sink->
      dn.task); // this can be NULL when if(0) ...
    __kmp_printf("%d(%s) -> %d(%s)\n", source->dn.id, task_source->
      td_ident->psource, sink->dn.id, task_sink->td_ident->
      psource);
#endif
#if OMPT_SUPPORT && OMPT_TRACE
    /* OMPT tracks dependences between task (a=source, b=sink) in which
       task a blocks the execution of b through the ompt_new_dependence_callback */
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_task_dependence_pair))
    {
        kmp_taskdata_t * task_source = KMP_TASK_TO_TASKDATA(source->
      dn.task);
        kmp_taskdata_t * task_sink = KMP_TASK_TO_TASKDATA(sink_task);
        ompt_callbacks.ompt_callback(ompt_event_task_dependence_pair)(
          task_source->ompt_task_info.task_id,
          task_sink->ompt_task_info.task_id);
    }
#endif /* OMPT_SUPPORT && OMPT_TRACE */
}