ompt-specific.c File Reference
#include `kmp.h`
*
#include `ompt-internal.h`
*
#include `ompt-specific.h`
*
Macros
#define GTID_TO_OMPT_THREAD_ID(id) ((ompt_thread_id_t) (id >=0) ? id + 1: 0)
#define LWT_FROM_TEAM(team) (team)->t.ompt_serialized_team_info;
#define OMPT_THREAD_ID_BITS 16
#define NEXT_ID(id_ptr, tid) (KMP_TEST_THEN_INC64((volatile kmp_int64 *)id_ptr))
Functions
ompt_team_info_t * __ompt_get_teaminfo (int depth, int *size)
ompt_task_info_t * __ompt_get_taskinfo (int depth)
ompt_parallel_id_t __ompt_thread_id_new ()
void __ompt_thread_begin (ompt_thread_type_t thread_type, int gtid)
void __ompt_thread_end (ompt_thread_type_t thread_type, int gtid)
ompt_thread_id_t __ompt_get_thread_id_internal ()
void __ompt_thread_assign_wait_id (void *variable)
ompt_state_t __ompt_get_state_internal (ompt_wait_id_t *ompt_wait_id)
void * __ompt_get_idle_frame_internal (void)
ompt_parallel_id_t __ompt_parallel_id_new (int gtid)
void * __ompt_get_parallel_function_internal (int depth)
ompt_parallel_id_t __ompt_get_parallel_id_internal (int depth)
int __ompt_get_parallel_team_size_internal (int depth)
void __ompt_lw_taskteam_init (ompt_lw_taskteam_t *lwt, kmp_info_t *thr, int gtid, void *microtask, ompt_parallel_id_t ompt_pid)
void __ompt_lw_taskteam_link (ompt_lw_taskteam_t *lwt, kmp_info_t *thr)
ompt_lw_taskteam_t * __ompt_lw_taskteam_unlink (kmp_info_t *thr)
ompt_task_id_t __ompt_task_id_new (int gtid)
ompt_task_id_t __ompt_get_task_id_internal (int depth)
void * __ompt_get_task_function_internal (int depth)
ompt_frame_t * __ompt_get_task_frame_internal (int depth)
void __ompt_team_assign_id (kmp_team_t *team, ompt_parallel_id_t ompt_pid)
Macro Definition Documentation
#define GTID_TO_OMPT_THREAD_ID(id) ((ompt_thread_id_t) (id >=0) ? id + 1: 0)
Definition at line 13 of file ompt-specific.c.
Referenced by __ompt_get_thread_id_internal(), __ompt_thread_begin(), and __ompt_thread_end().
#define LWT_FROM_TEAM(team) (team)->t.ompt_serialized_team_info;
Definition at line 15 of file ompt-specific.c.
Referenced by __ompt_get_taskinfo(), and __ompt_get_teaminfo().
#define NEXT_ID(id_ptr, tid) (KMP_TEST_THEN_INC64((volatile kmp_int64 *)id_ptr))
Definition at line 32 of file ompt-specific.c.
Referenced by __ompt_parallel_id_new(), __ompt_task_id_new(), and __ompt_thread_id_new().
#define OMPT_THREAD_ID_BITS 16
Definition at line 17 of file ompt-specific.c.
Function Documentation
void* __ompt_get_idle_frame_internal (void)
Definition at line 199 of file ompt-specific.c.
Referenced by ompt_get_idle_frame().
{
    kmp_info_t *ti = ompt_get_thread();
    return ti ? ti->th.ompt_thread_info.idle_frame : NULL;
}
void* __ompt_get_parallel_function_internal (int depth)
Definition at line 219 of file ompt-specific.c.
Referenced by ompt_get_parallel_function().
{
    ompt_team_info_t *info = __ompt_get_teaminfo(depth, NULL);
    void *function = info ? info->microtask : NULL;
    return function;
}
ompt_parallel_id_t __ompt_get_parallel_id_internal (int depth)
Definition at line 228 of file ompt-specific.c.
Referenced by ompt_get_parallel_id().
{
    ompt_team_info_t *info = __ompt_get_teaminfo(depth, NULL);
    ompt_parallel_id_t id = info ? info->parallel_id : 0;
    return id;
}
int __ompt_get_parallel_team_size_internal (int depth)
Definition at line 237 of file ompt-specific.c.
Referenced by ompt_get_parallel_team_size().
{
    // initialize the return value with the error value.
    // if there is a team at the specified depth, the default
    // value will be overwritten the size of that team.
    int size = -1;
    (void) __ompt_get_teaminfo(depth, &size);
    return size;
}
ompt_state_t __ompt_get_state_internal (ompt_wait_id_t * ompt_wait_id)
Definition at line 182 of file ompt-specific.c.
Referenced by ompt_get_state().
{
    kmp_info_t *ti = ompt_get_thread();
    if (ti) {
        if (ompt_wait_id)
            *ompt_wait_id = ti->th.ompt_thread_info.wait_id;
        return ti->th.ompt_thread_info.state;
    }
    return ompt_state_undefined;
}
ompt_frame_t* __ompt_get_task_frame_internal (int depth)
Definition at line 316 of file ompt-specific.c.
Referenced by __kmp_fork_call(), __kmp_GOMP_microtask_wrapper(), __kmp_GOMP_parallel_microtask_wrapper(), KMP_API_NAME_GOMP_PARALLEL_END(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS_START(), KMP_API_NAME_GOMP_PARALLEL_START(), and ompt_get_task_frame().
{
    ompt_task_info_t *info = __ompt_get_taskinfo(depth);
    ompt_frame_t *frame = info ? frame = &info->frame : NULL;
    return frame;
}
void* __ompt_get_task_function_internal (int depth)
Definition at line 307 of file ompt-specific.c.
Referenced by ompt_get_task_function().
{
    ompt_task_info_t *info = __ompt_get_taskinfo(depth);
    void *function = info ? info->function : NULL;
    return function;
}
ompt_task_id_t __ompt_get_task_id_internal (int depth)
Definition at line 298 of file ompt-specific.c.
Referenced by __kmp_fork_call(), and ompt_get_task_id().
{
    ompt_task_info_t *info = __ompt_get_taskinfo(depth);
    ompt_task_id_t task_id = info ? info->task_id : 0;
    return task_id;
}
ompt_task_info_t* __ompt_get_taskinfo (int depth)
Definition at line 88 of file ompt-specific.c.
Referenced by __kmp_for_static_init(), __kmp_GOMP_fork_call(), __kmp_GOMP_serialized_parallel(), __kmp_join_call(), __kmp_launch_thread(), __ompt_get_task_frame_internal(), __ompt_get_task_function_internal(), __ompt_get_task_id_internal(), and KMP_API_NAME_GOMP_PARALLEL_END().
{
    ompt_task_info_t *info = NULL;
    kmp_info_t *thr = ompt_get_thread();
    if (thr) {
        kmp_taskdata_t *taskdata = thr->th.th_current_task;
        ompt_lw_taskteam_t *lwt = LWT_FROM_TEAM(taskdata->
      td_team);
        while (depth > 0) {
            // next lightweight team (if any)
            if (lwt) lwt = lwt->parent;
            // next heavyweight team (if any) after
            // lightweight teams are exhausted
            if (!lwt && taskdata) {
                taskdata = taskdata->td_parent;
                if (taskdata) {
                    lwt = LWT_FROM_TEAM(taskdata->td_team);
                }
            }
            depth--;
        }
        if (lwt) {
            info = &lwt->ompt_task_info;
        } else if (taskdata) {
            info = &taskdata->ompt_task_info;
        }
    }
    return info;
}
ompt_team_info_t* __ompt_get_teaminfo (int depth, int * size)
Definition at line 47 of file ompt-specific.c.
Referenced by __kmp_for_static_init(), __kmp_GOMP_fork_call(), __ompt_get_parallel_function_internal(), __ompt_get_parallel_id_internal(), __ompt_get_parallel_team_size_internal(), and KMP_API_NAME_GOMP_PARALLEL_END().
{
    kmp_info_t *thr = ompt_get_thread();
    if (thr) {
        kmp_team *team = thr->th.th_team;
        if (team == NULL) return NULL;
        ompt_lw_taskteam_t *lwt = LWT_FROM_TEAM(team);
        while(depth > 0) {
            // next lightweight team (if any)
            if (lwt) lwt = lwt->parent;
            // next heavyweight team (if any) after
            // lightweight teams are exhausted
            if (!lwt && team) team=team->t.t_parent;
            depth--;
        }
        if (lwt) {
            // lightweight teams have one task
            if (size) *size = 1;
            // return team info for lightweight team
            return &lwt->ompt_team_info;
        } else if (team) {
            // extract size from heavyweight team
            if (size) *size = team->t.t_nproc;
            // return team info for heavyweight team
            return &team->t.ompt_team_info;
        }
    }
    return NULL;
}
ompt_thread_id_t __ompt_get_thread_id_internal ()
Definition at line 156 of file ompt-specific.c.
Referenced by ompt_get_thread_id().
{
    // FIXME
    // until we have a better way of assigning ids, use __kmp_get_gtid
    // since the return value might be negative, we need to test that before
    // assigning it to an ompt_thread_id_t, which is unsigned.
    int id = __kmp_get_gtid();
    assert(id >= 0);
    return GTID_TO_OMPT_THREAD_ID(id);
}
void __ompt_lw_taskteam_init (ompt_lw_taskteam_t * lwt, kmp_info_t * thr, int gtid, void * microtask, ompt_parallel_id_t ompt_pid)
Definition at line 253 of file ompt-specific.c.
Referenced by __kmp_fork_call(), and __kmp_GOMP_serialized_parallel().
{
    lwt->ompt_team_info.parallel_id = ompt_pid;
    lwt->ompt_team_info.microtask = microtask;
    lwt->ompt_task_info.task_id = 0;
    lwt->ompt_task_info.frame.reenter_runtime_frame = 0;
    lwt->ompt_task_info.frame.exit_runtime_frame = 0;
    lwt->ompt_task_info.function = NULL;
    lwt->parent = 0;
}
void __ompt_lw_taskteam_link (ompt_lw_taskteam_t * lwt, kmp_info_t * thr)
Definition at line 268 of file ompt-specific.c.
Referenced by __kmp_fork_call(), and __kmp_GOMP_serialized_parallel().
{
    ompt_lw_taskteam_t *my_parent = thr->th.th_team->t.ompt_serialized_team_info;
    lwt->parent = my_parent;
    thr->th.th_team->t.ompt_serialized_team_info = lwt;
}
ompt_lw_taskteam_t* __ompt_lw_taskteam_unlink (kmp_info_t * thr)
Definition at line 277 of file ompt-specific.c.
Referenced by __kmp_fork_call(), and KMP_API_NAME_GOMP_PARALLEL_END().
{
    ompt_lw_taskteam_t *lwtask = thr->th.th_team->t.ompt_serialized_team_info;
    if (lwtask) thr->th.th_team->t.ompt_serialized_team_info = lwtask->parent;
    return lwtask;
}
ompt_parallel_id_t __ompt_parallel_id_new (int gtid)
Definition at line 211 of file ompt-specific.c.
Referenced by __kmp_fork_call(), __kmp_GOMP_serialized_parallel(), and __kmp_serialized_parallel().
{
    static uint64_t ompt_parallel_id = 1;
    return gtid >= 0 ? NEXT_ID(&ompt_parallel_id, gtid) : 0;
}
ompt_task_id_t __ompt_task_id_new (int gtid)
Definition at line 290 of file ompt-specific.c.
Referenced by __kmp_fork_call(), __kmp_GOMP_serialized_parallel(), and __kmp_launch_thread().
{
    static uint64_t ompt_task_id = 1;
    return NEXT_ID(&ompt_task_id, gtid);
}
void __ompt_team_assign_id (kmp_team_t * team, ompt_parallel_id_t ompt_pid)
Definition at line 329 of file ompt-specific.c.
Referenced by __kmp_allocate_team(), and __kmp_serialized_parallel().
{
    team->t.ompt_team_info.parallel_id = ompt_pid;
}
void __ompt_thread_assign_wait_id (void * variable)
Definition at line 173 of file ompt-specific.c.
Referenced by KMP_API_NAME_GOMP_ATOMIC_START().
{
    int gtid = __kmp_gtid_get_specific();
    kmp_info_t *ti = ompt_get_thread_gtid(gtid);
    ti->th.ompt_thread_info.wait_id = (ompt_wait_id_t) variable;
}
void __ompt_thread_begin (ompt_thread_type_t thread_type, int gtid)
Definition at line 140 of file ompt-specific.c.
Referenced by __kmp_launch_thread().
{
    ompt_callbacks.ompt_callback(ompt_event_thread_begin)(
        thread_type, GTID_TO_OMPT_THREAD_ID(gtid));
}
void __ompt_thread_end (ompt_thread_type_t thread_type, int gtid)
Definition at line 148 of file ompt-specific.c.
Referenced by __kmp_launch_thread(), and __kmp_reset_root().
{
    ompt_callbacks.ompt_callback(ompt_event_thread_end)(
        thread_type, GTID_TO_OMPT_THREAD_ID(gtid));
}
ompt_parallel_id_t __ompt_thread_id_new ()
Definition at line 133 of file ompt-specific.c.
{
    static uint64_t ompt_thread_id = 1;
    return NEXT_ID(&ompt_thread_id, 0);
}