timeStat Class Reference
#include <kmp_stats.h>
Public Member Functions
timeStat ()
Static Public Member Functions
static const char * name (timer_e e)
static bool noTotal (timer_e e)
static bool masterOnly (timer_e e)
static bool workerOnly (timer_e e)
static bool noUnits (timer_e e)
static bool logEvent (timer_e e)
static void clearEventFlags ()
Static Private Attributes
static statInfo timerInfo []
Detailed Description
Definition at line 271 of file kmp_stats.h.
Constructor & Destructor Documentation
timeStat::timeStat () [inline]
Definition at line 276 of file kmp_stats.h.
: statistic() {}
Member Function Documentation
static void timeStat::clearEventFlags () [inline], [static]
Definition at line 283 of file kmp_stats.h.
Referenced by kmp_stats_output_module::init().
                                        {
        for(int i=0;i<TIMER_LAST;i++) {
            timerInfo[i].flags &= (~(stats_flags_e::logEvent));
        }
    }
static bool timeStat::logEvent (timer_e e) [inline], [static]
Definition at line 282 of file kmp_stats.h.
Referenced by kmp_stats_output_module::printPloticusFile(), kmp_stats_output_module::setupEventColors(), explicitTimer::start(), and explicitTimer::stop().
{ return timerInfo[e].flags & stats_flags_e::logEvent; }
static bool timeStat::masterOnly (timer_e e) [inline], [static]
Definition at line 279 of file kmp_stats.h.
Referenced by kmp_stats_output_module::outputStats().
{ return timerInfo[e].flags & stats_flags_e::onlyInMaster; }
static const char* timeStat::name (timer_e e) [inline], [static]
Definition at line 277 of file kmp_stats.h.
Referenced by kmp_stats_output_module::printEvents(), kmp_stats_output_module::printPloticusFile(), and kmp_stats_output_module::printTimerStats().
{ return timerInfo[e].name; }
static bool timeStat::noTotal (timer_e e) [inline], [static]
Definition at line 278 of file kmp_stats.h.
Referenced by kmp_stats_output_module::outputStats(), and kmp_stats_output_module::printTimerStats().
{ return timerInfo[e].flags & stats_flags_e::noTotal; }
static bool timeStat::noUnits (timer_e e) [inline], [static]
Definition at line 281 of file kmp_stats.h.
Referenced by kmp_stats_output_module::printTimerStats().
{ return timerInfo[e].flags & stats_flags_e::noUnits; }
static bool timeStat::workerOnly (timer_e e) [inline], [static]
Definition at line 280 of file kmp_stats.h.
Referenced by kmp_stats_output_module::outputStats().
{ return timerInfo[e].flags & stats_flags_e::notInMaster; }
Member Data Documentation
statInfo timeStat::timerInfo [static], [private]
Initial value:
= {
    KMP_FOREACH_TIMER(expandName,0)
    {0,0}
}
Definition at line 273 of file kmp_stats.h.
Referenced by clearEventFlags(), logEvent(), masterOnly(), name(), noTotal(), noUnits(), and workerOnly().
The documentation for this class was generated from the following files:
kmp_stats.h
kmp_stats.cpp