kmp_stats_list Class Reference
#include <kmp_stats.h>
Classes
class iterator
Public Member Functions
kmp_stats_list ()
~kmp_stats_list ()
timeStat * getTimer (timer_e idx)
counter * getCounter (counter_e idx)
explicitTimer * getExplicitTimer (explicit_timer_e idx)
timeStat * getTimers ()
counter * getCounters ()
explicitTimer * getExplicitTimers ()
kmp_stats_event_vector & getEventVector ()
void resetEventVector ()
void incrementNestValue ()
int getNestValue ()
void decrementNestValue ()
int getGtid () const
void setGtid (int newgtid)
kmp_stats_list * push_back (int gtid)
void push_event (uint64_t start_time, uint64_t stop_time, int nest_level, timer_e name)
void deallocate ()
kmp_stats_list::iterator begin ()
kmp_stats_list::iterator end ()
int size ()
Private Attributes
int gtid
timeStat _timers [TIMER_LAST+1]
counter _counters [COUNTER_LAST+1]
explicitTimer _explicitTimers [EXPLICIT_TIMER_LAST+1]
int _nestLevel
kmp_stats_event_vector _event_vector
kmp_stats_list * next
kmp_stats_list * prev
Detailed Description
Definition at line 471 of file kmp_stats.h.
Constructor & Destructor Documentation
kmp_stats_list::kmp_stats_list () [inline]
Definition at line 481 of file kmp_stats.h.
Referenced by push_back().
                     : next(this) , prev(this) , _event_vector(),
      _nestLevel(0) {
#define doInit(name,ignore1,ignore2) \
        getExplicitTimer(EXPLICIT_TIMER_##name)->setStat(getTimer(TIMER_##name));
        KMP_FOREACH_EXPLICIT_TIMER(doInit,0);
#undef doInit
    }
kmp_stats_list::~kmp_stats_list () [inline]
Definition at line 487 of file kmp_stats.h.
Referenced by deallocate().
{ }
Member Function Documentation
kmp_stats_list::iterator kmp_stats_list::begin ()
Definition at line 239 of file kmp_stats.cpp.
Referenced by __kmp_reset_stats(), kmp_stats_output_module::outputStats(), size(), and kmp_stats_output_module::windupExplicitTimers().
                                             {
    kmp_stats_list::iterator it;
    it.ptr = this->next;
    return it;
}
void kmp_stats_list::deallocate ()
Definition at line 227 of file kmp_stats.cpp.
Referenced by __kmp_cleanup().
                                {
    kmp_stats_list* ptr = this->next;
    kmp_stats_list* delptr = this->next;
    while(ptr != this) {
        delptr = ptr;
        ptr=ptr->next;
        // placement new means we have to explicitly call destructor.
        delptr->_event_vector.deallocate();
        delptr->~kmp_stats_list();
        __kmp_free(delptr);
    }
}
void kmp_stats_list::decrementNestValue () [inline]
Definition at line 498 of file kmp_stats.h.
Referenced by explicitTimer::stop().
{ _nestLevel--; }
kmp_stats_list::iterator kmp_stats_list::end ()
Definition at line 244 of file kmp_stats.cpp.
Referenced by __kmp_reset_stats(), kmp_stats_output_module::outputStats(), size(), and kmp_stats_output_module::windupExplicitTimers().
                                           {
    kmp_stats_list::iterator it;
    it.ptr = this;
    return it;
}
counter* kmp_stats_list::getCounter (counter_e idx) [inline]
Definition at line 489 of file kmp_stats.h.
{ return &_counters[idx]; }
counter* kmp_stats_list::getCounters () [inline]
Definition at line 492 of file kmp_stats.h.
{ return _counters; }
kmp_stats_event_vector& kmp_stats_list::getEventVector () [inline]
Definition at line 494 of file kmp_stats.h.
{ return _event_vector; }
explicitTimer* kmp_stats_list::getExplicitTimer (explicit_timer_e idx) [inline]
Definition at line 490 of file kmp_stats.h.
{ return &_explicitTimers[idx]; }
explicitTimer* kmp_stats_list::getExplicitTimers () [inline]
Definition at line 493 of file kmp_stats.h.
{ return _explicitTimers; }
int kmp_stats_list::getGtid () const [inline]
Definition at line 499 of file kmp_stats.h.
{ return gtid; }
int kmp_stats_list::getNestValue () [inline]
Definition at line 497 of file kmp_stats.h.
Referenced by explicitTimer::stop().
{ return _nestLevel; }
timeStat* kmp_stats_list::getTimer (timer_e idx) [inline]
Definition at line 488 of file kmp_stats.h.
{ return &_timers[idx]; }
timeStat* kmp_stats_list::getTimers () [inline]
Definition at line 491 of file kmp_stats.h.
{ return _timers; }
void kmp_stats_list::incrementNestValue () [inline]
Definition at line 496 of file kmp_stats.h.
Referenced by explicitTimer::start().
{ _nestLevel++; }
kmp_stats_list * kmp_stats_list::push_back (int gtid)
Definition at line 216 of file kmp_stats.cpp.
Referenced by __kmp_create_worker().
                                                  {
    kmp_stats_list* newnode = (kmp_stats_list*)
      __kmp_allocate(sizeof(kmp_stats_list));
    // placement new, only requires space and pointer and initializes (so __kmp_allocate instead of C++
       new[] is used)
    new (newnode) kmp_stats_list();
    newnode->setGtid(gtid);
    newnode->prev = this->prev;
    newnode->next = this;
    newnode->prev->next = newnode;
    newnode->next->prev = newnode;
    return newnode;
}
void kmp_stats_list::push_event (uint64_t start_time, uint64_t stop_time, int nest_level, timer_e name) [inline]
Definition at line 502 of file kmp_stats.h.
Referenced by explicitTimer::stop().
                                                                                                      {
        _event_vector.push_back(start_time, stop_time, nest_level,
      name);
    }
void kmp_stats_list::resetEventVector () [inline]
Definition at line 495 of file kmp_stats.h.
{ _event_vector.reset(); }
void kmp_stats_list::setGtid (int newgtid) [inline]
Definition at line 500 of file kmp_stats.h.
Referenced by push_back().
{ gtid = newgtid; }
int kmp_stats_list::size ()
Definition at line 249 of file kmp_stats.cpp.
Referenced by kmp_stats_output_module::printPloticusFile().
                         {
    int retval;
    kmp_stats_list::iterator it;
    for(retval=0, it=begin(); it!=end(); it++, retval++) {}
    return retval;
}
Member Data Documentation
counter kmp_stats_list::_counters[COUNTER_LAST+1] [private]
Definition at line 474 of file kmp_stats.h.
Referenced by getCounter(), and getCounters().
kmp_stats_event_vector kmp_stats_list::_event_vector [private]
Definition at line 477 of file kmp_stats.h.
Referenced by deallocate(), getEventVector(), push_event(), and resetEventVector().
explicitTimer kmp_stats_list::_explicitTimers[EXPLICIT_TIMER_LAST+1] [private]
Definition at line 475 of file kmp_stats.h.
Referenced by getExplicitTimer(), and getExplicitTimers().
int kmp_stats_list::_nestLevel [private]
Definition at line 476 of file kmp_stats.h.
Referenced by decrementNestValue(), getNestValue(), and incrementNestValue().
timeStat kmp_stats_list::_timers[TIMER_LAST+1] [private]
Definition at line 473 of file kmp_stats.h.
Referenced by getTimer(), and getTimers().
int kmp_stats_list::gtid [private]
Definition at line 472 of file kmp_stats.h.
Referenced by getGtid(), and setGtid().
kmp_stats_list* kmp_stats_list::next [private]
Definition at line 478 of file kmp_stats.h.
Referenced by begin(), deallocate(), and push_back().
kmp_stats_list* kmp_stats_list::prev [private]
Definition at line 479 of file kmp_stats.h.
Referenced by push_back().
The documentation for this class was generated from the following files:
kmp_stats.h
kmp_stats.cpp