counter Class Reference
#include <kmp_stats.h>
Public Member Functions
counter ()
void increment ()
uint64_t getValue () const
void reset ()
Static Public Member Functions
static const char * name (counter_e e)
static bool masterOnly (counter_e e)
Private Attributes
uint64_t value
Static Private Attributes
static const statInfo counterInfo []
Detailed Description
Definition at line 320 of file kmp_stats.h.
Constructor & Destructor Documentation
counter::counter () [inline]
Definition at line 326 of file kmp_stats.h.
: value(0) {}
Member Function Documentation
uint64_t counter::getValue () const [inline]
Definition at line 328 of file kmp_stats.h.
Referenced by kmp_stats_output_module::printCounters().
{ return value; }
void counter::increment () [inline]
Definition at line 327 of file kmp_stats.h.
{ value++; }
static bool counter::masterOnly (counter_e e) [inline], [static]
Definition at line 331 of file kmp_stats.h.
Referenced by kmp_stats_output_module::outputStats().
{ return counterInfo[e].flags & stats_flags_e::onlyInMaster; }
static const char* counter::name (counter_e e) [inline], [static]
Definition at line 330 of file kmp_stats.h.
Referenced by kmp_stats_output_module::printCounters(), and kmp_stats_output_module::printCounterStats().
{ return counterInfo[e].name; }
void counter::reset () [inline]
Definition at line 329 of file kmp_stats.h.
{ value = 0; }
Member Data Documentation
const statInfo counter::counterInfo [static], [private]
Initial value:
= {
    KMP_FOREACH_COUNTER(expandName,0)
    {0,0}
}
Definition at line 323 of file kmp_stats.h.
Referenced by masterOnly(), and name().
uint64_t counter::value [private]
Definition at line 322 of file kmp_stats.h.
Referenced by getValue(), increment(), and reset().
The documentation for this class was generated from the following files:
kmp_stats.h
kmp_stats.cpp