tsc_tick_count Class Reference
#include <kmp_stats_timing.h>
Classes
class tsc_interval_t
Public Member Functions
tsc_tick_count (int64_t value)
int64_t getValue () const
tsc_tick_count later (tsc_tick_count const other) const
tsc_tick_count earlier (tsc_tick_count const other) const
Static Public Member Functions
static tsc_tick_count now ()
Private Attributes
int64_t my_count
Friends
tsc_tick_count::tsc_interval_t operator- (const tsc_tick_count t1, const tsc_tick_count t0)
Detailed Description
Definition at line 28 of file kmp_stats_timing.h.
Constructor & Destructor Documentation
tsc_tick_count::tsc_tick_count (int64_t value) [inline]
Definition at line 57 of file kmp_stats_timing.h.
Referenced by now().
: my_count(value) {};
Member Function Documentation
tsc_tick_count tsc_tick_count::earlier (tsc_tick_count const other) const [inline]
Definition at line 62 of file kmp_stats_timing.h.
                                                             {
        return my_count < other.my_count ? (*this) : other;
    }
int64_t tsc_tick_count::getValue () const [inline]
Definition at line 58 of file kmp_stats_timing.h.
Referenced by explicitTimer::stop().
{ return my_count; }
tsc_tick_count tsc_tick_count::later (tsc_tick_count const other) const [inline]
Definition at line 59 of file kmp_stats_timing.h.
Referenced by computeLastInLastOutInterval().
                                                            {
        return my_count > other.my_count ? (*this) : other;
    }
static tsc_tick_count tsc_tick_count::now () [inline], [static]
Definition at line 68 of file kmp_stats_timing.h.
Referenced by __kmp_create_worker(), timePair::markEnd(), timePair::markStart(), explicitTimer::start(), and explicitTimer::stop().
{ return tsc_tick_count(); } // returns the rdtsc register value
Friends And Related Function Documentation
tsc_tick_count::tsc_interval_t operator- (const tsc_tick_count t1, const tsc_tick_count t0) [friend]
Definition at line 72 of file kmp_stats_timing.h.
{
    return tsc_tick_count::tsc_interval_t(t1.
      my_count-t0.my_count);
}
Member Data Documentation
int64_t tsc_tick_count::my_count [private]
Definition at line 30 of file kmp_stats_timing.h.
Referenced by earlier(), getValue(), later(), and operator-().
The documentation for this class was generated from the following file:
kmp_stats_timing.h