kmp_flag_oncore Class Reference
#include <kmp_wait_release.h>
Public Member Functions
kmp_flag_oncore (volatile kmp_uint64 *p)
kmp_flag_oncore (volatile kmp_uint64 *p, kmp_uint32 idx)
kmp_flag_oncore (volatile kmp_uint64 *p, kmp_uint64 c, kmp_uint32 idx, enum barrier_type bar_t, kmp_info_t *thr)
kmp_info_t * get_waiter (kmp_uint32 i)
kmp_uint32 get_num_waiters ()
void set_waiter (kmp_info_t *thr)
bool done_check_val (kmp_uint64 old_loc)
bool done_check ()
bool notdone_check ()
void internal_release ()
kmp_uint64 set_sleeping ()
kmp_uint64 unset_sleeping ()
bool is_sleeping_val (kmp_uint64 old_loc)
bool is_sleeping ()
bool is_any_sleeping ()
void wait (kmp_info_t *this_thr, int final_spin)
void release ()
void suspend (int th_gtid)
void resume (int th_gtid)
int execute_tasks (kmp_info_t *this_thr, kmp_int32 gtid, int final_spin, int *thread_finished USE_ITT_BUILD_ARG(void *itt_sync_obj), kmp_int32 is_constrained)
kmp_uint8 * get_stolen ()
enum barrier_type get_bt ()
flag_type get_ptr_type ()
Private Member Functions
unsigned char & byteref (volatile kmp_uint64 *loc, size_t offset)
Private Attributes
kmp_uint64 checker
kmp_info_t * waiting_threads [1]
kmp_uint32 num_waiting_threads
kmp_uint32 offset
bool flag_switch
enum barrier_type bt
kmp_info_t * this_thr
Additional Inherited Members
Detailed Description
Definition at line 468 of file kmp_wait_release.h.
Constructor & Destructor Documentation
kmp_flag_oncore::kmp_flag_oncore (volatile kmp_uint64 * p) [inline]
Definition at line 481 of file kmp_wait_release.h.
        : kmp_flag<kmp_uint64>(p, flag_oncore),
      num_waiting_threads(0), flag_switch(false) {}
kmp_flag_oncore::kmp_flag_oncore (volatile kmp_uint64 * p, kmp_uint32 idx) [inline]
Definition at line 483 of file kmp_wait_release.h.
        : kmp_flag<kmp_uint64>(p, flag_oncore),
      num_waiting_threads(0), offset(idx), flag_switch(false) {}
kmp_flag_oncore::kmp_flag_oncore (volatile kmp_uint64 * p, kmp_uint64 c, kmp_uint32 idx, enum barrier_type bar_t, kmp_info_t * thr) [inline]
Definition at line 485 of file kmp_wait_release.h.
        : kmp_flag<kmp_uint64>(p, flag_oncore),
      checker(c), num_waiting_threads(0), offset(idx),
          flag_switch(false), bt(bar_t), this_thr(thr)
#if USE_ITT_BUILD
        , itt_sync_obj(itt)
#endif
        {}
Member Function Documentation
unsigned char& kmp_flag_oncore::byteref (volatile kmp_uint64 * loc, size_t offset) [inline], [private]
Definition at line 479 of file kmp_wait_release.h.
Referenced by done_check_val(), internal_release(), and notdone_check().
{ return ((unsigned char *)loc)[offset]; }
bool kmp_flag_oncore::done_check () [inline]
Definition at line 507 of file kmp_wait_release.h.
{ return done_check_val(*get()); }
bool kmp_flag_oncore::done_check_val (kmp_uint64 old_loc) [inline]
Definition at line 506 of file kmp_wait_release.h.
Referenced by done_check().
{ return byteref(&old_loc,offset) == checker; }
int kmp_flag_oncore::execute_tasks (kmp_info_t * this_thr, kmp_int32 gtid, int final_spin, int *thread_finished USE_ITT_BUILD_ARGvoid *itt_sync_obj, kmp_int32 is_constrained) [inline]
Definition at line 551 of file kmp_wait_release.h.
                                                                                        {
        return __kmp_execute_tasks_oncore(this_thr, gtid, this,
      final_spin, thread_finished
                                          USE_ITT_BUILD_ARG(itt_sync_obj), is_constrained)
      ;
    }
enum barrier_type kmp_flag_oncore::get_bt () [inline]
Definition at line 557 of file kmp_wait_release.h.
{ return bt; }
kmp_uint32 kmp_flag_oncore::get_num_waiters () [inline]
Definition at line 501 of file kmp_wait_release.h.
{ return num_waiting_threads; }
flag_type kmp_flag_oncore::get_ptr_type () [inline]
Definition at line 558 of file kmp_wait_release.h.
{ return flag_oncore; }
kmp_uint8* kmp_flag_oncore::get_stolen () [inline]
Definition at line 556 of file kmp_wait_release.h.
{ return NULL; }
kmp_info_t* kmp_flag_oncore::get_waiter (kmp_uint32 i) [inline]
Definition at line 497 of file kmp_wait_release.h.
                                          {
        KMP_DEBUG_ASSERT(i<num_waiting_threads);
        return waiting_threads[i];
    }
void kmp_flag_oncore::internal_release () [inline]
Definition at line 525 of file kmp_wait_release.h.
                            {
        if (__kmp_dflt_blocktime == KMP_MAX_BLOCKTIME) {
            byteref(get(),offset) = 1;
        }
        else {
            kmp_uint64 mask=0;
            byteref(&mask,offset) = 1;
            (void) KMP_TEST_THEN_OR64((volatile kmp_int64 *)get(), mask);
        }
    }
bool kmp_flag_oncore::is_any_sleeping () [inline]
Definition at line 543 of file kmp_wait_release.h.
{ return is_sleeping_val(*get()); }
bool kmp_flag_oncore::is_sleeping () [inline]
Definition at line 542 of file kmp_wait_release.h.
{ return is_sleeping_val(*get()); }
bool kmp_flag_oncore::is_sleeping_val (kmp_uint64 old_loc) [inline]
Definition at line 541 of file kmp_wait_release.h.
Referenced by is_any_sleeping(), and is_sleeping().
{ return old_loc & KMP_BARRIER_SLEEP_STATE; }
bool kmp_flag_oncore::notdone_check () [inline]
Definition at line 508 of file kmp_wait_release.h.
                         {
        // Calculate flag_switch
        if (this_thr->th.th_bar[bt].bb.wait_flag ==
      KMP_BARRIER_SWITCH_TO_OWN_FLAG)
            flag_switch = true;
        if (byteref(get(),offset) != 1 && !flag_switch)
            return true;
        else if (flag_switch) {
            this_thr->th.th_bar[bt].bb.wait_flag =
      KMP_BARRIER_SWITCHING;
            kmp_flag_64 flag(&this_thr->th.th_bar[bt].bb.b_go, (kmp_uint64)
      KMP_BARRIER_STATE_BUMP);
            __kmp_wait_64(this_thr, &flag, TRUE
#if USE_ITT_BUILD
                          , itt_sync_obj
#endif
                          );
        }
        return false;
    }
void kmp_flag_oncore::release () [inline]
Definition at line 548 of file kmp_wait_release.h.
Referenced by __kmp_hierarchical_barrier_gather().
{ __kmp_release_template(this); }
void kmp_flag_oncore::resume (int th_gtid) [inline]
Definition at line 550 of file kmp_wait_release.h.
{ __kmp_resume_oncore(th_gtid, this); }
kmp_uint64 kmp_flag_oncore::set_sleeping () [inline]
Definition at line 535 of file kmp_wait_release.h.
                              {
        return KMP_TEST_THEN_OR64((kmp_int64 volatile *)get(),
      KMP_BARRIER_SLEEP_STATE);
    }
void kmp_flag_oncore::set_waiter (kmp_info_t * thr) [inline]
Definition at line 502 of file kmp_wait_release.h.
Referenced by __kmp_hierarchical_barrier_gather().
                                     {
        waiting_threads[0] = thr;
        num_waiting_threads = 1;
    }
void kmp_flag_oncore::suspend (int th_gtid) [inline]
Definition at line 549 of file kmp_wait_release.h.
{ __kmp_suspend_oncore(th_gtid, this); }
kmp_uint64 kmp_flag_oncore::unset_sleeping () [inline]
Definition at line 538 of file kmp_wait_release.h.
                                {
        return KMP_TEST_THEN_AND64((kmp_int64 volatile *)get(), ~
      KMP_BARRIER_SLEEP_STATE);
    }
void kmp_flag_oncore::wait (kmp_info_t * this_thr, int final_spin) [inline]
Definition at line 544 of file kmp_wait_release.h.
Referenced by __kmp_hierarchical_barrier_release().
                                                    {
        __kmp_wait_template<kmp_flag_oncore>(this_thr, this, final_spin
                            USE_ITT_BUILD_ARG(itt_sync_obj));
    }
Member Data Documentation
enum barrier_type kmp_flag_oncore::bt [private]
Barrier type.
Definition at line 474 of file kmp_wait_release.h.
Referenced by get_bt(), and notdone_check().
kmp_uint64 kmp_flag_oncore::checker [private]
Definition at line 469 of file kmp_wait_release.h.
Referenced by done_check_val().
bool kmp_flag_oncore::flag_switch [private]
Indicates a switch in flag location.
Definition at line 473 of file kmp_wait_release.h.
Referenced by notdone_check().
kmp_uint32 kmp_flag_oncore::num_waiting_threads [private]
Definition at line 471 of file kmp_wait_release.h.
Referenced by get_num_waiters(), get_waiter(), and set_waiter().
kmp_uint32 kmp_flag_oncore::offset [private]
Portion of flag that is of interest for an operation.
Definition at line 472 of file kmp_wait_release.h.
Referenced by byteref(), done_check_val(), internal_release(), and notdone_check().
kmp_info_t* kmp_flag_oncore::this_thr [private]
Thread that may be redirected to different flag location.
Definition at line 475 of file kmp_wait_release.h.
Referenced by wait().
kmp_info_t* kmp_flag_oncore::waiting_threads[1] [private]
Definition at line 470 of file kmp_wait_release.h.
Referenced by get_waiter(), and set_waiter().
The documentation for this class was generated from the following file:
kmp_wait_release.h