timePair Class Reference
#include <kmp_stats_timing.h>
Public Member Functions
timePair ()
tsc_tick_count get_start () const
tsc_tick_count get_end () const
tsc_tick_count * get_startp ()
tsc_tick_count * get_endp ()
void markStart ()
void markEnd ()
void set_start (tsc_tick_count s)
void set_end (tsc_tick_count e)
tsc_tick_count::tsc_interval_t duration () const
std::string format () const
Private Attributes
tsc_tick_count KMP_ALIGN_CACHE start
tsc_tick_count end
Detailed Description
Definition at line 96 of file kmp_stats_timing.h.
Constructor & Destructor Documentation
timePair::timePair () [inline]
Definition at line 102 of file kmp_stats_timing.h.
: start(-std::numeric_limits<int64_t>::max()), end(-std::numeric_limits<int64_t>::max()) {}
Member Function Documentation
tsc_tick_count::tsc_interval_t timePair::duration () const [inline]
Definition at line 113 of file kmp_stats_timing.h.
Referenced by computeLastInLastOutInterval().
{ return end-start; }
std::string timePair::format () const
Definition at line 161 of file kmp_stats_timing.cpp.
{
    std::ostringstream oss;
    oss << start.getValue() << ":" << end.getValue() << " = " << (
      end-start).getValue();
    return oss.str();
}
tsc_tick_count timePair::get_end () const [inline]
Definition at line 104 of file kmp_stats_timing.h.
{ return end; }
tsc_tick_count* timePair::get_endp () [inline]
Definition at line 106 of file kmp_stats_timing.h.
Referenced by computeLastInLastOutInterval().
{ return &end; }
tsc_tick_count timePair::get_start () const [inline]
Definition at line 103 of file kmp_stats_timing.h.
{ return start; }
tsc_tick_count* timePair::get_startp () [inline]
Definition at line 105 of file kmp_stats_timing.h.
Referenced by computeLastInLastOutInterval().
{ return &start; }
void timePair::markEnd () [inline]
Definition at line 109 of file kmp_stats_timing.h.
{ end = tsc_tick_count::now(); }
void timePair::markStart () [inline]
Definition at line 108 of file kmp_stats_timing.h.
{ start = tsc_tick_count::now(); }
void timePair::set_end (tsc_tick_count e) [inline]
Definition at line 111 of file kmp_stats_timing.h.
{ end = e; }
void timePair::set_start (tsc_tick_count s) [inline]
Definition at line 110 of file kmp_stats_timing.h.
{ start = s; }
Member Data Documentation
tsc_tick_count timePair::end [private]
Definition at line 99 of file kmp_stats_timing.h.
tsc_tick_count KMP_ALIGN_CACHE timePair::start [private]
Definition at line 98 of file kmp_stats_timing.h.
The documentation for this class was generated from the following files:
kmp_stats_timing.h
kmp_stats_timing.cpp