Deprecated Functions
Functions
kmp_int32 __kmpc_ok_to_fork (ident_t *loc)
Detailed Description
Functions in this group are for backwards compatibility only, and should not be used in new code.
Function Documentation
kmp_int32 __kmpc_ok_to_fork (ident_t * loc)
Parameters
loc location description
This function need not be called. It always returns TRUE.
Definition at line 161 of file kmp_csupport.c.
Referenced by KMP_API_NAME_GOMP_PARALLEL(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS_START(), and KMP_API_NAME_GOMP_PARALLEL_START().
{
#ifndef KMP_DEBUG
    return TRUE;
#else
    const char *semi2;
    const char *semi3;
    int line_no;
    if (__kmp_par_range == 0) {
        return TRUE;
    }
    semi2 = loc->psource;
    if (semi2 == NULL) {
        return TRUE;
    }
    semi2 = strchr(semi2, ';');
    if (semi2 == NULL) {
        return TRUE;
    }
    semi2 = strchr(semi2 + 1, ';');
    if (semi2 == NULL) {
        return TRUE;
    }
    if (__kmp_par_range_filename[0]) {
        const char *name = semi2 - 1;
        while ((name > loc->psource) && (*name != '/') && (*name != ';')) {
            name--;
        }
        if ((*name == '/') || (*name == ';')) {
            name++;
        }
        if (strncmp(__kmp_par_range_filename, name, semi2 - name)) {
            return __kmp_par_range < 0;
        }
    }
    semi3 = strchr(semi2 + 1, ';');
    if (__kmp_par_range_routine[0]) {
        if ((semi3 != NULL) && (semi3 > semi2)
          && (strncmp(__kmp_par_range_routine, semi2 + 1, semi3 - semi2 - 1))) {
            return __kmp_par_range < 0;
        }
    }
    if (KMP_SSCANF(semi3 + 1, "%d", &line_no) == 1) {
        if ((line_no >= __kmp_par_range_lb) && (line_no <= __kmp_par_range_ub)) {
            return __kmp_par_range > 0;
        }
        return __kmp_par_range < 0;
    }
    return TRUE;
#endif /* KMP_DEBUG */
}