Work Sharing
Enumerations
enum sched_type {
*
kmp_sch_lower = 32,
kmp_sch_static_chunked = 33,
kmp_sch_static = 34,
kmp_sch_dynamic_chunked = 35,
*
kmp_sch_guided_chunked = 36,
kmp_sch_runtime = 37,
kmp_sch_auto = 38,
kmp_sch_trapezoidal = 39,
*
kmp_sch_static_greedy = 40,
kmp_sch_static_balanced = 41,
kmp_sch_guided_iterative_chunked = 42,
kmp_sch_guided_analytical_chunked = 43,
*
kmp_sch_static_steal = 44,
kmp_sch_upper = 45,
kmp_ord_lower = 64,
kmp_ord_static_chunked = 65,
*
kmp_ord_static = 66,
kmp_ord_dynamic_chunked = 67,
kmp_ord_guided_chunked = 68,
kmp_ord_runtime = 69,
*
kmp_ord_auto = 70,
kmp_ord_trapezoidal = 71,
kmp_ord_upper = 72,
kmp_distribute_static_chunked = 91,
*
kmp_distribute_static = 92,
kmp_nm_lower = 160,
kmp_nm_static_chunked = (kmp_sch_static_chunked - kmp_sch_lower + kmp_nm_lower),
kmp_nm_static = 162,
*
kmp_nm_dynamic_chunked = 163,
kmp_nm_guided_chunked = 164,
kmp_nm_runtime = 165,
kmp_nm_auto = 166,
*
kmp_nm_trapezoidal = 167,
kmp_nm_static_greedy = 168,
kmp_nm_static_balanced = 169,
kmp_nm_guided_iterative_chunked = 170,
*
kmp_nm_guided_analytical_chunked = 171,
kmp_nm_static_steal = 172,
kmp_nm_ord_static_chunked = 193,
kmp_nm_ord_static = 194,
*
kmp_nm_ord_dynamic_chunked = 195,
kmp_nm_ord_guided_chunked = 196,
kmp_nm_ord_runtime = 197,
kmp_nm_ord_auto = 198,
*
kmp_nm_ord_trapezoidal = 199,
kmp_nm_upper = 200,
kmp_sch_default = kmp_sch_static
 }
Functions
kmp_int32 __kmpc_master (ident_t *loc, kmp_int32 global_tid)
void __kmpc_end_master (ident_t *loc, kmp_int32 global_tid)
void __kmpc_ordered (ident_t *loc, kmp_int32 gtid)
void __kmpc_end_ordered (ident_t *loc, kmp_int32 gtid)
void __kmpc_critical (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *crit)
void __kmpc_end_critical (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *crit)
kmp_int32 __kmpc_single (ident_t *loc, kmp_int32 global_tid)
void __kmpc_end_single (ident_t *loc, kmp_int32 global_tid)
void __kmpc_for_static_fini (ident_t *loc, kmp_int32 global_tid)
void __kmpc_dispatch_init_4 (ident_t *loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 lb, kmp_int32 ub, kmp_int32 st, kmp_int32 chunk)
void __kmpc_dispatch_init_4u (ident_t *loc, kmp_int32 gtid, enum sched_type schedule, kmp_uint32 lb, kmp_uint32 ub, kmp_int32 st, kmp_int32 chunk)
void __kmpc_dispatch_init_8 (ident_t *loc, kmp_int32 gtid, enum sched_type schedule, kmp_int64 lb, kmp_int64 ub, kmp_int64 st, kmp_int64 chunk)
void __kmpc_dispatch_init_8u (ident_t *loc, kmp_int32 gtid, enum sched_type schedule, kmp_uint64 lb, kmp_uint64 ub, kmp_int64 st, kmp_int64 chunk)
void __kmpc_dist_dispatch_init_4 (ident_t *loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 *p_last, kmp_int32 lb, kmp_int32 ub, kmp_int32 st, kmp_int32 chunk)
void __kmpc_dist_dispatch_init_4u (ident_t *loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 *p_last, kmp_uint32 lb, kmp_uint32 ub, kmp_int32 st, kmp_int32 chunk)
void __kmpc_dist_dispatch_init_8 (ident_t *loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 *p_last, kmp_int64 lb, kmp_int64 ub, kmp_int64 st, kmp_int64 chunk)
void __kmpc_dist_dispatch_init_8u (ident_t *loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 *p_last, kmp_uint64 lb, kmp_uint64 ub, kmp_int64 st, kmp_int64 chunk)
int __kmpc_dispatch_next_4 (ident_t *loc, kmp_int32 gtid, kmp_int32 *p_last, kmp_int32 *p_lb, kmp_int32 *p_ub, kmp_int32 *p_st)
int __kmpc_dispatch_next_4u (ident_t *loc, kmp_int32 gtid, kmp_int32 *p_last, kmp_uint32 *p_lb, kmp_uint32 *p_ub, kmp_int32 *p_st)
int __kmpc_dispatch_next_8 (ident_t *loc, kmp_int32 gtid, kmp_int32 *p_last, kmp_int64 *p_lb, kmp_int64 *p_ub, kmp_int64 *p_st)
int __kmpc_dispatch_next_8u (ident_t *loc, kmp_int32 gtid, kmp_int32 *p_last, kmp_uint64 *p_lb, kmp_uint64 *p_ub, kmp_int64 *p_st)
void __kmpc_dispatch_fini_4 (ident_t *loc, kmp_int32 gtid)
void __kmpc_dispatch_fini_8 (ident_t *loc, kmp_int32 gtid)
void __kmpc_dispatch_fini_4u (ident_t *loc, kmp_int32 gtid)
void __kmpc_dispatch_fini_8u (ident_t *loc, kmp_int32 gtid)
void __kmpc_for_static_init_4 (ident_t *loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 *plastiter, kmp_int32 *plower, kmp_int32 *pupper, kmp_int32 *pstride, kmp_int32 incr, kmp_int32 chunk)
void __kmpc_for_static_init_4u (ident_t *loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 *plastiter, kmp_uint32 *plower, kmp_uint32 *pupper, kmp_int32 *pstride, kmp_int32 incr, kmp_int32 chunk)
void __kmpc_for_static_init_8 (ident_t *loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 *plastiter, kmp_int64 *plower, kmp_int64 *pupper, kmp_int64 *pstride, kmp_int64 incr, kmp_int64 chunk)
void __kmpc_for_static_init_8u (ident_t *loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 *plastiter, kmp_uint64 *plower, kmp_uint64 *pupper, kmp_int64 *pstride, kmp_int64 incr, kmp_int64 chunk)
void __kmpc_dist_for_static_init_4 (ident_t *loc, kmp_int32 gtid, kmp_int32 schedule, kmp_int32 *plastiter, kmp_int32 *plower, kmp_int32 *pupper, kmp_int32 *pupperD, kmp_int32 *pstride, kmp_int32 incr, kmp_int32 chunk)
void __kmpc_dist_for_static_init_4u (ident_t *loc, kmp_int32 gtid, kmp_int32 schedule, kmp_int32 *plastiter, kmp_uint32 *plower, kmp_uint32 *pupper, kmp_uint32 *pupperD, kmp_int32 *pstride, kmp_int32 incr, kmp_int32 chunk)
void __kmpc_dist_for_static_init_8 (ident_t *loc, kmp_int32 gtid, kmp_int32 schedule, kmp_int32 *plastiter, kmp_int64 *plower, kmp_int64 *pupper, kmp_int64 *pupperD, kmp_int64 *pstride, kmp_int64 incr, kmp_int64 chunk)
void __kmpc_dist_for_static_init_8u (ident_t *loc, kmp_int32 gtid, kmp_int32 schedule, kmp_int32 *plastiter, kmp_uint64 *plower, kmp_uint64 *pupper, kmp_uint64 *pupperD, kmp_int64 *pstride, kmp_int64 incr, kmp_int64 chunk)
void __kmpc_team_static_init_4 (ident_t *loc, kmp_int32 gtid, kmp_int32 *p_last, kmp_int32 *p_lb, kmp_int32 *p_ub, kmp_int32 *p_st, kmp_int32 incr, kmp_int32 chunk)
void __kmpc_team_static_init_4u (ident_t *loc, kmp_int32 gtid, kmp_int32 *p_last, kmp_uint32 *p_lb, kmp_uint32 *p_ub, kmp_int32 *p_st, kmp_int32 incr, kmp_int32 chunk)
void __kmpc_team_static_init_8 (ident_t *loc, kmp_int32 gtid, kmp_int32 *p_last, kmp_int64 *p_lb, kmp_int64 *p_ub, kmp_int64 *p_st, kmp_int64 incr, kmp_int64 chunk)
void __kmpc_team_static_init_8u (ident_t *loc, kmp_int32 gtid, kmp_int32 *p_last, kmp_uint64 *p_lb, kmp_uint64 *p_ub, kmp_int64 *p_st, kmp_int64 incr, kmp_int64 chunk)
Detailed Description
These functions are used for implementing #pragma omp for, #pragma omp sections, #pragma omp single and #pragma omp master constructs.
When handling loops, there are different functions for each of the signed and unsigned 32 and 64 bit integer types which have the name suffixes _4, _4u, _8 and _8u. The semantics of each of the functions is the same, so they are only described once.
Static loop scheduling is handled by __kmpc_for_static_init_4 and friends. Only a single call is needed, since the iterations to be executed by any give thread can be determined as soon as the loop parameters are known.
Dynamic scheduling is handled by the __kmpc_dispatch_init_4 and __kmpc_dispatch_next_4 functions. The init function is called once in each thread outside the loop, while the next function is called each time that the previous chunk of work has been exhausted.
Enumeration Type Documentation
enum sched_type
Describes the loop schedule to be used for a parallel for loop.
Enumerator
kmp_sch_lower
 lower bound for unordered values
kmp_sch_static_chunked
kmp_sch_static
 static unspecialized
kmp_sch_dynamic_chunked
kmp_sch_guided_chunked
 guided unspecialized
kmp_sch_runtime
kmp_sch_auto
 auto
kmp_sch_trapezoidal
kmp_sch_static_greedy
kmp_sch_static_balanced
kmp_sch_guided_iterative_chunked
kmp_sch_guided_analytical_chunked
kmp_sch_static_steal
 accessible only through KMP_SCHEDULE environment variable
kmp_sch_upper
 upper bound for unordered values
kmp_ord_lower
 lower bound for ordered values, must be power of 2
kmp_ord_static_chunked
kmp_ord_static
 ordered static unspecialized
kmp_ord_dynamic_chunked
kmp_ord_guided_chunked
kmp_ord_runtime
kmp_ord_auto
 ordered auto
kmp_ord_trapezoidal
kmp_ord_upper
 upper bound for ordered values
kmp_distribute_static_chunked
 distribute static chunked
kmp_distribute_static
 distribute static unspecialized
kmp_nm_lower
 lower bound for nomerge values
kmp_nm_static_chunked
kmp_nm_static
 static unspecialized
kmp_nm_dynamic_chunked
kmp_nm_guided_chunked
 guided unspecialized
kmp_nm_runtime
kmp_nm_auto
 auto
kmp_nm_trapezoidal
kmp_nm_static_greedy
kmp_nm_static_balanced
kmp_nm_guided_iterative_chunked
kmp_nm_guided_analytical_chunked
kmp_nm_static_steal
kmp_nm_ord_static_chunked
kmp_nm_ord_static
 ordered static unspecialized
kmp_nm_ord_dynamic_chunked
kmp_nm_ord_guided_chunked
kmp_nm_ord_runtime
kmp_nm_ord_auto
 auto
kmp_nm_ord_trapezoidal
kmp_nm_upper
 upper bound for nomerge values
kmp_sch_default
 default scheduling algorithm
Definition at line 301 of file kmp.h.
                {
    kmp_sch_lower = 32, /**< lower bound for unordered values */
    kmp_sch_static_chunked = 33,
    kmp_sch_static = 34, /**< static unspecialized */
    kmp_sch_dynamic_chunked = 35,
    kmp_sch_guided_chunked = 36, /**< guided unspecialized */
    kmp_sch_runtime = 37,
    kmp_sch_auto = 38, /**< auto */
    kmp_sch_trapezoidal = 39,
    /* accessible only through KMP_SCHEDULE environment variable */
    kmp_sch_static_greedy = 40,
    kmp_sch_static_balanced = 41,
    /* accessible only through KMP_SCHEDULE environment variable */
    kmp_sch_guided_iterative_chunked = 42,
    kmp_sch_guided_analytical_chunked = 43,
    kmp_sch_static_steal = 44, /**< accessible only through KMP_SCHEDULE
       environment variable */
    /* accessible only through KMP_SCHEDULE environment variable */
    kmp_sch_upper = 45, /**< upper bound for unordered values */
    kmp_ord_lower = 64, /**< lower bound for ordered values, must be
       power of 2 */
    kmp_ord_static_chunked = 65,
    kmp_ord_static = 66, /**< ordered static unspecialized */
    kmp_ord_dynamic_chunked = 67,
    kmp_ord_guided_chunked = 68,
    kmp_ord_runtime = 69,
    kmp_ord_auto = 70, /**< ordered auto */
    kmp_ord_trapezoidal = 71,
    kmp_ord_upper = 72, /**< upper bound for ordered values */
#if OMP_40_ENABLED
    /* Schedules for Distribute construct */
    kmp_distribute_static_chunked = 91, /**< distribute static chunked
      */
    kmp_distribute_static = 92, /**< distribute static unspecialized */
#endif
    /*
     * For the "nomerge" versions, kmp_dispatch_next*() will always return
     * a single iteration/chunk, even if the loop is serialized. For the
     * schedule types listed above, the entire iteration vector is returned
     * if the loop is serialized. This doesn't work for gcc/gcomp sections.
     */
    kmp_nm_lower = 160, /**< lower bound for nomerge values */
    kmp_nm_static_chunked = (
      kmp_sch_static_chunked - kmp_sch_lower +
      kmp_nm_lower),
    kmp_nm_static = 162, /**< static unspecialized */
    kmp_nm_dynamic_chunked = 163,
    kmp_nm_guided_chunked = 164, /**< guided unspecialized */
    kmp_nm_runtime = 165,
    kmp_nm_auto = 166, /**< auto */
    kmp_nm_trapezoidal = 167,
    /* accessible only through KMP_SCHEDULE environment variable */
    kmp_nm_static_greedy = 168,
    kmp_nm_static_balanced = 169,
    /* accessible only through KMP_SCHEDULE environment variable */
    kmp_nm_guided_iterative_chunked = 170,
    kmp_nm_guided_analytical_chunked = 171,
    kmp_nm_static_steal = 172, /* accessible only through OMP_SCHEDULE
       environment variable */
    kmp_nm_ord_static_chunked = 193,
    kmp_nm_ord_static = 194, /**< ordered static unspecialized */
    kmp_nm_ord_dynamic_chunked = 195,
    kmp_nm_ord_guided_chunked = 196,
    kmp_nm_ord_runtime = 197,
    kmp_nm_ord_auto = 198, /**< auto */
    kmp_nm_ord_trapezoidal = 199,
    kmp_nm_upper = 200, /**< upper bound for nomerge values */
#if OMP_41_ENABLED
    /* Support for OpenMP 4.5 monotonic and nonmonotonic schedule modifiers.
     * Since we need to distinguish the three possible cases (no modifier, monotonic modifier,
     * nonmonotonic modifier), we need separate bits for each modifier.
     * The absence of monotonic does not imply nonmonotonic, especially since 4.5 says
     * that the behaviour of the "no modifier" case is implementation defined in 4.5,
     * but will become "nonmonotonic" in 5.0.
     *
     * Since we're passing a full 32 bit value, we can use a couple of high bits for these
     * flags; out of paranoia we avoid the sign bit.
     *
     * These modifiers can be or-ed into non-static schedules by the compiler to pass
     * the additional information.
     * They will be stripped early in the processing in __kmp_dispatch_init when setting up schedules, so
     * most of the code won't ever see schedules with these bits set.
     */
    kmp_sch_modifier_monotonic = (1<<29), /**< Set if the monotonic schedule modifier was present */
    kmp_sch_modifier_nonmonotonic = (1<<30), /**< Set if the nonmonotonic schedule modifier was present
      */
# define SCHEDULE_WITHOUT_MODIFIERS(s) (enum
      sched_type)((s) & ~ (kmp_sch_modifier_nonmonotonic | kmp_sch_modifier_monotonic))
# define SCHEDULE_HAS_MONOTONIC(s) (((s) & kmp_sch_modifier_monotonic) != 0)
# define SCHEDULE_HAS_NONMONOTONIC(s) (((s) & kmp_sch_modifier_nonmonotonic) != 0)
# define SCHEDULE_HAS_NO_MODIFIERS(s) (((s) & (kmp_sch_modifier_nonmonotonic |
       kmp_sch_modifier_monotonic)) == 0)
#else
    /* By doing this we hope to avoid multiple tests on OMP_41_ENABLED. Compilers can now eliminate tests
       on compile time
     * constants and dead code that results from them, so we can leave code guarded by such an if in place.
     */
# define SCHEDULE_WITHOUT_MODIFIERS(s) (s)
# define SCHEDULE_HAS_MONOTONIC(s) false
# define SCHEDULE_HAS_NONMONOTONIC(s) false
# define SCHEDULE_HAS_NO_MODIFIERS(s) true
#endif
    kmp_sch_default = kmp_sch_static /**< default scheduling algorithm */
};
Function Documentation
void __kmpc_critical (ident_t * loc, kmp_int32 global_tid, kmp_critical_name * crit)
Parameters
loc source location information.
global_tid global thread number .
crit identity of the critical section. This could be a pointer to a lock associated with the critical section, or some other suitably unique value.
Enter code protected by a critical construct. This function blocks until the executing thread can enter the critical section.
Definition at line 1111 of file kmp_csupport.c.
Referenced by KMP_API_NAME_GOMP_CRITICAL_NAME_START(), and KMP_API_NAME_GOMP_CRITICAL_START().
{
#if KMP_USE_DYNAMIC_LOCK
    __kmpc_critical_with_hint(loc, global_tid, crit, omp_lock_hint_none);
#else
    KMP_COUNT_BLOCK(OMP_CRITICAL);
    KMP_TIME_BLOCK(OMP_critical_wait); /* Time spent waiting to enter the critical
       section */
    kmp_user_lock_p lck;
    KC_TRACE(10, ("__kmpc_critical: called T#%d\n", global_tid));
    //TODO: add THR_OVHD_STATE
    KMP_CHECK_USER_LOCK_INIT();
    if ((__kmp_user_lock_kind == lk_tas)
      && (sizeof(lck->tas.lk.poll) <= OMP_CRITICAL_SIZE)) {
        lck = (kmp_user_lock_p)crit;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
      && (sizeof(lck->futex.lk.poll) <= OMP_CRITICAL_SIZE)) {
        lck = (kmp_user_lock_p)crit;
    }
#endif
    else { // ticket, queuing or drdpa
        lck = __kmp_get_critical_section_ptr(crit, loc, global_tid);
    }
    if (__kmp_env_consistency_check)
        __kmp_push_sync(global_tid, ct_critical, loc, lck);
    /* since the critical directive binds to all threads, not just
     * the current team we have to check this even if we are in a
     * serialized team */
    /* also, even if we are the uber thread, we still have to conduct the lock,
     * as we have to contend with sibling threads */
#if USE_ITT_BUILD
    __kmp_itt_critical_acquiring(lck);
#endif /* USE_ITT_BUILD */
    // Value of 'crit' should be good for using as a critical_id of the critical section directive.
    __kmp_acquire_user_lock_with_checks(lck, global_tid);
#if USE_ITT_BUILD
    __kmp_itt_critical_acquired(lck);
#endif /* USE_ITT_BUILD */
    KMP_START_EXPLICIT_TIMER(OMP_critical);
    KA_TRACE(15, ("__kmpc_critical: done T#%d\n", global_tid));
#endif // KMP_USE_DYNAMIC_LOCK
}
void __kmpc_dispatch_fini_4 (ident_t * loc, kmp_int32 gtid)
Parameters
loc Source code location
gtid Global thread id
Mark the end of a dynamic loop.
Definition at line 2476 of file kmp_dispatch.cpp.
{
    __kmp_dispatch_finish< kmp_uint32 >(gtid, loc);
}
void __kmpc_dispatch_fini_4u (ident_t * loc, kmp_int32 gtid)
See __kmpc_dispatch_fini_4
Definition at line 2494 of file kmp_dispatch.cpp.
{
    __kmp_dispatch_finish< kmp_uint32 >(gtid, loc);
}
void __kmpc_dispatch_fini_8 (ident_t * loc, kmp_int32 gtid)
See __kmpc_dispatch_fini_4
Definition at line 2485 of file kmp_dispatch.cpp.
{
    __kmp_dispatch_finish< kmp_uint64 >(gtid, loc);
}
void __kmpc_dispatch_fini_8u (ident_t * loc, kmp_int32 gtid)
See __kmpc_dispatch_fini_4
Definition at line 2503 of file kmp_dispatch.cpp.
{
    __kmp_dispatch_finish< kmp_uint64 >(gtid, loc);
}
void __kmpc_dispatch_init_4 (ident_t * loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 lb, kmp_int32 ub, kmp_int32 st, kmp_int32 chunk)
Parameters
loc Source location
gtid Global thread id
schedule Schedule type
lb Lower bound
ub Upper bound
st Step (or increment if you prefer)
chunk The chunk size to block with
This function prepares the runtime to start a dynamically scheduled for loop, saving the loop arguments. These functions are all identical apart from the types of the arguments.
Definition at line 2334 of file kmp_dispatch.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_dispatch_init< kmp_int32 >(loc, gtid, schedule, lb, ub, st, chunk, true);
}
void __kmpc_dispatch_init_4u (ident_t * loc, kmp_int32 gtid, enum sched_type schedule, kmp_uint32 lb, kmp_uint32 ub, kmp_int32 st, kmp_int32 chunk)
See __kmpc_dispatch_init_4
Definition at line 2344 of file kmp_dispatch.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_dispatch_init< kmp_uint32 >(loc, gtid, schedule, lb, ub, st, chunk, true);
}
void __kmpc_dispatch_init_8 (ident_t * loc, kmp_int32 gtid, enum sched_type schedule, kmp_int64 lb, kmp_int64 ub, kmp_int64 st, kmp_int64 chunk)
See __kmpc_dispatch_init_4
Definition at line 2355 of file kmp_dispatch.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_dispatch_init< kmp_int64 >(loc, gtid, schedule, lb, ub, st, chunk, true);
}
void __kmpc_dispatch_init_8u (ident_t * loc, kmp_int32 gtid, enum sched_type schedule, kmp_uint64 lb, kmp_uint64 ub, kmp_int64 st, kmp_int64 chunk)
See __kmpc_dispatch_init_4
Definition at line 2367 of file kmp_dispatch.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_dispatch_init< kmp_uint64 >(loc, gtid, schedule, lb, ub, st, chunk, true);
}
int __kmpc_dispatch_next_4 (ident_t * loc, kmp_int32 gtid, kmp_int32 * p_last, kmp_int32 * p_lb, kmp_int32 * p_ub, kmp_int32 * p_st)
Parameters
loc Source code location
gtid Global thread id
p_last Pointer to a flag set to one if this is the last chunk or zero otherwise
p_lb Pointer to the lower bound for the next chunk of work
p_ub Pointer to the upper bound for the next chunk of work
p_st Pointer to the stride for the next chunk of work
Returns
one if there is work to be done, zero otherwise
Get the next dynamically allocated chunk of work for this thread. If there is no more work, then the lb,ub and stride need not be modified.
Definition at line 2433 of file kmp_dispatch.cpp.
{
    return __kmp_dispatch_next< kmp_int32 >(loc, gtid, p_last, p_lb, p_ub, p_st);
}
int __kmpc_dispatch_next_4u (ident_t * loc, kmp_int32 gtid, kmp_int32 * p_last, kmp_uint32 * p_lb, kmp_uint32 * p_ub, kmp_int32 * p_st)
See __kmpc_dispatch_next_4
Definition at line 2443 of file kmp_dispatch.cpp.
{
    return __kmp_dispatch_next< kmp_uint32 >(loc, gtid, p_last, p_lb, p_ub, p_st);
}
int __kmpc_dispatch_next_8 (ident_t * loc, kmp_int32 gtid, kmp_int32 * p_last, kmp_int64 * p_lb, kmp_int64 * p_ub, kmp_int64 * p_st)
See __kmpc_dispatch_next_4
Definition at line 2453 of file kmp_dispatch.cpp.
{
    return __kmp_dispatch_next< kmp_int64 >(loc, gtid, p_last, p_lb, p_ub, p_st);
}
int __kmpc_dispatch_next_8u (ident_t * loc, kmp_int32 gtid, kmp_int32 * p_last, kmp_uint64 * p_lb, kmp_uint64 * p_ub, kmp_int64 * p_st)
See __kmpc_dispatch_next_4
Definition at line 2463 of file kmp_dispatch.cpp.
{
    return __kmp_dispatch_next< kmp_uint64 >(loc, gtid, p_last, p_lb, p_ub, p_st);
}
void __kmpc_dist_dispatch_init_4 (ident_t * loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 * p_last, kmp_int32 lb, kmp_int32 ub, kmp_int32 st, kmp_int32 chunk)
See __kmpc_dispatch_init_4
Difference from __kmpc_dispatch_init set of functions is these functions are called for composite distribute parallel for construct. Thus before regular iterations dispatching we need to calc per-team iteration space.
These functions are all identical apart from the types of the arguments.
Definition at line 2385 of file kmp_dispatch.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_dist_get_bounds< kmp_int32 >(loc, gtid, p_last, &lb, &ub, st);
    __kmp_dispatch_init< kmp_int32 >(loc, gtid, schedule, lb, ub, st, chunk, true);
}
void __kmpc_dist_dispatch_init_4u (ident_t * loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 * p_last, kmp_uint32 lb, kmp_uint32 ub, kmp_int32 st, kmp_int32 chunk)
Definition at line 2394 of file kmp_dispatch.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_dist_get_bounds< kmp_uint32 >(loc, gtid, p_last, &lb, &ub, st);
    __kmp_dispatch_init< kmp_uint32 >(loc, gtid, schedule, lb, ub, st, chunk, true);
}
void __kmpc_dist_dispatch_init_8 (ident_t * loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 * p_last, kmp_int64 lb, kmp_int64 ub, kmp_int64 st, kmp_int64 chunk)
Definition at line 2403 of file kmp_dispatch.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_dist_get_bounds< kmp_int64 >(loc, gtid, p_last, &lb, &ub, st);
    __kmp_dispatch_init< kmp_int64 >(loc, gtid, schedule, lb, ub, st, chunk, true);
}
void __kmpc_dist_dispatch_init_8u (ident_t * loc, kmp_int32 gtid, enum sched_type schedule, kmp_int32 * p_last, kmp_uint64 lb, kmp_uint64 ub, kmp_int64 st, kmp_int64 chunk)
Definition at line 2412 of file kmp_dispatch.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_dist_get_bounds< kmp_uint64 >(loc, gtid, p_last, &lb, &ub, st);
    __kmp_dispatch_init< kmp_uint64 >(loc, gtid, schedule, lb, ub, st, chunk, true);
}
void __kmpc_dist_for_static_init_4 (ident_t * loc, kmp_int32 gtid, kmp_int32 schedule, kmp_int32 * plastiter, kmp_int32 * plower, kmp_int32 * pupper, kmp_int32 * pupperD, kmp_int32 * pstride, kmp_int32 incr, kmp_int32 chunk)
Parameters
loc Source code location
gtid Global thread id of this thread
schedule Scheduling type for the parallel loop
plastiter Pointer to the `last iteration` flag
plower Pointer to the lower bound
pupper Pointer to the upper bound of loop chunk
pupperD Pointer to the upper bound of dist_chunk
pstride Pointer to the stride for parallel loop
incr Loop increment
chunk The chunk size for the parallel loop
Each of the four functions here are identical apart from the argument types.
The functions compute the upper and lower bounds and strides to be used for the set of iterations to be executed by the current thread from the statically scheduled loop that is described by the initial values of the bounds, strides, increment and chunks for parallel loop and distribute constructs.
Definition at line 818 of file kmp_sched.cpp.
{
    __kmp_dist_for_static_init< kmp_int32 >(
        loc, gtid, schedule, plastiter, plower, pupper, pupperD, pstride, incr, chunk);
}
void __kmpc_dist_for_static_init_4u (ident_t * loc, kmp_int32 gtid, kmp_int32 schedule, kmp_int32 * plastiter, kmp_uint32 * plower, kmp_uint32 * pupper, kmp_uint32 * pupperD, kmp_int32 * pstride, kmp_int32 incr, kmp_int32 chunk)
See __kmpc_dist_for_static_init_4
Definition at line 831 of file kmp_sched.cpp.
{
    __kmp_dist_for_static_init< kmp_uint32 >(
        loc, gtid, schedule, plastiter, plower, pupper, pupperD, pstride, incr, chunk);
}
void __kmpc_dist_for_static_init_8 (ident_t * loc, kmp_int32 gtid, kmp_int32 schedule, kmp_int32 * plastiter, kmp_int64 * plower, kmp_int64 * pupper, kmp_int64 * pupperD, kmp_int64 * pstride, kmp_int64 incr, kmp_int64 chunk)
See __kmpc_dist_for_static_init_4
Definition at line 844 of file kmp_sched.cpp.
{
    __kmp_dist_for_static_init< kmp_int64 >(
        loc, gtid, schedule, plastiter, plower, pupper, pupperD, pstride, incr, chunk);
}
void __kmpc_dist_for_static_init_8u (ident_t * loc, kmp_int32 gtid, kmp_int32 schedule, kmp_int32 * plastiter, kmp_uint64 * plower, kmp_uint64 * pupper, kmp_uint64 * pupperD, kmp_int64 * pstride, kmp_int64 incr, kmp_int64 chunk)
See __kmpc_dist_for_static_init_4
Definition at line 857 of file kmp_sched.cpp.
{
    __kmp_dist_for_static_init< kmp_uint64 >(
        loc, gtid, schedule, plastiter, plower, pupper, pupperD, pstride, incr, chunk);
}
void __kmpc_end_critical (ident_t * loc, kmp_int32 global_tid, kmp_critical_name * crit)
Parameters
loc source location information.
global_tid global thread number .
crit identity of the critical section. This could be a pointer to a lock associated with the critical section, or some other suitably unique value.
Leave a critical section, releasing any lock that was held during its execution.
Definition at line 1287 of file kmp_csupport.c.
Referenced by KMP_API_NAME_GOMP_CRITICAL_END(), and KMP_API_NAME_GOMP_CRITICAL_NAME_END().
{
    kmp_user_lock_p lck;
    KC_TRACE(10, ("__kmpc_end_critical: called T#%d\n", global_tid));
#if KMP_USE_DYNAMIC_LOCK
    if (KMP_IS_D_LOCK(__kmp_user_lock_seq)) {
        lck = (kmp_user_lock_p)crit;
        KMP_ASSERT(lck != NULL);
        if (__kmp_env_consistency_check) {
            __kmp_pop_sync(global_tid, ct_critical, loc);
        }
# if USE_ITT_BUILD
        __kmp_itt_critical_releasing(lck);
# endif
# if KMP_USE_INLINED_TAS
        if (__kmp_user_lock_seq == lockseq_tas && !__kmp_env_consistency_check)
      {
            KMP_RELEASE_TAS_LOCK(lck, global_tid);
        } else
# elif KMP_USE_INLINED_FUTEX
        if (__kmp_user_lock_seq == lockseq_futex && !__kmp_env_consistency_check
      ) {
            KMP_RELEASE_FUTEX_LOCK(lck, global_tid);
        } else
# endif
        {
            KMP_D_LOCK_FUNC(lck, unset)((kmp_dyna_lock_t *)lck, global_tid);
        }
    } else {
        kmp_indirect_lock_t *ilk = (kmp_indirect_lock_t *)TCR_PTR(*((kmp_indirect_lock_t **)crit));
        KMP_ASSERT(ilk != NULL);
        lck = ilk->lock;
        if (__kmp_env_consistency_check) {
            __kmp_pop_sync(global_tid, ct_critical, loc);
        }
# if USE_ITT_BUILD
        __kmp_itt_critical_releasing(lck);
# endif
        KMP_I_LOCK_FUNC(ilk, unset)(lck, global_tid);
    }
#else // KMP_USE_DYNAMIC_LOCK
    if ((__kmp_user_lock_kind == lk_tas)
      && (sizeof(lck->tas.lk.poll) <= OMP_CRITICAL_SIZE)) {
        lck = (kmp_user_lock_p)crit;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
      && (sizeof(lck->futex.lk.poll) <= OMP_CRITICAL_SIZE)) {
        lck = (kmp_user_lock_p)crit;
    }
#endif
    else { // ticket, queuing or drdpa
        lck = (kmp_user_lock_p) TCR_PTR(*((kmp_user_lock_p *)crit));
    }
    KMP_ASSERT(lck != NULL);
    if (__kmp_env_consistency_check)
        __kmp_pop_sync(global_tid, ct_critical, loc);
#if USE_ITT_BUILD
    __kmp_itt_critical_releasing(lck);
#endif /* USE_ITT_BUILD */
    // Value of 'crit' should be good for using as a critical_id of the critical section directive.
    __kmp_release_user_lock_with_checks(lck, global_tid);
#if OMPT_SUPPORT && OMPT_BLAME
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_release_critical)) {
        ompt_callbacks.ompt_callback(ompt_event_release_critical)(
            (uint64_t) lck);
    }
#endif
#endif // KMP_USE_DYNAMIC_LOCK
    KMP_STOP_EXPLICIT_TIMER(OMP_critical);
    KA_TRACE(15, ("__kmpc_end_critical: done T#%d\n", global_tid));
}
void __kmpc_end_master (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information.
global_tid global thread number .
Mark the end of a master region. This should only be called by the thread that executes the master region.
Definition at line 789 of file kmp_csupport.c.
{
    KC_TRACE(10, ("__kmpc_end_master: called T#%d\n", global_tid));
    KMP_DEBUG_ASSERT(KMP_MASTER_GTID(global_tid));
    KMP_STOP_EXPLICIT_TIMER(OMP_master);
#if OMPT_SUPPORT && OMPT_TRACE
    kmp_info_t *this_thr = __kmp_threads[ global_tid ];
    kmp_team_t *team = this_thr -> th.th_team;
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_master_end)) {
        int tid = __kmp_tid_from_gtid(global_tid);
        ompt_callbacks.ompt_callback(ompt_event_master_end)(
            team->t.ompt_team_info.parallel_id,
            team->t.t_implicit_task_taskdata[tid].ompt_task_info.task_id);
    }
#endif
    if (__kmp_env_consistency_check) {
        if(global_tid < 0)
            KMP_WARNING(ThreadIdentInvalid);
        if(KMP_MASTER_GTID(global_tid))
            __kmp_pop_sync(global_tid, ct_master, loc);
    }
}
void __kmpc_end_ordered (ident_t * loc, kmp_int32 gtid)
Parameters
loc source location information.
gtid global thread number.
End execution of an ordered construct.
Definition at line 889 of file kmp_csupport.c.
Referenced by KMP_API_NAME_GOMP_ORDERED_END().
{
    int cid = 0;
    kmp_info_t *th;
    KC_TRACE(10, ("__kmpc_end_ordered: called T#%d\n", gtid));
#if USE_ITT_BUILD
    __kmp_itt_ordered_end(gtid);
    // TODO: ordered_wait_id
#endif /* USE_ITT_BUILD */
    th = __kmp_threads[ gtid ];
    if (th -> th.th_dispatch -> th_dxo_fcn != 0)
        (*th->th.th_dispatch->th_dxo_fcn)(& gtid, & cid, loc);
    else
        __kmp_parallel_dxo(& gtid, & cid, loc);
#if OMPT_SUPPORT && OMPT_BLAME
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_release_ordered)) {
        ompt_callbacks.ompt_callback(ompt_event_release_ordered)(
            th->th.ompt_thread_info.wait_id);
    }
#endif
}
void __kmpc_end_single (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information
global_tid global thread number
Mark the end of a single construct. This function should only be called by the thread that executed the block of code protected by the single construct.
Definition at line 1526 of file kmp_csupport.c.
{
    __kmp_exit_single(global_tid);
    KMP_STOP_EXPLICIT_TIMER(OMP_single);
#if OMPT_SUPPORT && OMPT_TRACE
    kmp_info_t *this_thr = __kmp_threads[ global_tid ];
    kmp_team_t *team = this_thr -> th.th_team;
    int tid = __kmp_tid_from_gtid(global_tid);
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_single_in_block_end)) {
        ompt_callbacks.ompt_callback(ompt_event_single_in_block_end)(
            team->t.ompt_team_info.parallel_id,
            team->t.t_implicit_task_taskdata[tid].ompt_task_info.task_id);
    }
#endif
}
void __kmpc_for_static_fini (ident_t * loc, kmp_int32 global_tid)
Parameters
loc Source location
global_tid Global thread id
Mark the end of a statically scheduled loop.
Definition at line 1553 of file kmp_csupport.c.
{
    KE_TRACE(10, ("__kmpc_for_static_fini called T#%d\n", global_tid));
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_loop_end)) {
        kmp_info_t *this_thr = __kmp_threads[ global_tid ];
        kmp_team_t *team = this_thr -> th.th_team;
        int tid = __kmp_tid_from_gtid(global_tid);
        ompt_callbacks.ompt_callback(ompt_event_loop_end)(
            team->t.ompt_team_info.parallel_id,
            team->t.t_implicit_task_taskdata[tid].ompt_task_info.task_id);
    }
#endif
    if (__kmp_env_consistency_check)
     __kmp_pop_workshare(global_tid, ct_pdo, loc);
}
void __kmpc_for_static_init_4 (ident_t * loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 * plastiter, kmp_int32 * plower, kmp_int32 * pupper, kmp_int32 * pstride, kmp_int32 incr, kmp_int32 chunk)
Parameters
loc Source code location
gtid Global thread id of this thread
schedtype Scheduling type
plastiter Pointer to the `last iteration` flag
plower Pointer to the lower bound
pupper Pointer to the upper bound
pstride Pointer to the stride
incr Loop increment
chunk The chunk size
Each of the four functions here are identical apart from the argument types.
The functions compute the upper and lower bounds and stride to be used for the set of iterations to be executed by the current thread from the statically scheduled loop that is described by the initial values of the bounds, stride, increment and chunk size.
Definition at line 748 of file kmp_sched.cpp.
{
    __kmp_for_static_init< kmp_int32 >(
                      loc, gtid, schedtype, plastiter, plower, pupper, pstride, incr, chunk);
}
void __kmpc_for_static_init_4u (ident_t * loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 * plastiter, kmp_uint32 * plower, kmp_uint32 * pupper, kmp_int32 * pstride, kmp_int32 incr, kmp_int32 chunk)
See __kmpc_for_static_init_4
Definition at line 760 of file kmp_sched.cpp.
{
    __kmp_for_static_init< kmp_uint32 >(
                      loc, gtid, schedtype, plastiter, plower, pupper, pstride, incr, chunk);
}
void __kmpc_for_static_init_8 (ident_t * loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 * plastiter, kmp_int64 * plower, kmp_int64 * pupper, kmp_int64 * pstride, kmp_int64 incr, kmp_int64 chunk)
See __kmpc_for_static_init_4
Definition at line 772 of file kmp_sched.cpp.
{
    __kmp_for_static_init< kmp_int64 >(
                      loc, gtid, schedtype, plastiter, plower, pupper, pstride, incr, chunk);
}
void __kmpc_for_static_init_8u (ident_t * loc, kmp_int32 gtid, kmp_int32 schedtype, kmp_int32 * plastiter, kmp_uint64 * plower, kmp_uint64 * pupper, kmp_int64 * pstride, kmp_int64 incr, kmp_int64 chunk)
See __kmpc_for_static_init_4
Definition at line 784 of file kmp_sched.cpp.
{
    __kmp_for_static_init< kmp_uint64 >(
                      loc, gtid, schedtype, plastiter, plower, pupper, pstride, incr, chunk);
}
kmp_int32 __kmpc_master (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information.
global_tid global thread number .
Returns
1 if this thread should execute the master block, 0 otherwise.
Definition at line 733 of file kmp_csupport.c.
Referenced by __kmpc_barrier_master_nowait().
{
    int status = 0;
    KC_TRACE(10, ("__kmpc_master: called T#%d\n", global_tid));
    if(! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
    if(KMP_MASTER_GTID(global_tid)) {
        KMP_COUNT_BLOCK(OMP_MASTER);
        KMP_START_EXPLICIT_TIMER(OMP_master);
        status = 1;
    }
#if OMPT_SUPPORT && OMPT_TRACE
    if (status) {
        if (ompt_enabled &&
            ompt_callbacks.ompt_callback(ompt_event_master_begin)) {
            kmp_info_t *this_thr = __kmp_threads[ global_tid ];
            kmp_team_t *team = this_thr -> th.th_team;
            int tid = __kmp_tid_from_gtid(global_tid);
            ompt_callbacks.ompt_callback(ompt_event_master_begin)(
                team->t.ompt_team_info.parallel_id,
                team->t.t_implicit_task_taskdata[tid].ompt_task_info.task_id);
        }
    }
#endif
    if (__kmp_env_consistency_check) {
#if KMP_USE_DYNAMIC_LOCK
        if (status)
            __kmp_push_sync(global_tid, ct_master, loc, NULL, 0);
        else
            __kmp_check_sync(global_tid, ct_master, loc, NULL, 0);
#else
        if (status)
            __kmp_push_sync(global_tid, ct_master, loc, NULL);
        else
            __kmp_check_sync(global_tid, ct_master, loc, NULL);
#endif
    }
    return status;
}
void __kmpc_ordered (ident_t * loc, kmp_int32 gtid)
Parameters
loc source location information.
gtid global thread number.
Start execution of an ordered construct.
Definition at line 825 of file kmp_csupport.c.
Referenced by KMP_API_NAME_GOMP_ORDERED_START().
{
    int cid = 0;
    kmp_info_t *th;
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    KC_TRACE(10, ("__kmpc_ordered: called T#%d\n", gtid));
    if (! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
#if USE_ITT_BUILD
    __kmp_itt_ordered_prep(gtid);
    // TODO: ordered_wait_id
#endif /* USE_ITT_BUILD */
    th = __kmp_threads[ gtid ];
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled) {
        /* OMPT state update */
        th->th.ompt_thread_info.wait_id = (uint64_t) loc;
        th->th.ompt_thread_info.state = ompt_state_wait_ordered;
        /* OMPT event callback */
        if (ompt_callbacks.ompt_callback(ompt_event_wait_ordered)) {
            ompt_callbacks.ompt_callback(ompt_event_wait_ordered)(
                th->th.ompt_thread_info.wait_id);
        }
    }
#endif
    if (th -> th.th_dispatch -> th_deo_fcn != 0)
        (*th->th.th_dispatch->th_deo_fcn)(& gtid, & cid, loc);
    else
        __kmp_parallel_deo(& gtid, & cid, loc);
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled) {
        /* OMPT state update */
        th->th.ompt_thread_info.state = ompt_state_work_parallel;
        th->th.ompt_thread_info.wait_id = 0;
        /* OMPT event callback */
        if (ompt_callbacks.ompt_callback(ompt_event_acquired_ordered)) {
            ompt_callbacks.ompt_callback(ompt_event_acquired_ordered)(
                th->th.ompt_thread_info.wait_id);
        }
    }
#endif
#if USE_ITT_BUILD
    __kmp_itt_ordered_start(gtid);
#endif /* USE_ITT_BUILD */
}
kmp_int32 __kmpc_single (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information
global_tid global thread number
Returns
One if this thread should execute the single construct, zero otherwise.
Test whether to execute a single construct. There are no implicit barriers in the two `single` calls, rather the compiler should introduce an explicit barrier if it is required.
Definition at line 1479 of file kmp_csupport.c.
{
    kmp_int32 rc = __kmp_enter_single(global_tid, loc, TRUE);
    if (rc) {
        // We are going to execute the single statement, so we should count it.
        KMP_COUNT_BLOCK(OMP_SINGLE);
        KMP_START_EXPLICIT_TIMER(OMP_single);
    }
#if OMPT_SUPPORT && OMPT_TRACE
    kmp_info_t *this_thr = __kmp_threads[ global_tid ];
    kmp_team_t *team = this_thr -> th.th_team;
    int tid = __kmp_tid_from_gtid(global_tid);
    if (ompt_enabled) {
        if (rc) {
            if (ompt_callbacks.ompt_callback(ompt_event_single_in_block_begin)) {
                ompt_callbacks.ompt_callback(ompt_event_single_in_block_begin)(
                    team->t.ompt_team_info.parallel_id,
                    team->t.t_implicit_task_taskdata[tid].ompt_task_info.task_id,
                    team->t.ompt_team_info.microtask);
            }
        } else {
            if (ompt_callbacks.ompt_callback(ompt_event_single_others_begin)) {
                ompt_callbacks.ompt_callback(ompt_event_single_others_begin)(
                    team->t.ompt_team_info.parallel_id,
                    team->t.t_implicit_task_taskdata[tid].ompt_task_info.task_id);
            }
            this_thr->th.ompt_thread_info.state = ompt_state_wait_single;
        }
    }
#endif
    return rc;
}
void __kmpc_team_static_init_4 (ident_t * loc, kmp_int32 gtid, kmp_int32 * p_last, kmp_int32 * p_lb, kmp_int32 * p_ub, kmp_int32 * p_st, kmp_int32 incr, kmp_int32 chunk)
Parameters
loc Source location
gtid Global thread id
p_last pointer to last iteration flag
p_lb pointer to Lower bound
p_ub pointer to Upper bound
p_st Step (or increment if you prefer)
incr Loop increment
chunk The chunk size to block with
The functions compute the upper and lower bounds and stride to be used for the set of iterations to be executed by the current team from the statically scheduled loop that is described by the initial values of the bounds, stride, increment and chunk for the distribute construct as part of composite distribute parallel loop construct. These functions are all identical apart from the types of the arguments.
Definition at line 895 of file kmp_sched.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_team_static_init< kmp_int32 >(loc, gtid, p_last, p_lb, p_ub, p_st, incr, chunk);
}
void __kmpc_team_static_init_4u (ident_t * loc, kmp_int32 gtid, kmp_int32 * p_last, kmp_uint32 * p_lb, kmp_uint32 * p_ub, kmp_int32 * p_st, kmp_int32 incr, kmp_int32 chunk)
See __kmpc_team_static_init_4
Definition at line 907 of file kmp_sched.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_team_static_init< kmp_uint32 >(loc, gtid, p_last, p_lb, p_ub, p_st, incr, chunk);
}
void __kmpc_team_static_init_8 (ident_t * loc, kmp_int32 gtid, kmp_int32 * p_last, kmp_int64 * p_lb, kmp_int64 * p_ub, kmp_int64 * p_st, kmp_int64 incr, kmp_int64 chunk)
See __kmpc_team_static_init_4
Definition at line 919 of file kmp_sched.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_team_static_init< kmp_int64 >(loc, gtid, p_last, p_lb, p_ub, p_st, incr, chunk);
}
void __kmpc_team_static_init_8u (ident_t * loc, kmp_int32 gtid, kmp_int32 * p_last, kmp_uint64 * p_lb, kmp_uint64 * p_ub, kmp_int64 * p_st, kmp_int64 incr, kmp_int64 chunk)
See __kmpc_team_static_init_4
Definition at line 931 of file kmp_sched.cpp.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    __kmp_team_static_init< kmp_uint64 >(loc, gtid, p_last, p_lb, p_ub, p_st, incr, chunk);
}