Parallel (fork/join)
Typedefs
typedef void(* kmpc_micro)(kmp_int32 *global_tid, kmp_int32 *bound_tid,...)
Functions
void __kmpc_push_num_threads (ident_t *loc, kmp_int32 global_tid, kmp_int32 num_threads)
void __kmpc_fork_call (ident_t *loc, kmp_int32 argc, kmpc_micro microtask,...)
void __kmpc_push_num_teams (ident_t *loc, kmp_int32 global_tid, kmp_int32 num_teams, kmp_int32 num_threads)
void __kmpc_fork_teams (ident_t *loc, kmp_int32 argc, kmpc_micro microtask,...)
void __kmpc_serialized_parallel (ident_t *loc, kmp_int32 global_tid)
void __kmpc_end_serialized_parallel (ident_t *loc, kmp_int32 global_tid)
Detailed Description
These functions are used for implementing #pragma omp parallel.
Typedef Documentation
typedef void(* kmpc_micro)(kmp_int32 *global_tid, kmp_int32 *bound_tid,...)
The type for a microtask which gets passed to __kmpc_fork_call(). The arguments to the outlined function are
Parameters
global_tid the global thread identity of the thread executing the function.
bound_tid the local identitiy of the thread executing the function
... pointers to shared variables accessed by the function.
Definition at line 1413 of file kmp.h.
Function Documentation
void __kmpc_end_serialized_parallel (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information
global_tid global thread number
Leave a serialized parallel construct.
Definition at line 489 of file kmp_csupport.c.
Referenced by __kmp_join_call(), and KMP_API_NAME_GOMP_PARALLEL_END().
{
    kmp_internal_control_t *top;
    kmp_info_t *this_thr;
    kmp_team_t *serial_team;
    KC_TRACE(10, ("__kmpc_end_serialized_parallel: called by T#%d\n", global_tid));
    /* skip all this code for autopar serialized loops since it results in
       unacceptable overhead */
    if(loc != NULL && (loc->flags & KMP_IDENT_AUTOPAR))
        return;
    // Not autopar code
    if(! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
    this_thr = __kmp_threads[ global_tid ];
    serial_team = this_thr->th.th_serial_team;
   #if OMP_41_ENABLED
   kmp_task_team_t * task_team = this_thr->th.th_task_team;
   // we need to wait for the proxy tasks before finishing the thread
   if (task_team != NULL && task_team->tt.tt_found_proxy_tasks)
        __kmp_task_team_wait(this_thr, serial_team, NULL); // is an ITT object needed
       here?
   #endif
    KMP_MB();
    KMP_DEBUG_ASSERT(serial_team);
    KMP_ASSERT(serial_team -> t.t_serialized);
    KMP_DEBUG_ASSERT(this_thr -> th.th_team == serial_team);
    KMP_DEBUG_ASSERT(serial_team != this_thr->th.th_root->r.r_root_team);
    KMP_DEBUG_ASSERT(serial_team -> t.t_threads);
    KMP_DEBUG_ASSERT(serial_team -> t.t_threads[0] == this_thr);
    /* If necessary, pop the internal control stack values and replace the team values */
    top = serial_team -> t.t_control_stack_top;
    if (top && top -> serial_nesting_level == serial_team -> t.t_serialized) {
        copy_icvs(&serial_team -> t.t_threads[0] -> th.th_current_task -> td_icvs, top);
        serial_team -> t.t_control_stack_top = top -> next;
        __kmp_free(top);
    }
    //if(serial_team -> t.t_serialized > 1)
    serial_team -> t.t_level--;
    /* pop dispatch buffers stack */
    KMP_DEBUG_ASSERT(serial_team->t.t_dispatch->th_disp_buffer);
    {
        dispatch_private_info_t * disp_buffer = serial_team->
      t.t_dispatch->th_disp_buffer;
        serial_team->t.t_dispatch->th_disp_buffer =
            serial_team->t.t_dispatch->th_disp_buffer->next;
        __kmp_free(disp_buffer);
    }
    -- serial_team -> t.t_serialized;
    if (serial_team -> t.t_serialized == 0) {
        /* return to the parallel section */
#if KMP_ARCH_X86 || KMP_ARCH_X86_64
        if (__kmp_inherit_fp_control && serial_team->t.t_fp_control_saved) {
            __kmp_clear_x87_fpu_status_word();
            __kmp_load_x87_fpu_control_word(&serial_team->t.t_x87_fpu_control_word);
            __kmp_load_mxcsr(&serial_team->t.t_mxcsr);
        }
#endif /* KMP_ARCH_X86 || KMP_ARCH_X86_64 */
        this_thr -> th.th_team = serial_team -> t.t_parent;
        this_thr -> th.th_info.ds.ds_tid = serial_team -> t.t_master_tid;
        /* restore values cached in the thread */
        this_thr -> th.th_team_nproc = serial_team -> t.t_parent -> t.t_nproc; /* JPH */
        this_thr -> th.th_team_master = serial_team -> t.t_parent -> t.t_threads[0]; /* JPH */
        this_thr -> th.th_team_serialized = this_thr -> th.th_team -> t.t_serialized;
        /* TODO the below shouldn't need to be adjusted for serialized teams */
        this_thr -> th.th_dispatch = & this_thr -> th.th_team ->
            t.t_dispatch[ serial_team -> t.t_master_tid ];
        __kmp_pop_current_task_from_thread(this_thr);
        KMP_ASSERT(this_thr -> th.th_current_task -> td_flags.executing == 0);
        this_thr -> th.th_current_task -> td_flags.executing = 1;
        if (__kmp_tasking_mode != tskm_immediate_exec) {
            // Copy the task team from the new child / old parent team to the thread.
            this_thr->th.th_task_team = this_thr->th.th_team->t.t_task_team[this_thr->th.th_task_state];
            KA_TRACE(20, ("__kmpc_end_serialized_parallel: T#%d restoring task_team %p / team %p
      \n",
                            global_tid, this_thr -> th.th_task_team, this_thr -> th.th_team));
        }
    } else {
        if (__kmp_tasking_mode != tskm_immediate_exec) {
            KA_TRACE(20, ("__kmpc_end_serialized_parallel: T#%d decreasing nesting depth of
       serial team %p to %d\n",
                            global_tid, serial_team, serial_team -> t.t_serialized));
        }
    }
#if USE_ITT_BUILD
    kmp_uint64 cur_time = 0;
#if USE_ITT_NOTIFY
    if (__itt_get_timestamp_ptr) {
        cur_time = __itt_get_timestamp();
    }
#endif /* USE_ITT_NOTIFY */
    if (this_thr->th.th_team->t.t_level == 0
#if OMP_40_ENABLED
        && this_thr->th.th_teams_microtask == NULL
#endif
    ) {
        // Report the barrier
        this_thr->th.th_ident = loc;
        if ((__itt_frame_submit_v3_ptr || KMP_ITT_DEBUG) &&
            (__kmp_forkjoin_frames_mode == 3 || __kmp_forkjoin_frames_mode == 1))
        {
            __kmp_itt_frame_submit(global_tid, this_thr->th.th_frame_time_serialized,
                                    cur_time, 0, loc, this_thr->th.th_team_nproc, 0);
            if (__kmp_forkjoin_frames_mode == 3)
                // Since barrier frame for serialized region is equal to the region we use the same begin
       timestamp as for the barrier.
                __kmp_itt_frame_submit(global_tid, serial_team->t.t_region_time,
                                        cur_time, 0, loc, this_thr->th.th_team_nproc, 2);
        } else if ((__itt_frame_end_v3_ptr || KMP_ITT_DEBUG) &&
            ! __kmp_forkjoin_frames_mode && __kmp_forkjoin_frames)
            // Mark the end of the "parallel" region for VTune. Only use one of frame notification scheme
       at the moment.
            __kmp_itt_region_joined(global_tid, 1);
    }
#endif /* USE_ITT_BUILD */
    if (__kmp_env_consistency_check)
        __kmp_pop_parallel(global_tid, NULL);
}
void __kmpc_fork_call (ident_t * loc, kmp_int32 argc, kmpc_micro microtask, ...)
Parameters
loc source location information
argc total number of arguments in the ellipsis
microtask pointer to callback routine consisting of outlined parallel construct
... pointers to shared variables that aren't global
Do the actual fork and call the microtask in the relevant number of threads.
Definition at line 281 of file kmp_csupport.c.
{
  int gtid = __kmp_entry_gtid();
#if (KMP_STATS_ENABLED)
  int inParallel = __kmpc_in_parallel(loc);
  if (inParallel)
  {
      KMP_COUNT_BLOCK(OMP_NESTED_PARALLEL);
  }
  else
  {
      KMP_STOP_EXPLICIT_TIMER(OMP_serial);
      KMP_COUNT_BLOCK(OMP_PARALLEL);
  }
#endif
  // maybe to save thr_state is enough here
  {
    va_list ap;
    va_start(ap, microtask);
#if OMPT_SUPPORT
    int tid = __kmp_tid_from_gtid(gtid);
    kmp_info_t *master_th = __kmp_threads[ gtid ];
    kmp_team_t *parent_team = master_th->th.th_team;
    if (ompt_enabled) {
       parent_team->t.t_implicit_task_taskdata[tid].
           ompt_task_info.frame.reenter_runtime_frame = __builtin_frame_address(0);
    }
#endif
#if INCLUDE_SSC_MARKS
    SSC_MARK_FORKING();
#endif
    __kmp_fork_call(loc, gtid, fork_context_intel,
            argc,
#if OMPT_SUPPORT
            VOLATILE_CAST(void *) microtask, // "unwrapped" task
#endif
            VOLATILE_CAST(microtask_t) microtask, // "wrapped" task
            VOLATILE_CAST(launch_t)
      __kmp_invoke_task_func,
/* TODO: revert workaround for Intel(R) 64 tracker #96 */
#if (KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64) &&
      KMP_OS_LINUX
            &ap
#else
            ap
#endif
            );
#if INCLUDE_SSC_MARKS
    SSC_MARK_JOINING();
#endif
    __kmp_join_call(loc, gtid
#if OMPT_SUPPORT
        , fork_context_intel
#endif
    );
    va_end(ap);
#if OMPT_SUPPORT
    if (ompt_enabled) {
        parent_team->t.t_implicit_task_taskdata[tid].
            ompt_task_info.frame.reenter_runtime_frame = 0;
    }
#endif
  }
#if (KMP_STATS_ENABLED)
  if (!inParallel)
      KMP_START_EXPLICIT_TIMER(OMP_serial);
#endif
}
void __kmpc_fork_teams (ident_t * loc, kmp_int32 argc, kmpc_micro microtask, ...)
Parameters
loc source location information
argc total number of arguments in the ellipsis
microtask pointer to callback routine consisting of outlined teams construct
... pointers to shared variables that aren't global
Do the actual fork and call the microtask in the relevant number of threads.
Definition at line 385 of file kmp_csupport.c.
{
    int gtid = __kmp_entry_gtid();
    kmp_info_t *this_thr = __kmp_threads[ gtid ];
    va_list ap;
    va_start(ap, microtask);
    KMP_COUNT_BLOCK(OMP_TEAMS);
    // remember teams entry point and nesting level
    this_thr->th.th_teams_microtask = microtask;
    this_thr->th.th_teams_level = this_thr->th.th_team->t.t_level; // AC: can be >0 on host
#if OMPT_SUPPORT
    kmp_team_t *parent_team = this_thr->th.th_team;
    int tid = __kmp_tid_from_gtid(gtid);
    if (ompt_enabled) {
        parent_team->t.t_implicit_task_taskdata[tid].
           ompt_task_info.frame.reenter_runtime_frame = __builtin_frame_address(0);
    }
#endif
    // check if __kmpc_push_num_teams called, set default number of teams otherwise
    if (this_thr->th.th_teams_size.nteams == 0) {
        __kmp_push_num_teams(loc, gtid, 0, 0);
    }
    KMP_DEBUG_ASSERT(this_thr->th.th_set_nproc >= 1);
    KMP_DEBUG_ASSERT(this_thr->th.th_teams_size.nteams >= 1);
    KMP_DEBUG_ASSERT(this_thr->th.th_teams_size.nth >= 1);
    __kmp_fork_call(loc, gtid, fork_context_intel,
            argc,
#if OMPT_SUPPORT
            VOLATILE_CAST(void *) microtask, // "unwrapped" task
#endif
            VOLATILE_CAST(microtask_t)
      __kmp_teams_master, // "wrapped" task
            VOLATILE_CAST(launch_t)
      __kmp_invoke_teams_master,
#if (KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64) &&
      KMP_OS_LINUX
            &ap
#else
            ap
#endif
            );
    __kmp_join_call(loc, gtid
#if OMPT_SUPPORT
        , fork_context_intel
#endif
    );
#if OMPT_SUPPORT
    if (ompt_enabled) {
        parent_team->t.t_implicit_task_taskdata[tid].
           ompt_task_info.frame.reenter_runtime_frame = NULL;
    }
#endif
    this_thr->th.th_teams_microtask = NULL;
    this_thr->th.th_teams_level = 0;
    *(kmp_int64*)(&this_thr->th.th_teams_size) = 0L;
    va_end(ap);
}
void __kmpc_push_num_teams (ident_t * loc, kmp_int32 global_tid, kmp_int32 num_teams, kmp_int32 num_threads)
Parameters
loc source location information
global_tid global thread number
num_teams number of teams requested for the teams construct
num_threads number of threads per team requested for the teams construct
Set the number of teams to be used by the teams construct. This call is only required if the teams construct has a num_teams clause or a thread_limit clause (or both).
Definition at line 367 of file kmp_csupport.c.
{
    KA_TRACE(20, ("__kmpc_push_num_teams: enter T#%d num_teams=%d num_threads=%d\n",
      global_tid, num_teams, num_threads));
    __kmp_push_num_teams(loc, global_tid, num_teams, num_threads);
}
void __kmpc_push_num_threads (ident_t * loc, kmp_int32 global_tid, kmp_int32 num_threads)
Parameters
loc source location information
global_tid global thread number
num_threads number of threads requested for this parallel construct
Set the number of threads to be used by the next fork spawned by this thread. This call is only required if the parallel construct has a num_threads clause.
Definition at line 240 of file kmp_csupport.c.
{
    KA_TRACE(20, ("__kmpc_push_num_threads: enter T#%d num_threads=%d\n",
      global_tid, num_threads));
    __kmp_push_num_threads(loc, global_tid, num_threads);
}
void __kmpc_serialized_parallel (ident_t * loc, kmp_int32 global_tid)
Parameters
loc source location information
global_tid global thread number
Enter a serialized parallel construct. This interface is used to handle a conditional parallel region, like this,
#pragma omp parallel if (condition)
 when the condition is false.
Definition at line 474 of file kmp_csupport.c.
Referenced by __kmp_fork_call().
{
    __kmp_serialized_parallel(loc, global_tid); /* The implementation is now in
       kmp_runtime.c so that it can share static functions with
                                                 * kmp_fork_call since the tasks to be done are similar in
       each case.
                                                 */
}