kmp_i18n.c File Reference
#include `kmp_i18n.h`
*
#include `kmp_os.h`
*
#include `kmp_debug.h`
*
#include `kmp.h`
*
#include `kmp_lock.h`
*
#include `kmp_io.h`
*
#include <stdio.h>
*
#include <errno.h>
*
#include <string.h>
*
#include <locale.h>
*
#include <stdarg.h>
*
#include `kmp_i18n_default.inc`
*
#include `kmp_str.h`
*
#include `kmp_environment.h`
*
Macros
#define get_section(id) ((id) >> 16)
#define get_number(id) ((id) & 0xFFFF)
Typedefs
typedef enum kmp_i18n_cat_status kmp_i18n_cat_status_t
Enumerations
enum kmp_i18n_cat_status { KMP_I18N_CLOSED,
KMP_I18N_OPENED,
KMP_I18N_ABSENT
 }
Functions
static void __kmp_i18n_do_catopen ()
void __kmp_i18n_catopen ()
void __kmp_i18n_dump_catalog (kmp_str_buf_t *buffer)
kmp_msg_t __kmp_msg_format (kmp_i18n_id_t id,...)
static char * sys_error (int err)
kmp_msg_t __kmp_msg_error_code (int code)
kmp_msg_t __kmp_msg_error_mesg (char const *mesg)
void __kmp_msg (kmp_msg_severity_t severity, kmp_msg_t message,...)
Variables
kmp_msg_t __kmp_msg_empty = { kmp_mt_dummy, 0, ``, 0 }
kmp_msg_t __kmp_msg_null = { kmp_mt_dummy, 0, NULL, 0 }
static char const * no_message_available = `(No message available)`
static volatile
*
kmp_i18n_cat_status_t status = KMP_I18N_CLOSED
static kmp_bootstrap_lock_t lock = KMP_BOOTSTRAP_LOCK_INITIALIZER(lock)
Macro Definition Documentation
#define get_number(id) ((id) & 0xFFFF)
Definition at line 38 of file kmp_i18n.c.
#define get_section(id) ((id) >> 16)
Definition at line 37 of file kmp_i18n.c.
Typedef Documentation
typedef enum kmp_i18n_cat_status kmp_i18n_cat_status_t
Definition at line 49 of file kmp_i18n.c.
Enumeration Type Documentation
enum kmp_i18n_cat_status
Enumerator
KMP_I18N_CLOSED
KMP_I18N_OPENED
KMP_I18N_ABSENT
Definition at line 44 of file kmp_i18n.c.
                         {
    KMP_I18N_CLOSED, // Not yet opened or closed.
    KMP_I18N_OPENED, // Opened successfully, ready to use.
    KMP_I18N_ABSENT // Opening failed, message catalog should not be used.
}; // enum kmp_i18n_cat_status
Function Documentation
void __kmp_i18n_catopen ()
Definition at line 67 of file kmp_i18n.c.
  {
    if (status == KMP_I18N_CLOSED) {
        __kmp_acquire_bootstrap_lock(& lock);
        if (status == KMP_I18N_CLOSED) {
            __kmp_i18n_do_catopen();
        }; // if
        __kmp_release_bootstrap_lock(& lock);
    }; // if
} // func __kmp_i18n_catopen
static void __kmp_i18n_do_catopen () [static]
Referenced by __kmp_i18n_catopen().
void __kmp_i18n_dump_catalog (kmp_str_buf_t * buffer)
Definition at line 668 of file kmp_i18n.c.
Referenced by __kmp_do_serial_initialize().
  {
    struct kmp_i18n_id_range_t {
        kmp_i18n_id_t first;
        kmp_i18n_id_t last;
    }; // struct kmp_i18n_id_range_t
    static struct kmp_i18n_id_range_t ranges[] = {
        { kmp_i18n_prp_first, kmp_i18n_prp_last },
        { kmp_i18n_str_first, kmp_i18n_str_last },
        { kmp_i18n_fmt_first, kmp_i18n_fmt_last },
        { kmp_i18n_msg_first, kmp_i18n_msg_last },
        { kmp_i18n_hnt_first, kmp_i18n_hnt_last }
    }; // ranges
    int num_of_ranges = sizeof(ranges) / sizeof(struct kmp_i18n_id_range_t);
    int range;
    kmp_i18n_id_t id;
    for (range = 0; range < num_of_ranges; ++ range) {
        __kmp_str_buf_print(buffer, "*** Set #%d ***\n", range + 1);
        for (id = (kmp_i18n_id_t)(ranges[ range ].first + 1);
              id < ranges[ range ].last;
              id = (kmp_i18n_id_t)(id + 1)) {
             __kmp_str_buf_print(buffer, "%d: <<%s>>\n", id,
      __kmp_i18n_catgets(id));
        }; // for id
    }; // for range
    __kmp_printf("%s", buffer->str);
} // __kmp_i18n_dump_catalog
void __kmp_msg (kmp_msg_severity_t severity, kmp_msg_t message, ...)
Definition at line 891 of file kmp_i18n.c.
Referenced by __kmp_affinity_bind_thread(), __kmp_check_stack_overlap(), __kmp_create_monitor(), __kmp_create_worker(), __kmp_dispatch_init(), __kmp_dispatch_next(), __kmp_do_serial_initialize(), __kmp_env_blk_init(), __kmp_env_exists(), __kmp_env_get(), __kmp_env_set(), __kmp_env_unset(), __kmp_error_construct(), __kmp_error_construct2(), __kmp_free_handle(), __kmp_get_system_affinity(), __kmp_initialize_system_tick(), __kmp_is_thread_alive(), __kmp_launch_monitor(), __kmp_push_num_teams(), __kmp_reap_monitor(), __kmp_reap_worker(), __kmp_register_library_startup(), __kmp_register_root(), __kmp_reserve_threads(), __kmp_set_schedule(), __kmp_set_system_affinity(), __kmp_stg_parse_barrier_branch_bit(), __kmp_stg_parse_barrier_pattern(), __kmp_stg_parse_blocktime(), __kmp_stg_parse_bool(), __kmp_stg_parse_omp_schedule(), __kmp_terminate_thread(), and __kmp_thread_sleep().
  {
    va_list args;
    kmp_i18n_id_t format; // format identifier
    kmp_msg_t fmsg; // formatted message
    kmp_str_buf_t buffer;
    if (severity != kmp_ms_fatal && __kmp_generate_warnings ==
      kmp_warnings_off)
        return; // no reason to form a string in order to not print it
    __kmp_str_buf_init(& buffer);
    // Format the primary message.
    switch (severity) {
        case kmp_ms_inform : {
            format = kmp_i18n_fmt_Info;
        } break;
        case kmp_ms_warning : {
            format = kmp_i18n_fmt_Warning;
        } break;
        case kmp_ms_fatal : {
            format = kmp_i18n_fmt_Fatal;
        } break;
        default : {
            KMP_DEBUG_ASSERT(0);
        };
    }; // switch
    fmsg = __kmp_msg_format(format, message.num, message.str);
    KMP_INTERNAL_FREE((void *) message.str);
    __kmp_str_buf_cat(& buffer, fmsg.str, fmsg.len);
    KMP_INTERNAL_FREE((void *) fmsg.str);
    // Format other messages.
    va_start(args, message);
    for (; ;) {
        message = va_arg(args, kmp_msg_t);
        if (message.type == kmp_mt_dummy && message.str == NULL) {
            break;
        }; // if
        if (message.type == kmp_mt_dummy && message.str ==
      __kmp_msg_empty.str) {
            continue;
        }; // if
        switch (message.type) {
            case kmp_mt_hint : {
                format = kmp_i18n_fmt_Hint;
            } break;
            case kmp_mt_syserr : {
                format = kmp_i18n_fmt_SysErr;
            } break;
            default : {
                KMP_DEBUG_ASSERT(0);
            };
        }; // switch
        fmsg = __kmp_msg_format(format, message.num, message.
      str);
        KMP_INTERNAL_FREE((void *) message.str);
        __kmp_str_buf_cat(& buffer, fmsg.str, fmsg.len);
        KMP_INTERNAL_FREE((void *) fmsg.str);
    }; // forever
    va_end(args);
    // Print formatted messages.
    // This lock prevents multiple fatal errors on the same problem.
    // __kmp_acquire_bootstrap_lock(& lock); // GEH - This lock causing tests to hang on OS X*.
    __kmp_printf("%s", buffer.str);
    __kmp_str_buf_free(& buffer);
    if (severity == kmp_ms_fatal) {
        #if KMP_OS_WINDOWS
        __kmp_thread_sleep(500); /* Delay to give message a chance to appear before
       reaping */
        #endif
        __kmp_abort_process();
    }; // if
    // __kmp_release_bootstrap_lock(& lock); // GEH - this lock causing tests to hang on OS X*.
} // __kmp_msg
kmp_msg_t __kmp_msg_error_code (int code)
Definition at line 859 of file kmp_i18n.c.
  {
    kmp_msg_t msg;
    msg.type = kmp_mt_syserr;
    msg.num = code;
    msg.str = sys_error(code);
    msg.len = KMP_STRLEN(msg.str);
    return msg;
} // __kmp_msg_error_code
kmp_msg_t __kmp_msg_error_mesg (char const * mesg)
Definition at line 875 of file kmp_i18n.c.
  {
    kmp_msg_t msg;
    msg.type = kmp_mt_syserr;
    msg.num = 0;
    msg.str = __kmp_str_format("%s", mesg);
    msg.len = KMP_STRLEN(msg.str);
    return msg;
} // __kmp_msg_error_mesg
kmp_msg_t __kmp_msg_format (kmp_i18n_id_t id, ...)
Definition at line 705 of file kmp_i18n.c.
Referenced by __kmp_error_construct(), __kmp_error_construct2(), __kmp_msg(), and __kmp_pragma().
  {
    kmp_msg_t msg;
    va_list args;
    kmp_str_buf_t buffer;
    __kmp_str_buf_init(& buffer);
    va_start(args, id);
    #if KMP_OS_UNIX
        // On Linux* OS and OS X*, printf() family functions process parameter numbers, for example:
        // "%2$s %1$s".
        __kmp_str_buf_vprint(& buffer, __kmp_i18n_catgets(id),
      args);
    #elif KMP_OS_WINDOWS
        // On Winodws, printf() family functions does not recognize GNU style parameter numbers,
        // so we have to use FormatMessage() instead. It recognizes parameter numbers, e. g.:
        // "%2!s! "%1!s!".
        {
            LPTSTR str = NULL;
            int len;
            FormatMessage(
                FORMAT_MESSAGE_FROM_STRING | FORMAT_MESSAGE_ALLOCATE_BUFFER,
                __kmp_i18n_catgets(id),
                0, 0,
                (LPTSTR)(& str),
                0,
                & args
            );
            len = ___strip_crs(str);
            __kmp_str_buf_cat(& buffer, str, len);
            LocalFree(str);
        }
    #else
        #error
    #endif
    va_end(args);
    __kmp_str_buf_detach(& buffer);
    msg.type = (kmp_msg_type_t)(id >> 16);
    msg.num = id & 0xFFFF;
    msg.str = buffer.str;
    msg.len = buffer.used;
    return msg;
} // __kmp_msg_format
static char* sys_error (int err) [static]
Definition at line 758 of file kmp_i18n.c.
Referenced by __kmp_msg_error_code().
  {
    char * message = NULL;
    #if KMP_OS_WINDOWS
        LPVOID buffer = NULL;
        int len;
        DWORD rc;
        rc =
            FormatMessage(
                FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM,
                NULL,
                err,
                MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT), // Default language.
                (LPTSTR) & buffer,
                0,
                NULL
            );
        if (rc > 0) {
            // Message formatted. Copy it (so we can free it later with normal free().
            message = __kmp_str_format("%s", (char *) buffer);
            len = ___strip_crs(message); // Delete carriage returns if any.
            // Strip trailing newlines.
            while (len > 0 && message[ len - 1 ] == '\n') {
                -- len;
            }; // while
            message[ len ] = 0;
        } else {
            // FormatMessage() failed to format system error message. GetLastError() would give us
            // error code, which we would convert to message... this it dangerous recursion, which
            // cannot clarify original error, so we will not even start it.
        }; // if
        if (buffer != NULL) {
            LocalFree(buffer);
        }; // if
    #else // Non-Windows* OS: Linux* OS or OS X*
        /*
            There are 2 incompatible versions of strerror_r:
                char * strerror_r(int, char *, size_t); // GNU version
                int strerror_r(int, char *, size_t); // XSI version
        */
        #if KMP_OS_LINUX
            // GNU version of strerror_r.
            char buffer[ 2048 ];
            char * const err_msg = strerror_r(err, buffer, sizeof(buffer));
                // Do not eliminate this assignment to temporary variable, otherwise compiler would
                // not issue warning if strerror_r() returns `int' instead of expected `char *'.
            message = __kmp_str_format("%s", err_msg);
        #else // OS X*, FreeBSD* etc.
            // XSI version of strerror_r.
            int size = 2048;
            // TODO: Add checking result of malloc().
            char * buffer = (char *) KMP_INTERNAL_MALLOC(size);
            int rc;
            rc = strerror_r(err, buffer, size);
            if (rc == -1) {
                rc = errno; // XSI version sets errno.
            }; // if
            while (rc == ERANGE) { // ERANGE means the buffer is too small.
                KMP_INTERNAL_FREE(buffer);
                size *= 2;
                buffer = (char *) KMP_INTERNAL_MALLOC(size);
                rc = strerror_r(err, buffer, size);
                if (rc == -1) {
                    rc = errno; // XSI version sets errno.
                }; // if
            }; // while
            if (rc == 0) {
                message = buffer;
            } else {
                // Buffer is unused. Free it.
                KMP_INTERNAL_FREE(buffer);
            }; // if
        #endif
    #endif /* KMP_OS_WINDOWS */
    if (message == NULL) {
        // TODO: I18n this message.
        message = __kmp_str_format("%s", "(No system error message available)");
    }; // if
    return message;
} // sys_error
Variable Documentation
kmp_msg_t __kmp_msg_empty = { kmp_mt_dummy, 0, ``, 0 }
Definition at line 40 of file kmp_i18n.c.
kmp_msg_t __kmp_msg_null = { kmp_mt_dummy, 0, NULL, 0 }
Definition at line 41 of file kmp_i18n.c.
Referenced by __kmp_affinity_bind_thread(), __kmp_check_stack_overlap(), __kmp_create_monitor(), __kmp_create_worker(), __kmp_dispatch_init(), __kmp_dispatch_next(), __kmp_do_serial_initialize(), __kmp_env_blk_init(), __kmp_env_exists(), __kmp_env_get(), __kmp_env_set(), __kmp_env_unset(), __kmp_error_construct(), __kmp_error_construct2(), __kmp_free_handle(), __kmp_get_system_affinity(), __kmp_initialize_system_tick(), __kmp_is_thread_alive(), __kmp_launch_monitor(), __kmp_push_num_teams(), __kmp_reap_monitor(), __kmp_reap_worker(), __kmp_register_library_startup(), __kmp_register_root(), __kmp_reserve_threads(), __kmp_set_schedule(), __kmp_set_system_affinity(), __kmp_stg_parse_barrier_branch_bit(), __kmp_stg_parse_barrier_pattern(), __kmp_stg_parse_blocktime(), __kmp_stg_parse_bool(), __kmp_stg_parse_omp_schedule(), __kmp_terminate_thread(), and __kmp_thread_sleep().
kmp_bootstrap_lock_t lock = KMP_BOOTSTRAP_LOCK_INITIALIZER(lock) [static]
Definition at line 61 of file kmp_i18n.c.
char const* no_message_available = `(No message available)` [static]
Definition at line 42 of file kmp_i18n.c.
volatile kmp_i18n_cat_status_t status = KMP_I18N_CLOSED [static]
Definition at line 50 of file kmp_i18n.c.
Referenced by __kmp_barrier(), __kmp_clear_system_time(), __kmp_create_monitor(), __kmp_create_worker(), __kmp_disable(), __kmp_dispatch_next(), __kmp_elapsed(), __kmp_enable(), __kmp_enter_single(), __kmp_get_load_balance(), __kmp_gtid_set_specific(), __kmp_i18n_catopen(), __kmp_initialize_system_tick(), __kmp_is_address_mapped(), __kmp_launch_monitor(), __kmp_launch_worker(), __kmp_read_cpu_time(), __kmp_read_system_info(), __kmp_read_system_time(), __kmp_reap_monitor(), __kmp_reap_worker(), __kmp_register_atfork(), __kmp_resume_monitor(), __kmp_resume_template(), __kmp_runtime_destroy(), __kmp_runtime_initialize(), __kmp_set_stack_info(), __kmp_suspend_initialize(), __kmp_suspend_initialize_thread(), __kmp_suspend_template(), __kmp_suspend_uninitialize_thread(), __kmp_terminate_thread(), __kmp_thread_sleep(), __kmpc_barrier_master(), __kmpc_master(), __kmpc_taskq_task(), __kmps_get_wtime(), __kmps_init(), KMP_API_NAME_GOMP_SECTIONS_NEXT(), and KMP_API_NAME_GOMP_SECTIONS_START().