kmp_lock.h File Reference
#include <limits.h>
*
#include <stddef.h>
*
#include `kmp_os.h`
*
#include `kmp_debug.h`
*
Classes
struct kmp_lock_pool
struct kmp_base_tas_lock
union kmp_tas_lock
struct kmp_base_ticket_lock
union kmp_ticket_lock
struct kmp_base_queuing_lock
union kmp_queuing_lock
struct kmp_base_drdpa_lock
struct kmp_base_drdpa_lock::kmp_lock_poll
union kmp_drdpa_lock
union kmp_user_lock
struct kmp_lock_table
struct kmp_block_of_locks
Macros
#define KMP_PAD(type, sz) (sizeof(type) + (sz - ((sizeof(type) - 1) % (sz)) - 1))
#define KMP_GTID_DNE (-2)
#define OMP_LOCK_T_SIZE sizeof(void *)
#define OMP_NEST_LOCK_T_SIZE sizeof(void *)
#define OMP_CRITICAL_SIZE sizeof(void *)
#define INTEL_CRITICAL_SIZE 32
#define kmp_lf_critical_section 1
#define KMP_TAS_LOCK_INITIALIZER(lock) { { 0, 0 } }
#define KMP_LOCK_RELEASED 1
#define KMP_LOCK_STILL_HELD 0
#define KMP_LOCK_ACQUIRED_FIRST 1
#define KMP_LOCK_ACQUIRED_NEXT 0
#define KMP_TICKET_LOCK_INITIALIZER(lock) { { (kmp_ticket_lock_t *) & (lock), NULL, 0, 0, 0, -1 } }
#define KMP_BOOTSTRAP_LOCK_INITIALIZER(lock) KMP_TICKET_LOCK_INITIALIZER((lock))
#define KMP_BIND_USER_LOCK_TEMPLATE(nest, kind, suffix)
#define KMP_BIND_USER_LOCK(kind) KMP_BIND_USER_LOCK_TEMPLATE(_, kind, lock)
#define KMP_BIND_USER_LOCK_WITH_CHECKS(kind) KMP_BIND_USER_LOCK_TEMPLATE(_, kind, lock_with_checks)
#define KMP_BIND_NESTED_USER_LOCK(kind) KMP_BIND_USER_LOCK_TEMPLATE(_nested_, kind, lock)
#define KMP_BIND_NESTED_USER_LOCK_WITH_CHECKS(kind) KMP_BIND_USER_LOCK_TEMPLATE(_nested_, kind, lock_with_checks)
#define KMP_CHECK_USER_LOCK_INIT()
#define KMP_LOCK_BUSY(v, type) (v)
#define KMP_LOCK_FREE(type) 0
#define KMP_LOCK_STRIP(v) (v)
Typedefs
typedef struct ident ident_t
typedef kmp_uint32 kmp_lock_flags_t
typedef kmp_uint32 kmp_lock_index_t
typedef struct kmp_lock_pool kmp_lock_pool_t
typedef struct kmp_base_tas_lock kmp_base_tas_lock_t
typedef union kmp_tas_lock kmp_tas_lock_t
typedef struct kmp_base_ticket_lock kmp_base_ticket_lock_t
typedef union kmp_ticket_lock kmp_ticket_lock_t
typedef struct
*
kmp_base_queuing_lock kmp_base_queuing_lock_t
typedef union kmp_queuing_lock kmp_queuing_lock_t
typedef struct kmp_base_drdpa_lock kmp_base_drdpa_lock_t
typedef union kmp_drdpa_lock kmp_drdpa_lock_t
typedef kmp_ticket_lock_t kmp_bootstrap_lock_t
typedef kmp_ticket_lock_t kmp_lock_t
typedef enum kmp_lock_kind kmp_lock_kind_t
typedef union kmp_user_lock * kmp_user_lock_p
typedef struct kmp_lock_table kmp_lock_table_t
typedef struct kmp_block_of_locks kmp_block_of_locks_t
Enumerations
enum kmp_lock_kind {
*
lk_default = 0,
lk_tas,
lk_ticket,
lk_queuing,
*
lk_drdpa
 }
Functions
void __kmp_validate_locks (void)
int __kmp_acquire_tas_lock (kmp_tas_lock_t *lck, kmp_int32 gtid)
int __kmp_test_tas_lock (kmp_tas_lock_t *lck, kmp_int32 gtid)
int __kmp_release_tas_lock (kmp_tas_lock_t *lck, kmp_int32 gtid)
void __kmp_init_tas_lock (kmp_tas_lock_t *lck)
void __kmp_destroy_tas_lock (kmp_tas_lock_t *lck)
int __kmp_acquire_nested_tas_lock (kmp_tas_lock_t *lck, kmp_int32 gtid)
int __kmp_test_nested_tas_lock (kmp_tas_lock_t *lck, kmp_int32 gtid)
int __kmp_release_nested_tas_lock (kmp_tas_lock_t *lck, kmp_int32 gtid)
void __kmp_init_nested_tas_lock (kmp_tas_lock_t *lck)
void __kmp_destroy_nested_tas_lock (kmp_tas_lock_t *lck)
int __kmp_acquire_ticket_lock (kmp_ticket_lock_t *lck, kmp_int32 gtid)
int __kmp_test_ticket_lock (kmp_ticket_lock_t *lck, kmp_int32 gtid)
int __kmp_test_ticket_lock_with_cheks (kmp_ticket_lock_t *lck, kmp_int32 gtid)
int __kmp_release_ticket_lock (kmp_ticket_lock_t *lck, kmp_int32 gtid)
void __kmp_init_ticket_lock (kmp_ticket_lock_t *lck)
void __kmp_destroy_ticket_lock (kmp_ticket_lock_t *lck)
int __kmp_acquire_nested_ticket_lock (kmp_ticket_lock_t *lck, kmp_int32 gtid)
int __kmp_test_nested_ticket_lock (kmp_ticket_lock_t *lck, kmp_int32 gtid)
int __kmp_release_nested_ticket_lock (kmp_ticket_lock_t *lck, kmp_int32 gtid)
void __kmp_init_nested_ticket_lock (kmp_ticket_lock_t *lck)
void __kmp_destroy_nested_ticket_lock (kmp_ticket_lock_t *lck)
KMP_BUILD_ASSERT (offsetof(kmp_base_queuing_lock_t, tail_id)%8==0)
int __kmp_acquire_queuing_lock (kmp_queuing_lock_t *lck, kmp_int32 gtid)
int __kmp_test_queuing_lock (kmp_queuing_lock_t *lck, kmp_int32 gtid)
int __kmp_release_queuing_lock (kmp_queuing_lock_t *lck, kmp_int32 gtid)
void __kmp_init_queuing_lock (kmp_queuing_lock_t *lck)
void __kmp_destroy_queuing_lock (kmp_queuing_lock_t *lck)
int __kmp_acquire_nested_queuing_lock (kmp_queuing_lock_t *lck, kmp_int32 gtid)
int __kmp_test_nested_queuing_lock (kmp_queuing_lock_t *lck, kmp_int32 gtid)
int __kmp_release_nested_queuing_lock (kmp_queuing_lock_t *lck, kmp_int32 gtid)
void __kmp_init_nested_queuing_lock (kmp_queuing_lock_t *lck)
void __kmp_destroy_nested_queuing_lock (kmp_queuing_lock_t *lck)
int __kmp_acquire_drdpa_lock (kmp_drdpa_lock_t *lck, kmp_int32 gtid)
int __kmp_test_drdpa_lock (kmp_drdpa_lock_t *lck, kmp_int32 gtid)
int __kmp_release_drdpa_lock (kmp_drdpa_lock_t *lck, kmp_int32 gtid)
void __kmp_init_drdpa_lock (kmp_drdpa_lock_t *lck)
void __kmp_destroy_drdpa_lock (kmp_drdpa_lock_t *lck)
int __kmp_acquire_nested_drdpa_lock (kmp_drdpa_lock_t *lck, kmp_int32 gtid)
int __kmp_test_nested_drdpa_lock (kmp_drdpa_lock_t *lck, kmp_int32 gtid)
int __kmp_release_nested_drdpa_lock (kmp_drdpa_lock_t *lck, kmp_int32 gtid)
void __kmp_init_nested_drdpa_lock (kmp_drdpa_lock_t *lck)
void __kmp_destroy_nested_drdpa_lock (kmp_drdpa_lock_t *lck)
static int __kmp_acquire_bootstrap_lock (kmp_bootstrap_lock_t *lck)
static int __kmp_test_bootstrap_lock (kmp_bootstrap_lock_t *lck)
static void __kmp_release_bootstrap_lock (kmp_bootstrap_lock_t *lck)
static void __kmp_init_bootstrap_lock (kmp_bootstrap_lock_t *lck)
static void __kmp_destroy_bootstrap_lock (kmp_bootstrap_lock_t *lck)
static int __kmp_acquire_lock (kmp_lock_t *lck, kmp_int32 gtid)
static int __kmp_test_lock (kmp_lock_t *lck, kmp_int32 gtid)
static void __kmp_release_lock (kmp_lock_t *lck, kmp_int32 gtid)
static void __kmp_init_lock (kmp_lock_t *lck)
static void __kmp_destroy_lock (kmp_lock_t *lck)
static kmp_int32 __kmp_get_user_lock_owner (kmp_user_lock_p lck)
static int __kmp_acquire_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid)
static int __kmp_test_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid)
static void __kmp_release_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid)
static void __kmp_init_user_lock_with_checks (kmp_user_lock_p lck)
static void __kmp_destroy_user_lock (kmp_user_lock_p lck)
static void __kmp_destroy_user_lock_with_checks (kmp_user_lock_p lck)
static void __kmp_acquire_nested_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid, int *depth)
static int __kmp_test_nested_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid)
static int __kmp_release_nested_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid)
static void __kmp_init_nested_user_lock_with_checks (kmp_user_lock_p lck)
static void __kmp_destroy_nested_user_lock_with_checks (kmp_user_lock_p lck)
static const ident_t * __kmp_get_user_lock_location (kmp_user_lock_p lck)
static void __kmp_set_user_lock_location (kmp_user_lock_p lck, const ident_t *loc)
static void __kmp_set_user_lock_flags (kmp_user_lock_p lck, kmp_lock_flags_t flags)
void __kmp_set_user_lock_vptrs (kmp_lock_kind_t user_lock_kind)
kmp_user_lock_p __kmp_user_lock_allocate (void **user_lock, kmp_int32 gtid, kmp_lock_flags_t flags)
void __kmp_user_lock_free (void **user_lock, kmp_int32 gtid, kmp_user_lock_p lck)
kmp_user_lock_p __kmp_lookup_user_lock (void **user_lock, char const *func)
void __kmp_cleanup_user_locks ()
Variables
kmp_lock_kind_t __kmp_user_lock_kind
size_t __kmp_base_user_lock_size
size_t __kmp_user_lock_size
kmp_int32(* __kmp_get_user_lock_owner_)(kmp_user_lock_p lck)
int(* __kmp_acquire_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
int(* __kmp_test_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
int(* __kmp_release_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
void(* __kmp_init_user_lock_with_checks_)(kmp_user_lock_p lck)
void(* __kmp_destroy_user_lock_)(kmp_user_lock_p lck)
void(* __kmp_destroy_user_lock_with_checks_)(kmp_user_lock_p lck)
int(* __kmp_acquire_nested_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
int(* __kmp_test_nested_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
int(* __kmp_release_nested_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
void(* __kmp_init_nested_user_lock_with_checks_)(kmp_user_lock_p lck)
void(* __kmp_destroy_nested_user_lock_with_checks_)(kmp_user_lock_p lck)
int(* __kmp_is_user_lock_initialized_)(kmp_user_lock_p lck)
const ident_t *(* __kmp_get_user_lock_location_)(kmp_user_lock_p lck)
void(* __kmp_set_user_lock_location_)(kmp_user_lock_p lck, const ident_t *loc)
kmp_lock_flags_t(* __kmp_get_user_lock_flags_)(kmp_user_lock_p lck)
void(* __kmp_set_user_lock_flags_)(kmp_user_lock_p lck, kmp_lock_flags_t flags)
kmp_lock_table_t __kmp_user_lock_table
kmp_user_lock_p __kmp_lock_pool
kmp_block_of_locks_t * __kmp_lock_blocks
int __kmp_num_locks_in_block
Macro Definition Documentation
#define INTEL_CRITICAL_SIZE 32
Definition at line 69 of file kmp_lock.h.
Referenced by __kmp_enter_critical_section_reduce_block().
#define KMP_BIND_NESTED_USER_LOCK(kind) KMP_BIND_USER_LOCK_TEMPLATE(_nested_, kind, lock)
Definition at line 964 of file kmp_lock.h.
Referenced by __kmp_set_user_lock_vptrs().
#define KMP_BIND_NESTED_USER_LOCK_WITH_CHECKS(kind) KMP_BIND_USER_LOCK_TEMPLATE(_nested_, kind, lock_with_checks)
Definition at line 965 of file kmp_lock.h.
Referenced by __kmp_set_user_lock_vptrs().
#define KMP_BIND_USER_LOCK(kind) KMP_BIND_USER_LOCK_TEMPLATE(_, kind, lock)
Definition at line 962 of file kmp_lock.h.
Referenced by __kmp_set_user_lock_vptrs().
#define KMP_BIND_USER_LOCK_TEMPLATE(nest, kind, suffix)
Value:
{ \
    __kmp_acquire##nest##user_lock_with_checks_ = (int (*)(kmp_user_lock_p, kmp_int32)
       ) \
                                                  __kmp_acquire##nest##kind##_##suffix; \
    __kmp_release##nest##user_lock_with_checks_ = (int (*)(kmp_user_lock_p, kmp_int32)
       ) \
                                                  __kmp_release##nest##kind##_##suffix; \
    __kmp_test##nest##user_lock_with_checks_ = (int (*)(kmp_user_lock_p, kmp_int32)
       ) \
                                                  __kmp_test##nest##kind##_##suffix; \
    __kmp_init##nest##user_lock_with_checks_ = (void (*)(
      kmp_user_lock_p)) \
                                                  __kmp_init##nest##kind##_##suffix; \
    __kmp_destroy##nest##user_lock_with_checks_ = (void (*)(
      kmp_user_lock_p)) \
                                                  __kmp_destroy##nest##kind##_##suffix; \
}
Definition at line 949 of file kmp_lock.h.
#define KMP_BIND_USER_LOCK_WITH_CHECKS(kind) KMP_BIND_USER_LOCK_TEMPLATE(_, kind, lock_with_checks)
Definition at line 963 of file kmp_lock.h.
Referenced by __kmp_set_user_lock_vptrs().
#define KMP_BOOTSTRAP_LOCK_INITIALIZER(lock) KMP_TICKET_LOCK_INITIALIZER((lock))
Definition at line 502 of file kmp_lock.h.
#define KMP_CHECK_USER_LOCK_INIT()
Value:
{ \
            if (! TCR_4(__kmp_init_user_locks)) {
      \
                __kmp_acquire_bootstrap_lock(&
      __kmp_initz_lock); \
                if (! TCR_4(__kmp_init_user_locks)) {
      \
                    TCW_4(__kmp_init_user_locks,
      TRUE); \
                } \
                __kmp_release_bootstrap_lock(&
      __kmp_initz_lock); \
            } \
        }
Definition at line 1019 of file kmp_lock.h.
Referenced by __kmpc_critical(), __kmpc_init_lock(), and __kmpc_init_nest_lock().
#define KMP_GTID_DNE (-2)
Definition at line 34 of file kmp_lock.h.
Referenced by __kmp_acquire_bootstrap_lock(), __kmp_release_bootstrap_lock(), and __kmp_test_bootstrap_lock().
#define kmp_lf_critical_section 1
Definition at line 76 of file kmp_lock.h.
Referenced by __kmp_get_critical_section_ptr().
#define KMP_LOCK_ACQUIRED_FIRST 1
Definition at line 176 of file kmp_lock.h.
Referenced by __kmp_acquire_drdpa_lock_timed_template(), __kmp_acquire_drdpa_lock_with_checks(), __kmp_acquire_nested_drdpa_lock(), __kmp_acquire_nested_queuing_lock(), __kmp_acquire_nested_tas_lock(), __kmp_acquire_nested_ticket_lock(), __kmp_acquire_queuing_lock_timed_template(), __kmp_acquire_queuing_lock_with_checks(), __kmp_acquire_tas_lock_timed_template(), __kmp_acquire_ticket_lock_timed_template(), __kmp_acquire_ticket_lock_with_checks(), and __kmpc_set_nest_lock().
#define KMP_LOCK_ACQUIRED_NEXT 0
Definition at line 177 of file kmp_lock.h.
Referenced by __kmp_acquire_nested_drdpa_lock(), __kmp_acquire_nested_queuing_lock(), __kmp_acquire_nested_tas_lock(), and __kmp_acquire_nested_ticket_lock().
#define KMP_LOCK_BUSY(v, type) (v)
Definition at line 1262 of file kmp_lock.h.
Referenced by __kmp_acquire_tas_lock_timed_template(), and __kmp_test_tas_lock().
#define KMP_LOCK_FREE(type) 0
Definition at line 1263 of file kmp_lock.h.
Referenced by __kmp_acquire_tas_lock_timed_template(), __kmp_init_tas_lock(), __kmp_release_tas_lock(), and __kmp_test_tas_lock().
#define KMP_LOCK_RELEASED 1
Definition at line 174 of file kmp_lock.h.
Referenced by __kmp_release_drdpa_lock(), __kmp_release_nested_drdpa_lock(), __kmp_release_nested_queuing_lock(), __kmp_release_nested_tas_lock(), __kmp_release_nested_ticket_lock(), __kmp_release_queuing_lock(), __kmp_release_tas_lock(), __kmp_release_ticket_lock(), and __kmpc_unset_nest_lock().
#define KMP_LOCK_STILL_HELD 0
Definition at line 175 of file kmp_lock.h.
Referenced by __kmp_release_nested_drdpa_lock(), __kmp_release_nested_queuing_lock(), __kmp_release_nested_tas_lock(), and __kmp_release_nested_ticket_lock().
#define KMP_LOCK_STRIP(v) (v)
Definition at line 1264 of file kmp_lock.h.
Referenced by __kmp_get_tas_lock_owner().
#define KMP_PAD(type, sz) (sizeof(type) + (sz - ((sizeof(type) - 1) % (sz)) - 1))
Definition at line 33 of file kmp_lock.h.
#define KMP_TAS_LOCK_INITIALIZER(lock) { { 0, 0 } }
Definition at line 160 of file kmp_lock.h.
#define KMP_TICKET_LOCK_INITIALIZER(lock) { { (kmp_ticket_lock_t *) & (lock), NULL, 0, 0, 0, -1 } }
Definition at line 263 of file kmp_lock.h.
#define OMP_CRITICAL_SIZE sizeof(void *)
Definition at line 68 of file kmp_lock.h.
Referenced by __kmpc_critical(), and __kmpc_end_critical().
#define OMP_LOCK_T_SIZE sizeof(void *)
Definition at line 59 of file kmp_lock.h.
Referenced by __kmp_acquire_tas_lock_with_checks(), __kmp_destroy_tas_lock_with_checks(), __kmp_lookup_user_lock(), __kmp_release_tas_lock_with_checks(), __kmp_test_tas_lock_with_checks(), __kmp_user_lock_allocate(), __kmp_user_lock_free(), __kmpc_destroy_lock(), __kmpc_init_lock(), __kmpc_set_lock(), __kmpc_test_lock(), and __kmpc_unset_lock().
#define OMP_NEST_LOCK_T_SIZE sizeof(void *)
Definition at line 60 of file kmp_lock.h.
Referenced by __kmpc_destroy_nest_lock(), __kmpc_init_nest_lock(), __kmpc_set_nest_lock(), __kmpc_test_nest_lock(), and __kmpc_unset_nest_lock().
Typedef Documentation
typedef struct ident ident_t
Definition at line 39 of file kmp_lock.h.
typedef struct kmp_base_drdpa_lock kmp_base_drdpa_lock_t
Definition at line 461 of file kmp_lock.h.
typedef struct kmp_base_queuing_lock kmp_base_queuing_lock_t
Definition at line 355 of file kmp_lock.h.
typedef struct kmp_base_tas_lock kmp_base_tas_lock_t
Definition at line 145 of file kmp_lock.h.
typedef struct kmp_base_ticket_lock kmp_base_ticket_lock_t
Definition at line 247 of file kmp_lock.h.
typedef struct kmp_block_of_locks kmp_block_of_locks_t
Definition at line 1009 of file kmp_lock.h.
typedef kmp_ticket_lock_t kmp_bootstrap_lock_t
Definition at line 500 of file kmp_lock.h.
typedef union kmp_drdpa_lock kmp_drdpa_lock_t
Definition at line 470 of file kmp_lock.h.
typedef kmp_uint32 kmp_lock_flags_t
Definition at line 74 of file kmp_lock.h.
typedef kmp_uint32 kmp_lock_index_t
Definition at line 81 of file kmp_lock.h.
typedef enum kmp_lock_kind kmp_lock_kind_t
Definition at line 610 of file kmp_lock.h.
typedef struct kmp_lock_pool kmp_lock_pool_t
Definition at line 92 of file kmp_lock.h.
typedef kmp_ticket_lock_t kmp_lock_t
Definition at line 547 of file kmp_lock.h.
typedef struct kmp_lock_table kmp_lock_table_t
Definition at line 999 of file kmp_lock.h.
typedef union kmp_queuing_lock kmp_queuing_lock_t
Definition at line 366 of file kmp_lock.h.
typedef union kmp_tas_lock kmp_tas_lock_t
Definition at line 154 of file kmp_lock.h.
typedef union kmp_ticket_lock kmp_ticket_lock_t
Definition at line 256 of file kmp_lock.h.
typedef union kmp_user_lock* kmp_user_lock_p
Definition at line 628 of file kmp_lock.h.
Enumeration Type Documentation
enum kmp_lock_kind
Enumerator
lk_default
lk_tas
lk_ticket
lk_queuing
lk_drdpa
Definition at line 592 of file kmp_lock.h.
                   {
    lk_default = 0,
    lk_tas,
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    lk_futex,
#endif
#if KMP_USE_DYNAMIC_LOCK && KMP_USE_TSX
    lk_hle,
    lk_rtm,
#endif
    lk_ticket,
    lk_queuing,
    lk_drdpa,
#if KMP_USE_ADAPTIVE_LOCKS
    lk_adaptive
#endif // KMP_USE_ADAPTIVE_LOCKS
};
Function Documentation
static int __kmp_acquire_bootstrap_lock (kmp_bootstrap_lock_t * lck) [inline], [static]
Definition at line 505 of file kmp_lock.h.
Referenced by __kmp_abort_process(), __kmp_allocate_task_team(), __kmp_allocate_thread(), __kmp_aux_set_stacksize(), __kmp_bget_dequeue(), __kmp_bget_enqueue(), __kmp_dump_debug_buffer(), __kmp_expand_threads(), __kmp_fork_call(), __kmp_free_task_deque(), __kmp_free_task_team(), __kmp_free_task_threads_data(), __kmp_get_global_thread_id_reg(), __kmp_i18n_catopen(), __kmp_internal_end(), __kmp_internal_end_library(), __kmp_internal_end_thread(), __kmp_join_call(), __kmp_middle_initialize(), __kmp_parallel_initialize(), __kmp_print_storage_map_gtid(), __kmp_printf(), __kmp_push_task(), __kmp_realloc_task_threads_data(), __kmp_reap_task_teams(), __kmp_register_root(), __kmp_remove_my_task(), __kmp_serial_initialize(), __kmp_serialized_parallel(), __kmp_set_num_threads(), __kmp_steal_task(), __kmp_unregister_root_current_thread(), __kmp_warn(), and __kmpc_threadprivate_cached().
{
    return __kmp_acquire_ticket_lock(lck, KMP_GTID_DNE);
}
int __kmp_acquire_drdpa_lock (kmp_drdpa_lock_t * lck, kmp_int32 gtid)
Definition at line 2648 of file kmp_lock.cpp.
Referenced by __kmp_acquire_drdpa_lock_with_checks().
{
    return __kmp_acquire_drdpa_lock_timed_template(lck, gtid);
}
static int __kmp_acquire_lock (kmp_lock_t * lck, kmp_int32 gtid) [inline], [static]
Definition at line 550 of file kmp_lock.h.
Referenced by __kmp_alloc_taskq(), __kmp_alloc_thunk(), __kmp_bget_dequeue(), __kmp_bget_enqueue(), __kmp_dequeue_task(), __kmp_enqueue_task(), __kmp_execute_task_from_queue(), __kmp_find_and_remove_finished_child_taskq(), __kmp_find_task_in_ancestor_queue(), __kmp_find_task_in_descendant_queue(), __kmp_find_task_in_queue(), __kmp_free_taskq(), __kmp_free_thunk(), __kmp_internal_begin(), __kmp_remove_queue_from_tree(), __kmp_user_lock_allocate(), __kmp_user_lock_free(), __kmpc_end_taskq(), __kmpc_end_taskq_task(), __kmpc_taskq(), __kmpc_threadprivate_cached(), kmp_threadprivate_insert(), and kmp_threadprivate_insert_private_data().
{
    return __kmp_acquire_ticket_lock(lck, gtid);
}
int __kmp_acquire_nested_drdpa_lock (kmp_drdpa_lock_t * lck, kmp_int32 gtid)
Definition at line 2839 of file kmp_lock.cpp.
Referenced by __kmp_acquire_nested_drdpa_lock_with_checks().
{
    KMP_DEBUG_ASSERT(gtid >= 0);
    if (__kmp_get_drdpa_lock_owner(lck) == gtid) {
        lck->lk.depth_locked += 1;
        return KMP_LOCK_ACQUIRED_NEXT;
    }
    else {
        __kmp_acquire_drdpa_lock_timed_template(lck, gtid);
        KMP_MB();
        lck->lk.depth_locked = 1;
        KMP_MB();
        lck->lk.owner_id = gtid + 1;
        return KMP_LOCK_ACQUIRED_FIRST;
    }
}
int __kmp_acquire_nested_queuing_lock (kmp_queuing_lock_t * lck, kmp_int32 gtid)
Definition at line 1705 of file kmp_lock.cpp.
Referenced by __kmp_acquire_nested_queuing_lock_with_checks().
{
    KMP_DEBUG_ASSERT(gtid >= 0);
    if (__kmp_get_queuing_lock_owner(lck) == gtid) {
        lck->lk.depth_locked += 1;
        return KMP_LOCK_ACQUIRED_NEXT;
    }
    else {
        __kmp_acquire_queuing_lock_timed_template<false>(lck, gtid);
        KMP_MB();
        lck->lk.depth_locked = 1;
        KMP_MB();
        lck->lk.owner_id = gtid + 1;
        return KMP_LOCK_ACQUIRED_FIRST;
    }
}
int __kmp_acquire_nested_tas_lock (kmp_tas_lock_t * lck, kmp_int32 gtid)
Definition at line 246 of file kmp_lock.cpp.
Referenced by __kmp_acquire_nested_tas_lock_with_checks().
{
    KMP_DEBUG_ASSERT(gtid >= 0);
    if (__kmp_get_tas_lock_owner(lck) == gtid) {
        lck->lk.depth_locked += 1;
        return KMP_LOCK_ACQUIRED_NEXT;
    }
    else {
        __kmp_acquire_tas_lock_timed_template(lck, gtid);
        lck->lk.depth_locked = 1;
        return KMP_LOCK_ACQUIRED_FIRST;
    }
}
int __kmp_acquire_nested_ticket_lock (kmp_ticket_lock_t * lck, kmp_int32 gtid)
Definition at line 917 of file kmp_lock.cpp.
Referenced by __kmp_acquire_nested_ticket_lock_with_checks().
{
    KMP_DEBUG_ASSERT(gtid >= 0);
    if (__kmp_get_ticket_lock_owner(lck) == gtid) {
        lck->lk.depth_locked += 1;
        return KMP_LOCK_ACQUIRED_NEXT;
    }
    else {
        __kmp_acquire_ticket_lock_timed_template(lck, gtid);
        KMP_MB();
        lck->lk.depth_locked = 1;
        KMP_MB();
        lck->lk.owner_id = gtid + 1;
        return KMP_LOCK_ACQUIRED_FIRST;
    }
}
static void __kmp_acquire_nested_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid, int * depth) [inline], [static]
Definition at line 814 of file kmp_lock.h.
{
    KMP_DEBUG_ASSERT(
      __kmp_acquire_nested_user_lock_with_checks_ != NULL);
    *depth = (*__kmp_acquire_nested_user_lock_with_checks_)(lck, gtid);
}
int __kmp_acquire_queuing_lock (kmp_queuing_lock_t * lck, kmp_int32 gtid)
Definition at line 1407 of file kmp_lock.cpp.
Referenced by __kmp_acquire_atomic_lock(), and __kmp_acquire_queuing_lock_with_checks().
{
    KMP_DEBUG_ASSERT(gtid >= 0);
    return __kmp_acquire_queuing_lock_timed_template<false>(lck, gtid);
}
int __kmp_acquire_tas_lock (kmp_tas_lock_t * lck, kmp_int32 gtid)
Definition at line 134 of file kmp_lock.cpp.
Referenced by __kmp_acquire_tas_lock_with_checks(), and __kmp_create_worker().
{
    return __kmp_acquire_tas_lock_timed_template(lck, gtid);
}
int __kmp_acquire_ticket_lock (kmp_ticket_lock_t * lck, kmp_int32 gtid)
Definition at line 767 of file kmp_lock.cpp.
Referenced by __kmp_acquire_bootstrap_lock(), __kmp_acquire_lock(), and __kmp_acquire_ticket_lock_with_checks().
{
    return __kmp_acquire_ticket_lock_timed_template(lck, gtid);
}
static int __kmp_acquire_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid) [inline], [static]
Definition at line 687 of file kmp_lock.h.
Referenced by __kmp_enter_critical_section_reduce_block(), and __kmpc_critical().
{
    KMP_DEBUG_ASSERT(__kmp_acquire_user_lock_with_checks_
       != NULL);
    return (*__kmp_acquire_user_lock_with_checks_)(lck, gtid);
}
void __kmp_cleanup_user_locks ()
Definition at line 4080 of file kmp_lock.cpp.
Referenced by __kmp_cleanup().
{
    //
    // Reset lock pool. Do not worry about lock in the pool -- we will free
    // them when iterating through lock table (it includes all the locks,
    // dead or alive).
    //
    __kmp_lock_pool = NULL;
#define IS_CRITICAL(lck) \
        ((__kmp_get_user_lock_flags_ != NULL) && \
        ((*__kmp_get_user_lock_flags_)(lck) & kmp_lf_critical_section))
    //
    // Loop through lock table, free all locks.
    //
    // Do not free item [0], it is reserved for lock tables list.
    //
    // FIXME - we are iterating through a list of (pointers to) objects of
    // type union kmp_user_lock, but we have no way of knowing whether the
    // base type is currently "pool" or whatever the global user lock type
    // is.
    //
    // We are relying on the fact that for all of the user lock types
    // (except "tas"), the first field in the lock struct is the "initialized"
    // field, which is set to the address of the lock object itself when
    // the lock is initialized. When the union is of type "pool", the
    // first field is a pointer to the next object in the free list, which
    // will not be the same address as the object itself.
    //
    // This means that the check (*__kmp_is_user_lock_initialized_)(lck)
    // will fail for "pool" objects on the free list. This must happen as
    // the "location" field of real user locks overlaps the "index" field
    // of "pool" objects.
    //
    // It would be better to run through the free list, and remove all "pool"
    // objects from the lock table before executing this loop. However,
    // "pool" objects do not always have their index field set (only on
    // lin_32e), and I don't want to search the lock table for the address
    // of every "pool" object on the free list.
    //
    while (__kmp_user_lock_table.used > 1) {
        const ident *loc;
        //
        // reduce __kmp_user_lock_table.used before freeing the lock,
        // so that state of locks is consistent
        //
        kmp_user_lock_p lck = __kmp_user_lock_table.
      table[
          --__kmp_user_lock_table.used ];
        if ((__kmp_is_user_lock_initialized_ != NULL) &&
          (*__kmp_is_user_lock_initialized_)(lck)) {
            //
            // Issue a warning if: KMP_CONSISTENCY_CHECK AND lock is
            // initialized AND it is NOT a critical section (user is not
            // responsible for destroying criticals) AND we know source
            // location to report.
            //
            if (__kmp_env_consistency_check && (!
      IS_CRITICAL(lck)) &&
              ((loc = __kmp_get_user_lock_location(lck)) != NULL) &&
              (loc->psource != NULL)) {
                kmp_str_loc_t str_loc = __kmp_str_loc_init(loc->
      psource, 0);
                KMP_WARNING(CnsLockNotDestroyed, str_loc.file, str_loc.
      line);
                __kmp_str_loc_free(&str_loc);
            }
#ifdef KMP_DEBUG
            if (IS_CRITICAL(lck)) {
                KA_TRACE(20, ("__kmp_cleanup_user_locks: free critical section lock %p (%p)\n",
      lck, *(void**)lck));
            }
            else {
                KA_TRACE(20, ("__kmp_cleanup_user_locks: free lock %p (%p)\n", lck, *(void**)lck)
       );
            }
#endif // KMP_DEBUG
            //
            // Cleanup internal lock dynamic resources
            // (for drdpa locks particularly).
            //
            __kmp_destroy_user_lock(lck);
        }
        //
        // Free the lock if block allocation of locks is not used.
        //
        if (__kmp_lock_blocks == NULL) {
            __kmp_free(lck);
        }
    }
#undef IS_CRITICAL
    //
    // delete lock table(s).
    //
    kmp_user_lock_p *table_ptr = __kmp_user_lock_table.
      table;
    __kmp_user_lock_table.table = NULL;
    __kmp_user_lock_table.allocated = 0;
    while (table_ptr != NULL) {
        //
        // In the first element we saved the pointer to the previous
        // (smaller) lock table.
        //
        kmp_user_lock_p *next = (kmp_user_lock_p *)(table_ptr[ 0 ]);
        __kmp_free(table_ptr);
        table_ptr = next;
    }
    //
    // Free buffers allocated for blocks of locks.
    //
    kmp_block_of_locks_t *block_ptr = __kmp_lock_blocks;
    __kmp_lock_blocks = NULL;
    while (block_ptr != NULL) {
        kmp_block_of_locks_t *next = block_ptr->next_block;
        __kmp_free(block_ptr->locks);
        //
        // *block_ptr itself was allocated at the end of the locks vector.
        //
        block_ptr = next;
    }
    TCW_4(__kmp_init_user_locks, FALSE);
}
static void __kmp_destroy_bootstrap_lock (kmp_bootstrap_lock_t * lck) [inline], [static]
Definition at line 529 of file kmp_lock.h.
{
    __kmp_destroy_ticket_lock(lck);
}
void __kmp_destroy_drdpa_lock (kmp_drdpa_lock_t * lck)
Definition at line 2796 of file kmp_lock.cpp.
Referenced by __kmp_destroy_drdpa_lock_with_checks(), __kmp_destroy_nested_drdpa_lock(), and __kmp_set_user_lock_vptrs().
{
    lck->lk.initialized = NULL;
    lck->lk.location = NULL;
    if (lck->lk.polls != NULL) {
        __kmp_free((void *)lck->lk.polls);
        lck->lk.polls = NULL;
    }
    if (lck->lk.old_polls != NULL) {
        __kmp_free((void *)lck->lk.old_polls);
        lck->lk.old_polls = NULL;
    }
    lck->lk.mask = 0;
    lck->lk.num_polls = 0;
    lck->lk.cleanup_ticket = 0;
    lck->lk.next_ticket = 0;
    lck->lk.now_serving = 0;
    lck->lk.owner_id = 0;
    lck->lk.depth_locked = -1;
}
static void __kmp_destroy_lock (kmp_lock_t * lck) [inline], [static]
Definition at line 574 of file kmp_lock.h.
Referenced by __kmp_free_taskq().
{
    __kmp_destroy_ticket_lock(lck);
}
void __kmp_destroy_nested_drdpa_lock (kmp_drdpa_lock_t * lck)
Definition at line 2954 of file kmp_lock.cpp.
Referenced by __kmp_destroy_nested_drdpa_lock_with_checks().
{
    __kmp_destroy_drdpa_lock(lck);
    lck->lk.depth_locked = 0;
}
void __kmp_destroy_nested_queuing_lock (kmp_queuing_lock_t * lck)
Definition at line 1821 of file kmp_lock.cpp.
Referenced by __kmp_destroy_nested_queuing_lock_with_checks().
{
    __kmp_destroy_queuing_lock(lck);
    lck->lk.depth_locked = 0;
}
void __kmp_destroy_nested_tas_lock (kmp_tas_lock_t * lck)
Definition at line 345 of file kmp_lock.cpp.
Referenced by __kmp_destroy_nested_tas_lock_with_checks().
{
    __kmp_destroy_tas_lock(lck);
    lck->lk.depth_locked = 0;
}
void __kmp_destroy_nested_ticket_lock (kmp_ticket_lock_t * lck)
Definition at line 1033 of file kmp_lock.cpp.
Referenced by __kmp_destroy_nested_ticket_lock_with_checks().
{
    __kmp_destroy_ticket_lock(lck);
    lck->lk.depth_locked = 0;
}
static void __kmp_destroy_nested_user_lock_with_checks (kmp_user_lock_p lck) [inline], [static]
Definition at line 881 of file kmp_lock.h.
{
    KMP_DEBUG_ASSERT(
      __kmp_destroy_nested_user_lock_with_checks_ != NULL);
    (*__kmp_destroy_nested_user_lock_with_checks_)(lck);
}
void __kmp_destroy_queuing_lock (kmp_queuing_lock_t * lck)
Definition at line 1671 of file kmp_lock.cpp.
Referenced by __kmp_destroy_atomic_lock(), __kmp_destroy_nested_queuing_lock(), __kmp_destroy_queuing_lock_with_checks(), and __kmp_set_user_lock_vptrs().
{
    lck->lk.initialized = NULL;
    lck->lk.location = NULL;
    lck->lk.head_id = 0;
    lck->lk.tail_id = 0;
    lck->lk.next_ticket = 0;
    lck->lk.now_serving = 0;
    lck->lk.owner_id = 0;
    lck->lk.depth_locked = -1;
}
void __kmp_destroy_tas_lock (kmp_tas_lock_t * lck)
Definition at line 221 of file kmp_lock.cpp.
Referenced by __kmp_destroy_nested_tas_lock(), __kmp_destroy_tas_lock_with_checks(), and __kmp_set_user_lock_vptrs().
{
    lck->lk.poll = 0;
}
void __kmp_destroy_ticket_lock (kmp_ticket_lock_t * lck)
Definition at line 885 of file kmp_lock.cpp.
Referenced by __kmp_destroy_bootstrap_lock(), __kmp_destroy_lock(), __kmp_destroy_nested_ticket_lock(), __kmp_destroy_ticket_lock_with_checks(), and __kmp_set_user_lock_vptrs().
{
    lck->lk.initialized = NULL;
    lck->lk.location = NULL;
    lck->lk.next_ticket = 0;
    lck->lk.now_serving = 0;
    lck->lk.owner_id = 0;
    lck->lk.depth_locked = -1;
}
static void __kmp_destroy_user_lock (kmp_user_lock_p lck) [inline], [static]
Definition at line 752 of file kmp_lock.h.
Referenced by __kmp_cleanup_user_locks().
{
    KMP_DEBUG_ASSERT(__kmp_destroy_user_lock_ != NULL);
    (*__kmp_destroy_user_lock_)(lck);
}
static void __kmp_destroy_user_lock_with_checks (kmp_user_lock_p lck) [inline], [static]
Definition at line 761 of file kmp_lock.h.
Referenced by __kmp_get_critical_section_ptr().
{
    KMP_DEBUG_ASSERT(__kmp_destroy_user_lock_with_checks_
       != NULL);
    (*__kmp_destroy_user_lock_with_checks_)(lck);
}
static const ident_t* __kmp_get_user_lock_location (kmp_user_lock_p lck) [inline], [static]
Definition at line 909 of file kmp_lock.h.
Referenced by __kmp_cleanup_user_locks().
{
    if (__kmp_get_user_lock_location_ != NULL) {
        return (*__kmp_get_user_lock_location_)(lck);
    }
    else {
        return NULL;
    }
}
static kmp_int32 __kmp_get_user_lock_owner (kmp_user_lock_p lck) [inline], [static]
Definition at line 638 of file kmp_lock.h.
Referenced by __kmp_check_sync().
{
    KMP_DEBUG_ASSERT(__kmp_get_user_lock_owner_ != NULL);
    return (*__kmp_get_user_lock_owner_)(lck);
}
static void __kmp_init_bootstrap_lock (kmp_bootstrap_lock_t * lck) [inline], [static]
Definition at line 523 of file kmp_lock.h.
Referenced by __kmp_alloc_task_deque(), __kmp_allocate_task_team(), __kmp_atfork_child(), __kmp_do_serial_initialize(), and set_thr_data().
{
    __kmp_init_ticket_lock(lck);
}
void __kmp_init_drdpa_lock (kmp_drdpa_lock_t * lck)
Definition at line 2771 of file kmp_lock.cpp.
Referenced by __kmp_init_drdpa_lock_with_checks(), and __kmp_init_nested_drdpa_lock().
{
    lck->lk.location = NULL;
    lck->lk.mask = 0;
    lck->lk.num_polls = 1;
    lck->lk.polls = (volatile struct kmp_base_drdpa_lock::kmp_lock_poll
       *)
      __kmp_allocate(lck->lk.num_polls * sizeof(*(lck->
      lk.polls)));
    lck->lk.cleanup_ticket = 0;
    lck->lk.old_polls = NULL;
    lck->lk.next_ticket = 0;
    lck->lk.now_serving = 0;
    lck->lk.owner_id = 0; // no thread owns the lock.
    lck->lk.depth_locked = -1; // >= 0 for nestable locks, -1 for simple locks.
    lck->lk.initialized = lck;
    KA_TRACE(1000, ("__kmp_init_drdpa_lock: lock %p initialized\n", lck));
}
static void __kmp_init_lock (kmp_lock_t * lck) [inline], [static]
Definition at line 568 of file kmp_lock.h.
Referenced by __kmp_alloc_taskq(), __kmp_do_serial_initialize(), __kmp_init_node(), __kmp_initialize_root(), __kmp_initialize_team(), __kmpc_taskq(), and set_thr_data().
{
    __kmp_init_ticket_lock(lck);
}
void __kmp_init_nested_drdpa_lock (kmp_drdpa_lock_t * lck)
Definition at line 2941 of file kmp_lock.cpp.
Referenced by __kmp_init_nested_drdpa_lock_with_checks().
{
    __kmp_init_drdpa_lock(lck);
    lck->lk.depth_locked = 0; // >= 0 for nestable locks, -1 for simple locks
}
void __kmp_init_nested_queuing_lock (kmp_queuing_lock_t * lck)
Definition at line 1808 of file kmp_lock.cpp.
Referenced by __kmp_init_nested_queuing_lock_with_checks().
{
    __kmp_init_queuing_lock(lck);
    lck->lk.depth_locked = 0; // >= 0 for nestable locks, -1 for simple locks
}
void __kmp_init_nested_tas_lock (kmp_tas_lock_t * lck)
Definition at line 332 of file kmp_lock.cpp.
Referenced by __kmp_init_nested_tas_lock_with_checks().
{
    __kmp_init_tas_lock(lck);
    lck->lk.depth_locked = 0; // >= 0 for nestable locks, -1 for simple locks
}
void __kmp_init_nested_ticket_lock (kmp_ticket_lock_t * lck)
Definition at line 1020 of file kmp_lock.cpp.
Referenced by __kmp_init_nested_ticket_lock_with_checks().
{
    __kmp_init_ticket_lock(lck);
    lck->lk.depth_locked = 0; // >= 0 for nestable locks, -1 for simple locks
}
static void __kmp_init_nested_user_lock_with_checks (kmp_user_lock_p lck) [inline], [static]
Definition at line 872 of file kmp_lock.h.
{
    KMP_DEBUG_ASSERT(__kmp_init_nested_user_lock_with_checks_
       != NULL);
    (*__kmp_init_nested_user_lock_with_checks_)(lck);
}
void __kmp_init_queuing_lock (kmp_queuing_lock_t * lck)
Definition at line 1650 of file kmp_lock.cpp.
Referenced by __kmp_do_serial_initialize(), __kmp_init_atomic_lock(), __kmp_init_nested_queuing_lock(), and __kmp_init_queuing_lock_with_checks().
{
    lck->lk.location = NULL;
    lck->lk.head_id = 0;
    lck->lk.tail_id = 0;
    lck->lk.next_ticket = 0;
    lck->lk.now_serving = 0;
    lck->lk.owner_id = 0; // no thread owns the lock.
    lck->lk.depth_locked = -1; // >= 0 for nestable locks, -1 for simple locks.
    lck->lk.initialized = lck;
    KA_TRACE(1000, ("__kmp_init_queuing_lock: lock %p initialized\n", lck));
}
void __kmp_init_tas_lock (kmp_tas_lock_t * lck)
Definition at line 209 of file kmp_lock.cpp.
Referenced by __kmp_do_serial_initialize(), __kmp_init_nested_tas_lock(), and __kmp_init_tas_lock_with_checks().
{
    TCW_4(lck->lk.poll, KMP_LOCK_FREE(tas));
}
void __kmp_init_ticket_lock (kmp_ticket_lock_t * lck)
Definition at line 868 of file kmp_lock.cpp.
Referenced by __kmp_init_bootstrap_lock(), __kmp_init_lock(), __kmp_init_nested_ticket_lock(), and __kmp_init_ticket_lock_with_checks().
{
    lck->lk.location = NULL;
    TCW_4(lck->lk.next_ticket, 0);
    TCW_4(lck->lk.now_serving, 0);
    lck->lk.owner_id = 0; // no thread owns the lock.
    lck->lk.depth_locked = -1; // -1 => not a nested lock.
    lck->lk.initialized = (kmp_ticket_lock *)lck;
}
static void __kmp_init_user_lock_with_checks (kmp_user_lock_p lck) [inline], [static]
Definition at line 739 of file kmp_lock.h.
Referenced by __kmp_get_critical_section_ptr().
{
    KMP_DEBUG_ASSERT(__kmp_init_user_lock_with_checks_ !=
       NULL);
    (*__kmp_init_user_lock_with_checks_)(lck);
}
kmp_user_lock_p __kmp_lookup_user_lock (void ** user_lock, char const * func)
Definition at line 4045 of file kmp_lock.cpp.
Referenced by __kmpc_destroy_lock(), __kmpc_destroy_nest_lock(), __kmpc_set_lock(), __kmpc_set_nest_lock(), __kmpc_test_lock(), __kmpc_test_nest_lock(), __kmpc_unset_lock(), and __kmpc_unset_nest_lock().
{
    kmp_user_lock_p lck = NULL;
    if (__kmp_env_consistency_check) {
        if (user_lock == NULL) {
            KMP_FATAL(LockIsUninitialized, func);
        }
    }
    if (OMP_LOCK_T_SIZE < sizeof(void *)) {
        kmp_lock_index_t index = *((kmp_lock_index_t *)user_lock);
        if (__kmp_env_consistency_check) {
            if (! (0 < index && index < __kmp_user_lock_table.
      used)) {
                KMP_FATAL(LockIsUninitialized, func);
            }
        }
        KMP_DEBUG_ASSERT(0 < index && index <
      __kmp_user_lock_table.used);
        KMP_DEBUG_ASSERT(__kmp_user_lock_size > 0);
        lck = __kmp_user_lock_table.table[index];
    }
    else {
        lck = *((kmp_user_lock_p *)user_lock);
    }
    if (__kmp_env_consistency_check) {
        if (lck == NULL) {
            KMP_FATAL(LockIsUninitialized, func);
        }
    }
    return lck;
}
static void __kmp_release_bootstrap_lock (kmp_bootstrap_lock_t * lck) [inline], [static]
Definition at line 517 of file kmp_lock.h.
Referenced by __kmp_abort_process(), __kmp_allocate_task_team(), __kmp_allocate_thread(), __kmp_aux_set_stacksize(), __kmp_bget_dequeue(), __kmp_bget_enqueue(), __kmp_dump_debug_buffer(), __kmp_expand_threads(), __kmp_fork_call(), __kmp_free_task_deque(), __kmp_free_task_team(), __kmp_free_task_threads_data(), __kmp_get_global_thread_id_reg(), __kmp_i18n_catopen(), __kmp_internal_end(), __kmp_internal_end_library(), __kmp_internal_end_thread(), __kmp_join_call(), __kmp_middle_initialize(), __kmp_parallel_initialize(), __kmp_print_storage_map_gtid(), __kmp_printf(), __kmp_push_task(), __kmp_realloc_task_threads_data(), __kmp_reap_task_teams(), __kmp_register_root(), __kmp_remove_my_task(), __kmp_serial_initialize(), __kmp_serialized_parallel(), __kmp_set_num_threads(), __kmp_steal_task(), __kmp_unregister_root_current_thread(), __kmp_warn(), and __kmpc_threadprivate_cached().
{
    __kmp_release_ticket_lock(lck, KMP_GTID_DNE);
}
int __kmp_release_drdpa_lock (kmp_drdpa_lock_t * lck, kmp_int32 gtid)
Definition at line 2729 of file kmp_lock.cpp.
Referenced by __kmp_release_drdpa_lock_with_checks(), and __kmp_release_nested_drdpa_lock().
{
    //
    // Read the ticket value from the lock data struct, then the polls
    // pointer and the mask. The polls pointer must be read before the
    // mask!!! (See above)
    //
    kmp_uint64 ticket = lck->lk.now_serving + 1; // non-volatile load
    volatile struct kmp_base_drdpa_lock::kmp_lock_poll *
      polls
      = (volatile struct kmp_base_drdpa_lock::kmp_lock_poll *)
      TCR_PTR(lck->lk.polls); // volatile load
    kmp_uint64 mask = TCR_8(lck->lk.mask); // volatile load
    KA_TRACE(1000, ("__kmp_release_drdpa_lock: ticket #%lld released lock %p\n",
       ticket - 1, lck));
    KMP_FSYNC_RELEASING(lck);
    KMP_ST_REL64(&(polls[ticket & mask].poll), ticket); // volatile store
    return KMP_LOCK_RELEASED;
}
static void __kmp_release_lock (kmp_lock_t * lck, kmp_int32 gtid) [inline], [static]
Definition at line 562 of file kmp_lock.h.
Referenced by __kmp_alloc_taskq(), __kmp_alloc_thunk(), __kmp_bget_dequeue(), __kmp_bget_enqueue(), __kmp_dequeue_task(), __kmp_enqueue_task(), __kmp_execute_task_from_queue(), __kmp_find_and_remove_finished_child_taskq(), __kmp_find_task_in_ancestor_queue(), __kmp_find_task_in_descendant_queue(), __kmp_find_task_in_queue(), __kmp_free_taskq(), __kmp_free_thunk(), __kmp_internal_begin(), __kmp_remove_queue_from_tree(), __kmp_user_lock_allocate(), __kmp_user_lock_free(), __kmpc_end_taskq(), __kmpc_end_taskq_task(), __kmpc_taskq(), __kmpc_threadprivate_cached(), kmp_threadprivate_insert(), and kmp_threadprivate_insert_private_data().
{
    __kmp_release_ticket_lock(lck, gtid);
}
int __kmp_release_nested_drdpa_lock (kmp_drdpa_lock_t * lck, kmp_int32 gtid)
Definition at line 2906 of file kmp_lock.cpp.
Referenced by __kmp_release_nested_drdpa_lock_with_checks().
{
    KMP_DEBUG_ASSERT(gtid >= 0);
    KMP_MB();
    if (--(lck->lk.depth_locked) == 0) {
        KMP_MB();
        lck->lk.owner_id = 0;
        __kmp_release_drdpa_lock(lck, gtid);
        return KMP_LOCK_RELEASED;
    }
    return KMP_LOCK_STILL_HELD;
}
int __kmp_release_nested_queuing_lock (kmp_queuing_lock_t * lck, kmp_int32 gtid)
Definition at line 1773 of file kmp_lock.cpp.
Referenced by __kmp_release_nested_queuing_lock_with_checks().
{
    KMP_DEBUG_ASSERT(gtid >= 0);
    KMP_MB();
    if (--(lck->lk.depth_locked) == 0) {
        KMP_MB();
        lck->lk.owner_id = 0;
        __kmp_release_queuing_lock(lck, gtid);
        return KMP_LOCK_RELEASED;
    }
    return KMP_LOCK_STILL_HELD;
}
int __kmp_release_nested_tas_lock (kmp_tas_lock_t * lck, kmp_int32 gtid)
Definition at line 302 of file kmp_lock.cpp.
Referenced by __kmp_release_nested_tas_lock_with_checks().
{
    KMP_DEBUG_ASSERT(gtid >= 0);
    KMP_MB();
    if (--(lck->lk.depth_locked) == 0) {
        __kmp_release_tas_lock(lck, gtid);
        return KMP_LOCK_RELEASED;
    }
    return KMP_LOCK_STILL_HELD;
}
int __kmp_release_nested_ticket_lock (kmp_ticket_lock_t * lck, kmp_int32 gtid)
Definition at line 985 of file kmp_lock.cpp.
Referenced by __kmp_release_nested_ticket_lock_with_checks().
{
    KMP_DEBUG_ASSERT(gtid >= 0);
    KMP_MB();
    if (--(lck->lk.depth_locked) == 0) {
        KMP_MB();
        lck->lk.owner_id = 0;
        __kmp_release_ticket_lock(lck, gtid);
        return KMP_LOCK_RELEASED;
    }
    return KMP_LOCK_STILL_HELD;
}
static int __kmp_release_nested_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid) [inline], [static]
Definition at line 864 of file kmp_lock.h.
{
    KMP_DEBUG_ASSERT(
      __kmp_release_nested_user_lock_with_checks_ != NULL);
    return (*__kmp_release_nested_user_lock_with_checks_)(lck
      , gtid);
}
int __kmp_release_queuing_lock (kmp_queuing_lock_t * lck, kmp_int32 gtid)
Definition at line 1489 of file kmp_lock.cpp.
Referenced by __kmp_release_atomic_lock(), __kmp_release_nested_queuing_lock(), and __kmp_release_queuing_lock_with_checks().
{
    register kmp_info_t *this_thr;
    volatile kmp_int32 *head_id_p = & lck->lk.head_id;
    volatile kmp_int32 *tail_id_p = & lck->lk.tail_id;
    KA_TRACE(1000, ("__kmp_release_queuing_lock: lck:%p, T#%d entering\n", lck, gtid));
    KMP_DEBUG_ASSERT(gtid >= 0);
    this_thr = __kmp_thread_from_gtid(gtid);
    KMP_DEBUG_ASSERT(this_thr != NULL);
#ifdef DEBUG_QUEUING_LOCKS
    TRACE_LOCK(gtid+1, "rel ent");
    if (this_thr->th.th_spin_here)
        __kmp_dump_queuing_lock(this_thr, gtid, lck, *head_id_p, *tail_id_p);
    if (this_thr->th.th_next_waiting != 0)
        __kmp_dump_queuing_lock(this_thr, gtid, lck, *head_id_p, *tail_id_p);
#endif
    KMP_DEBUG_ASSERT(!this_thr->th.th_spin_here);
    KMP_DEBUG_ASSERT(this_thr->th.th_next_waiting == 0);
    KMP_FSYNC_RELEASING(lck);
    while(1) {
        kmp_int32 dequeued;
        kmp_int32 head;
        kmp_int32 tail;
        head = *head_id_p;
#ifdef DEBUG_QUEUING_LOCKS
        tail = *tail_id_p;
        TRACE_LOCK_HT(gtid+1, "rel read: ", head, tail);
        if (head == 0) __kmp_dump_queuing_lock(this_thr, gtid, lck, head, tail);
#endif
        KMP_DEBUG_ASSERT(head != 0); /* holding the lock, head must be -1 or queue head
      */
        if (head == -1) { /* nobody on queue */
            /* try (-1,0)->(0,0) */
            if (KMP_COMPARE_AND_STORE_REL32(head_id_p, -1, 0)) {
                KA_TRACE(1000, ("__kmp_release_queuing_lock: lck:%p, T#%d exiting: queue empty\n",
                          lck, gtid));
#ifdef DEBUG_QUEUING_LOCKS
                TRACE_LOCK_HT(gtid+1, "rel exit: ", 0, 0);
#endif
#if OMPT_SUPPORT
                /* nothing to do - no other thread is trying to shift blame */
#endif
                return KMP_LOCK_RELEASED;
            }
            dequeued = FALSE;
        }
        else {
            tail = *tail_id_p;
            if (head == tail) { /* only one thread on the queue */
#ifdef DEBUG_QUEUING_LOCKS
                if (head <= 0) __kmp_dump_queuing_lock(this_thr, gtid, lck, head, tail);
#endif
                KMP_DEBUG_ASSERT(head > 0);
                /* try (h,h)->(-1,0) */
                dequeued = KMP_COMPARE_AND_STORE_REL64((kmp_int64 *) tail_id_p,
                  KMP_PACK_64(head, head), KMP_PACK_64(-1, 0));
#ifdef DEBUG_QUEUING_LOCKS
                TRACE_LOCK(gtid+1, "rel deq: (h,h)->(-1,0)");
#endif
            }
            else {
                volatile kmp_int32 *waiting_id_p;
                kmp_info_t *head_thr = __kmp_thread_from_gtid(head
       - 1);
                KMP_DEBUG_ASSERT(head_thr != NULL);
                waiting_id_p = & head_thr->th.th_next_waiting;
                /* Does this require synchronous reads? */
#ifdef DEBUG_QUEUING_LOCKS
                if (head <= 0 || tail <= 0) __kmp_dump_queuing_lock(this_thr, gtid, lck, head, tail);
#endif
                KMP_DEBUG_ASSERT(head > 0 && tail > 0);
                /* try (h,t)->(h',t) or (t,t) */
                KMP_MB();
                /* make sure enqueuing thread has time to update next waiting thread field */
                *head_id_p = KMP_WAIT_YIELD((volatile kmp_uint32*)waiting_id_p, 0,
      KMP_NEQ, NULL);
#ifdef DEBUG_QUEUING_LOCKS
                TRACE_LOCK(gtid+1, "rel deq: (h,t)->(h',t)");
#endif
                dequeued = TRUE;
            }
        }
        if (dequeued) {
            kmp_info_t *head_thr = __kmp_thread_from_gtid(head - 1);
            KMP_DEBUG_ASSERT(head_thr != NULL);
            /* Does this require synchronous reads? */
#ifdef DEBUG_QUEUING_LOCKS
            if (head <= 0 || tail <= 0) __kmp_dump_queuing_lock(this_thr, gtid, lck, head, tail);
#endif
            KMP_DEBUG_ASSERT(head > 0 && tail > 0);
            /* For clean code only.
             * Thread not released until next statement prevents race with acquire code.
             */
            head_thr->th.th_next_waiting = 0;
#ifdef DEBUG_QUEUING_LOCKS
            TRACE_LOCK_T(gtid+1, "rel nw=0 for t=", head);
#endif
            KMP_MB();
            /* reset spin value */
            head_thr->th.th_spin_here = FALSE;
            KA_TRACE(1000, ("__kmp_release_queuing_lock: lck:%p, T#%d exiting: after dequeuing\n",
                      lck, gtid));
#ifdef DEBUG_QUEUING_LOCKS
            TRACE_LOCK(gtid+1, "rel exit 2");
#endif
            return KMP_LOCK_RELEASED;
        }
        /* KMP_CPU_PAUSE(); don't want to make releasing thread hold up acquiring threads */
#ifdef DEBUG_QUEUING_LOCKS
        TRACE_LOCK(gtid+1, "rel retry");
#endif
    } /* while */
    KMP_ASSERT2(0, "should not get here");
    return KMP_LOCK_RELEASED;
}
int __kmp_release_tas_lock (kmp_tas_lock_t * lck, kmp_int32 gtid)
Definition at line 176 of file kmp_lock.cpp.
Referenced by __kmp_create_worker(), __kmp_release_nested_tas_lock(), and __kmp_release_tas_lock_with_checks().
{
    KMP_MB(); /* Flush all pending memory write invalidates. */
    KMP_FSYNC_RELEASING(lck);
    KMP_ST_REL32(&(lck->lk.poll), KMP_LOCK_FREE(tas));
    KMP_MB(); /* Flush all pending memory write invalidates. */
    KMP_YIELD(TCR_4(__kmp_nth) > (__kmp_avail_proc ?
      __kmp_avail_proc :
      __kmp_xproc));
    return KMP_LOCK_RELEASED;
}
int __kmp_release_ticket_lock (kmp_ticket_lock_t * lck, kmp_int32 gtid)
Definition at line 827 of file kmp_lock.cpp.
Referenced by __kmp_release_bootstrap_lock(), __kmp_release_lock(), __kmp_release_nested_ticket_lock(), and __kmp_release_ticket_lock_with_checks().
{
    kmp_uint32 distance;
    KMP_MB(); /* Flush all pending memory write invalidates. */
    KMP_FSYNC_RELEASING(lck);
    distance = (TCR_4(lck->lk.next_ticket) - TCR_4(lck->
      lk.now_serving));
    KMP_ST_REL32(&(lck->lk.now_serving), lck->lk.
      now_serving + 1);
    KMP_MB(); /* Flush all pending memory write invalidates. */
    KMP_YIELD(distance
      > (kmp_uint32) (__kmp_avail_proc ? __kmp_avail_proc :
      __kmp_xproc));
    return KMP_LOCK_RELEASED;
}
static void __kmp_release_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid) [inline], [static]
Definition at line 730 of file kmp_lock.h.
Referenced by __kmp_end_critical_section_reduce_block(), and __kmpc_end_critical().
{
    KMP_DEBUG_ASSERT(__kmp_release_user_lock_with_checks_
       != NULL);
    (*__kmp_release_user_lock_with_checks_) (lck, gtid);
}
static void __kmp_set_user_lock_flags (kmp_user_lock_p lck, kmp_lock_flags_t flags) [inline], [static]
Definition at line 934 of file kmp_lock.h.
Referenced by __kmp_user_lock_allocate().
{
    if (__kmp_set_user_lock_flags_ != NULL) {
        (*__kmp_set_user_lock_flags_)(lck, flags);
    }
}
static void __kmp_set_user_lock_location (kmp_user_lock_p lck, const ident_t * loc) [inline], [static]
Definition at line 922 of file kmp_lock.h.
Referenced by __kmp_get_critical_section_ptr(), __kmpc_init_lock(), and __kmpc_init_nest_lock().
{
    if (__kmp_set_user_lock_location_ != NULL) {
        (*__kmp_set_user_lock_location_)(lck, loc);
    }
}
void __kmp_set_user_lock_vptrs (kmp_lock_kind_t user_lock_kind)
Definition at line 3639 of file kmp_lock.cpp.
Referenced by __kmp_env_initialize().
{
    switch (user_lock_kind) {
        case lk_default:
        default:
        KMP_ASSERT(0);
        case lk_tas: {
            __kmp_base_user_lock_size = sizeof(
      kmp_base_tas_lock_t);
            __kmp_user_lock_size = sizeof(kmp_tas_lock_t);
            __kmp_get_user_lock_owner_ =
              (kmp_int32 (*)(kmp_user_lock_p))
              (&__kmp_get_tas_lock_owner);
            if (__kmp_env_consistency_check) {
                KMP_BIND_USER_LOCK_WITH_CHECKS(tas);
                KMP_BIND_NESTED_USER_LOCK_WITH_CHECKS(tas);
            }
            else {
                KMP_BIND_USER_LOCK(tas);
                KMP_BIND_NESTED_USER_LOCK(tas);
            }
            __kmp_destroy_user_lock_ =
              (void (*)(kmp_user_lock_p))
              (&__kmp_destroy_tas_lock);
             __kmp_is_user_lock_initialized_ =
               (int (*)(kmp_user_lock_p)) NULL;
             __kmp_get_user_lock_location_ =
               (const ident_t * (*)(kmp_user_lock_p)) NULL;
             __kmp_set_user_lock_location_ =
               (void (*)(kmp_user_lock_p, const ident_t *)) NULL;
             __kmp_get_user_lock_flags_ =
               (kmp_lock_flags_t (*)(kmp_user_lock_p)) NULL;
             __kmp_set_user_lock_flags_ =
               (void (*)(kmp_user_lock_p,
      kmp_lock_flags_t)) NULL;
        }
        break;
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM)
        case lk_futex: {
            __kmp_base_user_lock_size = sizeof(kmp_base_futex_lock_t);
            __kmp_user_lock_size = sizeof(kmp_futex_lock_t);
            __kmp_get_user_lock_owner_ =
              (kmp_int32 (*)(kmp_user_lock_p))
              (&__kmp_get_futex_lock_owner);
            if (__kmp_env_consistency_check) {
                KMP_BIND_USER_LOCK_WITH_CHECKS(futex);
                KMP_BIND_NESTED_USER_LOCK_WITH_CHECKS(futex);
            }
            else {
                KMP_BIND_USER_LOCK(futex);
                KMP_BIND_NESTED_USER_LOCK(futex);
            }
            __kmp_destroy_user_lock_ =
              (void (*)(kmp_user_lock_p))
              (&__kmp_destroy_futex_lock);
             __kmp_is_user_lock_initialized_ =
               (int (*)(kmp_user_lock_p)) NULL;
             __kmp_get_user_lock_location_ =
               (const ident_t * (*)(kmp_user_lock_p)) NULL;
             __kmp_set_user_lock_location_ =
               (void (*)(kmp_user_lock_p, const ident_t *)) NULL;
             __kmp_get_user_lock_flags_ =
               (kmp_lock_flags_t (*)(kmp_user_lock_p)) NULL;
             __kmp_set_user_lock_flags_ =
               (void (*)(kmp_user_lock_p,
      kmp_lock_flags_t)) NULL;
        }
        break;
#endif // KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM)
        case lk_ticket: {
            __kmp_base_user_lock_size = sizeof(
      kmp_base_ticket_lock_t);
            __kmp_user_lock_size = sizeof(kmp_ticket_lock_t);
            __kmp_get_user_lock_owner_ =
              (kmp_int32 (*)(kmp_user_lock_p))
              (&__kmp_get_ticket_lock_owner);
            if (__kmp_env_consistency_check) {
                KMP_BIND_USER_LOCK_WITH_CHECKS(ticket);
                KMP_BIND_NESTED_USER_LOCK_WITH_CHECKS(ticket);
            }
            else {
                KMP_BIND_USER_LOCK(ticket);
                KMP_BIND_NESTED_USER_LOCK(ticket);
            }
            __kmp_destroy_user_lock_ =
              (void (*)(kmp_user_lock_p))
              (&__kmp_destroy_ticket_lock);
             __kmp_is_user_lock_initialized_ =
               (int (*)(kmp_user_lock_p))
               (&__kmp_is_ticket_lock_initialized);
             __kmp_get_user_lock_location_ =
               (const ident_t * (*)(kmp_user_lock_p))
               (&__kmp_get_ticket_lock_location);
             __kmp_set_user_lock_location_ =
               (void (*)(kmp_user_lock_p, const ident_t *))
               (&__kmp_set_ticket_lock_location);
             __kmp_get_user_lock_flags_ =
               (kmp_lock_flags_t (*)(kmp_user_lock_p))
               (&__kmp_get_ticket_lock_flags);
             __kmp_set_user_lock_flags_ =
               (void (*)(kmp_user_lock_p,
      kmp_lock_flags_t))
               (&__kmp_set_ticket_lock_flags);
        }
        break;
        case lk_queuing: {
            __kmp_base_user_lock_size = sizeof(
      kmp_base_queuing_lock_t);
            __kmp_user_lock_size = sizeof(
      kmp_queuing_lock_t);
            __kmp_get_user_lock_owner_ =
              (kmp_int32 (*)(kmp_user_lock_p))
              (&__kmp_get_queuing_lock_owner);
            if (__kmp_env_consistency_check) {
                KMP_BIND_USER_LOCK_WITH_CHECKS(queuing);
                KMP_BIND_NESTED_USER_LOCK_WITH_CHECKS(queuing);
            }
            else {
                KMP_BIND_USER_LOCK(queuing);
                KMP_BIND_NESTED_USER_LOCK(queuing);
            }
            __kmp_destroy_user_lock_ =
              (void (*)(kmp_user_lock_p))
              (&__kmp_destroy_queuing_lock);
             __kmp_is_user_lock_initialized_ =
               (int (*)(kmp_user_lock_p))
               (&__kmp_is_queuing_lock_initialized);
             __kmp_get_user_lock_location_ =
               (const ident_t * (*)(kmp_user_lock_p))
               (&__kmp_get_queuing_lock_location);
             __kmp_set_user_lock_location_ =
               (void (*)(kmp_user_lock_p, const ident_t *))
               (&__kmp_set_queuing_lock_location);
             __kmp_get_user_lock_flags_ =
               (kmp_lock_flags_t (*)(kmp_user_lock_p))
               (&__kmp_get_queuing_lock_flags);
             __kmp_set_user_lock_flags_ =
               (void (*)(kmp_user_lock_p,
      kmp_lock_flags_t))
               (&__kmp_set_queuing_lock_flags);
        }
        break;
#if KMP_USE_ADAPTIVE_LOCKS
        case lk_adaptive: {
            __kmp_base_user_lock_size = sizeof(kmp_base_adaptive_lock_t);
            __kmp_user_lock_size = sizeof(kmp_adaptive_lock_t);
            __kmp_get_user_lock_owner_ =
              (kmp_int32 (*)(kmp_user_lock_p))
              (&__kmp_get_queuing_lock_owner);
            if (__kmp_env_consistency_check) {
                KMP_BIND_USER_LOCK_WITH_CHECKS(adaptive);
            }
            else {
                KMP_BIND_USER_LOCK(adaptive);
            }
            __kmp_destroy_user_lock_ =
              (void (*)(kmp_user_lock_p))
              (&__kmp_destroy_adaptive_lock);
            __kmp_is_user_lock_initialized_ =
              (int (*)(kmp_user_lock_p))
              (&__kmp_is_queuing_lock_initialized);
            __kmp_get_user_lock_location_ =
              (const ident_t * (*)(kmp_user_lock_p))
              (&__kmp_get_queuing_lock_location);
            __kmp_set_user_lock_location_ =
              (void (*)(kmp_user_lock_p, const ident_t *))
              (&__kmp_set_queuing_lock_location);
            __kmp_get_user_lock_flags_ =
              (kmp_lock_flags_t (*)(kmp_user_lock_p))
              (&__kmp_get_queuing_lock_flags);
            __kmp_set_user_lock_flags_ =
              (void (*)(kmp_user_lock_p, kmp_lock_flags_t))
              (&__kmp_set_queuing_lock_flags);
        }
        break;
#endif // KMP_USE_ADAPTIVE_LOCKS
        case lk_drdpa: {
            __kmp_base_user_lock_size = sizeof(
      kmp_base_drdpa_lock_t);
            __kmp_user_lock_size = sizeof(kmp_drdpa_lock_t);
            __kmp_get_user_lock_owner_ =
              (kmp_int32 (*)(kmp_user_lock_p))
              (&__kmp_get_drdpa_lock_owner);
            if (__kmp_env_consistency_check) {
                KMP_BIND_USER_LOCK_WITH_CHECKS(drdpa);
                KMP_BIND_NESTED_USER_LOCK_WITH_CHECKS(drdpa);
            }
            else {
                KMP_BIND_USER_LOCK(drdpa);
                KMP_BIND_NESTED_USER_LOCK(drdpa);
            }
            __kmp_destroy_user_lock_ =
              (void (*)(kmp_user_lock_p))
              (&__kmp_destroy_drdpa_lock);
             __kmp_is_user_lock_initialized_ =
               (int (*)(kmp_user_lock_p))
               (&__kmp_is_drdpa_lock_initialized);
             __kmp_get_user_lock_location_ =
               (const ident_t * (*)(kmp_user_lock_p))
               (&__kmp_get_drdpa_lock_location);
             __kmp_set_user_lock_location_ =
               (void (*)(kmp_user_lock_p, const ident_t *))
               (&__kmp_set_drdpa_lock_location);
             __kmp_get_user_lock_flags_ =
               (kmp_lock_flags_t (*)(kmp_user_lock_p))
               (&__kmp_get_drdpa_lock_flags);
             __kmp_set_user_lock_flags_ =
               (void (*)(kmp_user_lock_p,
      kmp_lock_flags_t))
               (&__kmp_set_drdpa_lock_flags);
        }
        break;
    }
}
static int __kmp_test_bootstrap_lock (kmp_bootstrap_lock_t * lck) [inline], [static]
Definition at line 511 of file kmp_lock.h.
{
    return __kmp_test_ticket_lock(lck, KMP_GTID_DNE);
}
int __kmp_test_drdpa_lock (kmp_drdpa_lock_t * lck, kmp_int32 gtid)
Definition at line 2674 of file kmp_lock.cpp.
Referenced by __kmp_test_drdpa_lock_with_checks(), and __kmp_test_nested_drdpa_lock().
{
    //
    // First get a ticket, then read the polls pointer and the mask.
    // The polls pointer must be read before the mask!!! (See above)
    //
    kmp_uint64 ticket = TCR_8(lck->lk.next_ticket); // volatile load
    volatile struct kmp_base_drdpa_lock::kmp_lock_poll *
      polls
      = (volatile struct kmp_base_drdpa_lock::kmp_lock_poll *)
      TCR_PTR(lck->lk.polls); // volatile load
    kmp_uint64 mask = TCR_8(lck->lk.mask); // volatile load
    if (TCR_8(polls[ticket & mask].poll) == ticket) {
        kmp_uint64 next_ticket = ticket + 1;
        if (KMP_COMPARE_AND_STORE_ACQ64((kmp_int64 *)&lck->
      lk.next_ticket,
          ticket, next_ticket)) {
            KMP_FSYNC_ACQUIRED(lck);
            KA_TRACE(1000, ("__kmp_test_drdpa_lock: ticket #%lld acquired lock %p\n",
               ticket, lck));
            lck->lk.now_serving = ticket; // non-volatile store
            //
            // Since no threads are waiting, there is no possibility that
            // we would want to reconfigure the polling area. We might
            // have the cleanup ticket value (which says that it is now
            // safe to deallocate old_polls), but we'll let a later thread
            // which calls __kmp_acquire_lock do that - this routine
            // isn't supposed to block, and we would risk blocks if we
            // called __kmp_free() to do the deallocation.
            //
            return TRUE;
        }
    }
    return FALSE;
}
static int __kmp_test_lock (kmp_lock_t * lck, kmp_int32 gtid) [inline], [static]
Definition at line 556 of file kmp_lock.h.
Referenced by __kmp_find_and_remove_finished_child_taskq().
{
    return __kmp_test_ticket_lock(lck, gtid);
}
int __kmp_test_nested_drdpa_lock (kmp_drdpa_lock_t * lck, kmp_int32 gtid)
Definition at line 2871 of file kmp_lock.cpp.
Referenced by __kmp_test_nested_drdpa_lock_with_checks().
{
    int retval;
    KMP_DEBUG_ASSERT(gtid >= 0);
    if (__kmp_get_drdpa_lock_owner(lck) == gtid) {
        retval = ++lck->lk.depth_locked;
    }
    else if (!__kmp_test_drdpa_lock(lck, gtid)) {
        retval = 0;
    }
    else {
        KMP_MB();
        retval = lck->lk.depth_locked = 1;
        KMP_MB();
        lck->lk.owner_id = gtid + 1;
    }
    return retval;
}
int __kmp_test_nested_queuing_lock (kmp_queuing_lock_t * lck, kmp_int32 gtid)
Definition at line 1737 of file kmp_lock.cpp.
Referenced by __kmp_test_nested_queuing_lock_with_checks().
{
    int retval;
    KMP_DEBUG_ASSERT(gtid >= 0);
    if (__kmp_get_queuing_lock_owner(lck) == gtid) {
        retval = ++lck->lk.depth_locked;
    }
    else if (!__kmp_test_queuing_lock(lck, gtid)) {
        retval = 0;
    }
    else {
        KMP_MB();
        retval = lck->lk.depth_locked = 1;
        KMP_MB();
        lck->lk.owner_id = gtid + 1;
    }
    return retval;
}
int __kmp_test_nested_tas_lock (kmp_tas_lock_t * lck, kmp_int32 gtid)
Definition at line 272 of file kmp_lock.cpp.
Referenced by __kmp_test_nested_tas_lock_with_checks().
{
    int retval;
    KMP_DEBUG_ASSERT(gtid >= 0);
    if (__kmp_get_tas_lock_owner(lck) == gtid) {
        retval = ++lck->lk.depth_locked;
    }
    else if (!__kmp_test_tas_lock(lck, gtid)) {
        retval = 0;
    }
    else {
        KMP_MB();
        retval = lck->lk.depth_locked = 1;
    }
    return retval;
}
int __kmp_test_nested_ticket_lock (kmp_ticket_lock_t * lck, kmp_int32 gtid)
Definition at line 949 of file kmp_lock.cpp.
Referenced by __kmp_test_nested_ticket_lock_with_checks().
{
    int retval;
    KMP_DEBUG_ASSERT(gtid >= 0);
    if (__kmp_get_ticket_lock_owner(lck) == gtid) {
        retval = ++lck->lk.depth_locked;
    }
    else if (!__kmp_test_ticket_lock(lck, gtid)) {
        retval = 0;
    }
    else {
        KMP_MB();
        retval = lck->lk.depth_locked = 1;
        KMP_MB();
        lck->lk.owner_id = gtid + 1;
    }
    return retval;
}
static int __kmp_test_nested_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid) [inline], [static]
Definition at line 854 of file kmp_lock.h.
{
    KMP_DEBUG_ASSERT(__kmp_test_nested_user_lock_with_checks_
       != NULL);
    return (*__kmp_test_nested_user_lock_with_checks_)(lck, gtid
       );
}
int __kmp_test_queuing_lock (kmp_queuing_lock_t * lck, kmp_int32 gtid)
Definition at line 1436 of file kmp_lock.cpp.
Referenced by __kmp_test_atomic_lock(), __kmp_test_nested_queuing_lock(), and __kmp_test_queuing_lock_with_checks().
{
    volatile kmp_int32 *head_id_p = & lck->lk.head_id;
    kmp_int32 head;
#ifdef KMP_DEBUG
    kmp_info_t *this_thr;
#endif
    KA_TRACE(1000, ("__kmp_test_queuing_lock: T#%d entering\n", gtid));
    KMP_DEBUG_ASSERT(gtid >= 0);
#ifdef KMP_DEBUG
    this_thr = __kmp_thread_from_gtid(gtid);
    KMP_DEBUG_ASSERT(this_thr != NULL);
    KMP_DEBUG_ASSERT(!this_thr->th.th_spin_here);
#endif
    head = *head_id_p;
    if (head == 0) { /* nobody on queue, nobody holding */
        /* try (0,0)->(-1,0) */
        if (KMP_COMPARE_AND_STORE_ACQ32(head_id_p, 0, -1)) {
            KA_TRACE(1000, ("__kmp_test_queuing_lock: T#%d exiting: holding lock\n", gtid));
            KMP_FSYNC_ACQUIRED(lck);
            return TRUE;
        }
    }
    KA_TRACE(1000, ("__kmp_test_queuing_lock: T#%d exiting: without lock\n", gtid));
    return FALSE;
}
int __kmp_test_tas_lock (kmp_tas_lock_t * lck, kmp_int32 gtid)
Definition at line 154 of file kmp_lock.cpp.
Referenced by __kmp_test_nested_tas_lock(), and __kmp_test_tas_lock_with_checks().
{
    if ((lck->lk.poll == KMP_LOCK_FREE(tas))
      && KMP_COMPARE_AND_STORE_ACQ32(& (lck->lk.
      poll), KMP_LOCK_FREE(tas), KMP_LOCK_BUSY(gtid+1, tas))) {
        KMP_FSYNC_ACQUIRED(lck);
        return TRUE;
    }
    return FALSE;
}
int __kmp_test_ticket_lock (kmp_ticket_lock_t * lck, kmp_int32 gtid)
Definition at line 793 of file kmp_lock.cpp.
Referenced by __kmp_test_bootstrap_lock(), __kmp_test_lock(), __kmp_test_nested_ticket_lock(), and __kmp_test_ticket_lock_with_checks().
{
    kmp_uint32 my_ticket = TCR_4(lck->lk.next_ticket);
    if (TCR_4(lck->lk.now_serving) == my_ticket) {
        kmp_uint32 next_ticket = my_ticket + 1;
        if (KMP_COMPARE_AND_STORE_ACQ32((kmp_int32 *) &lck->
      lk.next_ticket,
          my_ticket, next_ticket)) {
            KMP_FSYNC_ACQUIRED(lck);
            return TRUE;
        }
    }
    return FALSE;
}
int __kmp_test_ticket_lock_with_cheks (kmp_ticket_lock_t * lck, kmp_int32 gtid)
static int __kmp_test_user_lock_with_checks (kmp_user_lock_p lck, kmp_int32 gtid) [inline], [static]
Definition at line 720 of file kmp_lock.h.
{
    KMP_DEBUG_ASSERT(__kmp_test_user_lock_with_checks_ !=
       NULL);
    return (*__kmp_test_user_lock_with_checks_)(lck, gtid);
}
kmp_user_lock_p __kmp_user_lock_allocate (void ** user_lock, kmp_int32 gtid, kmp_lock_flags_t flags)
Definition at line 3976 of file kmp_lock.cpp.
Referenced by __kmp_get_critical_section_ptr(), __kmpc_init_lock(), and __kmpc_init_nest_lock().
{
    kmp_user_lock_p lck;
    kmp_lock_index_t index;
    KMP_DEBUG_ASSERT(user_lock);
    __kmp_acquire_lock(&__kmp_global_lock, gtid);
    if (__kmp_lock_pool == NULL) {
        // Lock pool is empty. Allocate new memory.
        if (__kmp_num_locks_in_block <= 1) { // Tune this cutoff point.
            lck = (kmp_user_lock_p) __kmp_allocate(
      __kmp_user_lock_size);
        }
        else {
            lck = __kmp_lock_block_allocate();
        }
        // Insert lock in the table so that it can be freed in __kmp_cleanup,
        // and debugger has info on all allocated locks.
        index = __kmp_lock_table_insert(lck);
    }
    else {
        // Pick up lock from pool.
        lck = __kmp_lock_pool;
        index = __kmp_lock_pool->pool.index;
        __kmp_lock_pool = __kmp_lock_pool->pool.
      next;
    }
    //
    // We could potentially differentiate between nested and regular locks
    // here, and do the lock table lookup for regular locks only.
    //
    if (OMP_LOCK_T_SIZE < sizeof(void *)) {
        * ((kmp_lock_index_t *) user_lock) = index;
    }
    else {
        * ((kmp_user_lock_p *) user_lock) = lck;
    }
    // mark the lock if it is critical section lock.
    __kmp_set_user_lock_flags(lck, flags);
    __kmp_release_lock(& __kmp_global_lock, gtid); // AC: TODO: move
       this line upper
    return lck;
}
void __kmp_user_lock_free (void ** user_lock, kmp_int32 gtid, kmp_user_lock_p lck)
Definition at line 4026 of file kmp_lock.cpp.
Referenced by __kmp_get_critical_section_ptr(), __kmpc_destroy_lock(), and __kmpc_destroy_nest_lock().
{
    KMP_DEBUG_ASSERT(user_lock != NULL);
    KMP_DEBUG_ASSERT(lck != NULL);
    __kmp_acquire_lock(& __kmp_global_lock, gtid);
    lck->pool.next = __kmp_lock_pool;
    __kmp_lock_pool = lck;
    if (OMP_LOCK_T_SIZE < sizeof(void *)) {
        kmp_lock_index_t index = * ((kmp_lock_index_t *) user_lock);
        KMP_DEBUG_ASSERT(0 < index && index <=
      __kmp_user_lock_table.used);
        lck->pool.index = index;
    }
    __kmp_release_lock(& __kmp_global_lock, gtid);
}
void __kmp_validate_locks (void)
Definition at line 44 of file kmp_lock.cpp.
Referenced by __kmp_do_serial_initialize().
{
    int i;
    kmp_uint32 x, y;
    /* Check to make sure unsigned arithmetic does wraps properly */
    x = ~((kmp_uint32) 0) - 2;
    y = x - 2;
    for (i = 0; i < 8; ++i, ++x, ++y) {
        kmp_uint32 z = (x - y);
        KMP_ASSERT(z == 2);
    }
    KMP_ASSERT(offsetof(kmp_base_queuing_lock, tail_id) % 8 == 0);
}
KMP_BUILD_ASSERT (offsetof(kmp_base_queuing_lock_t, tail_id)% 8 = =0)
Variable Documentation
int(* __kmp_acquire_nested_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
Definition at line 3626 of file kmp_lock.cpp.
Referenced by __kmp_acquire_nested_user_lock_with_checks().
int(* __kmp_acquire_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
Definition at line 3619 of file kmp_lock.cpp.
Referenced by __kmp_acquire_user_lock_with_checks().
size_t __kmp_base_user_lock_size
Definition at line 3615 of file kmp_lock.cpp.
Referenced by __kmp_end_critical_section_reduce_block(), and __kmp_enter_critical_section_reduce_block().
void(* __kmp_destroy_nested_user_lock_with_checks_)(kmp_user_lock_p lck)
Definition at line 3631 of file kmp_lock.cpp.
Referenced by __kmp_destroy_nested_user_lock_with_checks().
void(* __kmp_destroy_user_lock_)(kmp_user_lock_p lck)
Definition at line 3624 of file kmp_lock.cpp.
Referenced by __kmp_destroy_user_lock(), and __kmp_set_user_lock_vptrs().
void(* __kmp_destroy_user_lock_with_checks_)(kmp_user_lock_p lck)
Definition at line 3625 of file kmp_lock.cpp.
Referenced by __kmp_destroy_user_lock_with_checks().
kmp_lock_flags_t(* __kmp_get_user_lock_flags_)(kmp_user_lock_p lck)
Definition at line 3636 of file kmp_lock.cpp.
Referenced by __kmp_set_user_lock_vptrs().
const ident_t*(* __kmp_get_user_lock_location_)(kmp_user_lock_p lck)
Definition at line 3634 of file kmp_lock.cpp.
Referenced by __kmp_get_user_lock_location(), and __kmp_set_user_lock_vptrs().
kmp_int32(* __kmp_get_user_lock_owner_)(kmp_user_lock_p lck)
Definition at line 3618 of file kmp_lock.cpp.
Referenced by __kmp_get_user_lock_owner(), and __kmp_set_user_lock_vptrs().
void(* __kmp_init_nested_user_lock_with_checks_)(kmp_user_lock_p lck)
Definition at line 3630 of file kmp_lock.cpp.
Referenced by __kmp_init_nested_user_lock_with_checks().
void(* __kmp_init_user_lock_with_checks_)(kmp_user_lock_p lck)
Definition at line 3623 of file kmp_lock.cpp.
Referenced by __kmp_init_user_lock_with_checks().
int(* __kmp_is_user_lock_initialized_)(kmp_user_lock_p lck)
Definition at line 3633 of file kmp_lock.cpp.
Referenced by __kmp_cleanup_user_locks(), and __kmp_set_user_lock_vptrs().
kmp_block_of_locks_t* __kmp_lock_blocks
Definition at line 3909 of file kmp_lock.cpp.
Referenced by __kmp_atfork_child(), __kmp_cleanup_user_locks(), and __kmp_lock_block_allocate().
kmp_user_lock_p __kmp_lock_pool
Definition at line 3906 of file kmp_lock.cpp.
Referenced by __kmp_user_lock_allocate(), and __kmp_user_lock_free().
int __kmp_num_locks_in_block
Definition at line 3910 of file kmp_lock.cpp.
Referenced by __kmp_lock_block_allocate(), __kmp_stg_parse_lock_block(), and __kmp_stg_print_lock_block().
int(* __kmp_release_nested_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
Definition at line 3629 of file kmp_lock.cpp.
Referenced by __kmp_release_nested_user_lock_with_checks().
int(* __kmp_release_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
Definition at line 3622 of file kmp_lock.cpp.
Referenced by __kmp_release_user_lock_with_checks().
void(* __kmp_set_user_lock_flags_)(kmp_user_lock_p lck, kmp_lock_flags_t flags)
Definition at line 3637 of file kmp_lock.cpp.
Referenced by __kmp_set_user_lock_flags(), and __kmp_set_user_lock_vptrs().
void(* __kmp_set_user_lock_location_)(kmp_user_lock_p lck, const ident_t *loc)
Definition at line 3635 of file kmp_lock.cpp.
Referenced by __kmp_set_user_lock_location(), and __kmp_set_user_lock_vptrs().
int(* __kmp_test_nested_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
Definition at line 3628 of file kmp_lock.cpp.
Referenced by __kmp_test_nested_user_lock_with_checks().
int(* __kmp_test_user_lock_with_checks_)(kmp_user_lock_p lck, kmp_int32 gtid)
Definition at line 3621 of file kmp_lock.cpp.
Referenced by __kmp_test_user_lock_with_checks().
kmp_lock_kind_t __kmp_user_lock_kind
Definition at line 3613 of file kmp_lock.cpp.
Referenced by __kmp_env_initialize(), __kmp_stg_parse_lock_kind(), __kmp_stg_print_lock_kind(), __kmpc_critical(), __kmpc_destroy_lock(), __kmpc_destroy_nest_lock(), __kmpc_end_critical(), __kmpc_init_lock(), __kmpc_init_nest_lock(), __kmpc_set_lock(), __kmpc_set_nest_lock(), __kmpc_test_lock(), __kmpc_test_nest_lock(), __kmpc_unset_lock(), and __kmpc_unset_nest_lock().
size_t __kmp_user_lock_size
Definition at line 3616 of file kmp_lock.cpp.
kmp_lock_table_t __kmp_user_lock_table
Definition at line 3905 of file kmp_lock.cpp.
Referenced by __kmp_atfork_child().