kmp_stub.h File Reference
Macros
#define KMP_SCHED_TYPE_DEFINED
Typedefs
typedef enum kmp_sched kmp_sched_t
Enumerations
enum kmp_sched {
*
kmp_sched_lower = 0,
kmp_sched_static = 1,
kmp_sched_dynamic = 2,
kmp_sched_guided = 3,
*
kmp_sched_auto = 4,
kmp_sched_upper_std = 5,
kmp_sched_lower_ext = 100,
kmp_sched_trapezoidal = 101,
*
kmp_sched_upper = 102,
kmp_sched_default = kmp_sched_static,
kmp_sched_static = 1,
kmp_sched_dynamic = 2,
*
kmp_sched_guided = 3,
kmp_sched_auto = 4,
kmp_sched_default = kmp_sched_static
 }
Functions
void __kmps_set_blocktime (int arg)
int __kmps_get_blocktime (void)
void __kmps_set_dynamic (int arg)
int __kmps_get_dynamic (void)
void __kmps_set_library (int arg)
int __kmps_get_library (void)
void __kmps_set_nested (int arg)
int __kmps_get_nested (void)
void __kmps_set_stacksize (int arg)
int __kmps_get_stacksize ()
void __kmps_set_schedule (kmp_sched_t kind, int modifier)
void __kmps_get_schedule (kmp_sched_t *kind, int *modifier)
void __kmps_set_proc_bind (kmp_proc_bind_t arg)
kmp_proc_bind_t __kmps_get_proc_bind (void)
double __kmps_get_wtime ()
double __kmps_get_wtick ()
Macro Definition Documentation
#define KMP_SCHED_TYPE_DEFINED
Definition at line 35 of file kmp_stub.h.
Typedef Documentation
typedef enum kmp_sched kmp_sched_t
Enumeration Type Documentation
enum kmp_sched
Enumerator
kmp_sched_lower
kmp_sched_static
kmp_sched_dynamic
kmp_sched_guided
kmp_sched_auto
kmp_sched_upper_std
kmp_sched_lower_ext
kmp_sched_trapezoidal
kmp_sched_upper
kmp_sched_default
kmp_sched_static
kmp_sched_dynamic
kmp_sched_guided
kmp_sched_auto
kmp_sched_default
Definition at line 36 of file kmp_stub.h.
                       {
    kmp_sched_static = 1, // mapped to kmp_sch_static_chunked (33)
    kmp_sched_dynamic = 2, // mapped to kmp_sch_dynamic_chunked (35)
    kmp_sched_guided = 3, // mapped to kmp_sch_guided_chunked (36)
    kmp_sched_auto = 4, // mapped to kmp_sch_auto (38)
    kmp_sched_default = kmp_sched_static // default scheduling
} kmp_sched_t;
Function Documentation
int __kmps_get_blocktime (void)
Definition at line 116 of file kmp_stub.c.
Referenced by FTN_GET_BLOCKTIME().
                                 {
    i;
    return __kmps_blocktime;
} // __kmps_get_blocktime
int __kmps_get_dynamic (void)
Definition at line 128 of file kmp_stub.c.
Referenced by FTN_GET_DYNAMIC().
                               {
    i;
    return __kmps_dynamic;
} // __kmps_get_dynamic
int __kmps_get_library (void)
Definition at line 140 of file kmp_stub.c.
Referenced by FTN_GET_LIBRARY().
                               {
    i;
    return __kmps_library;
} // __kmps_get_library
int __kmps_get_nested (void)
Definition at line 152 of file kmp_stub.c.
Referenced by FTN_GET_NESTED().
                              {
    i;
    return __kmps_nested;
} // __kmps_get_nested
kmp_proc_bind_t __kmps_get_proc_bind (void)
Definition at line 193 of file kmp_stub.c.
Referenced by FTN_GET_PROC_BIND().
                                             {
    i;
    return __kmps_proc_bind;
} // __kmps_get_proc_bind
void __kmps_get_schedule (kmp_sched_t * kind, int * modifier)
Definition at line 178 of file kmp_stub.c.
Referenced by FTN_GET_SCHEDULE().
                                                                 {
        i;
        *kind = __kmps_sched_kind;
        *modifier = __kmps_sched_modifier;
    } // __kmps_get_schedule
int __kmps_get_stacksize ()
Definition at line 164 of file kmp_stub.c.
Referenced by FTN_GET_STACKSIZE(), and FTN_GET_STACKSIZE_S().
                                 {
    i;
    return __kmps_stacksize;
} // __kmps_get_stacksize
double __kmps_get_wtick ()
Definition at line 226 of file kmp_stub.c.
Referenced by FTN_GET_WTICK().
                                {
    // Number of seconds between successive clock ticks.
    double wtick = 0.0;
    i;
    #if KMP_OS_WINDOWS
        {
            DWORD increment;
            DWORD adjustment;
            BOOL disabled;
            BOOL rc;
            rc = GetSystemTimeAdjustment(& adjustment, & increment, & disabled);
            if (rc) {
                wtick = 1.0E-07 * (double)(disabled ? increment : adjustment);
            } else {
                // TODO: Assert or abort here.
                wtick = 1.0E-03;
            }; // if
        }
    #else
        // TODO: gettimeofday() returns in microseconds, but what the precision?
        wtick = 1.0E-06;
    #endif
    return wtick;
}; // __kmps_get_wtick
double __kmps_get_wtime ()
Definition at line 200 of file kmp_stub.c.
Referenced by FTN_GET_WTIME().
                                {
    // Elapsed wall clock time (in second) from "sometime in the past".
    double wtime = 0.0;
    i;
    #if KMP_OS_WINDOWS
        if (frequency > 0.0) {
            LARGE_INTEGER now;
            BOOL status = QueryPerformanceCounter(& now);
            if (status) {
                wtime = double(now.QuadPart) / frequency;
            }; // if
        }; // if
    #else
        // gettimeofday() returns seconds and microseconds since the Epoch.
        struct timeval tval;
        int rc;
        rc = gettimeofday(& tval, NULL);
        if (rc == 0) {
            wtime = (double)(tval.tv_sec) + 1.0E-06 * (double)(tval.tv_usec);
        } else {
            // TODO: Assert or abort here.
        }; // if
    #endif
    return wtime;
}; // __kmps_get_wtime
void __kmps_set_blocktime (int arg)
Definition at line 111 of file kmp_stub.c.
Referenced by FTN_SET_BLOCKTIME(), and kmp_set_blocktime().
                                     {
    i;
    __kmps_blocktime = arg;
} // __kmps_set_blocktime
void __kmps_set_dynamic (int arg)
Definition at line 123 of file kmp_stub.c.
Referenced by FTN_SET_DYNAMIC(), and omp_set_dynamic().
                                   {
    i;
    __kmps_dynamic = arg;
} // __kmps_set_dynamic
void __kmps_set_library (int arg)
Definition at line 135 of file kmp_stub.c.
Referenced by FTN_SET_LIBRARY(), FTN_SET_LIBRARY_SERIAL(), FTN_SET_LIBRARY_THROUGHPUT(), FTN_SET_LIBRARY_TURNAROUND(), and kmp_set_library().
                                   {
    i;
    __kmps_library = arg;
} // __kmps_set_library
void __kmps_set_nested (int arg)
Definition at line 147 of file kmp_stub.c.
Referenced by FTN_SET_NESTED(), and omp_set_nested().
                                  {
    i;
    __kmps_nested = arg;
} // __kmps_set_nested
void __kmps_set_proc_bind (kmp_proc_bind_t arg)
Definition at line 188 of file kmp_stub.c.
                                                 {
    i;
    __kmps_proc_bind = arg;
} // __kmps_set_proc_bind
void __kmps_set_schedule (kmp_sched_t kind, int modifier)
Definition at line 172 of file kmp_stub.c.
Referenced by FTN_SET_SCHEDULE(), and omp_set_schedule().
                                                               {
        i;
        __kmps_sched_kind = kind;
        __kmps_sched_modifier = modifier;
    } // __kmps_set_schedule
void __kmps_set_stacksize (int arg)
Definition at line 159 of file kmp_stub.c.
Referenced by FTN_SET_STACKSIZE(), FTN_SET_STACKSIZE_S(), kmp_set_stacksize(), and kmp_set_stacksize_s().
                                     {
    i;
    __kmps_stacksize = arg;
} // __kmps_set_stacksize