kmp_csupport.c File Reference
#include `omp.h`
*
#include `kmp.h`
*
#include `kmp_i18n.h`
*
#include `kmp_itt.h`
*
#include `kmp_error.h`
*
#include `kmp_stats.h`
*
Macros
#define MAX_MESSAGE 512
#define INIT_LOCK __kmp_init_user_lock_with_checks
#define INIT_NESTED_LOCK __kmp_init_nested_user_lock_with_checks
#define ACQUIRE_LOCK __kmp_acquire_user_lock_with_checks
#define ACQUIRE_LOCK_TIMED __kmp_acquire_user_lock_with_checks_timed
#define ACQUIRE_NESTED_LOCK __kmp_acquire_nested_user_lock_with_checks
#define ACQUIRE_NESTED_LOCK_TIMED __kmp_acquire_nested_user_lock_with_checks_timed
#define RELEASE_LOCK __kmp_release_user_lock_with_checks
#define RELEASE_NESTED_LOCK __kmp_release_nested_user_lock_with_checks
#define TEST_LOCK __kmp_test_user_lock_with_checks
#define TEST_NESTED_LOCK __kmp_test_nested_user_lock_with_checks
#define DESTROY_LOCK __kmp_destroy_user_lock_with_checks
#define DESTROY_NESTED_LOCK __kmp_destroy_nested_user_lock_with_checks
#define __KMP_SET_REDUCTION_METHOD(gtid, rmethod) ((__kmp_threads[ (gtid) ] -> th.th_local.packed_reduction_method) = (rmethod))
#define __KMP_GET_REDUCTION_METHOD(gtid) (__kmp_threads[ (gtid) ] -> th.th_local.packed_reduction_method)
Functions
void __kmpc_begin (ident_t *loc, kmp_int32 flags)
void __kmpc_end (ident_t *loc)
kmp_int32 __kmpc_global_thread_num (ident_t *loc)
kmp_int32 __kmpc_global_num_threads (ident_t *loc)
kmp_int32 __kmpc_bound_thread_num (ident_t *loc)
kmp_int32 __kmpc_bound_num_threads (ident_t *loc)
kmp_int32 __kmpc_ok_to_fork (ident_t *loc)
kmp_int32 __kmpc_in_parallel (ident_t *loc)
void __kmpc_push_num_threads (ident_t *loc, kmp_int32 global_tid, kmp_int32 num_threads)
void __kmpc_pop_num_threads (ident_t *loc, kmp_int32 global_tid)
void __kmpc_push_proc_bind (ident_t *loc, kmp_int32 global_tid, kmp_int32 proc_bind)
void __kmpc_fork_call (ident_t *loc, kmp_int32 argc, kmpc_micro microtask,...)
void __kmpc_push_num_teams (ident_t *loc, kmp_int32 global_tid, kmp_int32 num_teams, kmp_int32 num_threads)
void __kmpc_fork_teams (ident_t *loc, kmp_int32 argc, kmpc_micro microtask,...)
int __kmpc_invoke_task_func (int gtid)
void __kmpc_serialized_parallel (ident_t *loc, kmp_int32 global_tid)
void __kmpc_end_serialized_parallel (ident_t *loc, kmp_int32 global_tid)
void __kmpc_flush (ident_t *loc)
void __kmpc_barrier (ident_t *loc, kmp_int32 global_tid)
kmp_int32 __kmpc_master (ident_t *loc, kmp_int32 global_tid)
void __kmpc_end_master (ident_t *loc, kmp_int32 global_tid)
void __kmpc_ordered (ident_t *loc, kmp_int32 gtid)
void __kmpc_end_ordered (ident_t *loc, kmp_int32 gtid)
static kmp_user_lock_p __kmp_get_critical_section_ptr (kmp_critical_name *crit, ident_t const *loc, kmp_int32 gtid)
void __kmpc_critical (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *crit)
void __kmpc_end_critical (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *crit)
kmp_int32 __kmpc_barrier_master (ident_t *loc, kmp_int32 global_tid)
void __kmpc_end_barrier_master (ident_t *loc, kmp_int32 global_tid)
kmp_int32 __kmpc_barrier_master_nowait (ident_t *loc, kmp_int32 global_tid)
kmp_int32 __kmpc_single (ident_t *loc, kmp_int32 global_tid)
void __kmpc_end_single (ident_t *loc, kmp_int32 global_tid)
void __kmpc_for_static_fini (ident_t *loc, kmp_int32 global_tid)
void ompc_set_num_threads (int arg)
void ompc_set_dynamic (int flag)
void ompc_set_nested (int flag)
void ompc_set_max_active_levels (int max_active_levels)
void ompc_set_schedule (omp_sched_t kind, int modifier)
int ompc_get_ancestor_thread_num (int level)
int ompc_get_team_size (int level)
void kmpc_set_stacksize (int arg)
void kmpc_set_stacksize_s (size_t arg)
void kmpc_set_blocktime (int arg)
void kmpc_set_library (int arg)
void kmpc_set_defaults (char const *str)
int kmpc_set_affinity_mask_proc (int proc, void **mask)
int kmpc_unset_affinity_mask_proc (int proc, void **mask)
int kmpc_get_affinity_mask_proc (int proc, void **mask)
void __kmpc_copyprivate (ident_t *loc, kmp_int32 gtid, size_t cpy_size, void *cpy_data, void(*cpy_func)(void *, void *), kmp_int32 didit)
void __kmpc_init_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
void __kmpc_init_nest_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
void __kmpc_destroy_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
void __kmpc_destroy_nest_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
void __kmpc_set_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
void __kmpc_set_nest_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
void __kmpc_unset_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
void __kmpc_unset_nest_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
int __kmpc_test_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
int __kmpc_test_nest_lock (ident_t *loc, kmp_int32 gtid, void **user_lock)
static __forceinline void __kmp_enter_critical_section_reduce_block (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *crit)
static __forceinline void __kmp_end_critical_section_reduce_block (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *crit)
kmp_int32 __kmpc_reduce_nowait (ident_t *loc, kmp_int32 global_tid, kmp_int32 num_vars, size_t reduce_size, void *reduce_data, void(*reduce_func)(void *lhs_data, void *rhs_data), kmp_critical_name *lck)
void __kmpc_end_reduce_nowait (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *lck)
kmp_int32 __kmpc_reduce (ident_t *loc, kmp_int32 global_tid, kmp_int32 num_vars, size_t reduce_size, void *reduce_data, void(*reduce_func)(void *lhs_data, void *rhs_data), kmp_critical_name *lck)
void __kmpc_end_reduce (ident_t *loc, kmp_int32 global_tid, kmp_critical_name *lck)
kmp_uint64 __kmpc_get_taskid ()
kmp_uint64 __kmpc_get_parent_taskid ()
void __kmpc_place_threads (int nS, int sO, int nC, int cO, int nT)
Macro Definition Documentation
#define __KMP_GET_REDUCTION_METHOD(gtid) (__kmp_threads[ (gtid) ] -> th.th_local.packed_reduction_method)
Definition at line 2541 of file kmp_csupport.c.
Referenced by __kmpc_end_reduce(), and __kmpc_end_reduce_nowait().
#define __KMP_SET_REDUCTION_METHOD(gtid, rmethod) ((__kmp_threads[ (gtid) ] -> th.th_local.packed_reduction_method) = (rmethod))
Definition at line 2538 of file kmp_csupport.c.
Referenced by __kmpc_reduce(), and __kmpc_reduce_nowait().
#define ACQUIRE_LOCK __kmp_acquire_user_lock_with_checks
Definition at line 1805 of file kmp_csupport.c.
Referenced by __kmpc_set_lock().
#define ACQUIRE_LOCK_TIMED __kmp_acquire_user_lock_with_checks_timed
Definition at line 1806 of file kmp_csupport.c.
#define ACQUIRE_NESTED_LOCK __kmp_acquire_nested_user_lock_with_checks
Definition at line 1807 of file kmp_csupport.c.
Referenced by __kmpc_set_nest_lock().
#define ACQUIRE_NESTED_LOCK_TIMED __kmp_acquire_nested_user_lock_with_checks_timed
Definition at line 1808 of file kmp_csupport.c.
#define DESTROY_LOCK __kmp_destroy_user_lock_with_checks
Definition at line 1813 of file kmp_csupport.c.
Referenced by __kmpc_destroy_lock().
#define DESTROY_NESTED_LOCK __kmp_destroy_nested_user_lock_with_checks
Definition at line 1814 of file kmp_csupport.c.
Referenced by __kmpc_destroy_nest_lock().
#define INIT_LOCK __kmp_init_user_lock_with_checks
Definition at line 1803 of file kmp_csupport.c.
Referenced by __kmpc_init_lock().
#define INIT_NESTED_LOCK __kmp_init_nested_user_lock_with_checks
Definition at line 1804 of file kmp_csupport.c.
Referenced by __kmpc_init_nest_lock().
#define MAX_MESSAGE 512
Definition at line 28 of file kmp_csupport.c.
#define RELEASE_LOCK __kmp_release_user_lock_with_checks
Definition at line 1809 of file kmp_csupport.c.
Referenced by __kmpc_unset_lock().
#define RELEASE_NESTED_LOCK __kmp_release_nested_user_lock_with_checks
Definition at line 1810 of file kmp_csupport.c.
Referenced by __kmpc_unset_nest_lock().
#define TEST_LOCK __kmp_test_user_lock_with_checks
Definition at line 1811 of file kmp_csupport.c.
Referenced by __kmpc_test_lock().
#define TEST_NESTED_LOCK __kmp_test_nested_user_lock_with_checks
Definition at line 1812 of file kmp_csupport.c.
Referenced by __kmpc_test_nest_lock().
Function Documentation
static __forceinline void __kmp_end_critical_section_reduce_block (ident_t * loc, kmp_int32 global_tid, kmp_critical_name * crit) [static]
Definition at line 2610 of file kmp_csupport.c.
Referenced by __kmpc_end_reduce(), and __kmpc_end_reduce_nowait().
                                                                                                         {
    kmp_user_lock_p lck;
#if KMP_USE_DYNAMIC_LOCK
    if (KMP_IS_D_LOCK(__kmp_user_lock_seq)) {
        lck = (kmp_user_lock_p)crit;
        if (__kmp_env_consistency_check)
            __kmp_pop_sync(global_tid, ct_critical, loc);
        KMP_D_LOCK_FUNC(lck, unset)((kmp_dyna_lock_t *)lck, global_tid);
    } else {
        kmp_indirect_lock_t *ilk = (kmp_indirect_lock_t *)TCR_PTR(*((kmp_indirect_lock_t **)crit));
        if (__kmp_env_consistency_check)
            __kmp_pop_sync(global_tid, ct_critical, loc);
        KMP_I_LOCK_FUNC(ilk, unset)(ilk->lock, global_tid);
    }
#else // KMP_USE_DYNAMIC_LOCK
    // We know that the fast reduction code is only emitted by Intel compilers with 32 byte critical
    // sections. If there isn't enough space, then we have to use a pointer.
    if (__kmp_base_user_lock_size > 32) {
        lck = *((kmp_user_lock_p *) crit);
        KMP_ASSERT(lck != NULL);
    } else {
        lck = (kmp_user_lock_p) crit;
    }
    if (__kmp_env_consistency_check)
        __kmp_pop_sync(global_tid, ct_critical, loc);
    __kmp_release_user_lock_with_checks(lck, global_tid);
#endif // KMP_USE_DYNAMIC_LOCK
} // __kmp_end_critical_section_reduce_block
static __forceinline void __kmp_enter_critical_section_reduce_block (ident_t * loc, kmp_int32 global_tid, kmp_critical_name * crit) [static]
Definition at line 2549 of file kmp_csupport.c.
Referenced by __kmpc_reduce(), and __kmpc_reduce_nowait().
                                                                                                           
      {
    // this lock was visible to a customer and to the threading profile tool as a serial overhead span
    // (although it's used for an internal purpose only)
    // why was it visible in previous implementation?
    // should we keep it visible in new reduce block?
    kmp_user_lock_p lck;
#if KMP_USE_DYNAMIC_LOCK
    kmp_dyna_lock_t *lk = (kmp_dyna_lock_t *)crit;
    // Check if it is initialized.
    if (*lk == 0) {
        if (KMP_IS_D_LOCK(__kmp_user_lock_seq)) {
            KMP_COMPARE_AND_STORE_ACQ32((volatile kmp_int32 *)crit, 0,
      KMP_GET_D_TAG(__kmp_user_lock_seq));
        } else {
            __kmp_init_indirect_csptr(crit, loc, global_tid, KMP_GET_I_TAG(__kmp_user_lock_seq));
        }
    }
    // Branch for accessing the actual lock object and set operation. This branching is inevitable since
    // this lock initialization does not follow the normal dispatch path (lock table is not used).
    if (KMP_EXTRACT_D_TAG(lk) != 0) {
        lck = (kmp_user_lock_p)lk;
        KMP_DEBUG_ASSERT(lck != NULL);
        if (__kmp_env_consistency_check) {
            __kmp_push_sync(global_tid, ct_critical, loc, lck,
      __kmp_user_lock_seq);
        }
        KMP_D_LOCK_FUNC(lk, set)(lk, global_tid);
    } else {
        kmp_indirect_lock_t *ilk = *((kmp_indirect_lock_t **)lk);
        lck = ilk->lock;
        KMP_DEBUG_ASSERT(lck != NULL);
        if (__kmp_env_consistency_check) {
            __kmp_push_sync(global_tid, ct_critical, loc, lck,
      __kmp_user_lock_seq);
        }
        KMP_I_LOCK_FUNC(ilk, set)(lck, global_tid);
    }
#else // KMP_USE_DYNAMIC_LOCK
    // We know that the fast reduction code is only emitted by Intel compilers
    // with 32 byte critical sections. If there isn't enough space, then we
    // have to use a pointer.
    if (__kmp_base_user_lock_size <=
      INTEL_CRITICAL_SIZE) {
        lck = (kmp_user_lock_p)crit;
    }
    else {
        lck = __kmp_get_critical_section_ptr(crit, loc, global_tid);
    }
    KMP_DEBUG_ASSERT(lck != NULL);
    if (__kmp_env_consistency_check)
        __kmp_push_sync(global_tid, ct_critical, loc, lck);
    __kmp_acquire_user_lock_with_checks(lck, global_tid);
#endif // KMP_USE_DYNAMIC_LOCK
}
static kmp_user_lock_p __kmp_get_critical_section_ptr (kmp_critical_name * crit, ident_t const * loc, kmp_int32 gtid) [static]
Definition at line 1048 of file kmp_csupport.c.
Referenced by __kmp_enter_critical_section_reduce_block(), and __kmpc_critical().
{
    kmp_user_lock_p *lck_pp = (kmp_user_lock_p *)crit;
    //
    // Because of the double-check, the following load
    // doesn't need to be volatile.
    //
    kmp_user_lock_p lck = (kmp_user_lock_p)TCR_PTR(*lck_pp);
    if (lck == NULL) {
        void * idx;
        // Allocate & initialize the lock.
        // Remember allocated locks in table in order to free them in __kmp_cleanup()
        lck = __kmp_user_lock_allocate(&idx, gtid,
      kmp_lf_critical_section);
        __kmp_init_user_lock_with_checks(lck);
        __kmp_set_user_lock_location(lck, loc);
#if USE_ITT_BUILD
        __kmp_itt_critical_creating(lck);
            // __kmp_itt_critical_creating() should be called *before* the first usage of underlying
            // lock. It is the only place where we can guarantee it. There are chances the lock will
            // destroyed with no usage, but it is not a problem, because this is not real event seen
            // by user but rather setting name for object (lock). See more details in kmp_itt.h.
#endif /* USE_ITT_BUILD */
        //
        // Use a cmpxchg instruction to slam the start of the critical
        // section with the lock pointer. If another thread beat us
        // to it, deallocate the lock, and use the lock that the other
        // thread allocated.
        //
        int status = KMP_COMPARE_AND_STORE_PTR(lck_pp, 0, lck);
        if (status == 0) {
            // Deallocate the lock and reload the value.
#if USE_ITT_BUILD
            __kmp_itt_critical_destroyed(lck);
                // Let ITT know the lock is destroyed and the same memory location may be reused for
                // another purpose.
#endif /* USE_ITT_BUILD */
            __kmp_destroy_user_lock_with_checks(lck);
            __kmp_user_lock_free(&idx, gtid, lck);
            lck = (kmp_user_lock_p)TCR_PTR(*lck_pp);
            KMP_DEBUG_ASSERT(lck != NULL);
        }
    }
    return lck;
}
void __kmpc_destroy_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 2017 of file kmp_csupport.c.
Referenced by FTN_DESTROY_LOCK().
                                                                        {
#if KMP_USE_DYNAMIC_LOCK
# if USE_ITT_BUILD
    kmp_user_lock_p lck;
    if (KMP_EXTRACT_D_TAG(user_lock) == 0) {
        lck = ((kmp_indirect_lock_t *)KMP_LOOKUP_I_LOCK(user_lock))->lock;
    } else {
        lck = (kmp_user_lock_p)user_lock;
    }
    __kmp_itt_lock_destroyed(lck);
# endif
    KMP_D_LOCK_FUNC(user_lock, destroy)((kmp_dyna_lock_t *)user_lock);
#else
    kmp_user_lock_p lck;
    if ((__kmp_user_lock_kind == lk_tas)
      && (sizeof(lck->tas.lk.poll) <= OMP_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
      && (sizeof(lck->futex.lk.poll) <= OMP_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_lookup_user_lock(user_lock, "omp_destroy_lock");
    }
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_destroy_lock)) {
        ompt_callbacks.ompt_callback(ompt_event_destroy_lock)((uint64_t) lck);
    }
#endif
#if USE_ITT_BUILD
    __kmp_itt_lock_destroyed(lck);
#endif /* USE_ITT_BUILD */
    DESTROY_LOCK(lck);
    if ((__kmp_user_lock_kind == lk_tas)
      && (sizeof(lck->tas.lk.poll) <= OMP_LOCK_T_SIZE)) {
        ;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
      && (sizeof(lck->futex.lk.poll) <= OMP_LOCK_T_SIZE)) {
        ;
    }
#endif
    else {
        __kmp_user_lock_free(user_lock, gtid, lck);
    }
#endif // KMP_USE_DYNAMIC_LOCK
} // __kmpc_destroy_lock
void __kmpc_destroy_nest_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 2077 of file kmp_csupport.c.
Referenced by FTN_DESTROY_NEST_LOCK().
                                                                             {
#if KMP_USE_DYNAMIC_LOCK
# if USE_ITT_BUILD
    kmp_indirect_lock_t *ilk = KMP_LOOKUP_I_LOCK(user_lock);
    __kmp_itt_lock_destroyed(ilk->lock);
# endif
    KMP_D_LOCK_FUNC(user_lock, destroy)((kmp_dyna_lock_t *)user_lock);
#else // KMP_USE_DYNAMIC_LOCK
    kmp_user_lock_p lck;
    if ((__kmp_user_lock_kind == lk_tas) && (sizeof(lck->
      tas.lk.poll)
      + sizeof(lck->tas.lk.depth_locked) <=
      OMP_NEST_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
     && (sizeof(lck->futex.lk.poll) + sizeof(lck->futex.lk.depth_locked)
     <= OMP_NEST_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_lookup_user_lock(user_lock, "omp_destroy_nest_lock");
    }
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_destroy_nest_lock)) {
        ompt_callbacks.ompt_callback(ompt_event_destroy_nest_lock)((uint64_t) lck);
    }
#endif
#if USE_ITT_BUILD
    __kmp_itt_lock_destroyed(lck);
#endif /* USE_ITT_BUILD */
    DESTROY_NESTED_LOCK(lck);
    if ((__kmp_user_lock_kind == lk_tas) && (sizeof(lck->
      tas.lk.poll)
     + sizeof(lck->tas.lk.depth_locked) <=
      OMP_NEST_LOCK_T_SIZE)) {
        ;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
     && (sizeof(lck->futex.lk.poll) + sizeof(lck->futex.lk.depth_locked)
     <= OMP_NEST_LOCK_T_SIZE)) {
        ;
    }
#endif
    else {
        __kmp_user_lock_free(user_lock, gtid, lck);
    }
#endif // KMP_USE_DYNAMIC_LOCK
} // __kmpc_destroy_nest_lock
kmp_uint64 __kmpc_get_parent_taskid ()
Definition at line 3028 of file kmp_csupport.c.
                           {
    kmp_int32 gtid;
    kmp_info_t * thread;
    kmp_taskdata_t * parent_task;
    gtid = __kmp_get_gtid();
    if (gtid < 0) {
        return 0;
    }; // if
    thread = __kmp_thread_from_gtid(gtid);
    parent_task = thread->th.th_current_task->td_parent;
    return (parent_task == NULL ? 0 : parent_task->td_task_id);
} // __kmpc_get_parent_taskid
kmp_uint64 __kmpc_get_taskid ()
Definition at line 3012 of file kmp_csupport.c.
                    {
    kmp_int32 gtid;
    kmp_info_t * thread;
    gtid = __kmp_get_gtid();
    if (gtid < 0) {
        return 0;
    }; // if
    thread = __kmp_thread_from_gtid(gtid);
    return thread->th.th_current_task->td_task_id;
} // __kmpc_get_taskid
void __kmpc_init_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 1907 of file kmp_csupport.c.
Referenced by FTN_INIT_LOCK().
                                                                      {
#if KMP_USE_DYNAMIC_LOCK
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    if (__kmp_env_consistency_check && user_lock == NULL) {
        KMP_FATAL(LockIsUninitialized, "omp_init_lock");
    }
    __kmp_init_lock_with_hint(loc, user_lock, __kmp_user_lock_seq);
#else // KMP_USE_DYNAMIC_LOCK
    static char const * const func = "omp_init_lock";
    kmp_user_lock_p lck;
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    if (__kmp_env_consistency_check) {
        if (user_lock == NULL) {
            KMP_FATAL(LockIsUninitialized, func);
        }
    }
    KMP_CHECK_USER_LOCK_INIT();
    if ((__kmp_user_lock_kind == lk_tas)
      && (sizeof(lck->tas.lk.poll) <= OMP_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
      && (sizeof(lck->futex.lk.poll) <= OMP_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_user_lock_allocate(user_lock, gtid, 0);
    }
    INIT_LOCK(lck);
    __kmp_set_user_lock_location(lck, loc);
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_init_lock)) {
        ompt_callbacks.ompt_callback(ompt_event_init_lock)((uint64_t) lck);
    }
#endif
#if USE_ITT_BUILD
    __kmp_itt_lock_creating(lck);
#endif /* USE_ITT_BUILD */
#endif // KMP_USE_DYNAMIC_LOCK
} // __kmpc_init_lock
void __kmpc_init_nest_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 1961 of file kmp_csupport.c.
Referenced by FTN_INIT_NEST_LOCK().
                                                                          {
#if KMP_USE_DYNAMIC_LOCK
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    if (__kmp_env_consistency_check && user_lock == NULL) {
        KMP_FATAL(LockIsUninitialized, "omp_init_nest_lock");
    }
    __kmp_init_nest_lock_with_hint(loc, user_lock, __kmp_user_lock_seq);
#else // KMP_USE_DYNAMIC_LOCK
    static char const * const func = "omp_init_nest_lock";
    kmp_user_lock_p lck;
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    if (__kmp_env_consistency_check) {
        if (user_lock == NULL) {
            KMP_FATAL(LockIsUninitialized, func);
        }
    }
    KMP_CHECK_USER_LOCK_INIT();
    if ((__kmp_user_lock_kind == lk_tas) && (sizeof(lck->
      tas.lk.poll)
      + sizeof(lck->tas.lk.depth_locked) <=
      OMP_NEST_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
     && (sizeof(lck->futex.lk.poll) + sizeof(lck->futex.lk.depth_locked)
     <= OMP_NEST_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_user_lock_allocate(user_lock, gtid, 0);
    }
    INIT_NESTED_LOCK(lck);
    __kmp_set_user_lock_location(lck, loc);
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_init_nest_lock)) {
        ompt_callbacks.ompt_callback(ompt_event_init_nest_lock)((uint64_t) lck);
    }
#endif
#if USE_ITT_BUILD
    __kmp_itt_lock_creating(lck);
#endif /* USE_ITT_BUILD */
#endif // KMP_USE_DYNAMIC_LOCK
} // __kmpc_init_nest_lock
int __kmpc_invoke_task_func (int gtid)
Definition at line 456 of file kmp_csupport.c.
{
    return __kmp_invoke_task_func(gtid);
}
void __kmpc_place_threads (int nS, int sO, int nC, int cO, int nT)
Definition at line 3044 of file kmp_csupport.c.
{
    if (! __kmp_init_serial) {
        __kmp_serial_initialize();
    }
    __kmp_place_num_sockets = nS;
    __kmp_place_socket_offset = sO;
    __kmp_place_num_cores = nC;
    __kmp_place_core_offset = cO;
    __kmp_place_num_threads_per_core = nT;
}
void __kmpc_pop_num_threads (ident_t * loc, kmp_int32 global_tid)
Definition at line 249 of file kmp_csupport.c.
{
    KA_TRACE(20, ("__kmpc_pop_num_threads: enter\n"));
    /* the num_threads are automatically popped */
}
void __kmpc_push_proc_bind (ident_t * loc, kmp_int32 global_tid, kmp_int32 proc_bind)
Definition at line 260 of file kmp_csupport.c.
{
    KA_TRACE(20, ("__kmpc_push_proc_bind: enter T#%d proc_bind=%d\n",
      global_tid, proc_bind));
    __kmp_push_proc_bind(loc, global_tid, (kmp_proc_bind_t)proc_bind);
}
void __kmpc_set_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 2136 of file kmp_csupport.c.
Referenced by FTN_SET_LOCK().
                                                                    {
    KMP_COUNT_BLOCK(OMP_set_lock);
#if KMP_USE_DYNAMIC_LOCK
    int tag = KMP_EXTRACT_D_TAG(user_lock);
# if USE_ITT_BUILD
   __kmp_itt_lock_acquiring((kmp_user_lock_p)user_lock); // itt function will get to the
       right lock object.
# endif
# if KMP_USE_INLINED_TAS
    if (tag == locktag_tas && !__kmp_env_consistency_check) {
        KMP_ACQUIRE_TAS_LOCK(user_lock, gtid);
    } else
# elif KMP_USE_INLINED_FUTEX
    if (tag == locktag_futex && !__kmp_env_consistency_check) {
        KMP_ACQUIRE_FUTEX_LOCK(user_lock, gtid);
    } else
# endif
    {
        __kmp_direct_set[tag]((kmp_dyna_lock_t *)user_lock, gtid);
    }
# if USE_ITT_BUILD
    __kmp_itt_lock_acquired((kmp_user_lock_p)user_lock);
# endif
#else // KMP_USE_DYNAMIC_LOCK
    kmp_user_lock_p lck;
    if ((__kmp_user_lock_kind == lk_tas)
      && (sizeof(lck->tas.lk.poll) <= OMP_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
      && (sizeof(lck->futex.lk.poll) <= OMP_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_lookup_user_lock(user_lock, "omp_set_lock");
    }
#if USE_ITT_BUILD
    __kmp_itt_lock_acquiring(lck);
#endif /* USE_ITT_BUILD */
    ACQUIRE_LOCK(lck, gtid);
#if USE_ITT_BUILD
    __kmp_itt_lock_acquired(lck);
#endif /* USE_ITT_BUILD */
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_acquired_lock)) {
        ompt_callbacks.ompt_callback(ompt_event_acquired_lock)((uint64_t) lck);
    }
#endif
#endif // KMP_USE_DYNAMIC_LOCK
}
void __kmpc_set_nest_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 2198 of file kmp_csupport.c.
Referenced by FTN_SET_NEST_LOCK().
                                                                         {
#if KMP_USE_DYNAMIC_LOCK
# if USE_ITT_BUILD
    __kmp_itt_lock_acquiring((kmp_user_lock_p)user_lock);
# endif
    KMP_D_LOCK_FUNC(user_lock, set)((kmp_dyna_lock_t *)user_lock, gtid);
# if USE_ITT_BUILD
    __kmp_itt_lock_acquired((kmp_user_lock_p)user_lock);
#endif
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled) {
        // missing support here: need to know whether acquired first or not
    }
#endif
#else // KMP_USE_DYNAMIC_LOCK
    int acquire_status;
    kmp_user_lock_p lck;
    if ((__kmp_user_lock_kind == lk_tas) && (sizeof(lck->
      tas.lk.poll)
      + sizeof(lck->tas.lk.depth_locked) <=
      OMP_NEST_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
     && (sizeof(lck->futex.lk.poll) + sizeof(lck->futex.lk.depth_locked)
     <= OMP_NEST_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_lookup_user_lock(user_lock, "omp_set_nest_lock");
    }
#if USE_ITT_BUILD
    __kmp_itt_lock_acquiring(lck);
#endif /* USE_ITT_BUILD */
    ACQUIRE_NESTED_LOCK(lck, gtid, &acquire_status);
#if USE_ITT_BUILD
    __kmp_itt_lock_acquired(lck);
#endif /* USE_ITT_BUILD */
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled) {
        if (acquire_status == KMP_LOCK_ACQUIRED_FIRST) {
           if(ompt_callbacks.ompt_callback(ompt_event_acquired_nest_lock_first))
              ompt_callbacks.ompt_callback(ompt_event_acquired_nest_lock_first)((uint64_t)
      lck);
        } else {
           if(ompt_callbacks.ompt_callback(ompt_event_acquired_nest_lock_next))
              ompt_callbacks.ompt_callback(ompt_event_acquired_nest_lock_next)((uint64_t) lck
      );
        }
    }
#endif
#endif // KMP_USE_DYNAMIC_LOCK
}
int __kmpc_test_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 2398 of file kmp_csupport.c.
Referenced by FTN_TEST_LOCK().
{
    KMP_COUNT_BLOCK(OMP_test_lock);
#if KMP_USE_DYNAMIC_LOCK
    int rc;
    int tag = KMP_EXTRACT_D_TAG(user_lock);
# if USE_ITT_BUILD
    __kmp_itt_lock_acquiring((kmp_user_lock_p)user_lock);
# endif
# if KMP_USE_INLINED_TAS
    if (tag == locktag_tas && !__kmp_env_consistency_check) {
        KMP_TEST_TAS_LOCK(user_lock, gtid, rc);
    } else
# elif KMP_USE_INLINED_FUTEX
    if (tag == locktag_futex && !__kmp_env_consistency_check) {
        KMP_TEST_FUTEX_LOCK(user_lock, gtid, rc);
    } else
# endif
    {
        rc = __kmp_direct_test[tag]((kmp_dyna_lock_t *)user_lock, gtid);
    }
    if (rc) {
# if USE_ITT_BUILD
        __kmp_itt_lock_acquired((kmp_user_lock_p)user_lock);
# endif
        return FTN_TRUE;
    } else {
# if USE_ITT_BUILD
        __kmp_itt_lock_cancelled((kmp_user_lock_p)user_lock);
# endif
        return FTN_FALSE;
    }
#else // KMP_USE_DYNAMIC_LOCK
    kmp_user_lock_p lck;
    int rc;
    if ((__kmp_user_lock_kind == lk_tas)
      && (sizeof(lck->tas.lk.poll) <= OMP_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
      && (sizeof(lck->futex.lk.poll) <= OMP_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_lookup_user_lock(user_lock, "omp_test_lock");
    }
#if USE_ITT_BUILD
    __kmp_itt_lock_acquiring(lck);
#endif /* USE_ITT_BUILD */
    rc = TEST_LOCK(lck, gtid);
#if USE_ITT_BUILD
    if (rc) {
        __kmp_itt_lock_acquired(lck);
    } else {
        __kmp_itt_lock_cancelled(lck);
    }
#endif /* USE_ITT_BUILD */
    return (rc ? FTN_TRUE : FTN_FALSE);
    /* Can't use serial interval since not block structured */
#endif // KMP_USE_DYNAMIC_LOCK
}
int __kmpc_test_nest_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 2472 of file kmp_csupport.c.
Referenced by FTN_TEST_NEST_LOCK().
{
#if KMP_USE_DYNAMIC_LOCK
    int rc;
# if USE_ITT_BUILD
    __kmp_itt_lock_acquiring((kmp_user_lock_p)user_lock);
# endif
    rc = KMP_D_LOCK_FUNC(user_lock, test)((kmp_dyna_lock_t *)user_lock, gtid);
# if USE_ITT_BUILD
    if (rc) {
        __kmp_itt_lock_acquired((kmp_user_lock_p)user_lock);
    } else {
        __kmp_itt_lock_cancelled((kmp_user_lock_p)user_lock);
    }
# endif
    return rc;
#else // KMP_USE_DYNAMIC_LOCK
    kmp_user_lock_p lck;
    int rc;
    if ((__kmp_user_lock_kind == lk_tas) && (sizeof(lck->
      tas.lk.poll)
      + sizeof(lck->tas.lk.depth_locked) <=
      OMP_NEST_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
     && (sizeof(lck->futex.lk.poll) + sizeof(lck->futex.lk.depth_locked)
     <= OMP_NEST_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_lookup_user_lock(user_lock, "omp_test_nest_lock");
    }
#if USE_ITT_BUILD
    __kmp_itt_lock_acquiring(lck);
#endif /* USE_ITT_BUILD */
    rc = TEST_NESTED_LOCK(lck, gtid);
#if USE_ITT_BUILD
    if (rc) {
        __kmp_itt_lock_acquired(lck);
    } else {
        __kmp_itt_lock_cancelled(lck);
    }
#endif /* USE_ITT_BUILD */
    return rc;
    /* Can't use serial interval since not block structured */
#endif // KMP_USE_DYNAMIC_LOCK
}
void __kmpc_unset_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 2260 of file kmp_csupport.c.
Referenced by FTN_UNSET_LOCK().
{
#if KMP_USE_DYNAMIC_LOCK
    int tag = KMP_EXTRACT_D_TAG(user_lock);
# if USE_ITT_BUILD
    __kmp_itt_lock_releasing((kmp_user_lock_p)user_lock);
# endif
# if KMP_USE_INLINED_TAS
    if (tag == locktag_tas && !__kmp_env_consistency_check) {
        KMP_RELEASE_TAS_LOCK(user_lock, gtid);
    } else
# elif KMP_USE_INLINED_FUTEX
    if (tag == locktag_futex && !__kmp_env_consistency_check) {
        KMP_RELEASE_FUTEX_LOCK(user_lock, gtid);
    } else
# endif
    {
        __kmp_direct_unset[tag]((kmp_dyna_lock_t *)user_lock, gtid);
    }
#else // KMP_USE_DYNAMIC_LOCK
    kmp_user_lock_p lck;
    /* Can't use serial interval since not block structured */
    /* release the lock */
    if ((__kmp_user_lock_kind == lk_tas)
      && (sizeof(lck->tas.lk.poll) <= OMP_LOCK_T_SIZE)) {
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
        // "fast" path implemented to fix customer performance issue
#if USE_ITT_BUILD
        __kmp_itt_lock_releasing((kmp_user_lock_p)user_lock);
#endif /* USE_ITT_BUILD */
        TCW_4(((kmp_user_lock_p)user_lock)->tas.lk.poll, 0);
        KMP_MB();
        return;
#else
        lck = (kmp_user_lock_p)user_lock;
#endif
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
      && (sizeof(lck->futex.lk.poll) <= OMP_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_lookup_user_lock(user_lock, "omp_unset_lock");
    }
#if USE_ITT_BUILD
    __kmp_itt_lock_releasing(lck);
#endif /* USE_ITT_BUILD */
    RELEASE_LOCK(lck, gtid);
#if OMPT_SUPPORT && OMPT_BLAME
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_release_lock)) {
        ompt_callbacks.ompt_callback(ompt_event_release_lock)((uint64_t) lck);
    }
#endif
#endif // KMP_USE_DYNAMIC_LOCK
}
void __kmpc_unset_nest_lock (ident_t * loc, kmp_int32 gtid, void ** user_lock)
Definition at line 2330 of file kmp_csupport.c.
Referenced by FTN_UNSET_NEST_LOCK().
{
#if KMP_USE_DYNAMIC_LOCK
# if USE_ITT_BUILD
    __kmp_itt_lock_releasing((kmp_user_lock_p)user_lock);
# endif
    KMP_D_LOCK_FUNC(user_lock, unset)((kmp_dyna_lock_t *)user_lock, gtid);
#else // KMP_USE_DYNAMIC_LOCK
    kmp_user_lock_p lck;
    /* Can't use serial interval since not block structured */
    if ((__kmp_user_lock_kind == lk_tas) && (sizeof(lck->
      tas.lk.poll)
      + sizeof(lck->tas.lk.depth_locked) <=
      OMP_NEST_LOCK_T_SIZE)) {
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
        // "fast" path implemented to fix customer performance issue
        kmp_tas_lock_t *tl = (kmp_tas_lock_t*)user_lock;
#if USE_ITT_BUILD
        __kmp_itt_lock_releasing((kmp_user_lock_p)user_lock);
#endif /* USE_ITT_BUILD */
        if (--(tl->lk.depth_locked) == 0) {
            TCW_4(tl->lk.poll, 0);
        }
        KMP_MB();
        return;
#else
        lck = (kmp_user_lock_p)user_lock;
#endif
    }
#if KMP_OS_LINUX && (KMP_ARCH_X86 || KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64)
    else if ((__kmp_user_lock_kind == lk_futex)
     && (sizeof(lck->futex.lk.poll) + sizeof(lck->futex.lk.depth_locked)
     <= OMP_NEST_LOCK_T_SIZE)) {
        lck = (kmp_user_lock_p)user_lock;
    }
#endif
    else {
        lck = __kmp_lookup_user_lock(user_lock, "omp_unset_nest_lock");
    }
#if USE_ITT_BUILD
    __kmp_itt_lock_releasing(lck);
#endif /* USE_ITT_BUILD */
    int release_status;
    release_status = RELEASE_NESTED_LOCK(lck, gtid);
#if OMPT_SUPPORT && OMPT_BLAME
    if (ompt_enabled) {
        if (release_status == KMP_LOCK_RELEASED) {
            if (ompt_callbacks.ompt_callback(ompt_event_release_nest_lock_last)) {
                ompt_callbacks.ompt_callback(ompt_event_release_nest_lock_last)(
                    (uint64_t) lck);
            }
        } else if (ompt_callbacks.ompt_callback(ompt_event_release_nest_lock_prev)) {
            ompt_callbacks.ompt_callback(ompt_event_release_nest_lock_prev)(
                (uint64_t) lck);
        }
    }
#endif
#endif // KMP_USE_DYNAMIC_LOCK
}
int kmpc_get_affinity_mask_proc (int proc, void ** mask)
Definition at line 1709 of file kmp_csupport.c.
{
#if defined(KMP_STUB) || !KMP_AFFINITY_SUPPORTED
    return -1;
#else
    if (! TCR_4(__kmp_init_middle)) {
        __kmp_middle_initialize();
    }
    return __kmp_aux_get_affinity_mask_proc(proc, mask);
#endif
}
int kmpc_set_affinity_mask_proc (int proc, void ** mask)
Definition at line 1683 of file kmp_csupport.c.
{
#if defined(KMP_STUB) || !KMP_AFFINITY_SUPPORTED
    return -1;
#else
    if (! TCR_4(__kmp_init_middle)) {
        __kmp_middle_initialize();
    }
    return __kmp_aux_set_affinity_mask_proc(proc, mask);
#endif
}
void kmpc_set_blocktime (int arg)
Definition at line 1656 of file kmp_csupport.c.
Referenced by __kmp_aux_env_initialize().
{
    int gtid, tid;
    kmp_info_t *thread;
    gtid = __kmp_entry_gtid();
    tid = __kmp_tid_from_gtid(gtid);
    thread = __kmp_thread_from_gtid(gtid);
    __kmp_aux_set_blocktime(arg, thread, tid);
}
void kmpc_set_defaults (char const * str)
Definition at line 1676 of file kmp_csupport.c.
{
    // __kmp_aux_set_defaults initializes the library if needed
    __kmp_aux_set_defaults(str, KMP_STRLEN(
      str));
}
void kmpc_set_library (int arg)
Definition at line 1669 of file kmp_csupport.c.
{
    // __kmp_user_set_library initializes the library if needed
    __kmp_user_set_library((enum library_type)arg);
}
void kmpc_set_stacksize (int arg)
Definition at line 1642 of file kmp_csupport.c.
{
    // __kmp_aux_set_stacksize initializes the library if needed
    __kmp_aux_set_stacksize(arg);
}
void kmpc_set_stacksize_s (size_t arg)
Definition at line 1649 of file kmp_csupport.c.
{
    // __kmp_aux_set_stacksize initializes the library if needed
    __kmp_aux_set_stacksize(arg);
}
int kmpc_unset_affinity_mask_proc (int proc, void ** mask)
Definition at line 1696 of file kmp_csupport.c.
{
#if defined(KMP_STUB) || !KMP_AFFINITY_SUPPORTED
    return -1;
#else
    if (! TCR_4(__kmp_init_middle)) {
        __kmp_middle_initialize();
    }
    return __kmp_aux_unset_affinity_mask_proc(proc, mask);
#endif
}
int ompc_get_ancestor_thread_num (int level)
Definition at line 1630 of file kmp_csupport.c.
{
    return __kmp_get_ancestor_thread_num(
      __kmp_entry_gtid(), level);
}
int ompc_get_team_size (int level)
Definition at line 1636 of file kmp_csupport.c.
{
    return __kmp_get_team_size(__kmp_entry_gtid(), level);
}
void ompc_set_dynamic (int flag)
Definition at line 1587 of file kmp_csupport.c.
Referenced by __kmp_aux_env_initialize().
{
    kmp_info_t *thread;
    /* For the thread-private implementation of the internal controls */
    thread = __kmp_entry_thread();
    __kmp_save_internal_controls(thread);
    set__dynamic(thread, flag ? TRUE : FALSE);
}
void ompc_set_max_active_levels (int max_active_levels)
Definition at line 1613 of file kmp_csupport.c.
{
    /* TO DO */
    /* we want per-task implementation of this internal control */
    /* For the per-thread internal controls implementation */
    __kmp_set_max_active_levels(__kmp_entry_gtid(),
      max_active_levels);
}
void ompc_set_nested (int flag)
Definition at line 1600 of file kmp_csupport.c.
Referenced by __kmp_aux_env_initialize().
{
    kmp_info_t *thread;
    /* For the thread-private internal controls implementation */
    thread = __kmp_entry_thread();
    __kmp_save_internal_controls(thread);
    set__nested(thread, flag ? TRUE : FALSE);
}
void ompc_set_num_threads (int arg)
Definition at line 1580 of file kmp_csupport.c.
Referenced by __kmp_aux_env_initialize().
{
// !!!!! TODO: check the per-task binding
    __kmp_set_num_threads(arg, __kmp_entry_gtid());
}
void ompc_set_schedule (omp_sched_t kind, int modifier)
Definition at line 1623 of file kmp_csupport.c.
{
// !!!!! TODO: check the per-task binding
    __kmp_set_schedule(__kmp_entry_gtid(), (
      kmp_sched_t) kind, modifier);
}