kmp_stats_timing.h File Reference
#include <stdint.h>
*
#include <string>
*
#include <limits>
*
#include `kmp_os.h`
*
Classes
class tsc_tick_count
class tsc_tick_count::tsc_interval_t
class timePair
Functions
tsc_tick_count::tsc_interval_t operator- (const tsc_tick_count t1, const tsc_tick_count t0)
std::string formatSI (double interval, int width, char unit)
std::string formatSeconds (double interval, int width)
std::string formatTicks (double interval, int width)
tsc_tick_count::tsc_interval_t computeLastInLastOutInterval (timePair *times, int nTimes)
Detailed Description
Access to real time clock and timers.
Definition in file kmp_stats_timing.h.
Function Documentation
tsc_tick_count::tsc_interval_t computeLastInLastOutInterval (timePair * times, int nTimes)
Definition at line 146 of file kmp_stats_timing.cpp.
{
    timePair lastTimes = times[0];
    tsc_tick_count * startp = lastTimes.get_startp();
    tsc_tick_count * endp = lastTimes.get_endp();
    for (int i=1; i<nTimes; i++)
    {
       (*startp) = startp->later(times[i].get_start());
       (*endp) = endp->later (times[i].get_end());
    }
    return lastTimes.duration();
}
std::string formatSeconds (double interval, int width) [inline]
Definition at line 86 of file kmp_stats_timing.h.
{
    return formatSI(interval, width, 'S');
}
std::string formatSI (double interval, int width, char unit)
Definition at line 91 of file kmp_stats_timing.cpp.
Referenced by statistic::format(), formatSeconds(), formatTicks(), kmp_stats_output_module::printCounters(), and kmp_stats_output_module::printHeaderInfo().
{
    std::stringstream os;
    if (useSI)
    {
        // Preserve accuracy for small numbers, since we only multiply and the positive powers
        // of ten are precisely representable.
        static struct { double scale; char prefix; } ranges[] = {
            {1.e12,'f'},
            {1.e9, 'p'},
            {1.e6, 'n'},
            {1.e3, 'u'},
            {1.0, 'm'},
            {1.e-3,' '},
            {1.e-6,'k'},
            {1.e-9,'M'},
            {1.e-12,'G'},
            {1.e-15,'T'},
            {1.e-18,'P'},
            {1.e-21,'E'},
            {1.e-24,'Z'},
            {1.e-27,'Y'}
        };
        
        if (interval == 0.0)
        {
            os << std::setw(width-3) << std::right << "0.00" << std::setw(3) << unit;
            return os.str();
        }
        bool negative = false;
        if (interval < 0.0)
        {
            negative = true;
            interval = -interval;
        }
        
        for (int i=0; i<(int)(sizeof(ranges)/sizeof(ranges[0])); i++)
        {
            if (interval*ranges[i].scale < 1.e0)
            {
                interval = interval * 1000.e0 * ranges[i].scale;
                os << std::fixed << std::setprecision(2) << std::setw(width-3) << std::right <<
                    (negative ? -interval : interval) << std::setw(2) << ranges[
      i].prefix << std::setw(1) << unit;
                return os.str();
            }
        }
    }
    os << std::setprecision(2) << std::fixed << std::right << std::setw(width-3) << interval << std::setw(3
      ) << unit;
    return os.str();
}
std::string formatTicks (double interval, int width) [inline]
Definition at line 91 of file kmp_stats_timing.h.
{
    return formatSI(interval, width, 'T');
}
tsc_tick_count::tsc_interval_t operator- (const tsc_tick_count t1, const tsc_tick_count t0) [inline]
Definition at line 72 of file kmp_stats_timing.h.
{
    return tsc_tick_count::tsc_interval_t(t1.
      my_count-t0.my_count);
}