kmp_debug.c File Reference
#include `kmp.h`
*
#include `kmp_debug.h`
*
#include `kmp_i18n.h`
*
#include `kmp_io.h`
*
Functions
void __kmp_debug_printf (char const *format,...)
void __kmp_dump_debug_buffer (void)
Function Documentation
void __kmp_debug_printf (char const * format, ...)
Definition at line 35 of file kmp_debug.c.
{
    va_list ap;
    va_start(ap, format);
    __kmp_vprintf(kmp_err, format, ap);
    va_end(ap);
}
void __kmp_dump_debug_buffer (void)
Definition at line 100 of file kmp_debug.c.
Referenced by __kmp_abort_process(), __kmp_internal_end_library(), and __kmp_internal_end_thread().
{
    if (__kmp_debug_buffer != NULL) {
        int i;
        int dc = __kmp_debug_count;
        char *db = & __kmp_debug_buffer[ (dc %
      __kmp_debug_buf_lines) * __kmp_debug_buf_chars ];
        char *db_end = & __kmp_debug_buffer[
      __kmp_debug_buf_lines * __kmp_debug_buf_chars ];
        char *db2;
        __kmp_acquire_bootstrap_lock(&
      __kmp_stdio_lock);
        __kmp_printf_no_lock("\nStart dump of debugging buffer (entry=%d):\n",
                 dc % __kmp_debug_buf_lines);
        for (i = 0; i < __kmp_debug_buf_lines; i++) {
            if (*db != '\0') {
                /* Fix up where no carriage return before string termination char */
                for (db2 = db + 1; db2 < db + __kmp_debug_buf_chars - 1; db2 ++) {
                    if (*db2 == '\0') {
                        if (*(db2-1) != '\n') { *db2 = '\n'; *(db2+1) = '\0'; }
                        break;
                    }
                }
                /* Handle case at end by shortening the printed message by one char if necessary */
                if (db2 == db + __kmp_debug_buf_chars - 1 &&
                     *db2 == '\0' && *(db2-1) != '\n') {
                    *(db2-1) = '\n';
                }
                __kmp_printf_no_lock("%4d: %.*s", i, __kmp_debug_buf_chars, db);
                *db = '\0'; /* only let it print once! */
            }
            db += __kmp_debug_buf_chars;
            if (db >= db_end)
                db = __kmp_debug_buffer;
        }
        __kmp_printf_no_lock("End dump of debugging buffer (entry=%d).\n\n",
                 (dc+i-1) % __kmp_debug_buf_lines);
        __kmp_release_bootstrap_lock(&
      __kmp_stdio_lock);
    }
}