kmp_atomic.h File Reference
#include `kmp_os.h`
*
#include `kmp_lock.h`
*
Macros
#define QUAD_LEGACY _Quad
#define CPLX128_LEG kmp_cmplx128
Typedefs
typedef float _Complex kmp_cmplx32
typedef double _Complex kmp_cmplx64
typedef long double _Complex kmp_cmplx80
typedef kmp_queuing_lock_t kmp_atomic_lock_t
Functions
static void __kmp_acquire_atomic_lock (kmp_atomic_lock_t *lck, kmp_int32 gtid)
static int __kmp_test_atomic_lock (kmp_atomic_lock_t *lck, kmp_int32 gtid)
static void __kmp_release_atomic_lock (kmp_atomic_lock_t *lck, kmp_int32 gtid)
static void __kmp_init_atomic_lock (kmp_atomic_lock_t *lck)
static void __kmp_destroy_atomic_lock (kmp_atomic_lock_t *lck)
void __kmpc_atomic_fixed1_add (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1_andb (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1_div (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1u_div (ident_t *id_ref, int gtid, unsigned char *lhs, unsigned char rhs)
void __kmpc_atomic_fixed1_mul (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1_orb (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1_shl (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1_shr (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1u_shr (ident_t *id_ref, int gtid, unsigned char *lhs, unsigned char rhs)
void __kmpc_atomic_fixed1_sub (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1_xor (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed2_add (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2_andb (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2_div (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2u_div (ident_t *id_ref, int gtid, unsigned short *lhs, unsigned short rhs)
void __kmpc_atomic_fixed2_mul (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2_orb (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2_shl (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2_shr (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2u_shr (ident_t *id_ref, int gtid, unsigned short *lhs, unsigned short rhs)
void __kmpc_atomic_fixed2_sub (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2_xor (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed4_add (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_sub (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_float4_add (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real32 rhs)
void __kmpc_atomic_float4_sub (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real32 rhs)
void __kmpc_atomic_fixed8_add (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_sub (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_float8_add (ident_t *id_ref, int gtid, kmp_real64 *lhs, kmp_real64 rhs)
void __kmpc_atomic_float8_sub (ident_t *id_ref, int gtid, kmp_real64 *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed4_andb (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_div (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4u_div (ident_t *id_ref, int gtid, kmp_uint32 *lhs, kmp_uint32 rhs)
void __kmpc_atomic_fixed4_mul (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_orb (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_shl (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_shr (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4u_shr (ident_t *id_ref, int gtid, kmp_uint32 *lhs, kmp_uint32 rhs)
void __kmpc_atomic_fixed4_xor (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed8_andb (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_div (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8u_div (ident_t *id_ref, int gtid, kmp_uint64 *lhs, kmp_uint64 rhs)
void __kmpc_atomic_fixed8_mul (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_orb (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_shl (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_shr (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8u_shr (ident_t *id_ref, int gtid, kmp_uint64 *lhs, kmp_uint64 rhs)
void __kmpc_atomic_fixed8_xor (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_float4_div (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real32 rhs)
void __kmpc_atomic_float4_mul (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real32 rhs)
void __kmpc_atomic_float8_div (ident_t *id_ref, int gtid, kmp_real64 *lhs, kmp_real64 rhs)
void __kmpc_atomic_float8_mul (ident_t *id_ref, int gtid, kmp_real64 *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed1_andl (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1_orl (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed2_andl (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2_orl (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed4_andl (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_orl (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed8_andl (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_orl (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed1_max (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed1_min (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed2_max (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed2_min (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed4_max (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_min (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed8_max (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_min (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_float4_max (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real32 rhs)
void __kmpc_atomic_float4_min (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real32 rhs)
void __kmpc_atomic_float8_max (ident_t *id_ref, int gtid, kmp_real64 *lhs, kmp_real64 rhs)
void __kmpc_atomic_float8_min (ident_t *id_ref, int gtid, kmp_real64 *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed1_neqv (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed2_neqv (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed4_neqv (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed8_neqv (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed1_eqv (ident_t *id_ref, int gtid, char *lhs, char rhs)
void __kmpc_atomic_fixed2_eqv (ident_t *id_ref, int gtid, short *lhs, short rhs)
void __kmpc_atomic_fixed4_eqv (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed8_eqv (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_int64 rhs)
void __kmpc_atomic_float10_add (ident_t *id_ref, int gtid, long double *lhs, long double rhs)
void __kmpc_atomic_float10_sub (ident_t *id_ref, int gtid, long double *lhs, long double rhs)
void __kmpc_atomic_float10_mul (ident_t *id_ref, int gtid, long double *lhs, long double rhs)
void __kmpc_atomic_float10_div (ident_t *id_ref, int gtid, long double *lhs, long double rhs)
void __kmpc_atomic_cmplx4_add (ident_t *id_ref, int gtid, kmp_cmplx32 *lhs, kmp_cmplx32 rhs)
void __kmpc_atomic_cmplx4_sub (ident_t *id_ref, int gtid, kmp_cmplx32 *lhs, kmp_cmplx32 rhs)
void __kmpc_atomic_cmplx4_mul (ident_t *id_ref, int gtid, kmp_cmplx32 *lhs, kmp_cmplx32 rhs)
void __kmpc_atomic_cmplx4_div (ident_t *id_ref, int gtid, kmp_cmplx32 *lhs, kmp_cmplx32 rhs)
void __kmpc_atomic_cmplx8_add (ident_t *id_ref, int gtid, kmp_cmplx64 *lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx8_sub (ident_t *id_ref, int gtid, kmp_cmplx64 *lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx8_mul (ident_t *id_ref, int gtid, kmp_cmplx64 *lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx8_div (ident_t *id_ref, int gtid, kmp_cmplx64 *lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx10_add (ident_t *id_ref, int gtid, kmp_cmplx80 *lhs, kmp_cmplx80 rhs)
void __kmpc_atomic_cmplx10_sub (ident_t *id_ref, int gtid, kmp_cmplx80 *lhs, kmp_cmplx80 rhs)
void __kmpc_atomic_cmplx10_mul (ident_t *id_ref, int gtid, kmp_cmplx80 *lhs, kmp_cmplx80 rhs)
void __kmpc_atomic_cmplx10_div (ident_t *id_ref, int gtid, kmp_cmplx80 *lhs, kmp_cmplx80 rhs)
void __kmpc_atomic_fixed1_mul_float8 (ident_t *id_ref, int gtid, char *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed1_div_float8 (ident_t *id_ref, int gtid, char *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed2_mul_float8 (ident_t *id_ref, int gtid, short *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed2_div_float8 (ident_t *id_ref, int gtid, short *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed4_mul_float8 (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed4_div_float8 (ident_t *id_ref, int gtid, kmp_int32 *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed8_mul_float8 (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed8_div_float8 (ident_t *id_ref, int gtid, kmp_int64 *lhs, kmp_real64 rhs)
void __kmpc_atomic_float4_add_float8 (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real64 rhs)
void __kmpc_atomic_float4_sub_float8 (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real64 rhs)
void __kmpc_atomic_float4_mul_float8 (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real64 rhs)
void __kmpc_atomic_float4_div_float8 (ident_t *id_ref, int gtid, kmp_real32 *lhs, kmp_real64 rhs)
void __kmpc_atomic_cmplx4_add_cmplx8 (ident_t *id_ref, int gtid, kmp_cmplx32 *lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx4_sub_cmplx8 (ident_t *id_ref, int gtid, kmp_cmplx32 *lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx4_mul_cmplx8 (ident_t *id_ref, int gtid, kmp_cmplx32 *lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx4_div_cmplx8 (ident_t *id_ref, int gtid, kmp_cmplx32 *lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_1 (ident_t *id_ref, int gtid, void *lhs, void *rhs, void(*f)(void *, void *, void *))
void __kmpc_atomic_2 (ident_t *id_ref, int gtid, void *lhs, void *rhs, void(*f)(void *, void *, void *))
void __kmpc_atomic_4 (ident_t *id_ref, int gtid, void *lhs, void *rhs, void(*f)(void *, void *, void *))
void __kmpc_atomic_8 (ident_t *id_ref, int gtid, void *lhs, void *rhs, void(*f)(void *, void *, void *))
void __kmpc_atomic_10 (ident_t *id_ref, int gtid, void *lhs, void *rhs, void(*f)(void *, void *, void *))
void __kmpc_atomic_16 (ident_t *id_ref, int gtid, void *lhs, void *rhs, void(*f)(void *, void *, void *))
void __kmpc_atomic_20 (ident_t *id_ref, int gtid, void *lhs, void *rhs, void(*f)(void *, void *, void *))
void __kmpc_atomic_32 (ident_t *id_ref, int gtid, void *lhs, void *rhs, void(*f)(void *, void *, void *))
Variables
int __kmp_atomic_mode
kmp_atomic_lock_t __kmp_atomic_lock
kmp_atomic_lock_t __kmp_atomic_lock_1i
kmp_atomic_lock_t __kmp_atomic_lock_2i
kmp_atomic_lock_t __kmp_atomic_lock_4i
kmp_atomic_lock_t __kmp_atomic_lock_4r
kmp_atomic_lock_t __kmp_atomic_lock_8i
kmp_atomic_lock_t __kmp_atomic_lock_8r
kmp_atomic_lock_t __kmp_atomic_lock_8c
kmp_atomic_lock_t __kmp_atomic_lock_10r
kmp_atomic_lock_t __kmp_atomic_lock_16r
kmp_atomic_lock_t __kmp_atomic_lock_16c
kmp_atomic_lock_t __kmp_atomic_lock_20c
kmp_atomic_lock_t __kmp_atomic_lock_32c
Macro Definition Documentation
#define CPLX128_LEG kmp_cmplx128
Definition at line 355 of file kmp_atomic.h.
#define QUAD_LEGACY _Quad
Definition at line 354 of file kmp_atomic.h.
Typedef Documentation
typedef kmp_queuing_lock_t kmp_atomic_lock_t
Definition at line 368 of file kmp_atomic.h.
typedef float _Complex kmp_cmplx32
Definition at line 204 of file kmp_atomic.h.
typedef double _Complex kmp_cmplx64
Definition at line 205 of file kmp_atomic.h.
typedef long double _Complex kmp_cmplx80
Definition at line 206 of file kmp_atomic.h.
Function Documentation
static void __kmp_acquire_atomic_lock (kmp_atomic_lock_t * lck, kmp_int32 gtid) [inline], [static]
Definition at line 371 of file kmp_atomic.h.
Referenced by __kmpc_atomic_10(), __kmpc_atomic_16(), __kmpc_atomic_2(), __kmpc_atomic_20(), __kmpc_atomic_32(), __kmpc_atomic_4(), __kmpc_atomic_8(), __kmpc_atomic_start(), ATOMIC_FIXED_ADD(), and KMP_API_NAME_GOMP_ATOMIC_START().
{
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_wait_atomic)) {
        ompt_callbacks.ompt_callback(ompt_event_wait_atomic)(
            (ompt_wait_id_t) lck);
    }
#endif
    __kmp_acquire_queuing_lock(lck, gtid);
#if OMPT_SUPPORT && OMPT_TRACE
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_acquired_atomic)) {
        ompt_callbacks.ompt_callback(ompt_event_acquired_atomic)(
            (ompt_wait_id_t) lck);
    }
#endif
}
static void __kmp_destroy_atomic_lock (kmp_atomic_lock_t * lck) [inline], [static]
Definition at line 418 of file kmp_atomic.h.
{
    __kmp_destroy_queuing_lock(lck);
}
static void __kmp_init_atomic_lock (kmp_atomic_lock_t * lck) [inline], [static]
Definition at line 412 of file kmp_atomic.h.
Referenced by __kmp_do_serial_initialize().
{
    __kmp_init_queuing_lock(lck);
}
static void __kmp_release_atomic_lock (kmp_atomic_lock_t * lck, kmp_int32 gtid) [inline], [static]
Definition at line 399 of file kmp_atomic.h.
Referenced by __kmpc_atomic_10(), __kmpc_atomic_16(), __kmpc_atomic_2(), __kmpc_atomic_20(), __kmpc_atomic_32(), __kmpc_atomic_4(), __kmpc_atomic_8(), __kmpc_atomic_end(), ATOMIC_FIXED_ADD(), and KMP_API_NAME_GOMP_ATOMIC_END().
{
    __kmp_release_queuing_lock(lck, gtid);
#if OMPT_SUPPORT && OMPT_BLAME
    if (ompt_enabled &&
        ompt_callbacks.ompt_callback(ompt_event_release_atomic)) {
        ompt_callbacks.ompt_callback(ompt_event_release_atomic)(
            (ompt_wait_id_t) lck);
  }
#endif
}
static int __kmp_test_atomic_lock (kmp_atomic_lock_t * lck, kmp_int32 gtid) [inline], [static]
Definition at line 393 of file kmp_atomic.h.
{
    return __kmp_test_queuing_lock(lck, gtid);
}
void __kmpc_atomic_1 (ident_t * id_ref, int gtid, void * lhs, void * rhs, void(*)(void *, void *, void *) f)
void __kmpc_atomic_10 (ident_t * id_ref, int gtid, void * lhs, void * rhs, void(*)(void *, void *, void *) f)
Definition at line 2786 of file kmp_atomic.c.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
#ifdef KMP_GOMP_COMPAT
    if (__kmp_atomic_mode == 2) {
        __kmp_acquire_atomic_lock(& __kmp_atomic_lock, gtid);
    }
    else
#endif /* KMP_GOMP_COMPAT */
    __kmp_acquire_atomic_lock(& __kmp_atomic_lock_10r, gtid
      );
    (*f)(lhs, lhs, rhs);
#ifdef KMP_GOMP_COMPAT
    if (__kmp_atomic_mode == 2) {
        __kmp_release_atomic_lock(& __kmp_atomic_lock, gtid);
    }
    else
#endif /* KMP_GOMP_COMPAT */
    __kmp_release_atomic_lock(& __kmp_atomic_lock_10r, gtid
      );
}
void __kmpc_atomic_16 (ident_t * id_ref, int gtid, void * lhs, void * rhs, void(*)(void *, void *, void *) f)
Definition at line 2810 of file kmp_atomic.c.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
#ifdef KMP_GOMP_COMPAT
    if (__kmp_atomic_mode == 2) {
        __kmp_acquire_atomic_lock(& __kmp_atomic_lock, gtid);
    }
    else
#endif /* KMP_GOMP_COMPAT */
    __kmp_acquire_atomic_lock(& __kmp_atomic_lock_16c, gtid
      );
    (*f)(lhs, lhs, rhs);
#ifdef KMP_GOMP_COMPAT
    if (__kmp_atomic_mode == 2) {
        __kmp_release_atomic_lock(& __kmp_atomic_lock, gtid);
    }
    else
#endif /* KMP_GOMP_COMPAT */
    __kmp_release_atomic_lock(& __kmp_atomic_lock_16c, gtid
      );
}
void __kmpc_atomic_2 (ident_t * id_ref, int gtid, void * lhs, void * rhs, void(*)(void *, void *, void *) f)
Definition at line 2614 of file kmp_atomic.c.
{
    if (
#if KMP_ARCH_X86 && defined(KMP_GOMP_COMPAT)
        FALSE /* must use lock */
#elif KMP_ARCH_X86 || KMP_ARCH_X86_64
        TRUE /* no alignment problems */
#else
        ! ((kmp_uintptr_t) lhs & 0x1) /* make sure address is 2-byte aligned */
#endif
        )
    {
        kmp_int16 old_value, new_value;
        old_value = *(kmp_int16 *) lhs;
        (*f)(&new_value, &old_value, rhs);
        /* TODO: Should this be acquire or release? */
        while (! KMP_COMPARE_AND_STORE_ACQ16 ((kmp_int16 *) lhs,
                                *(kmp_int16 *) &old_value, *(kmp_int16 *) &new_value))
        {
            KMP_CPU_PAUSE();
            old_value = *(kmp_int16 *) lhs;
            (*f)(&new_value, &old_value, rhs);
        }
        return;
    }
    else {
        //
        // All 2-byte data is of integer data type.
        //
#ifdef KMP_GOMP_COMPAT
        if (__kmp_atomic_mode == 2) {
            __kmp_acquire_atomic_lock(&
      __kmp_atomic_lock, gtid);
        }
        else
#endif /* KMP_GOMP_COMPAT */
        __kmp_acquire_atomic_lock(&
      __kmp_atomic_lock_2i, gtid);
        (*f)(lhs, lhs, rhs);
#ifdef KMP_GOMP_COMPAT
        if (__kmp_atomic_mode == 2) {
            __kmp_release_atomic_lock(&
      __kmp_atomic_lock, gtid);
        }
        else
#endif /* KMP_GOMP_COMPAT */
        __kmp_release_atomic_lock(&
      __kmp_atomic_lock_2i, gtid);
    }
}
void __kmpc_atomic_20 (ident_t * id_ref, int gtid, void * lhs, void * rhs, void(*)(void *, void *, void *) f)
Definition at line 2834 of file kmp_atomic.c.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
#ifdef KMP_GOMP_COMPAT
    if (__kmp_atomic_mode == 2) {
        __kmp_acquire_atomic_lock(& __kmp_atomic_lock, gtid);
    }
    else
#endif /* KMP_GOMP_COMPAT */
    __kmp_acquire_atomic_lock(& __kmp_atomic_lock_20c, gtid
      );
    (*f)(lhs, lhs, rhs);
#ifdef KMP_GOMP_COMPAT
    if (__kmp_atomic_mode == 2) {
        __kmp_release_atomic_lock(& __kmp_atomic_lock, gtid);
    }
    else
#endif /* KMP_GOMP_COMPAT */
    __kmp_release_atomic_lock(& __kmp_atomic_lock_20c, gtid
      );
}
void __kmpc_atomic_32 (ident_t * id_ref, int gtid, void * lhs, void * rhs, void(*)(void *, void *, void *) f)
Definition at line 2858 of file kmp_atomic.c.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
#ifdef KMP_GOMP_COMPAT
    if (__kmp_atomic_mode == 2) {
        __kmp_acquire_atomic_lock(& __kmp_atomic_lock, gtid);
    }
    else
#endif /* KMP_GOMP_COMPAT */
    __kmp_acquire_atomic_lock(& __kmp_atomic_lock_32c, gtid
      );
    (*f)(lhs, lhs, rhs);
#ifdef KMP_GOMP_COMPAT
    if (__kmp_atomic_mode == 2) {
        __kmp_release_atomic_lock(& __kmp_atomic_lock, gtid);
    }
    else
#endif /* KMP_GOMP_COMPAT */
    __kmp_release_atomic_lock(& __kmp_atomic_lock_32c, gtid
      );
}
void __kmpc_atomic_4 (ident_t * id_ref, int gtid, void * lhs, void * rhs, void(*)(void *, void *, void *) f)
Definition at line 2669 of file kmp_atomic.c.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    if (
        //
        // FIXME: On IA-32 architecture, gcc uses cmpxchg only for 4-byte ints.
        // Gomp compatibility is broken if this routine is called for floats.
        //
#if KMP_ARCH_X86 || KMP_ARCH_X86_64
        TRUE /* no alignment problems */
#else
        ! ((kmp_uintptr_t) lhs & 0x3) /* make sure address is 4-byte aligned */
#endif
        )
    {
        kmp_int32 old_value, new_value;
        old_value = *(kmp_int32 *) lhs;
        (*f)(&new_value, &old_value, rhs);
        /* TODO: Should this be acquire or release? */
        while (! KMP_COMPARE_AND_STORE_ACQ32 ((kmp_int32 *) lhs,
                                *(kmp_int32 *) &old_value, *(kmp_int32 *) &new_value))
        {
            KMP_CPU_PAUSE();
            old_value = *(kmp_int32 *) lhs;
            (*f)(&new_value, &old_value, rhs);
        }
        return;
    }
    else {
        //
        // Use __kmp_atomic_lock_4i for all 4-byte data,
        // even if it isn't of integer data type.
        //
#ifdef KMP_GOMP_COMPAT
        if (__kmp_atomic_mode == 2) {
            __kmp_acquire_atomic_lock(&
      __kmp_atomic_lock, gtid);
        }
        else
#endif /* KMP_GOMP_COMPAT */
        __kmp_acquire_atomic_lock(&
      __kmp_atomic_lock_4i, gtid);
        (*f)(lhs, lhs, rhs);
#ifdef KMP_GOMP_COMPAT
        if (__kmp_atomic_mode == 2) {
            __kmp_release_atomic_lock(&
      __kmp_atomic_lock, gtid);
        }
        else
#endif /* KMP_GOMP_COMPAT */
        __kmp_release_atomic_lock(&
      __kmp_atomic_lock_4i, gtid);
    }
}
void __kmpc_atomic_8 (ident_t * id_ref, int gtid, void * lhs, void * rhs, void(*)(void *, void *, void *) f)
Definition at line 2729 of file kmp_atomic.c.
{
    KMP_DEBUG_ASSERT(__kmp_init_serial);
    if (
#if KMP_ARCH_X86 && defined(KMP_GOMP_COMPAT)
        FALSE /* must use lock */
#elif KMP_ARCH_X86 || KMP_ARCH_X86_64
        TRUE /* no alignment problems */
#else
        ! ((kmp_uintptr_t) lhs & 0x7) /* make sure address is 8-byte aligned */
#endif
        )
    {
        kmp_int64 old_value, new_value;
        old_value = *(kmp_int64 *) lhs;
        (*f)(&new_value, &old_value, rhs);
        /* TODO: Should this be acquire or release? */
        while (! KMP_COMPARE_AND_STORE_ACQ64 ((kmp_int64 *) lhs,
                                               *(kmp_int64 *) &old_value,
                                               *(kmp_int64 *) &new_value))
        {
            KMP_CPU_PAUSE();
            old_value = *(kmp_int64 *) lhs;
            (*f)(&new_value, &old_value, rhs);
        }
        return;
    } else {
        //
        // Use __kmp_atomic_lock_8i for all 8-byte data,
        // even if it isn't of integer data type.
        //
#ifdef KMP_GOMP_COMPAT
        if (__kmp_atomic_mode == 2) {
            __kmp_acquire_atomic_lock(&
      __kmp_atomic_lock, gtid);
        }
        else
#endif /* KMP_GOMP_COMPAT */
        __kmp_acquire_atomic_lock(&
      __kmp_atomic_lock_8i, gtid);
        (*f)(lhs, lhs, rhs);
#ifdef KMP_GOMP_COMPAT
        if (__kmp_atomic_mode == 2) {
            __kmp_release_atomic_lock(&
      __kmp_atomic_lock, gtid);
        }
        else
#endif /* KMP_GOMP_COMPAT */
        __kmp_release_atomic_lock(&
      __kmp_atomic_lock_8i, gtid);
    }
}
void __kmpc_atomic_cmplx10_add (ident_t * id_ref, int gtid, kmp_cmplx80 * lhs, kmp_cmplx80 rhs)
void __kmpc_atomic_cmplx10_div (ident_t * id_ref, int gtid, kmp_cmplx80 * lhs, kmp_cmplx80 rhs)
void __kmpc_atomic_cmplx10_mul (ident_t * id_ref, int gtid, kmp_cmplx80 * lhs, kmp_cmplx80 rhs)
void __kmpc_atomic_cmplx10_sub (ident_t * id_ref, int gtid, kmp_cmplx80 * lhs, kmp_cmplx80 rhs)
void __kmpc_atomic_cmplx4_add (ident_t * id_ref, int gtid, kmp_cmplx32 * lhs, kmp_cmplx32 rhs)
void __kmpc_atomic_cmplx4_add_cmplx8 (ident_t * id_ref, int gtid, kmp_cmplx32 * lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx4_div (ident_t * id_ref, int gtid, kmp_cmplx32 * lhs, kmp_cmplx32 rhs)
void __kmpc_atomic_cmplx4_div_cmplx8 (ident_t * id_ref, int gtid, kmp_cmplx32 * lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx4_mul (ident_t * id_ref, int gtid, kmp_cmplx32 * lhs, kmp_cmplx32 rhs)
void __kmpc_atomic_cmplx4_mul_cmplx8 (ident_t * id_ref, int gtid, kmp_cmplx32 * lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx4_sub (ident_t * id_ref, int gtid, kmp_cmplx32 * lhs, kmp_cmplx32 rhs)
void __kmpc_atomic_cmplx4_sub_cmplx8 (ident_t * id_ref, int gtid, kmp_cmplx32 * lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx8_add (ident_t * id_ref, int gtid, kmp_cmplx64 * lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx8_div (ident_t * id_ref, int gtid, kmp_cmplx64 * lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx8_mul (ident_t * id_ref, int gtid, kmp_cmplx64 * lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_cmplx8_sub (ident_t * id_ref, int gtid, kmp_cmplx64 * lhs, kmp_cmplx64 rhs)
void __kmpc_atomic_fixed1_add (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_andb (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_andl (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_div (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_div_float8 (ident_t * id_ref, int gtid, char * lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed1_eqv (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_max (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_min (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_mul (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_mul_float8 (ident_t * id_ref, int gtid, char * lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed1_neqv (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_orb (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_orl (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_shl (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_shr (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_sub (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1_xor (ident_t * id_ref, int gtid, char * lhs, char rhs)
void __kmpc_atomic_fixed1u_div (ident_t * id_ref, int gtid, unsigned char * lhs, unsigned char rhs)
void __kmpc_atomic_fixed1u_shr (ident_t * id_ref, int gtid, unsigned char * lhs, unsigned char rhs)
void __kmpc_atomic_fixed2_add (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_andb (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_andl (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_div (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_div_float8 (ident_t * id_ref, int gtid, short * lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed2_eqv (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_max (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_min (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_mul (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_mul_float8 (ident_t * id_ref, int gtid, short * lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed2_neqv (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_orb (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_orl (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_shl (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_shr (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_sub (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2_xor (ident_t * id_ref, int gtid, short * lhs, short rhs)
void __kmpc_atomic_fixed2u_div (ident_t * id_ref, int gtid, unsigned short * lhs, unsigned short rhs)
void __kmpc_atomic_fixed2u_shr (ident_t * id_ref, int gtid, unsigned short * lhs, unsigned short rhs)
void __kmpc_atomic_fixed4_add (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_andb (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_andl (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_div (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_div_float8 (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed4_eqv (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_max (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_min (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_mul (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_mul_float8 (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed4_neqv (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_orb (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_orl (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_shl (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_shr (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_sub (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4_xor (ident_t * id_ref, int gtid, kmp_int32 * lhs, kmp_int32 rhs)
void __kmpc_atomic_fixed4u_div (ident_t * id_ref, int gtid, kmp_uint32 * lhs, kmp_uint32 rhs)
void __kmpc_atomic_fixed4u_shr (ident_t * id_ref, int gtid, kmp_uint32 * lhs, kmp_uint32 rhs)
void __kmpc_atomic_fixed8_add (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_andb (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_andl (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_div (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_div_float8 (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed8_eqv (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_max (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_min (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_mul (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_mul_float8 (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_real64 rhs)
void __kmpc_atomic_fixed8_neqv (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_orb (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_orl (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_shl (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_shr (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_sub (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8_xor (ident_t * id_ref, int gtid, kmp_int64 * lhs, kmp_int64 rhs)
void __kmpc_atomic_fixed8u_div (ident_t * id_ref, int gtid, kmp_uint64 * lhs, kmp_uint64 rhs)
void __kmpc_atomic_fixed8u_shr (ident_t * id_ref, int gtid, kmp_uint64 * lhs, kmp_uint64 rhs)
void __kmpc_atomic_float10_add (ident_t * id_ref, int gtid, long double * lhs, long double rhs)
void __kmpc_atomic_float10_div (ident_t * id_ref, int gtid, long double * lhs, long double rhs)
void __kmpc_atomic_float10_mul (ident_t * id_ref, int gtid, long double * lhs, long double rhs)
void __kmpc_atomic_float10_sub (ident_t * id_ref, int gtid, long double * lhs, long double rhs)
void __kmpc_atomic_float4_add (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real32 rhs)
void __kmpc_atomic_float4_add_float8 (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real64 rhs)
void __kmpc_atomic_float4_div (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real32 rhs)
void __kmpc_atomic_float4_div_float8 (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real64 rhs)
void __kmpc_atomic_float4_max (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real32 rhs)
void __kmpc_atomic_float4_min (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real32 rhs)
void __kmpc_atomic_float4_mul (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real32 rhs)
void __kmpc_atomic_float4_mul_float8 (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real64 rhs)
void __kmpc_atomic_float4_sub (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real32 rhs)
void __kmpc_atomic_float4_sub_float8 (ident_t * id_ref, int gtid, kmp_real32 * lhs, kmp_real64 rhs)
void __kmpc_atomic_float8_add (ident_t * id_ref, int gtid, kmp_real64 * lhs, kmp_real64 rhs)
void __kmpc_atomic_float8_div (ident_t * id_ref, int gtid, kmp_real64 * lhs, kmp_real64 rhs)
void __kmpc_atomic_float8_max (ident_t * id_ref, int gtid, kmp_real64 * lhs, kmp_real64 rhs)
void __kmpc_atomic_float8_min (ident_t * id_ref, int gtid, kmp_real64 * lhs, kmp_real64 rhs)
void __kmpc_atomic_float8_mul (ident_t * id_ref, int gtid, kmp_real64 * lhs, kmp_real64 rhs)
void __kmpc_atomic_float8_sub (ident_t * id_ref, int gtid, kmp_real64 * lhs, kmp_real64 rhs)
Variable Documentation
kmp_atomic_lock_t __kmp_atomic_lock
Definition at line 551 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize(), KMP_API_NAME_GOMP_ATOMIC_END(), and KMP_API_NAME_GOMP_ATOMIC_START().
kmp_atomic_lock_t __kmp_atomic_lock_10r
Definition at line 559 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_16c
Definition at line 561 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_16r
Definition at line 560 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_1i
Definition at line 552 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_20c
Definition at line 562 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_2i
Definition at line 553 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_32c
Definition at line 563 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_4i
Definition at line 554 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_4r
Definition at line 555 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_8c
Definition at line 558 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_8i
Definition at line 556 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().
kmp_atomic_lock_t __kmp_atomic_lock_8r
Definition at line 557 of file kmp_atomic.c.
Referenced by __kmp_do_serial_initialize().