kmp_gsupport.c File Reference
#include `kmp.h`
*
#include `kmp_atomic.h`
*
#include `kmp_ftn_os.h`
*
Macros
#define MKLOC(loc, routine) static ident_t (loc) = {0, KMP_IDENT_KMPC, 0, 0, `;unknown;unknown;0;0;;` };
#define KMP_DISPATCH_INIT __kmp_aux_dispatch_init_8
#define KMP_DISPATCH_FINI_CHUNK __kmp_aux_dispatch_fini_chunk_8
#define KMP_DISPATCH_NEXT __kmpc_dispatch_next_8
#define KMP_DISPATCH_INIT_ULL __kmp_aux_dispatch_init_8u
#define KMP_DISPATCH_FINI_CHUNK_ULL __kmp_aux_dispatch_fini_chunk_8u
#define KMP_DISPATCH_NEXT_ULL __kmpc_dispatch_next_8u
#define LOOP_START(func, schedule)
#define LOOP_RUNTIME_START(func, schedule)
#define LOOP_NEXT(func, fini_code)
#define LOOP_START_ULL(func, schedule)
#define LOOP_RUNTIME_START_ULL(func, schedule)
#define LOOP_NEXT_ULL(func, fini_code)
#define PARALLEL_LOOP_START(func, schedule, ompt_pre, ompt_post)
#define OMPT_LOOP_PRE()
#define OMPT_LOOP_POST()
#define PARALLEL_LOOP(func, schedule)
Functions
void xexpand() KMP_API_NAME_GOMP_BARRIER (void)
void xexpand() KMP_API_NAME_GOMP_CRITICAL_START (void)
void xexpand() KMP_API_NAME_GOMP_CRITICAL_END (void)
void xexpand() KMP_API_NAME_GOMP_CRITICAL_NAME_START (void **pptr)
void xexpand() KMP_API_NAME_GOMP_CRITICAL_NAME_END (void **pptr)
void xexpand() KMP_API_NAME_GOMP_ATOMIC_START (void)
void xexpand() KMP_API_NAME_GOMP_ATOMIC_END (void)
int xexpand() KMP_API_NAME_GOMP_SINGLE_START (void)
void *xexpand() KMP_API_NAME_GOMP_SINGLE_COPY_START (void)
void xexpand() KMP_API_NAME_GOMP_SINGLE_COPY_END (void *data)
void xexpand() KMP_API_NAME_GOMP_ORDERED_START (void)
void xexpand() KMP_API_NAME_GOMP_ORDERED_END (void)
static void __kmp_GOMP_microtask_wrapper (int *gtid, int *npr, void(*task)(void *), void *data)
static void __kmp_GOMP_parallel_microtask_wrapper (int *gtid, int *npr, void(*task)(void *), void *data, unsigned num_threads, ident_t *loc, enum sched_type schedule, long start, long end, long incr, long chunk_size)
static void __kmp_GOMP_fork_call (ident_t *loc, int gtid, void(*unwrapped_task)(void *), microtask_t wrapper, int argc,...)
static void __kmp_GOMP_serialized_parallel (ident_t *loc, kmp_int32 gtid, void(*task)(void *))
void xexpand() KMP_API_NAME_GOMP_PARALLEL_START (void(*task)(void *), void *data, unsigned num_threads)
void xexpand() KMP_API_NAME_GOMP_PARALLEL_END (void)
LOOP_NEXT (xexpand(KMP_API_NAME_GOMP_LOOP_ORDERED_STATIC_NEXT),{KMP_DISPATCH_FINI_CHUNK(&loc, gtid);})
LOOP_NEXT (xexpand(KMP_API_NAME_GOMP_LOOP_ORDERED_GUIDED_NEXT),{KMP_DISPATCH_FINI_CHUNK(&loc, gtid);})
void xexpand() KMP_API_NAME_GOMP_LOOP_END (void)
void xexpand() KMP_API_NAME_GOMP_LOOP_END_NOWAIT (void)
LOOP_NEXT_ULL (xexpand(KMP_API_NAME_GOMP_LOOP_ULL_ORDERED_STATIC_NEXT),{KMP_DISPATCH_FINI_CHUNK_ULL(&loc, gtid);})
LOOP_NEXT_ULL (xexpand(KMP_API_NAME_GOMP_LOOP_ULL_ORDERED_GUIDED_NEXT),{KMP_DISPATCH_FINI_CHUNK_ULL(&loc, gtid);})
PARALLEL_LOOP_START (xexpand(KMP_API_NAME_GOMP_PARALLEL_LOOP_STATIC_START), kmp_sch_static, PARALLEL_LOOP_START((KMP_API_NAME_GOMP_PARALLEL_LOOP_DYNAMIC_START) OMPT_LOOP_PRE, OMPT_LOOP_POST)
void xexpand() KMP_API_NAME_GOMP_TASKWAIT (void)
unsigned xexpand() KMP_API_NAME_GOMP_SECTIONS_START (unsigned count)
unsigned xexpand() KMP_API_NAME_GOMP_SECTIONS_NEXT (void)
void xexpand() KMP_API_NAME_GOMP_PARALLEL_SECTIONS_START (void(*task)(void *), void *data, unsigned num_threads, unsigned count)
void xexpand() KMP_API_NAME_GOMP_SECTIONS_END (void)
void xexpand() KMP_API_NAME_GOMP_SECTIONS_END_NOWAIT (void)
void xexpand() KMP_API_NAME_GOMP_TASKYIELD (void)
void xexpand() KMP_API_NAME_GOMP_PARALLEL (void(*task)(void *), void *data, unsigned num_threads, unsigned int flags)
void xexpand() KMP_API_NAME_GOMP_PARALLEL_SECTIONS (void(*task)(void *), void *data, unsigned num_threads, unsigned count, unsigned flags)
void xexpand() KMP_API_NAME_GOMP_TASKGROUP_START (void)
void xexpand() KMP_API_NAME_GOMP_TASKGROUP_END (void)
static kmp_int32 __kmp_gomp_to_omp_cancellation_kind (int gomp_kind)
bool xexpand() KMP_API_NAME_GOMP_CANCELLATION_POINT (int which)
bool xexpand() KMP_API_NAME_GOMP_BARRIER_CANCEL (void)
bool xexpand() KMP_API_NAME_GOMP_CANCEL (int which, bool do_cancel)
bool xexpand() KMP_API_NAME_GOMP_SECTIONS_END_CANCEL (void)
bool xexpand() KMP_API_NAME_GOMP_LOOP_END_CANCEL (void)
void xexpand() KMP_API_NAME_GOMP_TARGET (int device, void(*fn)(void *), const void *openmp_target, size_t mapnum, void **hostaddrs, size_t *sizes, unsigned char *kinds)
void xexpand() KMP_API_NAME_GOMP_TARGET_DATA (int device, const void *openmp_target, size_t mapnum, void **hostaddrs, size_t *sizes, unsigned char *kinds)
void xexpand() KMP_API_NAME_GOMP_TARGET_END_DATA (void)
void xexpand() KMP_API_NAME_GOMP_TARGET_UPDATE (int device, const void *openmp_target, size_t mapnum, void **hostaddrs, size_t *sizes, unsigned char *kinds)
void xexpand() KMP_API_NAME_GOMP_TEAMS (unsigned int num_teams, unsigned int thread_limit)
Variables
kmp_critical_name * __kmp_unnamed_critical_addr
Macro Definition Documentation
#define KMP_DISPATCH_FINI_CHUNK __kmp_aux_dispatch_fini_chunk_8
Definition at line 234 of file kmp_gsupport.c.
Referenced by LOOP_NEXT().
#define KMP_DISPATCH_FINI_CHUNK_ULL __kmp_aux_dispatch_fini_chunk_8u
Definition at line 239 of file kmp_gsupport.c.
Referenced by LOOP_NEXT_ULL().
#define KMP_DISPATCH_INIT __kmp_aux_dispatch_init_8
Definition at line 233 of file kmp_gsupport.c.
Referenced by __kmp_GOMP_parallel_microtask_wrapper(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS_START(), and KMP_API_NAME_GOMP_SECTIONS_START().
#define KMP_DISPATCH_INIT_ULL __kmp_aux_dispatch_init_8u
Definition at line 238 of file kmp_gsupport.c.
#define KMP_DISPATCH_NEXT __kmpc_dispatch_next_8
Definition at line 235 of file kmp_gsupport.c.
Referenced by KMP_API_NAME_GOMP_SECTIONS_NEXT(), and KMP_API_NAME_GOMP_SECTIONS_START().
#define KMP_DISPATCH_NEXT_ULL __kmpc_dispatch_next_8u
Definition at line 240 of file kmp_gsupport.c.
#define LOOP_NEXT(func, fini_code)
Value:
int func(long *p_lb, long *p_ub) \
    { \
        int status; \
        long stride; \
        int gtid = __kmp_get_gtid();
      \
        MKLOC(loc, #func);
      \
        KA_TRACE(20, (#func ": T#%d\n", gtid)); \
                                                                             \
        fini_code \
        status = KMP_DISPATCH_NEXT(&loc, gtid, NULL, (
      kmp_int *)p_lb, \
          (kmp_int *)p_ub, (kmp_int *)&stride); \
        if (status) { \
            *p_ub += (stride > 0) ? 1 : -1; \
        } \
                                                                             \
        KA_TRACE(20, (#func " exit: T#%d, *p_lb 0x%lx, *p_ub 0x%lx, stride 0x%lx, " \
          "returning %d\n", gtid, *p_lb, *p_ub, stride, status)); \
        return status; \
    }
Definition at line 666 of file kmp_gsupport.c.
#define LOOP_NEXT_ULL(func, fini_code)
Value:
int func(unsigned long long *p_lb, unsigned long long *p_ub) \
    { \
        int status; \
        long long stride; \
        int gtid = __kmp_get_gtid();
      \
        MKLOC(loc, #func);
      \
        KA_TRACE(20, (#func ": T#%d\n", gtid)); \
                                                                             \
        fini_code \
        status = KMP_DISPATCH_NEXT_ULL(&loc, gtid, NULL, (kmp_uint64 *)
      p_lb, \
          (kmp_uint64 *)p_ub, (kmp_int64 *)&stride); \
        if (status) { \
            *p_ub += (stride > 0) ? 1 : -1; \
        } \
                                                                             \
        KA_TRACE(20, (#func " exit: T#%d, *p_lb 0x%llx, *p_ub 0x%llx, stride 0x%llx, " \
          "returning %d\n", gtid, *p_lb, *p_ub, stride, status)); \
        return status; \
    }
Definition at line 806 of file kmp_gsupport.c.
#define LOOP_RUNTIME_START(func, schedule)
Value:
int func (long lb, long ub, long str, long *p_lb, long *p_ub) \
    { \
        int status; \
        long stride; \
        long chunk_sz = 0; \
        int gtid = __kmp_entry_gtid();
      \
        MKLOC(loc, #func);
      \
        KA_TRACE(20, (#func ": T#%d, lb 0x%lx, ub 0x%lx, str 0x%lx, chunk_sz %d\n", \
          gtid, lb, ub, str, chunk_sz)); \
                                                                             \
        if ((str > 0) ? (lb < ub) : (lb > ub)) {
      \
            KMP_DISPATCH_INIT(&loc, gtid, (schedule), lb, \
              (str > 0) ? (ub - 1) : (ub + 1), str, chunk_sz, TRUE);
      \
            status = KMP_DISPATCH_NEXT(&loc, gtid, NULL, (
      kmp_int *)p_lb, \
              (kmp_int *)p_ub, (kmp_int *)&stride); \
            if (status) { \
                KMP_DEBUG_ASSERT(stride == str);
           \
                *p_ub += (str > 0) ? 1 : -1; \
            } \
        } \
        else { \
            status = 0; \
        } \
                                                                             \
        KA_TRACE(20, (#func " exit: T#%d, *p_lb 0x%lx, *p_ub 0x%lx, returning %d\n", \
          gtid, *p_lb, *p_ub, status)); \
        return status; \
    }
Definition at line 635 of file kmp_gsupport.c.
#define LOOP_RUNTIME_START_ULL(func, schedule)
Definition at line 771 of file kmp_gsupport.c.
#define LOOP_START(func, schedule)
Value:
int func (long lb, long ub, long str, long chunk_sz, long *p_lb, \
      long *p_ub) \
    { \
        int status; \
        long stride; \
        int gtid = __kmp_entry_gtid();
      \
        MKLOC(loc, #func);
      \
        KA_TRACE(20, (#func ": T#%d, lb 0x%lx, ub 0x%lx, str 0x%lx, chunk_sz 0x%lx\n", \
          gtid, lb, ub, str, chunk_sz)); \
                                                                             \
        if ((str > 0) ? (lb < ub) : (lb > ub)) {
      \
            KMP_DISPATCH_INIT(&loc, gtid, (schedule), lb, \
              (str > 0) ? (ub - 1) : (ub + 1), str, chunk_sz, \
              (schedule) != kmp_sch_static);
      \
            status = KMP_DISPATCH_NEXT(&loc, gtid, NULL, (
      kmp_int *)p_lb, \
              (kmp_int *)p_ub, (kmp_int *)&stride); \
            if (status) { \
                KMP_DEBUG_ASSERT(stride == str);
           \
                *p_ub += (str > 0) ? 1 : -1; \
            } \
        } \
        else { \
            status = 0; \
        } \
                                                                             \
        KA_TRACE(20, (#func " exit: T#%d, *p_lb 0x%lx, *p_ub 0x%lx, returning %d\n", \
          gtid, *p_lb, *p_ub, status)); \
        return status; \
    }
Definition at line 603 of file kmp_gsupport.c.
#define LOOP_START_ULL(func, schedule)
Definition at line 736 of file kmp_gsupport.c.
#define MKLOC(loc, routine) static ident_t (loc) = {0, KMP_IDENT_KMPC, 0, 0, `;unknown;unknown;0;0;;` };
Definition at line 27 of file kmp_gsupport.c.
Referenced by KMP_API_NAME_GOMP_BARRIER(), KMP_API_NAME_GOMP_BARRIER_CANCEL(), KMP_API_NAME_GOMP_CANCEL(), KMP_API_NAME_GOMP_CANCELLATION_POINT(), KMP_API_NAME_GOMP_CRITICAL_END(), KMP_API_NAME_GOMP_CRITICAL_NAME_END(), KMP_API_NAME_GOMP_CRITICAL_NAME_START(), KMP_API_NAME_GOMP_CRITICAL_START(), KMP_API_NAME_GOMP_LOOP_END_CANCEL(), KMP_API_NAME_GOMP_ORDERED_END(), KMP_API_NAME_GOMP_ORDERED_START(), KMP_API_NAME_GOMP_PARALLEL(), KMP_API_NAME_GOMP_PARALLEL_END(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS_START(), KMP_API_NAME_GOMP_PARALLEL_START(), KMP_API_NAME_GOMP_SECTIONS_END_CANCEL(), KMP_API_NAME_GOMP_SECTIONS_NEXT(), KMP_API_NAME_GOMP_SECTIONS_START(), KMP_API_NAME_GOMP_SINGLE_COPY_START(), KMP_API_NAME_GOMP_SINGLE_START(), KMP_API_NAME_GOMP_TASKGROUP_END(), KMP_API_NAME_GOMP_TASKGROUP_START(), KMP_API_NAME_GOMP_TASKWAIT(), and PARALLEL_LOOP_START().
#define OMPT_LOOP_POST()
Definition at line 911 of file kmp_gsupport.c.
#define OMPT_LOOP_PRE()
Definition at line 909 of file kmp_gsupport.c.
#define PARALLEL_LOOP(func, schedule)
Definition at line 1216 of file kmp_gsupport.c.
#define PARALLEL_LOOP_START(func, schedule, ompt_pre, ompt_post)
Definition at line 857 of file kmp_gsupport.c.
Function Documentation
static void __kmp_GOMP_fork_call (ident_t * loc, int gtid, void(*)(void *) unwrapped_task, microtask_t wrapper, int argc, ...) [static]
Definition at line 339 of file kmp_gsupport.c.
Referenced by KMP_API_NAME_GOMP_PARALLEL(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS_START(), and KMP_API_NAME_GOMP_PARALLEL_START().
{
    int rc;
    kmp_info_t *thr = __kmp_threads[gtid];
    kmp_team_t *team = thr->th.th_team;
    int tid = __kmp_tid_from_gtid(gtid);
    va_list ap;
    va_start(ap, argc);
    rc = __kmp_fork_call(loc, gtid, fork_context_gnu, argc,
#if OMPT_SUPPORT
      VOLATILE_CAST(void *) unwrapped_task,
#endif
      wrapper, __kmp_invoke_task_func,
#if (KMP_ARCH_X86_64 || KMP_ARCH_ARM || KMP_ARCH_AARCH64) &&
      KMP_OS_LINUX
      &ap
#else
      ap
#endif
      );
    va_end(ap);
    if (rc) {
        __kmp_run_before_invoked_task(gtid, tid, thr, team);
    }
#if OMPT_SUPPORT
    if (ompt_enabled) {
#if OMPT_TRACE
        ompt_team_info_t *team_info = __ompt_get_teaminfo(0, NULL);
        ompt_task_info_t *task_info = __ompt_get_taskinfo(0);
        // implicit task callback
        if (ompt_callbacks.ompt_callback(ompt_event_implicit_task_begin)) {
            ompt_callbacks.ompt_callback(ompt_event_implicit_task_begin)(
                team_info->parallel_id, task_info->task_id);
        }
#endif
        thr->th.ompt_thread_info.state = ompt_state_work_parallel;
    }
#endif
}
static void __kmp_GOMP_microtask_wrapper (int * gtid, int * npr, void(*)(void *) task, void * data) [static]
Definition at line 251 of file kmp_gsupport.c.
Referenced by KMP_API_NAME_GOMP_PARALLEL(), and KMP_API_NAME_GOMP_PARALLEL_START().
{
#if OMPT_SUPPORT
    kmp_info_t *thr;
    ompt_frame_t *ompt_frame;
    ompt_state_t enclosing_state;
    if (ompt_enabled) {
        // get pointer to thread data structure
        thr = __kmp_threads[*gtid];
        // save enclosing task state; set current state for task
        enclosing_state = thr->th.ompt_thread_info.state;
        thr->th.ompt_thread_info.state = ompt_state_work_parallel;
        // set task frame
        ompt_frame = __ompt_get_task_frame_internal(0);
        ompt_frame->exit_runtime_frame = __builtin_frame_address(0);
    }
#endif
    task(data);
#if OMPT_SUPPORT
    if (ompt_enabled) {
        // clear task frame
        ompt_frame->exit_runtime_frame = NULL;
        // restore enclosing state
        thr->th.ompt_thread_info.state = enclosing_state;
    }
#endif
}
static void __kmp_GOMP_parallel_microtask_wrapper (int * gtid, int * npr, void(*)(void *) task, void * data, unsigned num_threads, ident_t * loc, enum sched_type schedule, long start, long end, long incr, long chunk_size) [static]
Definition at line 291 of file kmp_gsupport.c.
Referenced by KMP_API_NAME_GOMP_PARALLEL_SECTIONS(), and KMP_API_NAME_GOMP_PARALLEL_SECTIONS_START().
{
    //
    // Intialize the loop worksharing construct.
    //
    KMP_DISPATCH_INIT(loc, *gtid, schedule, start, end, incr, chunk_size,
      schedule != kmp_sch_static);
#if OMPT_SUPPORT
    kmp_info_t *thr;
    ompt_frame_t *ompt_frame;
    ompt_state_t enclosing_state;
    if (ompt_enabled) {
        thr = __kmp_threads[*gtid];
        // save enclosing task state; set current state for task
        enclosing_state = thr->th.ompt_thread_info.state;
        thr->th.ompt_thread_info.state = ompt_state_work_parallel;
        // set task frame
        ompt_frame = __ompt_get_task_frame_internal(0);
        ompt_frame->exit_runtime_frame = __builtin_frame_address(0);
    }
#endif
    //
    // Now invoke the microtask.
    //
    task(data);
#if OMPT_SUPPORT
    if (ompt_enabled) {
        // clear task frame
        ompt_frame->exit_runtime_frame = NULL;
        // reset enclosing state
        thr->th.ompt_thread_info.state = enclosing_state;
    }
#endif
}
static void __kmp_GOMP_serialized_parallel (ident_t * loc, kmp_int32 gtid, void(*)(void *) task) [static]
Definition at line 385 of file kmp_gsupport.c.
Referenced by KMP_API_NAME_GOMP_PARALLEL(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS(), KMP_API_NAME_GOMP_PARALLEL_SECTIONS_START(), and KMP_API_NAME_GOMP_PARALLEL_START().
{
#if OMPT_SUPPORT
    ompt_parallel_id_t ompt_parallel_id;
    if (ompt_enabled) {
        ompt_task_info_t *task_info = __ompt_get_taskinfo(0);
        task_info->frame.exit_runtime_frame = NULL;
        ompt_parallel_id = __ompt_parallel_id_new(gtid);
        // parallel region callback
        if (ompt_callbacks.ompt_callback(ompt_event_parallel_begin)) {
            int team_size = 1;
            ompt_callbacks.ompt_callback(ompt_event_parallel_begin)(
                task_info->task_id, &task_info->frame, ompt_parallel_id,
                team_size, (void *) task,
                OMPT_INVOKER(fork_context_gnu));
        }
    }
#endif
    __kmp_serialized_parallel(loc, gtid);
#if OMPT_SUPPORT
    if (ompt_enabled) {
        kmp_info_t *thr = __kmp_threads[gtid];
        ompt_task_id_t my_ompt_task_id = __ompt_task_id_new(gtid);
        // set up lightweight task
        ompt_lw_taskteam_t *lwt = (ompt_lw_taskteam_t *)
            __kmp_allocate(sizeof(ompt_lw_taskteam_t));
        __ompt_lw_taskteam_init(lwt, thr, gtid, (void *)
      task, ompt_parallel_id);
        lwt->ompt_task_info.task_id = my_ompt_task_id;
        lwt->ompt_task_info.frame.exit_runtime_frame = 0;
        __ompt_lw_taskteam_link(lwt, thr);
#if OMPT_TRACE
        // implicit task callback
        if (ompt_callbacks.ompt_callback(ompt_event_implicit_task_begin)) {
            ompt_callbacks.ompt_callback(ompt_event_implicit_task_begin)(
                ompt_parallel_id, my_ompt_task_id);
        }
        thr->th.ompt_thread_info.state = ompt_state_work_parallel;
#endif
    }
#endif
}
static kmp_int32 __kmp_gomp_to_omp_cancellation_kind (int gomp_kind) [static]
Definition at line 1283 of file kmp_gsupport.c.
Referenced by KMP_API_NAME_GOMP_CANCEL(), and KMP_API_NAME_GOMP_CANCELLATION_POINT().
                                                             {
    kmp_int32 cncl_kind = 0;
    switch(gomp_kind) {
      case 1:
        cncl_kind = cancel_parallel;
        break;
      case 2:
        cncl_kind = cancel_loop;
        break;
      case 4:
        cncl_kind = cancel_sections;
        break;
      case 8:
        cncl_kind = cancel_taskgroup;
        break;
    }
    return cncl_kind;
}
void xexpand() KMP_API_NAME_GOMP_ATOMIC_END (void)
Definition at line 120 of file kmp_gsupport.c.
{
    int gtid = __kmp_get_gtid();
    KA_TRACE(20, ("GOMP_atomic_start: T#%d\n", gtid));
    __kmp_release_atomic_lock(&__kmp_atomic_lock, gtid);
}
void xexpand() KMP_API_NAME_GOMP_ATOMIC_START (void)
Definition at line 106 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
    KA_TRACE(20, ("GOMP_atomic_start: T#%d\n", gtid));
#if OMPT_SUPPORT
    __ompt_thread_assign_wait_id(0);
#endif
    __kmp_acquire_atomic_lock(&__kmp_atomic_lock, gtid);
}
void xexpand() KMP_API_NAME_GOMP_BARRIER (void)
Definition at line 33 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
    MKLOC(loc, "GOMP_barrier");
    KA_TRACE(20, ("GOMP_barrier: T#%d\n", gtid));
    __kmpc_barrier(&loc, gtid);
}
bool xexpand() KMP_API_NAME_GOMP_BARRIER_CANCEL (void)
Definition at line 1318 of file kmp_gsupport.c.
{
    if(__kmp_omp_cancellation) {
        KMP_FATAL(NoGompCancellation);
    }
    KMP_FATAL(NoGompCancellation);
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_barrier_cancel");
    KA_TRACE(20, ("GOMP_barrier_cancel: T#%d\n", gtid));
    return __kmpc_cancel_barrier(&loc, gtid);
}
bool xexpand() KMP_API_NAME_GOMP_CANCEL (int which, bool do_cancel)
Definition at line 1332 of file kmp_gsupport.c.
{
    if(__kmp_omp_cancellation) {
        KMP_FATAL(NoGompCancellation);
    } else {
        return FALSE;
    }
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_cancel");
    KA_TRACE(20, ("GOMP_cancel: T#%d\n", gtid));
    kmp_int32 cncl_kind = __kmp_gomp_to_omp_cancellation_kind(which);
    if(do_cancel == FALSE) {
        return xexpand(KMP_API_NAME_GOMP_CANCELLATION_POINT)(
      which);
    } else {
        return __kmpc_cancel(&loc, gtid, cncl_kind);
    }
}
bool xexpand() KMP_API_NAME_GOMP_CANCELLATION_POINT (int which)
Definition at line 1303 of file kmp_gsupport.c.
Referenced by KMP_API_NAME_GOMP_CANCEL().
{
    if(__kmp_omp_cancellation) {
        KMP_FATAL(NoGompCancellation);
    }
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_cancellation_point");
    KA_TRACE(20, ("GOMP_cancellation_point: T#%d\n", gtid));
    kmp_int32 cncl_kind = __kmp_gomp_to_omp_cancellation_kind(which);
    return __kmpc_cancellationpoint(&loc, gtid, cncl_kind);
}
void xexpand() KMP_API_NAME_GOMP_CRITICAL_END (void)
Definition at line 70 of file kmp_gsupport.c.
{
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_critical_end");
    KA_TRACE(20, ("GOMP_critical_end: T#%d\n", gtid));
    __kmpc_end_critical(&loc, gtid,
      __kmp_unnamed_critical_addr);
}
void xexpand() KMP_API_NAME_GOMP_CRITICAL_NAME_END (void ** pptr)
Definition at line 90 of file kmp_gsupport.c.
{
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_critical_name_end");
    KA_TRACE(20, ("GOMP_critical_name_end: T#%d\n", gtid));
    __kmpc_end_critical(&loc, gtid, (kmp_critical_name *)pptr);
}
void xexpand() KMP_API_NAME_GOMP_CRITICAL_NAME_START (void ** pptr)
Definition at line 80 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
    MKLOC(loc, "GOMP_critical_name_start");
    KA_TRACE(20, ("GOMP_critical_name_start: T#%d\n", gtid));
    __kmpc_critical(&loc, gtid, (kmp_critical_name *)pptr);
}
void xexpand() KMP_API_NAME_GOMP_CRITICAL_START (void)
Definition at line 60 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
    MKLOC(loc, "GOMP_critical_start");
    KA_TRACE(20, ("GOMP_critical_start: T#%d\n", gtid));
    __kmpc_critical(&loc, gtid, __kmp_unnamed_critical_addr);
}
void xexpand() KMP_API_NAME_GOMP_LOOP_END (void)
Definition at line 712 of file kmp_gsupport.c.
{
    int gtid = __kmp_get_gtid();
    KA_TRACE(20, ("GOMP_loop_end: T#%d\n", gtid))
    __kmp_barrier(bs_plain_barrier, gtid, FALSE, 0, NULL, NULL);
    KA_TRACE(20, ("GOMP_loop_end exit: T#%d\n", gtid))
}
bool xexpand() KMP_API_NAME_GOMP_LOOP_END_CANCEL (void)
Definition at line 1367 of file kmp_gsupport.c.
{
    if(__kmp_omp_cancellation) {
        KMP_FATAL(NoGompCancellation);
    }
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_loop_end_cancel");
    KA_TRACE(20, ("GOMP_loop_end_cancel: T#%d\n", gtid));
    return __kmpc_cancel_barrier(&loc, gtid);
}
void xexpand() KMP_API_NAME_GOMP_LOOP_END_NOWAIT (void)
Definition at line 724 of file kmp_gsupport.c.
{
    KA_TRACE(20, ("GOMP_loop_end_nowait: T#%d\n", __kmp_get_gtid()))
}
void xexpand() KMP_API_NAME_GOMP_ORDERED_END (void)
Definition at line 212 of file kmp_gsupport.c.
{
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_ordered_end");
    KA_TRACE(20, ("GOMP_ordered_start: T#%d\n", gtid));
    __kmpc_end_ordered(&loc, gtid);
}
void xexpand() KMP_API_NAME_GOMP_ORDERED_START (void)
Definition at line 202 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
    MKLOC(loc, "GOMP_ordered_start");
    KA_TRACE(20, ("GOMP_ordered_start: T#%d\n", gtid));
    __kmpc_ordered(&loc, gtid);
}
void xexpand() KMP_API_NAME_GOMP_PARALLEL (void(*)(void *) task, void * data, unsigned num_threads, unsigned int flags)
Definition at line 1162 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
    MKLOC(loc, "GOMP_parallel");
    KA_TRACE(20, ("GOMP_parallel: T#%d\n", gtid));
    if (__kmpc_ok_to_fork(&loc) && (num_threads != 1)) {
        if (num_threads != 0) {
            __kmp_push_num_threads(&loc, gtid, num_threads);
        }
        if(flags != 0) {
            __kmp_push_proc_bind(&loc, gtid, (
      kmp_proc_bind_t)flags);
        }
        __kmp_GOMP_fork_call(&loc, gtid, task,
          (microtask_t)__kmp_GOMP_microtask_wrapper, 2,
      task, data);
    }
    else {
        __kmp_GOMP_serialized_parallel(&loc, gtid,
      task);
    }
    task(data);
    xexpand(KMP_API_NAME_GOMP_PARALLEL_END)();
}
void xexpand() KMP_API_NAME_GOMP_PARALLEL_END (void)
Definition at line 472 of file kmp_gsupport.c.
Referenced by KMP_API_NAME_GOMP_PARALLEL(), and KMP_API_NAME_GOMP_PARALLEL_SECTIONS().
{
    int gtid = __kmp_get_gtid();
    kmp_info_t *thr;
    thr = __kmp_threads[gtid];
    MKLOC(loc, "GOMP_parallel_end");
    KA_TRACE(20, ("GOMP_parallel_end: T#%d\n", gtid));
#if OMPT_SUPPORT
    ompt_parallel_id_t parallel_id;
    ompt_frame_t *ompt_frame = NULL;
    if (ompt_enabled) {
        ompt_team_info_t *team_info = __ompt_get_teaminfo(0, NULL);
        parallel_id = team_info->parallel_id;
        // Record that we re-entered the runtime system in the implicit
        // task frame representing the parallel region.
        ompt_frame = __ompt_get_task_frame_internal(0);
        ompt_frame->reenter_runtime_frame = __builtin_frame_address(0);
#if OMPT_TRACE
        if (ompt_enabled &&
            ompt_callbacks.ompt_callback(ompt_event_implicit_task_end)) {
            ompt_task_info_t *task_info = __ompt_get_taskinfo(0);
            ompt_callbacks.ompt_callback(ompt_event_implicit_task_end)(
                parallel_id, task_info->task_id);
        }
#endif
        // unlink if necessary. no-op if there is not a lightweight task.
        ompt_lw_taskteam_t *lwt = __ompt_lw_taskteam_unlink(thr)
      ;
        // GOMP allocates/frees lwt since it can't be kept on the stack
        if (lwt) {
           __kmp_free(lwt);
     
#if OMPT_SUPPORT
           if (ompt_enabled) {
              // Since a lightweight task was destroyed, make sure that the
              // remaining deepest task knows the stack frame where the runtime
              // was reentered.
              ompt_frame = __ompt_get_task_frame_internal(0);
              ompt_frame->reenter_runtime_frame = __builtin_frame_address(0);
           }
#endif
        }
    }
#endif
    if (! thr->th.th_team->t.t_serialized) {
        __kmp_run_after_invoked_task(gtid,
      __kmp_tid_from_gtid(gtid), thr,
          thr->th.th_team);
#if OMPT_SUPPORT
        if (ompt_enabled) {
          // Set reenter frame in parent task, which will become current task
          // in the midst of join. This is needed before the end_parallel callback.
          ompt_frame = __ompt_get_task_frame_internal(1);
          ompt_frame->reenter_runtime_frame = __builtin_frame_address(0);
        }
#endif
        __kmp_join_call(&loc, gtid
#if OMPT_SUPPORT
            , fork_context_gnu
#endif
        );
#if OMPT_SUPPORT
        if (ompt_enabled) {
          ompt_frame->reenter_runtime_frame = NULL;
        }
#endif
    }
    else {
        __kmpc_end_serialized_parallel(&loc, gtid);
#if OMPT_SUPPORT
        if (ompt_enabled) {
            // Record that we re-entered the runtime system in the frame that
            // created the parallel region.
            ompt_frame->reenter_runtime_frame = __builtin_frame_address(0);
            if (ompt_callbacks.ompt_callback(ompt_event_parallel_end)) {
                ompt_task_info_t *task_info =
      __ompt_get_taskinfo(0);
                ompt_callbacks.ompt_callback(ompt_event_parallel_end)(
                    parallel_id, task_info->task_id,
                    OMPT_INVOKER(fork_context_gnu));
            }
            ompt_frame->reenter_runtime_frame = NULL;
            thr->th.ompt_thread_info.state =
                (((thr->th.th_team)->t.t_serialized) ?
                ompt_state_work_serial : ompt_state_work_parallel);
        }
#endif
    }
}
void xexpand() KMP_API_NAME_GOMP_PARALLEL_SECTIONS (void(*)(void *) task, void * data, unsigned num_threads, unsigned count, unsigned flags)
Definition at line 1186 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
    MKLOC(loc, "GOMP_parallel_sections");
    KA_TRACE(20, ("GOMP_parallel_sections: T#%d\n", gtid));
    if (__kmpc_ok_to_fork(&loc) && (num_threads != 1)) {
        if (num_threads != 0) {
            __kmp_push_num_threads(&loc, gtid, num_threads);
        }
        if(flags != 0) {
            __kmp_push_proc_bind(&loc, gtid, (
      kmp_proc_bind_t)flags);
        }
        __kmp_GOMP_fork_call(&loc, gtid, task,
          (microtask_t)__kmp_GOMP_parallel_microtask_wrapper
      , 9, task, data,
          num_threads, &loc, kmp_nm_dynamic_chunked, (
      kmp_int)1,
          (kmp_int)count, (kmp_int)1, (kmp_int)1);
    }
    else {
        __kmp_GOMP_serialized_parallel(&loc, gtid,
      task);
    }
    KMP_DISPATCH_INIT(&loc, gtid, kmp_nm_dynamic_chunked, 1, count,
      1, 1, TRUE);
    task(data);
    xexpand(KMP_API_NAME_GOMP_PARALLEL_END)();
    KA_TRACE(20, ("GOMP_parallel_sections exit: T#%d\n", gtid));
}
void xexpand() KMP_API_NAME_GOMP_PARALLEL_SECTIONS_START (void(*)(void *) task, void * data, unsigned num_threads, unsigned count)
Definition at line 1091 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
#if OMPT_SUPPORT
    ompt_frame_t *parent_frame;
    if (ompt_enabled) {
        parent_frame = __ompt_get_task_frame_internal(0);
        parent_frame->reenter_runtime_frame = __builtin_frame_address(0);
    }
#endif
    MKLOC(loc, "GOMP_parallel_sections_start");
    KA_TRACE(20, ("GOMP_parallel_sections_start: T#%d\n", gtid));
    if (__kmpc_ok_to_fork(&loc) && (num_threads != 1)) {
        if (num_threads != 0) {
            __kmp_push_num_threads(&loc, gtid, num_threads);
        }
        __kmp_GOMP_fork_call(&loc, gtid, task,
          (microtask_t)__kmp_GOMP_parallel_microtask_wrapper
      , 9, task, data,
          num_threads, &loc, kmp_nm_dynamic_chunked, (
      kmp_int)1,
          (kmp_int)count, (kmp_int)1, (kmp_int)1);
    }
    else {
        __kmp_GOMP_serialized_parallel(&loc, gtid,
      task);
    }
#if OMPT_SUPPORT
    if (ompt_enabled) {
        parent_frame->reenter_runtime_frame = NULL;
    }
#endif
    KMP_DISPATCH_INIT(&loc, gtid, kmp_nm_dynamic_chunked, 1, count,
      1, 1, TRUE);
    KA_TRACE(20, ("GOMP_parallel_sections_start exit: T#%d\n", gtid));
}
void xexpand() KMP_API_NAME_GOMP_PARALLEL_START (void(*)(void *) task, void * data, unsigned num_threads)
Definition at line 436 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
#if OMPT_SUPPORT
    ompt_frame_t *parent_frame;
    if (ompt_enabled) {
        parent_frame = __ompt_get_task_frame_internal(0);
        parent_frame->reenter_runtime_frame = __builtin_frame_address(0);
    }
#endif
    MKLOC(loc, "GOMP_parallel_start");
    KA_TRACE(20, ("GOMP_parallel_start: T#%d\n", gtid));
    if (__kmpc_ok_to_fork(&loc) && (num_threads != 1)) {
        if (num_threads != 0) {
            __kmp_push_num_threads(&loc, gtid, num_threads);
        }
        __kmp_GOMP_fork_call(&loc, gtid, task,
          (microtask_t)__kmp_GOMP_microtask_wrapper, 2,
      task, data);
    }
    else {
        __kmp_GOMP_serialized_parallel(&loc, gtid,
      task);
    }
#if OMPT_SUPPORT
    if (ompt_enabled) {
        parent_frame->reenter_runtime_frame = NULL;
    }
#endif
}
void xexpand() KMP_API_NAME_GOMP_SECTIONS_END (void)
Definition at line 1134 of file kmp_gsupport.c.
{
    int gtid = __kmp_get_gtid();
    KA_TRACE(20, ("GOMP_sections_end: T#%d\n", gtid))
    __kmp_barrier(bs_plain_barrier, gtid, FALSE, 0, NULL, NULL);
    KA_TRACE(20, ("GOMP_sections_end exit: T#%d\n", gtid))
}
bool xexpand() KMP_API_NAME_GOMP_SECTIONS_END_CANCEL (void)
Definition at line 1354 of file kmp_gsupport.c.
{
    if(__kmp_omp_cancellation) {
        KMP_FATAL(NoGompCancellation);
    }
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_sections_end_cancel");
    KA_TRACE(20, ("GOMP_sections_end_cancel: T#%d\n", gtid));
    return __kmpc_cancel_barrier(&loc, gtid);
}
void xexpand() KMP_API_NAME_GOMP_SECTIONS_END_NOWAIT (void)
Definition at line 1146 of file kmp_gsupport.c.
{
    KA_TRACE(20, ("GOMP_sections_end_nowait: T#%d\n", __kmp_get_gtid()))
}
unsigned xexpand() KMP_API_NAME_GOMP_SECTIONS_NEXT (void)
Definition at line 1066 of file kmp_gsupport.c.
{
    int status;
    kmp_int lb, ub, stride;
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_sections_next");
    KA_TRACE(20, ("GOMP_sections_next: T#%d\n", gtid));
    status = KMP_DISPATCH_NEXT(&loc, gtid, NULL, &lb, &ub, &stride);
    if (status) {
        KMP_DEBUG_ASSERT(stride == 1);
        KMP_DEBUG_ASSERT(lb > 0);
        KMP_ASSERT(lb == ub);
    }
    else {
        lb = 0;
    }
    KA_TRACE(20, ("GOMP_sections_next exit: T#%d returning %u\n", gtid,
      (unsigned)lb));
    return (unsigned)lb;
}
unsigned xexpand() KMP_API_NAME_GOMP_SECTIONS_START (unsigned count)
Definition at line 1039 of file kmp_gsupport.c.
{
    int status;
    kmp_int lb, ub, stride;
    int gtid = __kmp_entry_gtid();
    MKLOC(loc, "GOMP_sections_start");
    KA_TRACE(20, ("GOMP_sections_start: T#%d\n", gtid));
    KMP_DISPATCH_INIT(&loc, gtid, kmp_nm_dynamic_chunked, 1,
      count, 1, 1, TRUE);
    status = KMP_DISPATCH_NEXT(&loc, gtid, NULL, &lb, &ub, &stride);
    if (status) {
        KMP_DEBUG_ASSERT(stride == 1);
        KMP_DEBUG_ASSERT(lb > 0);
        KMP_ASSERT(lb == ub);
    }
    else {
        lb = 0;
    }
    KA_TRACE(20, ("GOMP_sections_start exit: T#%d returning %u\n", gtid,
      (unsigned)lb));
    return (unsigned)lb;
}
void xexpand() KMP_API_NAME_GOMP_SINGLE_COPY_END (void * data)
Definition at line 183 of file kmp_gsupport.c.
{
    int gtid = __kmp_get_gtid();
    KA_TRACE(20, ("GOMP_single_copy_end: T#%d\n", gtid));
    //
    // Set the copyprivate data pointer fo the team, then hit the barrier
    // so that the other threads will continue on and read it. Hit another
    // barrier before continuing, so that the know that the copyprivate
    // data pointer has been propagated to all threads before trying to
    // reuse the t_copypriv_data field.
    //
    __kmp_team_from_gtid(gtid)->t.t_copypriv_data = data;
    __kmp_barrier(bs_plain_barrier, gtid, FALSE, 0, NULL, NULL);
    __kmp_barrier(bs_plain_barrier, gtid, FALSE, 0, NULL, NULL);
}
void* xexpand() KMP_API_NAME_GOMP_SINGLE_COPY_START (void)
Definition at line 148 of file kmp_gsupport.c.
{
    void *retval;
    int gtid = __kmp_entry_gtid();
    MKLOC(loc, "GOMP_single_copy_start");
    KA_TRACE(20, ("GOMP_single_copy_start: T#%d\n", gtid));
    if (! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
    //
    // If this is the first thread to enter, return NULL. The generated
    // code will then call GOMP_single_copy_end() for this thread only,
    // with the copyprivate data pointer as an argument.
    //
    if (__kmp_enter_single(gtid, &loc, FALSE))
        return NULL;
    //
    // Wait for the first thread to set the copyprivate data pointer,
    // and for all other threads to reach this point.
    //
    __kmp_barrier(bs_plain_barrier, gtid, FALSE, 0, NULL, NULL);
    //
    // Retrieve the value of the copyprivate data point, and wait for all
    // threads to do likewise, then return.
    //
    retval = __kmp_team_from_gtid(gtid)->t.t_copypriv_data;
    __kmp_barrier(bs_plain_barrier, gtid, FALSE, 0, NULL, NULL);
    return retval;
}
int xexpand() KMP_API_NAME_GOMP_SINGLE_START (void)
Definition at line 129 of file kmp_gsupport.c.
{
    int gtid = __kmp_entry_gtid();
    MKLOC(loc, "GOMP_single_start");
    KA_TRACE(20, ("GOMP_single_start: T#%d\n", gtid));
    if (! TCR_4(__kmp_init_parallel))
        __kmp_parallel_initialize();
    //
    // 3rd parameter == FALSE prevents kmp_enter_single from pushing a
    // workshare when USE_CHECKS is defined. We need to avoid the push,
    // as there is no corresponding GOMP_single_end() call.
    //
    return __kmp_enter_single(gtid, &loc, FALSE);
}
void xexpand() KMP_API_NAME_GOMP_TARGET (int device, void(*)(void *) fn, const void * openmp_target, size_t mapnum, void ** hostaddrs, size_t * sizes, unsigned char * kinds)
Definition at line 1381 of file kmp_gsupport.c.
{
    return;
}
void xexpand() KMP_API_NAME_GOMP_TARGET_DATA (int device, const void * openmp_target, size_t mapnum, void ** hostaddrs, size_t * sizes, unsigned char * kinds)
Definition at line 1388 of file kmp_gsupport.c.
{
    return;
}
void xexpand() KMP_API_NAME_GOMP_TARGET_END_DATA (void)
Definition at line 1395 of file kmp_gsupport.c.
{
    return;
}
void xexpand() KMP_API_NAME_GOMP_TARGET_UPDATE (int device, const void * openmp_target, size_t mapnum, void ** hostaddrs, size_t * sizes, unsigned char * kinds)
Definition at line 1401 of file kmp_gsupport.c.
{
    return;
}
void xexpand() KMP_API_NAME_GOMP_TASKGROUP_END (void)
Definition at line 1269 of file kmp_gsupport.c.
{
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_taskgroup_end");
    KA_TRACE(20, ("GOMP_taskgroup_end: T#%d\n", gtid));
    __kmpc_end_taskgroup(&loc, gtid);
    return;
}
void xexpand() KMP_API_NAME_GOMP_TASKGROUP_START (void)
Definition at line 1257 of file kmp_gsupport.c.
{
    int gtid = __kmp_get_gtid();
    MKLOC(loc, "GOMP_taskgroup_start");
    KA_TRACE(20, ("GOMP_taskgroup_start: T#%d\n", gtid));
    __kmpc_taskgroup(&loc, gtid);
    return;
}
void xexpand() KMP_API_NAME_GOMP_TASKWAIT (void)
Definition at line 1012 of file kmp_gsupport.c.
{
    MKLOC(loc, "GOMP_taskwait");
    int gtid = __kmp_entry_gtid();
    KA_TRACE(20, ("GOMP_taskwait: T#%d\n", gtid));
    __kmpc_omp_taskwait(&loc, gtid);
    KA_TRACE(20, ("GOMP_taskwait exit: T#%d\n", gtid));
}
void xexpand() KMP_API_NAME_GOMP_TASKYIELD (void)
Definition at line 1153 of file kmp_gsupport.c.
{
    KA_TRACE(20, ("GOMP_taskyield: T#%d\n", __kmp_get_gtid()))
    return;
}
void xexpand() KMP_API_NAME_GOMP_TEAMS (unsigned int num_teams, unsigned int thread_limit)
Definition at line 1408 of file kmp_gsupport.c.
{
    return;
}
LOOP_NEXT (xexpand(KMP_API_NAME_GOMP_LOOP_ORDERED_STATIC_NEXT) , {KMP_DISPATCH_FINI_CHUNK(&loc, gtid);})
Definition at line 698 of file kmp_gsupport.c.
    { KMP_DISPATCH_FINI_CHUNK(&loc, gtid); })
LOOP_START(xexpand(KMP_API_NAME_GOMP_LOOP_ORDERED_DYNAMIC_START
      ), kmp_ord_dynamic_chunked)
LOOP_NEXT(xexpand(KMP_API_NAME_GOMP_LOOP_ORDERED_DYNAMIC_NEXT
      ), \
    { KMP_DISPATCH_FINI_CHUNK(&loc, gtid); })
LOOP_NEXT (xexpand(KMP_API_NAME_GOMP_LOOP_ORDERED_GUIDED_NEXT) , {KMP_DISPATCH_FINI_CHUNK(&loc, gtid);})
Definition at line 704 of file kmp_gsupport.c.
    { KMP_DISPATCH_FINI_CHUNK(&loc, gtid); })
LOOP_RUNTIME_START(xexpand(
      KMP_API_NAME_GOMP_LOOP_ORDERED_RUNTIME_START),
      kmp_ord_runtime)
LOOP_NEXT(xexpand(KMP_API_NAME_GOMP_LOOP_ORDERED_RUNTIME_NEXT
      ), \
    { KMP_DISPATCH_FINI_CHUNK(&loc, gtid); })
LOOP_NEXT_ULL (xexpand(KMP_API_NAME_GOMP_LOOP_ULL_ORDERED_STATIC_NEXT) , {KMP_DISPATCH_FINI_CHUNK_ULL(&loc, gtid);})
Definition at line 838 of file kmp_gsupport.c.
    { KMP_DISPATCH_FINI_CHUNK_ULL(&loc, gtid); })
LOOP_START_ULL(xexpand(
      KMP_API_NAME_GOMP_LOOP_ULL_ORDERED_DYNAMIC_START),
      kmp_ord_dynamic_chunked)
LOOP_NEXT_ULL(xexpand(
      KMP_API_NAME_GOMP_LOOP_ULL_ORDERED_DYNAMIC_NEXT), \
    { KMP_DISPATCH_FINI_CHUNK_ULL(&loc, gtid); })
LOOP_NEXT_ULL (xexpand(KMP_API_NAME_GOMP_LOOP_ULL_ORDERED_GUIDED_NEXT) , {KMP_DISPATCH_FINI_CHUNK_ULL(&loc, gtid);})
Definition at line 844 of file kmp_gsupport.c.
    { KMP_DISPATCH_FINI_CHUNK_ULL(&loc, gtid); })
LOOP_RUNTIME_START_ULL(xexpand(
      KMP_API_NAME_GOMP_LOOP_ULL_ORDERED_RUNTIME_START),
      kmp_ord_runtime)
LOOP_NEXT_ULL(xexpand(
      KMP_API_NAME_GOMP_LOOP_ULL_ORDERED_RUNTIME_NEXT), \
    { KMP_DISPATCH_FINI_CHUNK_ULL(&loc, gtid); })
PARALLEL_LOOP_START (xexpand(KMP_API_NAME_GOMP_PARALLEL_LOOP_STATIC_START) , kmp_sch_static , PARALLEL_LOOP_START((KMP_API_NAME_GOMP_PARALLEL_LOOP_DYNAMIC_START) OMPT_LOOP_PRE, OMPT_LOOP_POST)
Definition at line 916 of file kmp_gsupport.c.
{
    MKLOC(loc, "GOMP_task");
    int gtid = __kmp_entry_gtid();
    kmp_int32 flags = 0;
    kmp_tasking_flags_t *input_flags = (kmp_tasking_flags_t *) &
      flags;
    KA_TRACE(20, ("GOMP_task: T#%d\n", gtid));
    // The low-order bit is the "tied" flag
    if (gomp_flags & 1) {
        input_flags->tiedness = 1;
    }
    // The second low-order bit is the "final" flag
    if (gomp_flags & 2) {
        input_flags->final = 1;
    }
    input_flags->native = 1;
    // __kmp_task_alloc() sets up all other flags
    if (! if_cond) {
        arg_size = 0;
    }
    kmp_task_t *task = __kmp_task_alloc(&loc, gtid, input_flags,
      sizeof(kmp_task_t), arg_size ? arg_size + arg_align - 1 : 0,
      (kmp_routine_entry_t)func);
    if (arg_size > 0) {
        if (arg_align > 0) {
            task->shareds = (void *)((((size_t)task->shareds)
              + arg_align - 1) / arg_align * arg_align);
        }
        //else error??
        if (copy_func) {
            (*copy_func)(task->shareds, data);
        }
        else {
            KMP_MEMCPY(task->shareds, data, arg_size);
        }
    }
    if (if_cond) {
        __kmpc_omp_task(&loc, gtid, task);
    }
    else {
#if OMPT_SUPPORT
        ompt_thread_info_t oldInfo;
        kmp_info_t *thread;
        kmp_taskdata_t *taskdata;
        if (ompt_enabled) {
            // Store the threads states and restore them after the task
            thread = __kmp_threads[ gtid ];
            taskdata = KMP_TASK_TO_TASKDATA(task);
            oldInfo = thread->th.ompt_thread_info;
            thread->th.ompt_thread_info.wait_id = 0;
            thread->th.ompt_thread_info.state = ompt_state_work_parallel;
            taskdata->ompt_task_info.frame.exit_runtime_frame =
                __builtin_frame_address(0);
        }
#endif
        __kmpc_omp_task_begin_if0(&loc, gtid, task);
        func(data);
        __kmpc_omp_task_complete_if0(&loc, gtid, task);
#if OMPT_SUPPORT
        if (ompt_enabled) {
            thread->th.ompt_thread_info = oldInfo;
            taskdata->ompt_task_info.frame.exit_runtime_frame = 0;
        }
#endif
    }
    KA_TRACE(20, ("GOMP_task exit: T#%d\n", gtid));
}
Variable Documentation
kmp_critical_name* __kmp_unnamed_critical_addr