kmp_stats.cpp File Reference
#include `kmp.h`
*
#include `kmp_str.h`
*
#include `kmp_lock.h`
*
#include `kmp_stats.h`
*
#include <algorithm>
*
#include <sstream>
*
#include <iomanip>
*
#include <stdlib.h>
*
#include <ctime>
*
Macros
#define STRINGIZE2(x) #x
#define STRINGIZE(x) STRINGIZE2(x)
#define expandName(name, flags, ignore) {STRINGIZE(name),flags},
#define expandName(ignore1, ignore2, ignore3) {0.0,0.0,0.0},
Functions
int compare_two_events (const void *event1, const void *event2)
void __kmp_reset_stats ()
void __kmp_output_stats (const char *heading)
void __kmp_accumulate_stats_at_exit (void)
void __kmp_stats_init (void)
Variables
static uint32_t statsPrinted = 0
static kmp_stats_output_module __kmp_stats_global_output
Detailed Description
Statistics gathering and processing.
Definition in file kmp_stats.cpp.
Macro Definition Documentation
#define expandName(name, flags, ignore) {STRINGIZE(name),flags},
Definition at line 40 of file kmp_stats.cpp.
#define expandName(ignore1, ignore2, ignore3) {0.0,0.0,0.0},
Definition at line 40 of file kmp_stats.cpp.
#define STRINGIZE(x) STRINGIZE2(x)
Definition at line 27 of file kmp_stats.cpp.
#define STRINGIZE2(x) #x
Definition at line 26 of file kmp_stats.cpp.
Function Documentation
void __kmp_accumulate_stats_at_exit (void)
Definition at line 609 of file kmp_stats.cpp.
Referenced by __kmp_cleanup().
{
    // Only do this once.
    if (KMP_XCHG_FIXED32(&statsPrinted, 1) != 0)
        return;
    __kmp_output_stats("Statistics on exit");
}
void __kmp_output_stats (const char * heading)
Definition at line 603 of file kmp_stats.cpp.
Referenced by __kmp_accumulate_stats_at_exit().
{
    __kmp_stats_global_output.outputStats(heading);
    __kmp_reset_stats();
}
void __kmp_reset_stats ()
Definition at line 576 of file kmp_stats.cpp.
Referenced by __kmp_output_stats().
{
    kmp_stats_list::iterator it;
    for(it = __kmp_stats_list.begin(); it !=
      __kmp_stats_list.end(); it++) {
        timeStat * timers = (*it)->getTimers();
        counter * counters = (*it)->getCounters();
        explicitTimer * eTimers = (*it)->getExplicitTimers();
        for (int t = 0; t<TIMER_LAST; t++)
            timers[t].reset();
        for (int c = 0; c<COUNTER_LAST; c++)
            counters[c].reset();
        for (int t=0; t<EXPLICIT_TIMER_LAST; t++)
            eTimers[t].reset();
        // reset the event vector so all previous events are "erased"
        (*it)->resetEventVector();
        // May need to restart the explicit timers in thread zero?
    }
    KMP_START_EXPLICIT_TIMER(OMP_serial);
    KMP_START_EXPLICIT_TIMER(OMP_start_end);
}
void __kmp_stats_init (void)
Definition at line 618 of file kmp_stats.cpp.
Referenced by __kmp_create_worker().
{
}
int compare_two_events (const void * event1, const void * event2)
Definition at line 199 of file kmp_stats.cpp.
Referenced by kmp_stats_event_vector::sort().
                                                               {
    kmp_stats_event* ev1 = (kmp_stats_event*)event1;
    kmp_stats_event* ev2 = (kmp_stats_event*)event2;
    if(ev1->getStart() < ev2->getStart()) return -1;
    else if(ev1->getStart() > ev2->getStart()) return 1;
    else return 0;
}
Variable Documentation
kmp_stats_output_module __kmp_stats_global_output [static]
Definition at line 74 of file kmp_stats.cpp.
uint32_t statsPrinted = 0 [static]
Definition at line 71 of file kmp_stats.cpp.
Referenced by __kmp_accumulate_stats_at_exit().