kmp_io.h File Reference
Enumerations
enum kmp_io { kmp_out = 0,
kmp_err
 }
Functions
void __kmp_vprintf (enum kmp_io __kmp_io, char const *format, va_list ap)
void __kmp_printf (char const *format,...)
void __kmp_printf_no_lock (char const *format,...)
void __kmp_close_console (void)
Variables
kmp_bootstrap_lock_t __kmp_stdio_lock
kmp_bootstrap_lock_t __kmp_console_lock
Enumeration Type Documentation
enum kmp_io
Enumerator
kmp_out
kmp_err
Definition at line 26 of file kmp_io.h.
            {
    kmp_out = 0,
    kmp_err
};
Function Documentation
void __kmp_close_console (void)
Referenced by __kmp_internal_end_atexit(), and __kmp_internal_end_library().
void __kmp_printf (char const * format, ...)
Definition at line 224 of file kmp_io.c.
Referenced by __kmp_acquire_drdpa_lock_timed_template(), __kmp_acquire_tas_lock_timed_template(), __kmp_acquire_ticket_lock_timed_template(), __kmp_do_serial_initialize(), __kmp_env_print(), __kmp_env_print_2(), __kmp_i18n_dump_catalog(), __kmp_internal_join(), __kmp_msg(), __kmp_print_version_1(), __kmp_resume_monitor(), __kmp_resume_template(), __kmp_suspend_template(), and __kmp_track_dependence().
{
    va_list ap;
    va_start(ap, format);
    __kmp_acquire_bootstrap_lock(& __kmp_stdio_lock);
    __kmp_vprintf(kmp_err, format, ap);
    __kmp_release_bootstrap_lock(& __kmp_stdio_lock);
    va_end(ap);
}
void __kmp_printf_no_lock (char const * format, ...)
Definition at line 237 of file kmp_io.c.
Referenced by __kmp_dump_debug_buffer(), __kmp_print_storage_map_gtid(), and bfreed().
{
    va_list ap;
    va_start(ap, format);
    __kmp_vprintf(kmp_err, format, ap);
    va_end(ap);
}
void __kmp_vprintf (enum kmp_io __kmp_io, char const * format, va_list ap)
Definition at line 147 of file kmp_io.c.
Referenced by __kmp_debug_printf(), __kmp_print_storage_map_gtid(), __kmp_printf(), __kmp_printf_no_lock(), and __kmp_warn().
{
    #if KMP_OS_WINDOWS
        if(!__kmp_console_exists) {
            __kmp_redirect_output();
        }
            if(! __kmp_stderr && __kmp_io == kmp_err) {
            return;
        }
        #ifdef KMP_DEBUG
            if(! __kmp_stdout && __kmp_io == kmp_out) {
                return;
            }
        #endif
    #endif /* KMP_OS_WINDOWS */
    if (__kmp_debug_buf && __kmp_debug_buffer != NULL) {
        int dc = (__kmp_debug_buf_atomic ?
                   KMP_TEST_THEN_INC32(& __kmp_debug_count) :
      __kmp_debug_count++)
                   % __kmp_debug_buf_lines;
        char *db = & __kmp_debug_buffer[ dc *
      __kmp_debug_buf_chars ];
        int chars = 0;
        #ifdef KMP_DEBUG_PIDS
            chars = KMP_SNPRINTF(db, __kmp_debug_buf_chars, "pid=%d: ", (
      kmp_int32)getpid());
        #endif
        chars += KMP_VSNPRINTF(db, __kmp_debug_buf_chars, format, ap);
        if (chars + 1 > __kmp_debug_buf_chars) {
            if (chars + 1 > __kmp_debug_buf_warn_chars) {
                #if KMP_OS_WINDOWS
                    DWORD count;
                    __kmp_str_buf_print(&__kmp_console_buf,
                        "OMP warning: Debugging buffer overflow; increase KMP_DEBUG_BUF_CHARS to %d\n",
                        chars + 1);
                    WriteFile(__kmp_stderr, __kmp_console_buf.str, __kmp_console_buf.used, &
      count, NULL);
                    __kmp_str_buf_clear(&__kmp_console_buf);
                #else
                    fprintf(__kmp_stderr,
                         "OMP warning: Debugging buffer overflow; increase KMP_DEBUG_BUF_CHARS to %d\n",
                         chars + 1);
                    fflush(__kmp_stderr);
                #endif
                __kmp_debug_buf_warn_chars = chars + 1;
            }
            /* terminate string if overflow occurred */
            db[ __kmp_debug_buf_chars - 2 ] = '\n';
            db[ __kmp_debug_buf_chars - 1 ] = '\0';
        }
    } else {
        #if KMP_OS_WINDOWS
            DWORD count;
            #ifdef KMP_DEBUG_PIDS
                __kmp_str_buf_print(&__kmp_console_buf, "pid=%d: ",
                  (kmp_int32)getpid());
            #endif
            __kmp_str_buf_vprint(&__kmp_console_buf, format, ap);
            WriteFile(
                __kmp_stderr,
                __kmp_console_buf.str,
                __kmp_console_buf.used,
                &count,
                NULL
            );
            __kmp_str_buf_clear(&__kmp_console_buf);
        #else
            #ifdef KMP_DEBUG_PIDS
                fprintf(__kmp_stderr, "pid=%d: ", (kmp_int32)getpid());
            #endif
            vfprintf(__kmp_stderr, format, ap);
            fflush(__kmp_stderr);
        #endif
    }
}
Variable Documentation
kmp_bootstrap_lock_t __kmp_console_lock
Definition at line 42 of file kmp_io.c.
Referenced by __kmp_atfork_child().
kmp_bootstrap_lock_t __kmp_stdio_lock
Definition at line 41 of file kmp_io.c.
Referenced by __kmp_atfork_child(), __kmp_dump_debug_buffer(), __kmp_print_storage_map_gtid(), and __kmp_warn().