kmp_error.h File Reference
#include `kmp_i18n.h`
*
Functions
void __kmp_error_construct (kmp_i18n_id_t id, enum cons_type ct, ident_t const *ident)
void __kmp_error_construct2 (kmp_i18n_id_t id, enum cons_type ct, ident_t const *ident, struct cons_data const *cons)
struct cons_header * __kmp_allocate_cons_stack (int gtid)
void __kmp_free_cons_stack (void *ptr)
void __kmp_push_parallel (int gtid, ident_t const *ident)
void __kmp_push_workshare (int gtid, enum cons_type ct, ident_t const *ident)
void __kmp_push_sync (int gtid, enum cons_type ct, ident_t const *ident, kmp_user_lock_p name)
void __kmp_check_workshare (int gtid, enum cons_type ct, ident_t const *ident)
void __kmp_check_sync (int gtid, enum cons_type ct, ident_t const *ident, kmp_user_lock_p name)
void __kmp_pop_parallel (int gtid, ident_t const *ident)
enum cons_type __kmp_pop_workshare (int gtid, enum cons_type ct, ident_t const *ident)
void __kmp_pop_sync (int gtid, enum cons_type ct, ident_t const *ident)
void __kmp_check_barrier (int gtid, enum cons_type ct, ident_t const *ident)
Function Documentation
struct cons_header* __kmp_allocate_cons_stack (int gtid)
Definition at line 157 of file kmp_error.c.
Referenced by __kmp_launch_thread(), and __kmp_register_root().
{
    struct cons_header *p;
    /* TODO for monitor perhaps? */
    if (gtid < 0) {
        __kmp_check_null_func();
    }; // if
    KE_TRACE(10, ("allocate cons_stack (%d)\n", gtid));
    p = (struct cons_header *) __kmp_allocate(sizeof(struct
      cons_header));
    p->p_top = p->w_top = p->s_top = 0;
    p->stack_data = (struct cons_data *) __kmp_allocate(sizeof(struct
      cons_data) * (MIN_STACK+1));
    p->stack_size = MIN_STACK;
    p->stack_top = 0;
    p->stack_data[ 0 ].type = ct_none;
    p->stack_data[ 0 ].prev = 0;
    p->stack_data[ 0 ].ident = NULL;
    return p;
}
void __kmp_check_barrier (int gtid, enum cons_type ct, ident_t const * ident)
Definition at line 494 of file kmp_error.c.
Referenced by __kmpc_barrier(), __kmpc_barrier_master(), and __kmpc_barrier_master_nowait().
{
    struct cons_header *p = __kmp_threads[ gtid ]->th.th_cons;
    KE_TRACE(10, ("__kmp_check_barrier (loc: %p, gtid: %d %d)\n", ident, gtid,
      __kmp_get_gtid()));
    if (ident != 0) {
        __kmp_check_null_func();
    }
    if (p->w_top > p->p_top) {
        /* we are already in a WORKSHARING construct for this PARALLEL region */
        __kmp_error_construct2(
            kmp_i18n_msg_CnsInvalidNesting,
            ct, ident,
            & p->stack_data[ p->w_top ]
        );
    }
    if (p->s_top > p->p_top) {
        /* we are already in a SYNC construct for this PARALLEL region */
        __kmp_error_construct2(
            kmp_i18n_msg_CnsInvalidNesting,
            ct, ident,
            & p->stack_data[ p->s_top ]
        );
    }
}
void __kmp_check_sync (int gtid, enum cons_type ct, ident_t const * ident, kmp_user_lock_p name)
Definition at line 276 of file kmp_error.c.
Referenced by __kmp_push_sync(), and __kmpc_master().
{
    struct cons_header *p = __kmp_threads[ gtid ]->th.th_cons;
    KE_TRACE(10, ("__kmp_check_sync (gtid=%d)\n", __kmp_get_gtid()));
    if (p->stack_top >= p->stack_size)
       __kmp_expand_cons_stack(gtid, p);
    if (ct == ct_ordered_in_parallel || ct ==
      ct_ordered_in_pdo || ct == ct_ordered_in_taskq) {
        if (p->w_top <= p->p_top) {
            /* we are not in a worksharing construct */
            #ifdef BUILD_PARALLEL_ORDERED
                /* do not report error messages for PARALLEL ORDERED */
                KMP_ASSERT(ct == ct_ordered_in_parallel);
            #else
                __kmp_error_construct(kmp_i18n_msg_CnsBoundToWorksharing, ct,
      ident);
            #endif /* BUILD_PARALLEL_ORDERED */
        } else {
            /* inside a WORKSHARING construct for this PARALLEL region */
            if (!IS_CONS_TYPE_ORDERED(p->stack_data[ p->
      w_top ].type)) {
                if (p->stack_data[ p->w_top ].type ==
      ct_taskq) {
                    __kmp_error_construct2(
                        kmp_i18n_msg_CnsNotInTaskConstruct,
                        ct, ident,
                        & p->stack_data[ p->w_top ]
                    );
                } else {
                    __kmp_error_construct2(
                        kmp_i18n_msg_CnsNoOrderedClause,
                        ct, ident,
                        & p->stack_data[ p->w_top ]
                    );
               }
            }
        }
        if (p->s_top > p->p_top && p->s_top > p->w_top) {
            /* inside a sync construct which is inside a worksharing construct */
            int index = p->s_top;
            enum cons_type stack_type;
            stack_type = p->stack_data[ index ].type;
            if (stack_type == ct_critical ||
                ((stack_type == ct_ordered_in_parallel ||
                    stack_type == ct_ordered_in_pdo ||
                    stack_type == ct_ordered_in_taskq) && /* C doesn't allow named
       ordered; ordered in ordered gets error */
                 p->stack_data[ index ].ident != NULL &&
                 (p->stack_data[ index ].ident->flags &
      KMP_IDENT_KMPC))) {
                /* we are in ORDERED which is inside an ORDERED or CRITICAL construct */
                __kmp_error_construct2(
                    kmp_i18n_msg_CnsInvalidNesting,
                    ct, ident,
                    & p->stack_data[ index ]
                );
            }
        }
    } else if (ct == ct_critical) {
#if KMP_USE_DYNAMIC_LOCK
        if (lck != NULL && __kmp_get_user_lock_owner(lck, seq) == gtid) {
      /* this same thread already has lock for this critical section */
#else
        if (lck != NULL && __kmp_get_user_lock_owner(lck) == gtid) { /*
       this same thread already has lock for this critical section */
#endif
            int index = p->s_top;
            struct cons_data cons = { NULL, ct_critical, 0, NULL };
            /* walk up construct stack and try to find critical with matching name */
            while (index != 0 && p->stack_data[ index ].name != lck) {
                index = p->stack_data[ index ].prev;
            }
            if (index != 0) {
                /* found match on the stack (may not always because of interleaved critical for Fortran) */
                cons = p->stack_data[ index ];
            }
            /* we are in CRITICAL which is inside a CRITICAL construct of the same name */
            __kmp_error_construct2(kmp_i18n_msg_CnsNestingSameName, ct,
      ident, & cons);
        }
    } else if (ct == ct_master || ct == ct_reduce) {
        if (p->w_top > p->p_top) {
            /* inside a WORKSHARING construct for this PARALLEL region */
           __kmp_error_construct2(
               kmp_i18n_msg_CnsInvalidNesting,
               ct, ident,
               & p->stack_data[ p->w_top ]
           );
        }
        if (ct == ct_reduce && p->s_top > p->p_top) {
            /* inside a another SYNC construct for this PARALLEL region */
            __kmp_error_construct2(
                kmp_i18n_msg_CnsInvalidNesting,
                ct, ident,
                & p->stack_data[ p->s_top ]
            );
        }; // if
    }; // if
}
void __kmp_check_workshare (int gtid, enum cons_type ct, ident_t const * ident)
Definition at line 233 of file kmp_error.c.
Referenced by __kmp_dispatch_init(), __kmp_enter_single(), and __kmp_push_workshare().
{
    struct cons_header *p = __kmp_threads[ gtid ]->th.th_cons;
    KMP_DEBUG_ASSERT(__kmp_threads[ gtid ]-> th.th_cons);
    KE_TRACE(10, ("__kmp_check_workshare (%d %d)\n", gtid,
      __kmp_get_gtid()));
    if (p->stack_top >= p->stack_size) {
        __kmp_expand_cons_stack(gtid, p);
    }; // if
    if (p->w_top > p->p_top &&
        !(IS_CONS_TYPE_TASKQ(p->stack_data[ p->w_top ].
      type) && IS_CONS_TYPE_TASKQ(ct))) {
        // We are already in a WORKSHARE construct for this PARALLEL region.
        __kmp_error_construct2(kmp_i18n_msg_CnsInvalidNesting, ct,
      ident, & p->stack_data[ p->w_top ]);
    }; // if
    if (p->s_top > p->p_top) {
        // We are already in a SYNC construct for this PARALLEL region.
        __kmp_error_construct2(kmp_i18n_msg_CnsInvalidNesting, ct,
      ident, & p->stack_data[ p->s_top ]);
    }; // if
}
void __kmp_error_construct (kmp_i18n_id_t id, enum cons_type ct, ident_t const * ident)
Definition at line 131 of file kmp_error.c.
Referenced by __kmp_check_sync(), __kmp_dispatch_init(), __kmp_dist_for_static_init(), __kmp_dist_get_bounds(), __kmp_for_static_init(), __kmp_pop_parallel(), __kmp_pop_sync(), __kmp_pop_workshare(), and __kmp_team_static_init().
  {
    char const * construct = __kmp_pragma(ct, ident);
    __kmp_msg(kmp_ms_fatal, __kmp_msg_format(id, construct),
      __kmp_msg_null);
    KMP_INTERNAL_FREE((void *) construct);
}
void __kmp_error_construct2 (kmp_i18n_id_t id, enum cons_type ct, ident_t const * ident, struct cons_data const * cons)
Definition at line 142 of file kmp_error.c.
Referenced by __kmp_check_barrier(), __kmp_check_sync(), __kmp_check_workshare(), __kmp_dispatch_deo(), __kmp_dispatch_dxo(), __kmp_pop_parallel(), __kmp_pop_sync(), and __kmp_pop_workshare().
  {
    char const * construct1 = __kmp_pragma(ct, ident);
    char const * construct2 = __kmp_pragma(cons->type, cons->ident);
    __kmp_msg(kmp_ms_fatal, __kmp_msg_format(id, construct1,
      construct2), __kmp_msg_null);
    KMP_INTERNAL_FREE((void *) construct1);
    KMP_INTERNAL_FREE((void *) construct2);
}
void __kmp_free_cons_stack (void * ptr)
Definition at line 178 of file kmp_error.c.
Referenced by __kmp_reap_thread().
                                    {
    struct cons_header * p = (struct cons_header *) ptr;
    if (p != NULL) {
        if (p->stack_data != NULL) {
            __kmp_free(p->stack_data);
            p->stack_data = NULL;
        }; // if
        __kmp_free(p);
    }; // if
}
void __kmp_pop_parallel (int gtid, ident_t const * ident)
Definition at line 403 of file kmp_error.c.
Referenced by __kmp_run_after_invoked_task(), and __kmpc_end_serialized_parallel().
{
    int tos;
    struct cons_header *p = __kmp_threads[ gtid ]->th.th_cons;
    tos = p->stack_top;
    KE_TRACE(10, ("__kmp_pop_parallel (%d %d)\n", gtid, __kmp_get_gtid()));
    if (tos == 0 || p->p_top == 0) {
        __kmp_error_construct(kmp_i18n_msg_CnsDetectedEnd,
      ct_parallel, ident);
    }
    if (tos != p->p_top || p->stack_data[ tos ].type !=
      ct_parallel) {
        __kmp_error_construct2(
            kmp_i18n_msg_CnsExpectedEnd,
            ct_parallel, ident,
            & p->stack_data[ tos ]
        );
    }
    KE_TRACE(100, (POP_MSG(p)));
    p->p_top = p->stack_data[ tos ].prev;
    p->stack_data[ tos ].type = ct_none;
    p->stack_data[ tos ].ident = NULL;
    p->stack_top = tos - 1;
    KE_DUMP(1000, dump_cons_stack(gtid, p));
}
void __kmp_pop_sync (int gtid, enum cons_type ct, ident_t const * ident)
Definition at line 463 of file kmp_error.c.
Referenced by __kmp_dispatch_dxo(), __kmp_dispatch_dxo_error(), __kmp_end_critical_section_reduce_block(), __kmp_parallel_dxo(), __kmp_taskq_xo(), __kmpc_barrier_master_nowait(), __kmpc_end_critical(), __kmpc_end_master(), __kmpc_end_reduce(), __kmpc_end_reduce_nowait(), __kmpc_reduce(), and __kmpc_reduce_nowait().
{
    int tos;
    struct cons_header *p = __kmp_threads[ gtid ]->th.th_cons;
    tos = p->stack_top;
    KE_TRACE(10, ("__kmp_pop_sync (%d %d)\n", gtid, __kmp_get_gtid()));
    if (tos == 0 || p->s_top == 0) {
        __kmp_error_construct(kmp_i18n_msg_CnsDetectedEnd, ct,
      ident);
    };
    if (tos != p->s_top || p->stack_data[ tos ].type != ct) {
        __kmp_check_null_func();
        __kmp_error_construct2(
            kmp_i18n_msg_CnsExpectedEnd,
            ct, ident,
            & p->stack_data[ tos ]
        );
    };
    if (gtid < 0) {
        __kmp_check_null_func();
    };
    KE_TRACE(100, (POP_MSG(p)));
    p->s_top = p->stack_data[ tos ].prev;
    p->stack_data[ tos ].type = ct_none;
    p->stack_data[ tos ].ident = NULL;
    p->stack_top = tos - 1;
    KE_DUMP(1000, dump_cons_stack(gtid, p));
}
enum cons_type __kmp_pop_workshare (int gtid, enum cons_type ct, ident_t const * ident)
Definition at line 428 of file kmp_error.c.
Referenced by __kmp_dispatch_next(), __kmp_execute_task_from_queue(), __kmp_exit_single(), __kmpc_end_taskq_task(), __kmpc_for_static_fini(), and __kmpc_taskq_task().
{
    int tos;
    struct cons_header *p = __kmp_threads[ gtid ]->th.th_cons;
    tos = p->stack_top;
    KE_TRACE(10, ("__kmp_pop_workshare (%d %d)\n", gtid, __kmp_get_gtid()));
    if (tos == 0 || p->w_top == 0) {
        __kmp_error_construct(kmp_i18n_msg_CnsDetectedEnd, ct,
      ident);
    }
    if (tos != p->w_top ||
         (p->stack_data[ tos ].type != ct &&
          /* below are two exceptions to the rule that construct types must match */
          ! (p->stack_data[ tos ].type == ct_pdo_ordered && ct ==
      ct_pdo) &&
          ! (p->stack_data[ tos ].type == ct_task_ordered && ct ==
      ct_task)
         )
       ) {
        __kmp_check_null_func();
        __kmp_error_construct2(
            kmp_i18n_msg_CnsExpectedEnd,
            ct, ident,
            & p->stack_data[ tos ]
        );
    }
    KE_TRACE(100, (POP_MSG(p)));
    p->w_top = p->stack_data[ tos ].prev;
    p->stack_data[ tos ].type = ct_none;
    p->stack_data[ tos ].ident = NULL;
    p->stack_top = tos - 1;
    KE_DUMP(1000, dump_cons_stack(gtid, p));
    return p->stack_data[ p->w_top ].type;
}
void __kmp_push_parallel (int gtid, ident_t const * ident)
Definition at line 212 of file kmp_error.c.
Referenced by __kmp_run_before_invoked_task(), and __kmp_serialized_parallel().
{
    int tos;
    struct cons_header *p = __kmp_threads[ gtid ]->th.th_cons;
    KMP_DEBUG_ASSERT(__kmp_threads[ gtid ]-> th.th_cons);
    KE_TRACE(10, ("__kmp_push_parallel (%d %d)\n", gtid, __kmp_get_gtid()));
    KE_TRACE(100, (PUSH_MSG(ct_parallel, ident)));
    if (p->stack_top >= p->stack_size) {
        __kmp_expand_cons_stack(gtid, p);
    }; // if
    tos = ++p->stack_top;
    p->stack_data[ tos ].type = ct_parallel;
    p->stack_data[ tos ].prev = p->p_top;
    p->stack_data[ tos ].ident = ident;
    p->stack_data[ tos ].name = NULL;
    p->p_top = tos;
    KE_DUMP(1000, dump_cons_stack(gtid, p));
}
void __kmp_push_sync (int gtid, enum cons_type ct, ident_t const * ident, kmp_user_lock_p name)
Definition at line 377 of file kmp_error.c.
Referenced by __kmp_check_sync(), __kmp_dispatch_deo(), __kmp_dispatch_deo_error(), __kmp_enter_critical_section_reduce_block(), __kmp_parallel_deo(), __kmp_taskq_eo(), __kmpc_critical(), __kmpc_master(), __kmpc_reduce(), and __kmpc_reduce_nowait().
{
    int tos;
    struct cons_header *p = __kmp_threads[ gtid ]->th.th_cons;
    KMP_ASSERT(gtid == __kmp_get_gtid());
    KE_TRACE(10, ("__kmp_push_sync (gtid=%d)\n", gtid));
#if KMP_USE_DYNAMIC_LOCK
    __kmp_check_sync(gtid, ct, ident, lck, seq);
#else
    __kmp_check_sync(gtid, ct, ident, lck);
#endif
    KE_TRACE(100, (PUSH_MSG(ct, ident)));
    tos = ++ p->stack_top;
    p->stack_data[ tos ].type = ct;
    p->stack_data[ tos ].prev = p->s_top;
    p->stack_data[ tos ].ident = ident;
    p->stack_data[ tos ].name = lck;
    p->s_top = tos;
    KE_DUMP(1000, dump_cons_stack(gtid, p));
}
void __kmp_push_workshare (int gtid, enum cons_type ct, ident_t const * ident)
Definition at line 256 of file kmp_error.c.
Referenced by __kmp_dispatch_init(), __kmp_dist_for_static_init(), __kmp_enter_single(), __kmp_execute_task_from_queue(), __kmp_for_static_init(), and __kmpc_taskq().
{
    int tos;
    struct cons_header *p = __kmp_threads[ gtid ]->th.th_cons;
    KE_TRACE(10, ("__kmp_push_workshare (%d %d)\n", gtid,
      __kmp_get_gtid()));
    __kmp_check_workshare(gtid, ct, ident);
    KE_TRACE(100, (PUSH_MSG(ct, ident)));
    tos = ++p->stack_top;
    p->stack_data[ tos ].type = ct;
    p->stack_data[ tos ].prev = p->w_top;
    p->stack_data[ tos ].ident = ident;
    p->stack_data[ tos ].name = NULL;
    p->w_top = tos;
    KE_DUMP(1000, dump_cons_stack(gtid, p));
}