kmp_environment.h File Reference
Classes
struct __kmp_env_var
struct __kmp_env_blk
Typedefs
typedef struct __kmp_env_var kmp_env_var_t
typedef struct __kmp_env_blk kmp_env_blk_t
Functions
char * __kmp_env_get (char const *name)
void __kmp_env_free (char const **value)
int __kmp_env_exists (char const *name)
void __kmp_env_set (char const *name, char const *value, int overwrite)
void __kmp_env_unset (char const *name)
void __kmp_env_blk_init (kmp_env_blk_t *block, char const *bulk)
void __kmp_env_blk_free (kmp_env_blk_t *block)
void __kmp_env_blk_sort (kmp_env_blk_t *block)
char const * __kmp_env_blk_var (kmp_env_blk_t *block, char const *name)
Typedef Documentation
typedef struct __kmp_env_blk kmp_env_blk_t
Definition at line 67 of file kmp_environment.h.
typedef struct __kmp_env_var kmp_env_var_t
Definition at line 60 of file kmp_environment.h.
Function Documentation
void __kmp_env_blk_free (kmp_env_blk_t * block)
Definition at line 564 of file kmp_environment.c.
Referenced by __kmp_env_initialize(), __kmp_env_print(), and __kmp_env_print_2().
  {
    KMP_INTERNAL_FREE((void *) block->vars);
    KMP_INTERNAL_FREE((void *) block->bulk);
    block->count = 0;
    block->vars = NULL;
    block->bulk = NULL;
} // __kmp_env_blk_free
void __kmp_env_blk_init (kmp_env_blk_t * block, char const * bulk)
Definition at line 504 of file kmp_environment.c.
Referenced by __kmp_env_initialize(), __kmp_env_print(), and __kmp_env_print_2().
  {
    if (bulk != NULL) {
        ___kmp_env_blk_parse_string(block, bulk);
    } else {
        #if KMP_OS_UNIX
            ___kmp_env_blk_parse_unix(block, environ);
        #elif KMP_OS_WINDOWS
            {
                char * mem = GetEnvironmentStrings();
                if (mem == NULL) {
                    DWORD error = GetLastError();
                    __kmp_msg(
                        kmp_ms_fatal,
                        KMP_MSG(CantGetEnvironment),
                        KMP_ERR(error),
                        __kmp_msg_null
                    );
                }; // if
                ___kmp_env_blk_parse_windows(block, mem);
                FreeEnvironmentStrings(mem);
            }
        #else
            #error Unknown or unsupported OS.
        #endif
    }; // if
} // __kmp_env_blk_init
void __kmp_env_blk_sort (kmp_env_blk_t * block)
Definition at line 548 of file kmp_environment.c.
Referenced by __kmp_env_print(), and __kmp_env_print_2().
  {
    qsort(
        (void *) block->vars,
        block->count,
        sizeof(kmp_env_var_t),
        (int (*)(void const *, void const *)) & ___kmp_env_var_cmp
    );
} // __kmp_env_block_sort
char const* __kmp_env_blk_var (kmp_env_blk_t * block, char const * name)
Definition at line 580 of file kmp_environment.c.
Referenced by __kmp_aux_env_initialize(), and __kmp_env_initialize().
  {
    int i;
    for (i = 0; i < block->count; ++ i) {
        if (strcmp(block->vars[ i ].name, name) == 0) {
            return block->vars[ i ].value;
        }; // if
    }; // for
    return NULL;
} // __kmp_env_block_var
int __kmp_env_exists (char const * name)
Definition at line 179 of file kmp_environment.c.
                                      {
    #if KMP_OS_UNIX
        char const * value = getenv(name);
        return ((value == NULL) ? (0) : (1));
    #elif KMP_OS_WINDOWS
        DWORD rc;
        rc = GetEnvironmentVariable(name, NULL, 0);
        if (rc == 0) {
            DWORD error = GetLastError();
            if (error != ERROR_ENVVAR_NOT_FOUND) {
                __kmp_msg(
                    kmp_ms_fatal,
                    KMP_MSG(CantGetEnvVar, name),
                    KMP_ERR(error),
                    __kmp_msg_null
                );
            }; // if
            return 0;
        }; // if
        return 1;
    #else
        #error Unknown or unsupported OS.
    #endif
} // func __kmp_env_exists
void __kmp_env_free (char const ** value)
Definition at line 168 of file kmp_environment.c.
Referenced by __kmp_do_serial_initialize().
                                       {
    KMP_DEBUG_ASSERT(value != NULL);
    KMP_INTERNAL_FREE((void *) * value);
    * value = NULL;
} // func __kmp_env_free
char* __kmp_env_get (char const * name)
Definition at line 96 of file kmp_environment.c.
Referenced by __kmp_do_serial_initialize(), __kmp_register_library_startup(), and __kmp_unregister_library().
                                   {
    char * result = NULL;
    #if KMP_OS_UNIX
        char const * value = getenv(name);
        if (value != NULL) {
            size_t len = KMP_STRLEN(value) + 1;
            result = (char *) KMP_INTERNAL_MALLOC(len);
            if (result == NULL) {
                KMP_FATAL(MemoryAllocFailed);
            }; // if
            KMP_STRNCPY_S(result, len, value, len);
        }; // if
    #elif KMP_OS_WINDOWS
        /*
            We use GetEnvironmentVariable for Windows* OS instead of getenv because the act of
            loading a DLL on Windows* OS makes any user-set environment variables (i.e. with putenv())
            unavailable. getenv() apparently gets a clean copy of the env variables as they existed
            at the start of the run.
            JH 12/23/2002
        */
        DWORD rc;
        rc = GetEnvironmentVariable(name, NULL, 0);
        if (! rc) {
            DWORD error = GetLastError();
            if (error != ERROR_ENVVAR_NOT_FOUND) {
                __kmp_msg(
                    kmp_ms_fatal,
                    KMP_MSG(CantGetEnvVar, name),
                    KMP_ERR(error),
                    __kmp_msg_null
                );
            }; // if
            // Variable is not found, it's ok, just continue.
        } else {
            DWORD len = rc;
            result = (char *) KMP_INTERNAL_MALLOC(len);
            if (result == NULL) {
                KMP_FATAL(MemoryAllocFailed);
            }; // if
            rc = GetEnvironmentVariable(name, result, len);
            if (! rc) {
                // GetEnvironmentVariable() may return 0 if variable is empty.
                // In such a case GetLastError() returns ERROR_SUCCESS.
                DWORD error = GetLastError();
                if (error != ERROR_SUCCESS) {
                    // Unexpected error. The variable should be in the environment,
                    // and buffer should be large enough.
                    __kmp_msg(
                        kmp_ms_fatal,
                        KMP_MSG(CantGetEnvVar, name),
                        KMP_ERR(error),
                        __kmp_msg_null
                    );
                    KMP_INTERNAL_FREE((void *) result);
                    result = NULL;
                }; // if
            }; // if
        }; // if
    #else
        #error Unknown or unsupported OS.
    #endif
    return result;
} // func __kmp_env_get
void __kmp_env_set (char const * name, char const * value, int overwrite)
Definition at line 209 of file kmp_environment.c.
Referenced by __kmp_register_library_startup().
                                                                      {
    #if KMP_OS_UNIX
        int rc = setenv(name, value, overwrite);
        if (rc != 0) {
            // Dead code. I tried to put too many variables into Linux* OS
            // environment on IA-32 architecture. When application consumes
            // more than ~2.5 GB of memory, entire system feels bad. Sometimes
            // application is killed (by OS?), sometimes system stops
            // responding... But this error message never appears. --ln
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(CantSetEnvVar, name),
                KMP_HNT(NotEnoughMemory),
                __kmp_msg_null
            );
        }; // if
    #elif KMP_OS_WINDOWS
        BOOL rc;
        if (! overwrite) {
            rc = GetEnvironmentVariable(name, NULL, 0);
            if (rc) {
                // Variable exists, do not overwrite.
                return;
            }; // if
            DWORD error = GetLastError();
            if (error != ERROR_ENVVAR_NOT_FOUND) {
                __kmp_msg(
                    kmp_ms_fatal,
                    KMP_MSG(CantGetEnvVar, name),
                    KMP_ERR(error),
                    __kmp_msg_null
                );
            }; // if
        }; // if
        rc = SetEnvironmentVariable(name, value);
        if (! rc) {
            DWORD error = GetLastError();
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(CantSetEnvVar, name),
                KMP_ERR(error),
                __kmp_msg_null
            );
        }; // if
    #else
        #error Unknown or unsupported OS.
    #endif
} // func __kmp_env_set
void __kmp_env_unset (char const * name)
Definition at line 263 of file kmp_environment.c.
Referenced by __kmp_register_library_startup(), and __kmp_unregister_library().
                                     {
    #if KMP_OS_UNIX
        unsetenv(name);
    #elif KMP_OS_WINDOWS
        BOOL rc = SetEnvironmentVariable(name, NULL);
        if (! rc) {
            DWORD error = GetLastError();
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(CantSetEnvVar, name),
                KMP_ERR(error),
                __kmp_msg_null
            );
        }; // if
    #else
        #error Unknown or unsupported OS.
    #endif
} // func __kmp_env_unset