kmp_str.c File Reference
#include `kmp_str.h`
*
#include <stdarg.h>
*
#include <stdio.h>
*
#include <stdlib.h>
*
#include `kmp.h`
*
#include `kmp_i18n.h`
*
Macros
#define KMP_STR_BUF_INVARIANT(b)
#define args _args
#define _case(ch, exp)
Functions
void __kmp_str_buf_clear (kmp_str_buf_t *buffer)
void __kmp_str_buf_reserve (kmp_str_buf_t *buffer, int size)
void __kmp_str_buf_detach (kmp_str_buf_t *buffer)
void __kmp_str_buf_free (kmp_str_buf_t *buffer)
void __kmp_str_buf_cat (kmp_str_buf_t *buffer, char const *str, int len)
void __kmp_str_buf_vprint (kmp_str_buf_t *buffer, char const *format, va_list args)
void __kmp_str_buf_print (kmp_str_buf_t *buffer, char const *format,...)
void __kmp_str_buf_print_size (kmp_str_buf_t *buf, size_t size)
void __kmp_str_fname_init (kmp_str_fname_t *fname, char const *path)
void __kmp_str_fname_free (kmp_str_fname_t *fname)
int __kmp_str_fname_match (kmp_str_fname_t const *fname, char const *pattern)
kmp_str_loc_t __kmp_str_loc_init (char const *psource, int init_fname)
void __kmp_str_loc_free (kmp_str_loc_t *loc)
int __kmp_str_eqf (char const *lhs, char const *rhs)
char * __kmp_str_format (char const *format,...)
void __kmp_str_free (char const **str)
int __kmp_str_match (char const *target, int len, char const *data)
int __kmp_str_match_false (char const *data)
int __kmp_str_match_true (char const *data)
void __kmp_str_replace (char *str, char search_for, char replace_with)
void __kmp_str_split (char *str, char delim, char **head, char **tail)
char * __kmp_str_token (char *str, char const *delim, char **buf)
int __kmp_str_to_int (char const *str, char sentinel)
void __kmp_str_to_size (char const *str, size_t *out, size_t dfactor, char const **error)
void __kmp_str_to_uint (char const *str, kmp_uint64 *out, char const **error)
Macro Definition Documentation
#define _case(ch, exp)
Value:
case ch : \
        case ch - ('a' - 'A') : { \
            size_t shift = (exp) * 10; \
            ++ i; \
            if (shift < sizeof(size_t) * 8) { \
                factor = (size_t)(1) << shift; \
            } else { \
                overflow = 1; \
            }; \
        } break;
Referenced by __kmp_str_to_size().
#define args _args
Referenced by __itt_report_error(), __kmp_fork_call(), __kmp_msg(), __kmp_msg_format(), __kmp_read_from_file(), __kmp_str_buf_print(), and __kmp_str_format().
#define KMP_STR_BUF_INVARIANT(b)
Value:
{
      \
        KMP_DEBUG_ASSERT((b)->str != NULL);
                        \
        KMP_DEBUG_ASSERT((b)->size >= sizeof((b)->bulk));
                         \
        KMP_DEBUG_ASSERT((b)->size % sizeof((b)->bulk) == 0);
                         \
        KMP_DEBUG_ASSERT((unsigned)(b)->used < (b)->
      size); \
        KMP_DEBUG_ASSERT((b)->size == sizeof((b)->bulk) ? (b)->
      str == & (b)->bulk[ 0 ] : 1); \
        KMP_DEBUG_ASSERT((b)->size > sizeof((b)->bulk) ? (b)->
      str != & (b)->bulk[ 0 ] : 1); \
    }
Definition at line 70 of file kmp_str.c.
Referenced by __kmp_str_buf_cat(), __kmp_str_buf_clear(), __kmp_str_buf_detach(), __kmp_str_buf_free(), __kmp_str_buf_reserve(), and __kmp_str_buf_vprint().
Function Documentation
void __kmp_str_buf_cat (kmp_str_buf_t * buffer, char const * str, int len)
Definition at line 167 of file kmp_str.c.
Referenced by __kmp_msg(), and __kmp_msg_format().
  {
    KMP_STR_BUF_INVARIANT(buffer);
    KMP_DEBUG_ASSERT(str != NULL);
    KMP_DEBUG_ASSERT(len >= 0);
    __kmp_str_buf_reserve(buffer, buffer->used + len + 1);
    KMP_MEMCPY(buffer->str + buffer->used, str, len);
    buffer->str[ buffer->used + len ] = 0;
    buffer->used += len;
    KMP_STR_BUF_INVARIANT(buffer);
} // __kmp_str_buf_cat
void __kmp_str_buf_clear (kmp_str_buf_t * buffer)
Definition at line 81 of file kmp_str.c.
Referenced by __kmp_vprintf().
  {
    KMP_STR_BUF_INVARIANT(buffer);
    if (buffer->used > 0) {
        buffer->used = 0;
        buffer->str[ 0 ] = 0;
    }; // if
    KMP_STR_BUF_INVARIANT(buffer);
} // __kmp_str_buf_clear
void __kmp_str_buf_detach (kmp_str_buf_t * buffer)
Definition at line 133 of file kmp_str.c.
Referenced by __kmp_msg_format().
  {
    KMP_STR_BUF_INVARIANT(buffer);
    // If internal bulk is used, allocate memory and copy it.
    if (buffer->size <= sizeof(buffer->bulk)) {
        buffer->str = (char *) KMP_INTERNAL_MALLOC(buffer->
      size);
        if (buffer->str == NULL) {
                KMP_FATAL(MemoryAllocFailed);
        }; // if
        KMP_MEMCPY_S(buffer->str, buffer->size, buffer->bulk, buffer->
      used + 1);
    }; // if
} // __kmp_str_buf_detach
void __kmp_str_buf_free (kmp_str_buf_t * buffer)
Definition at line 152 of file kmp_str.c.
Referenced by __kmp_do_serial_initialize(), __kmp_env_print(), __kmp_env_print_2(), __kmp_msg(), __kmp_pragma(), __kmp_print_version_1(), __kmp_runtime_initialize(), __kmp_stg_parse_int(), __kmp_stg_parse_size(), __kmp_stg_print_num_threads(), and __kmp_stg_print_place_threads().
  {
    KMP_STR_BUF_INVARIANT(buffer);
    if (buffer->size > sizeof(buffer->bulk)) {
        KMP_INTERNAL_FREE(buffer->str);
    }; // if
    buffer->str = buffer->bulk;
    buffer->size = sizeof(buffer->bulk);
    buffer->used = 0;
    KMP_STR_BUF_INVARIANT(buffer);
} // __kmp_str_buf_free
void __kmp_str_buf_print (kmp_str_buf_t * buffer, char const * format, ...)
Definition at line 250 of file kmp_str.c.
Referenced by __kmp_env_print(), __kmp_env_print_2(), __kmp_i18n_dump_catalog(), __kmp_pragma(), __kmp_print_version_1(), __kmp_runtime_initialize(), __kmp_stg_parse_int(), __kmp_stg_print_barrier_branch_bit(), __kmp_stg_print_barrier_pattern(), __kmp_stg_print_bool(), __kmp_stg_print_cpuinfo_file(), __kmp_stg_print_force_reduction(), __kmp_stg_print_int(), __kmp_stg_print_kmp_dynamic_mode(), __kmp_stg_print_monitor_stacksize(), __kmp_stg_print_num_threads(), __kmp_stg_print_omp_schedule(), __kmp_stg_print_place_threads(), __kmp_stg_print_proc_bind(), __kmp_stg_print_schedule(), __kmp_stg_print_size(), __kmp_stg_print_stacksize(), __kmp_stg_print_str(), __kmp_stg_print_uint64(), __kmp_str_buf_print_size(), and __kmp_vprintf().
  {
    va_list args;
    va_start(args, format);
    __kmp_str_buf_vprint(buffer, format, args);
    va_end(args);
} // __kmp_str_buf_print
void __kmp_str_buf_print_size (kmp_str_buf_t * buf, size_t size)
Definition at line 270 of file kmp_str.c.
Referenced by __kmp_stg_parse_size(), __kmp_stg_print_monitor_stacksize(), __kmp_stg_print_size(), and __kmp_stg_print_stacksize().
  {
    char const * names[] = { "", "k", "M", "G", "T", "P", "E", "Z", "Y" };
    int const units = sizeof(names) / sizeof(char const *);
    int u = 0;
    if (size > 0) {
        while ((size % 1024 == 0) && (u + 1 < units)) {
            size = size / 1024;
            ++ u;
        }; // while
    }; // if
    __kmp_str_buf_print(buf, "%" KMP_SIZE_T_SPEC "%s", size, names[ u ]);
} // __kmp_str_buf_print_size
void __kmp_str_buf_reserve (kmp_str_buf_t * buffer, int size)
Definition at line 94 of file kmp_str.c.
Referenced by __kmp_runtime_initialize(), __kmp_str_buf_cat(), and __kmp_str_buf_vprint().
  {
    KMP_STR_BUF_INVARIANT(buffer);
    KMP_DEBUG_ASSERT(size >= 0);
    if (buffer->size < (unsigned int)size) {
        // Calculate buffer size.
        do {
            buffer->size *= 2;
        } while (buffer->size < (unsigned int)size);
        // Enlarge buffer.
        if (buffer->str == & buffer->bulk[ 0 ]) {
            buffer->str = (char *) KMP_INTERNAL_MALLOC(buffer->
      size);
            if (buffer->str == NULL) {
                KMP_FATAL(MemoryAllocFailed);
            }; // if
            KMP_MEMCPY_S(buffer->str, buffer->size, buffer->
      bulk, buffer->used + 1);
        } else {
            buffer->str = (char *) KMP_INTERNAL_REALLOC(buffer->
      str, buffer->size);
            if (buffer->str == NULL) {
                KMP_FATAL(MemoryAllocFailed);
            }; // if
        }; // if
    }; // if
    KMP_DEBUG_ASSERT(buffer->size > 0);
    KMP_DEBUG_ASSERT(buffer->size >= (unsigned)size);
    KMP_STR_BUF_INVARIANT(buffer);
} // __kmp_str_buf_reserve
void __kmp_str_buf_vprint (kmp_str_buf_t * buffer, char const * format, va_list args)
Definition at line 184 of file kmp_str.c.
Referenced by __kmp_msg_format(), __kmp_str_buf_print(), and __kmp_vprintf().
  {
    KMP_STR_BUF_INVARIANT(buffer);
    for (; ;) {
        int const free = buffer->size - buffer->used;
        int rc;
        int size;
        // Try to format string.
        {
            /*
                On Linux* OS Intel(R) 64, vsnprintf() modifies args argument, so vsnprintf() crashes if it
                is called for the second time with the same args. To prevent the crash, we have to
                pass a fresh intact copy of args to vsnprintf() on each iteration.
                Unfortunately, standard va_copy() macro is not available on Windows* OS. However, it
                seems vsnprintf() does not modify args argument on Windows* OS.
            */
            #if ! KMP_OS_WINDOWS
                va_list _args;
                __va_copy(_args, args); // Make copy of args.
                #define args _args // Substitute args with its copy, _args.
            #endif // KMP_OS_WINDOWS
            rc = KMP_VSNPRINTF(buffer->str + buffer->used, free, format,
      args);
            #if ! KMP_OS_WINDOWS
                #undef args // Remove substitution.
                va_end(_args);
            #endif // KMP_OS_WINDOWS
        }
        // No errors, string has been formatted.
        if (rc >= 0 && rc < free) {
            buffer->used += rc;
            break;
        }; // if
        // Error occurred, buffer is too small.
        if (rc >= 0) {
            // C99-conforming implementation of vsnprintf returns required buffer size.
            size = buffer->used + rc + 1;
        } else {
            // Older implementations just return -1. Double buffer size.
            size = buffer->size * 2;
        }; // if
        // Enlarge buffer.
        __kmp_str_buf_reserve(buffer, size);
        // And try again.
    }; // forever
    KMP_DEBUG_ASSERT(buffer->size > 0);
    KMP_STR_BUF_INVARIANT(buffer);
} // __kmp_str_buf_vprint
int __kmp_str_eqf (char const * lhs, char const * rhs)
Definition at line 439 of file kmp_str.c.
Referenced by __kmp_str_fname_match().
  {
    int result;
    #if KMP_OS_WINDOWS
        result = (_stricmp(lhs, rhs) == 0);
    #else
        result = (strcmp(lhs, rhs) == 0);
    #endif
    return result;
} // __kmp_str_eqf
void __kmp_str_fname_free (kmp_str_fname_t * fname)
Definition at line 326 of file kmp_str.c.
Referenced by __kmp_str_fname_match(), and __kmp_str_loc_free().
  {
    __kmp_str_free((char const **)(& fname->path));
    __kmp_str_free((char const **)(& fname->dir));
    __kmp_str_free((char const **)(& fname->base));
} // kmp_str_fname_free
void __kmp_str_fname_init (kmp_str_fname_t * fname, char const * path)
Definition at line 291 of file kmp_str.c.
Referenced by __kmp_str_fname_match(), and __kmp_str_loc_init().
  {
    fname->path = NULL;
    fname->dir = NULL;
    fname->base = NULL;
    if (path != NULL) {
        char * slash = NULL; // Pointer to the last character of dir.
        char * base = NULL; // Pointer to the beginning of basename.
        fname->path = __kmp_str_format("%s", path);
            // Original code used strdup() function to copy a string, but on Windows* OS Intel(R) 64 it
            // causes assertioon id debug heap, so I had to replace strdup with __kmp_str_format().
        if (KMP_OS_WINDOWS) {
            __kmp_str_replace(fname->path, '\\', '/');
        }; // if
        fname->dir = __kmp_str_format("%s", fname->path);
        slash = strrchr(fname->dir, '/');
        if (KMP_OS_WINDOWS && slash == NULL) { // On Windows* OS, if slash not
       found,
            char first = TOLOWER(fname->dir[ 0 ]); // look for drive.
            if ('a' <= first && first <= 'z' && fname->dir[ 1 ] == ':') {
                slash = & fname->dir[ 1 ];
            }; // if
        }; // if
        base = (slash == NULL ? fname->dir : slash + 1);
        fname->base = __kmp_str_format("%s", base); // Copy basename
        * base = 0; // and truncate dir.
    }; // if
} // kmp_str_fname_init
int __kmp_str_fname_match (kmp_str_fname_t const * fname, char const * pattern)
Definition at line 336 of file kmp_str.c.
  {
    int dir_match = 1;
    int base_match = 1;
    if (pattern != NULL) {
        kmp_str_fname_t ptrn;
        __kmp_str_fname_init(& ptrn, pattern);
        dir_match =
            strcmp(ptrn.dir, "*/") == 0
            ||
            (fname->dir != NULL && __kmp_str_eqf(fname->dir, ptrn.
      dir));
        base_match =
            strcmp(ptrn.base, "*") == 0
            ||
            (fname->base != NULL && __kmp_str_eqf(fname->base, ptrn.
      base));
        __kmp_str_fname_free(& ptrn);
    }; // if
    return dir_match && base_match;
} // __kmp_str_fname_match
char* __kmp_str_format (char const * format, ...)
Definition at line 484 of file kmp_str.c.
Referenced by ___kmp_env_blk_parse_string(), __kmp_dispatch_deo(), __kmp_dispatch_finish(), __kmp_dispatch_init(), __kmp_dispatch_next(), __kmp_dist_for_static_init(), __kmp_dist_get_bounds(), __kmp_for_static_init(), __kmp_is_address_mapped(), __kmp_msg_error_mesg(), __kmp_reg_status_name(), __kmp_register_library_startup(), __kmp_str_fname_init(), __kmp_str_loc_init(), __kmp_team_static_init(), and sys_error().
  {
    va_list args;
    int size = 512;
    char * buffer = NULL;
    int rc;
    // Allocate buffer.
    buffer = (char *) KMP_INTERNAL_MALLOC(size);
    if (buffer == NULL) {
        KMP_FATAL(MemoryAllocFailed);
    }; // if
    for (; ;) {
        // Try to format string.
        va_start(args, format);
        rc = KMP_VSNPRINTF(buffer, size, format, args);
        va_end(args);
        // No errors, string has been formatted.
        if (rc >= 0 && rc < size) {
            break;
        }; // if
        // Error occurred, buffer is too small.
        if (rc >= 0) {
            // C99-conforming implementation of vsnprintf returns required buffer size.
            size = rc + 1;
        } else {
            // Older implementations just return -1.
            size = size * 2;
        }; // if
        // Enlarge buffer and try again.
        buffer = (char *) KMP_INTERNAL_REALLOC(buffer, size);
        if (buffer == NULL) {
            KMP_FATAL(MemoryAllocFailed);
        }; // if
    }; // forever
    return buffer;
} // func __kmp_str_format
void __kmp_str_free (char const ** str)
Definition at line 535 of file kmp_str.c.
Referenced by __kmp_dispatch_deo(), __kmp_dispatch_finish(), __kmp_dispatch_init(), __kmp_dispatch_next(), __kmp_dist_for_static_init(), __kmp_dist_get_bounds(), __kmp_for_static_init(), __kmp_str_fname_free(), and __kmp_team_static_init().
  {
    KMP_DEBUG_ASSERT(str != NULL);
    KMP_INTERNAL_FREE((void *) * str);
    * str = NULL;
} // func __kmp_str_free
void __kmp_str_loc_free (kmp_str_loc_t * loc)
Definition at line 419 of file kmp_str.c.
Referenced by __kmp_cleanup_user_locks().
  {
    __kmp_str_fname_free(& loc->fname);
    KMP_INTERNAL_FREE(loc->_bulk);
    loc->_bulk = NULL;
    loc->file = NULL;
    loc->func = NULL;
} // kmp_str_loc_free
kmp_str_loc_t __kmp_str_loc_init (char const * psource, int init_fname)
Definition at line 364 of file kmp_str.c.
Referenced by __kmp_cleanup_user_locks().
  {
    kmp_str_loc_t loc;
    loc._bulk = NULL;
    loc.file = NULL;
    loc.func = NULL;
    loc.line = 0;
    loc.col = 0;
    if (psource != NULL) {
        char * str = NULL;
        char * dummy = NULL;
        char * line = NULL;
        char * col = NULL;
        // Copy psource to keep it intact.
        loc._bulk = __kmp_str_format("%s", psource);
        // Parse psource string: ";file;func;line;col;;"
        str = loc._bulk;
        __kmp_str_split(str, ';', & dummy, & str);
        __kmp_str_split(str, ';', & loc.file, & str);
        __kmp_str_split(str, ';', & loc.func, & str);
        __kmp_str_split(str, ';', & line, & str);
        __kmp_str_split(str, ';', & col, & str);
        // Convert line and col into numberic values.
        if (line != NULL) {
            loc.line = atoi(line);
            if (loc.line < 0) {
                loc.line = 0;
            }; // if
        }; // if
        if (col != NULL) {
            loc.col = atoi(col);
            if (loc.col < 0) {
                loc.col = 0;
            }; // if
        }; // if
    }; // if
    __kmp_str_fname_init(& loc.fname, init_fname ? loc.
      file : NULL);
    return loc;
} // kmp_str_loc_init
int __kmp_str_match (char const * target, int len, char const * data)
Definition at line 550 of file kmp_str.c.
Referenced by __kmp_convert_to_milliseconds(), __kmp_stg_parse_barrier_pattern(), __kmp_stg_parse_force_reduction(), __kmp_stg_parse_kmp_dynamic_mode(), __kmp_stg_parse_lock_kind(), __kmp_stg_parse_omp_display_env(), __kmp_stg_parse_storage_map(), __kmp_stg_parse_wait_policy(), __kmp_str_match_false(), and __kmp_str_match_true().
  {
    int i;
    if (target == NULL || data == NULL) {
        return FALSE;
    }; // if
    for (i = 0; target[i] && data[i]; ++ i) {
        if (TOLOWER(target[i]) != TOLOWER(data[i])) {
            return FALSE;
        }; // if
    }; // for i
    return ((len > 0) ? i >= len : (! target[i] && (len || ! data[i])));
} // __kmp_str_match
int __kmp_str_match_false (char const * data)
Definition at line 569 of file kmp_str.c.
Referenced by __kmp_ignore_mppbeg(), __kmp_ignore_mppend(), and __kmp_stg_parse_bool().
                                           {
    int result =
        __kmp_str_match("false", 1, data) ||
        __kmp_str_match("off", 2, data) ||
        __kmp_str_match("0", 1, data) ||
        __kmp_str_match(".false.", 2, data) ||
        __kmp_str_match(".f.", 2, data) ||
        __kmp_str_match("no", 1, data);
    return result;
} // __kmp_str_match_false
int __kmp_str_match_true (char const * data)
Definition at line 582 of file kmp_str.c.
Referenced by __kmp_do_serial_initialize(), __kmp_register_library_startup(), __kmp_stg_parse_bool(), and kmp_stats_output_module::init().
                                          {
    int result =
        __kmp_str_match("true", 1, data) ||
        __kmp_str_match("on", 2, data) ||
        __kmp_str_match("1", 1, data) ||
        __kmp_str_match(".true.", 2, data) ||
        __kmp_str_match(".t.", 2, data) ||
        __kmp_str_match("yes", 1, data);
    return result;
} // __kmp_str_match_true
void __kmp_str_replace (char * str, char search_for, char replace_with)
Definition at line 594 of file kmp_str.c.
Referenced by __kmp_str_fname_init().
  {
    char * found = NULL;
    found = strchr(str, search_for);
    while (found) {
        * found = replace_with;
        found = strchr(found + 1, search_for);
    }; // while
} // __kmp_str_replace
void __kmp_str_split (char * str, char delim, char ** head, char ** tail)
Definition at line 612 of file kmp_str.c.
Referenced by ___kmp_env_blk_parse_string(), ___kmp_env_blk_parse_unix(), __kmp_pragma(), __kmp_register_library_startup(), and __kmp_str_loc_init().
  {
    char * h = str;
    char * t = NULL;
    if (str != NULL) {
        char * ptr = strchr(str, delim);
        if (ptr != NULL) {
            * ptr = 0;
            t = ptr + 1;
        }; // if
    }; // if
    if (head != NULL) {
        * head = h;
    }; // if
    if (tail != NULL) {
        * tail = t;
    }; // if
} // __kmp_str_split
int __kmp_str_to_int (char const * str, char sentinel)
Definition at line 668 of file kmp_str.c.
Referenced by __kmp_parse_nested_num_threads(), __kmp_stg_parse_barrier_branch_bit(), __kmp_stg_parse_omp_schedule(), __kmp_stg_parse_place_threads(), and __kmp_stg_parse_proc_bind().
  {
    int result, factor;
    char const * t;
    result = 0;
    for (t = str; *t != '\0'; ++t) {
        if (*t < '0' || *t > '9')
            break;
        result = (result * 10) + (*t - '0');
    }
    switch (*t) {
    case '\0': /* the current default for no suffix is bytes */
        factor = 1;
        break;
    case 'b': case 'B': /* bytes */
        ++t;
        factor = 1;
        break;
    case 'k': case 'K': /* kilo-bytes */
        ++t;
        factor = 1024;
        break;
    case 'm': case 'M': /* mega-bytes */
        ++t;
        factor = (1024 * 1024);
        break;
    default:
        if(*t != sentinel)
            return (-1);
        t = "";
        factor = 1;
    }
    if (result > (INT_MAX / factor))
        result = INT_MAX;
    else
        result *= factor;
    return (*t != 0 ? 0 : result);
} // __kmp_str_to_int
void __kmp_str_to_size (char const * str, size_t * out, size_t dfactor, char const ** error)
Definition at line 725 of file kmp_str.c.
Referenced by __kmp_stg_parse_size().
  {
    size_t value = 0;
    size_t factor = 0;
    int overflow = 0;
    int i = 0;
    int digit;
    KMP_DEBUG_ASSERT(str != NULL);
    // Skip spaces.
    while (str[ i ] == ' ' || str[ i ] == '\t') {
        ++ i;
    }; // while
    // Parse number.
    if (str[ i ] < '0' || str[ i ] > '9') {
        * error = KMP_I18N_STR(NotANumber);
        return;
    }; // if
    do {
        digit = str[ i ] - '0';
        overflow = overflow || (value > (KMP_SIZE_T_MAX - digit) / 10);
        value = (value * 10) + digit;
        ++ i;
    } while (str[ i ] >= '0' && str[ i ] <= '9');
    // Skip spaces.
    while (str[ i ] == ' ' || str[ i ] == '\t') {
        ++ i;
    }; // while
    // Parse unit.
    #define _case(ch, exp) \
        case ch : \
        case ch - ('a' - 'A') : { \
            size_t shift = (exp) * 10; \
            ++ i; \
            if (shift < sizeof(size_t) * 8) { \
                factor = (size_t)(1) << shift; \
            } else { \
                overflow = 1; \
            }; \
        } break;
    switch (str[ i ]) {
        _case('k', 1); // Kilo
        _case('m', 2); // Mega
        _case('g', 3); // Giga
        _case('t', 4); // Tera
        _case('p', 5); // Peta
        _case('e', 6); // Exa
        _case('z', 7); // Zetta
        _case('y', 8); // Yotta
        // Oops. No more units...
    }; // switch
    #undef _case
    if (str[ i ] == 'b' || str[ i ] == 'B') { // Skip optional "b".
        if (factor == 0) {
            factor = 1;
        }
        ++ i;
    }; // if
    if (! (str[ i ] == ' ' || str[ i ] == '\t' || str[ i ] == 0)) { // Bad unit
        * error = KMP_I18N_STR(BadUnit);
        return;
    }; // if
    if (factor == 0) {
        factor = dfactor;
    }
    // Apply factor.
    overflow = overflow || (value > (KMP_SIZE_T_MAX / factor));
    value *= factor;
    // Skip spaces.
    while (str[ i ] == ' ' || str[ i ] == '\t') {
        ++ i;
    }; // while
    if (str[ i ] != 0) {
        * error = KMP_I18N_STR(IllegalCharacters);
        return;
    }; // if
    if (overflow) {
        * error = KMP_I18N_STR(ValueTooLarge);
        * out = KMP_SIZE_T_MAX;
        return;
    }; // if
    * error = NULL;
    * out = value;
} // __kmp_str_to_size
void __kmp_str_to_uint (char const * str, kmp_uint64 * out, char const ** error)
Definition at line 829 of file kmp_str.c.
Referenced by __kmp_stg_parse_int().
  {
    size_t value = 0;
    int overflow = 0;
    int i = 0;
    int digit;
    KMP_DEBUG_ASSERT(str != NULL);
    // Skip spaces.
    while (str[ i ] == ' ' || str[ i ] == '\t') {
        ++ i;
    }; // while
    // Parse number.
    if (str[ i ] < '0' || str[ i ] > '9') {
        * error = KMP_I18N_STR(NotANumber);
        return;
    }; // if
    do {
        digit = str[ i ] - '0';
        overflow = overflow || (value > (KMP_SIZE_T_MAX - digit) / 10);
        value = (value * 10) + digit;
        ++ i;
    } while (str[ i ] >= '0' && str[ i ] <= '9');
    // Skip spaces.
    while (str[ i ] == ' ' || str[ i ] == '\t') {
        ++ i;
    }; // while
    if (str[ i ] != 0) {
        * error = KMP_I18N_STR(IllegalCharacters);
        return;
    }; // if
    if (overflow) {
        * error = KMP_I18N_STR(ValueTooLarge);
        * out = (kmp_uint64) -1;
        return;
    }; // if
    * error = NULL;
    * out = value;
} // __kmp_str_to_unit
char* __kmp_str_token (char * str, char const * delim, char ** buf)
Definition at line 639 of file kmp_str.c.
Referenced by ___kmp_env_blk_parse_string().
  {
    char * token = NULL;
    #if KMP_OS_WINDOWS
        // On Windows* OS there is no strtok_r() function. Let us implement it.
        if (str != NULL) {
            * buf = str; // First call, initialize buf.
        }; // if
        * buf += strspn(* buf, delim); // Skip leading delimiters.
        if (** buf != 0) { // Rest of the string is not yet empty.
            token = * buf; // Use it as result.
            * buf += strcspn(* buf, delim); // Skip non-delimiters.
            if (** buf != 0) { // Rest of the string is not yet empty.
                ** buf = 0; // Terminate token here.
                * buf += 1; // Advance buf to start with the next token next time.
            }; // if
        }; // if
    #else
        // On Linux* OS and OS X*, strtok_r() is available. Let us use it.
        token = strtok_r(str, delim, buf);
    #endif
    return token;
}; // __kmp_str_token