kmp_settings.h File Reference
Macros
#define KMP_STR_BUF_PRINT_NAME __kmp_str_buf_print(buffer, ` %s %s`, KMP_I18N_STR(Host), name)
#define KMP_STR_BUF_PRINT_NAME_EX(x) __kmp_str_buf_print(buffer, ` %s %s='`, KMP_I18N_STR(Host), x)
#define KMP_STR_BUF_PRINT_BOOL __kmp_str_buf_print(buffer, ` %s %s='%s'\n`, KMP_I18N_STR(Host), name, value ? `TRUE` : `FALSE`);
#define KMP_STR_BUF_PRINT_INT __kmp_str_buf_print(buffer, ` %s %s='%d'\n`, KMP_I18N_STR(Host), name, value)
#define KMP_STR_BUF_PRINT_UINT64 __kmp_str_buf_print(buffer, ` %s %s='%` KMP_UINT64_SPEC `'\n`, KMP_I18N_STR(Host), name, value);
#define KMP_STR_BUF_PRINT_STR __kmp_str_buf_print(buffer, ` %s %s='%s'\n`, KMP_I18N_STR(Host), name, value)
Functions
void __kmp_reset_global_vars (void)
void __kmp_env_initialize (char const *)
void __kmp_env_print ()
void __kmp_env_print_2 ()
int __kmp_initial_threads_capacity (int req_nproc)
void __kmp_init_dflt_team_nth ()
int __kmp_convert_to_milliseconds (char const *)
int __kmp_default_tp_capacity (int, int, int)
Macro Definition Documentation
#define KMP_STR_BUF_PRINT_BOOL __kmp_str_buf_print(buffer, ` %s %s='%s'\n`, KMP_I18N_STR(Host), name, value ? `TRUE` : `FALSE`);
Definition at line 41 of file kmp_settings.h.
Referenced by __kmp_stg_print_bool().
#define KMP_STR_BUF_PRINT_INT __kmp_str_buf_print(buffer, ` %s %s='%d'\n`, KMP_I18N_STR(Host), name, value)
Definition at line 42 of file kmp_settings.h.
Referenced by __kmp_stg_print_int().
#define KMP_STR_BUF_PRINT_NAME __kmp_str_buf_print(buffer, ` %s %s`, KMP_I18N_STR(Host), name)
Definition at line 39 of file kmp_settings.h.
Referenced by __kmp_stg_print_cpuinfo_file(), __kmp_stg_print_force_reduction(), __kmp_stg_print_monitor_stacksize(), __kmp_stg_print_num_threads(), and __kmp_stg_print_proc_bind().
#define KMP_STR_BUF_PRINT_NAME_EX(x) __kmp_str_buf_print(buffer, ` %s %s='`, KMP_I18N_STR(Host), x)
Definition at line 40 of file kmp_settings.h.
Referenced by __kmp_stg_print_barrier_branch_bit(), __kmp_stg_print_barrier_pattern(), __kmp_stg_print_monitor_stacksize(), __kmp_stg_print_omp_schedule(), __kmp_stg_print_place_threads(), __kmp_stg_print_schedule(), __kmp_stg_print_size(), and __kmp_stg_print_stacksize().
#define KMP_STR_BUF_PRINT_STR __kmp_str_buf_print(buffer, ` %s %s='%s'\n`, KMP_I18N_STR(Host), name, value)
Definition at line 44 of file kmp_settings.h.
Referenced by __kmp_stg_print_str().
#define KMP_STR_BUF_PRINT_UINT64 __kmp_str_buf_print(buffer, ` %s %s='%` KMP_UINT64_SPEC `'\n`, KMP_I18N_STR(Host), name, value);
Definition at line 43 of file kmp_settings.h.
Referenced by __kmp_stg_print_uint64().
Function Documentation
int __kmp_convert_to_milliseconds (char const *)
Definition at line 157 of file kmp_settings.c.
Referenced by __kmp_stg_parse_blocktime().
{
    int ret, nvalues, factor;
    char mult, extra;
    double value;
    if (data == NULL) return (-1);
    if (__kmp_str_match("infinit", -1, data)) return (INT_MAX);
    value = (double) 0.0;
    mult = '\0';
    nvalues = KMP_SSCANF (data, "%lf%c%c", &value, &mult, &extra);
    if (nvalues < 1) return (-1);
    if (nvalues == 1) mult = '\0';
    if (nvalues == 3) return (-1);
    if (value < 0) return (-1);
    switch (mult) {
    case '\0':
        /* default is milliseconds */
        factor = 1;
        break;
    case 's': case 'S':
        factor = 1000;
        break;
    case 'm': case 'M':
        factor = 1000 * 60;
        break;
    case 'h': case 'H':
        factor = 1000 * 60 * 60;
        break;
    case 'd': case 'D':
        factor = 1000 * 24 * 60 * 60;
        break;
    default:
        return (-1);
    }
    if (value >= ((INT_MAX-1) / factor))
        ret = INT_MAX-1; /* Don't allow infinite value here */
    else
        ret = (int) (value * (double) factor); /* truncate to int */
    return ret;
}
int __kmp_default_tp_capacity (int , int , int)
Definition at line 531 of file kmp_settings.c.
Referenced by __kmp_do_serial_initialize().
                                                                                  {
    int nth = 128;
    if(all_threads_specified)
        return max_nth;
    /* MIN(MAX (128, 4 * $OMP_NUM_THREADS, 4 * omp_get_num_procs()), __kmp_max_nth) */
    if (nth < (4 * req_nproc))
        nth = (4 * req_nproc);
    if (nth < (4 * __kmp_xproc))
        nth = (4 * __kmp_xproc);
    if (nth > __kmp_max_nth)
        nth = __kmp_max_nth;
    return nth;
}
void __kmp_env_initialize (char const *)
Definition at line 4997 of file kmp_settings.c.
Referenced by __kmp_aux_set_defaults(), and __kmp_do_serial_initialize().
                                            {
    kmp_env_blk_t block;
    int i;
    __kmp_stg_init();
    // Hack!!!
    if (string == NULL) {
        // __kmp_max_nth = __kmp_sys_max_nth;
        __kmp_threads_capacity =
      __kmp_initial_threads_capacity(
      __kmp_dflt_team_nth_ub);
    }; // if
    __kmp_env_blk_init(& block, string);
    //
    // update the set flag on all entries that have an env var
    //
    for (i = 0; i < block.count; ++ i) {
        if ((block.vars[ i ].name == NULL)
          || (*block.vars[ i ].name == '\0')) {
            continue;
        }
        if (block.vars[ i ].value == NULL) {
            continue;
        }
        kmp_setting_t * setting = __kmp_stg_find(block.
      vars[ i ].name);
        if (setting != NULL) {
            setting->set = 1;
        }
    }; // for i
    // Special case. If we parse environment, not a string, process KMP_WARNINGS first.
    if (string == NULL) {
        char const * name = "KMP_WARNINGS";
        char const * value = __kmp_env_blk_var(& block, name);
        __kmp_stg_parse(name, value);
    }; // if
#if KMP_AFFINITY_SUPPORTED
    //
    // Special case. KMP_AFFINITY is not a rival to other affinity env vars
    // if no affinity type is specified. We want to allow
    // KMP_AFFINITY=[no],verbose/[no]warnings/etc. to be enabled when
    // specifying the affinity type via GOMP_CPU_AFFINITY or the OMP 4.0
    // affinity mechanism.
    //
    __kmp_affinity_notype = NULL;
    char const *aff_str = __kmp_env_blk_var(& block, "KMP_AFFINITY");
    if (aff_str != NULL) {
        //
        // Check if the KMP_AFFINITY type is specified in the string.
        // We just search the string for "compact", "scatter", etc.
        // without really parsing the string. The syntax of the
        // KMP_AFFINITY env var is such that none of the affinity
        // type names can appear anywhere other that the type
        // specifier, even as substrings.
        //
        // I can't find a case-insensitive version of strstr on Windows* OS.
        // Use the case-sensitive version for now.
        //
# if KMP_OS_WINDOWS
# define FIND strstr
# else
# define FIND strcasestr
# endif
        if ((FIND(aff_str, "none") == NULL)
          && (FIND(aff_str, "physical") == NULL)
          && (FIND(aff_str, "logical") == NULL)
          && (FIND(aff_str, "compact") == NULL)
          && (FIND(aff_str, "scatter") == NULL)
          && (FIND(aff_str, "explicit") == NULL)
          && (FIND(aff_str, "balanced") == NULL)
          && (FIND(aff_str, "disabled") == NULL)) {
            __kmp_affinity_notype = __kmp_stg_find("KMP_AFFINITY");
        }
        else {
            //
            // A new affinity type is specified.
            // Reset the affinity flags to their default values,
            // in case this is called from kmp_set_defaults().
            //
            __kmp_affinity_type = affinity_default;
            __kmp_affinity_gran = affinity_gran_default;
            __kmp_affinity_top_method = affinity_top_method_default;
            __kmp_affinity_respect_mask = affinity_respect_mask_default;
        }
# undef FIND
#if OMP_40_ENABLED
        //
        // Also reset the affinity flags if OMP_PROC_BIND is specified.
        //
        aff_str = __kmp_env_blk_var(& block, "OMP_PROC_BIND");
        if (aff_str != NULL) {
            __kmp_affinity_type = affinity_default;
            __kmp_affinity_gran = affinity_gran_default;
            __kmp_affinity_top_method = affinity_top_method_default;
            __kmp_affinity_respect_mask = affinity_respect_mask_default;
        }
#endif /* OMP_40_ENABLED */
    }
#endif /* KMP_AFFINITY_SUPPORTED */
#if OMP_40_ENABLED
    //
    // Set up the nested proc bind type vector.
    //
    if (__kmp_nested_proc_bind.bind_types == NULL) {
        __kmp_nested_proc_bind.bind_types = (
      kmp_proc_bind_t *)
          KMP_INTERNAL_MALLOC(sizeof(kmp_proc_bind_t));
        if (__kmp_nested_proc_bind.bind_types == NULL) {
            KMP_FATAL(MemoryAllocFailed);
        }
        __kmp_nested_proc_bind.size = 1;
        __kmp_nested_proc_bind.used = 1;
# if KMP_AFFINITY_SUPPORTED
        __kmp_nested_proc_bind.bind_types[0] =
      proc_bind_default;
# else
        // default proc bind is false if affinity not supported
        __kmp_nested_proc_bind.bind_types[0] =
      proc_bind_false;
# endif
    }
#endif /* OMP_40_ENABLED */
    //
    // Now process all of the settings.
    //
    for (i = 0; i < block.count; ++ i) {
        __kmp_stg_parse(block.vars[ i ].name, block.vars[ i ].
      value);
    }; // for i
    //
    // If user locks have been allocated yet, don't reset the lock vptr table.
    //
    if (! __kmp_init_user_locks) {
        if (__kmp_user_lock_kind == lk_default) {
            __kmp_user_lock_kind = lk_queuing;
        }
#if KMP_USE_DYNAMIC_LOCK
        __kmp_init_dynamic_user_locks();
#else
        __kmp_set_user_lock_vptrs(__kmp_user_lock_kind);
#endif
    }
    else {
        KMP_DEBUG_ASSERT(string != NULL); // kmp_set_defaults() was called
        KMP_DEBUG_ASSERT(__kmp_user_lock_kind !=
      lk_default);
        // Binds lock functions again to follow the transition between different
        // KMP_CONSISTENCY_CHECK values. Calling this again is harmless as long
        // as we do not allow lock kind changes after making a call to any
        // user lock functions (true).
#if KMP_USE_DYNAMIC_LOCK
        __kmp_init_dynamic_user_locks();
#else
        __kmp_set_user_lock_vptrs(__kmp_user_lock_kind);
#endif
    }
#if KMP_AFFINITY_SUPPORTED
    if (! TCR_4(__kmp_init_middle)) {
        //
        // Determine if the machine/OS is actually capable of supporting
        // affinity.
        //
        const char *var = "KMP_AFFINITY";
# if KMP_USE_HWLOC
        if(hwloc_topology_init(&__kmp_hwloc_topology) < 0) {
            __kmp_hwloc_error = TRUE;
            if(__kmp_affinity_verbose)
                KMP_WARNING(AffHwlocErrorOccurred, var, "hwloc_topology_init()");
        }
        hwloc_topology_ignore_type(__kmp_hwloc_topology, HWLOC_OBJ_CACHE);
# endif
        if (__kmp_affinity_type == affinity_disabled) {
            KMP_AFFINITY_DISABLE();
        }
        else if (! KMP_AFFINITY_CAPABLE()) {
# if KMP_USE_HWLOC
            const hwloc_topology_support* topology_support = hwloc_topology_get_support(
      __kmp_hwloc_topology);
            if(hwloc_topology_load(__kmp_hwloc_topology) < 0) {
                __kmp_hwloc_error = TRUE;
                if(__kmp_affinity_verbose)
                    KMP_WARNING(AffHwlocErrorOccurred, var, "hwloc_topology_load()");
            }
            // Is the system capable of setting/getting this thread's affinity?
            // also, is topology discovery possible? (pu indicates ability to discover processing units)
            // and finally, were there no errors when calling any hwloc_* API functions?
            if(topology_support->cpubind->set_thisthread_cpubind &&
               topology_support->cpubind->get_thisthread_cpubind &&
               topology_support->discovery->pu &&
               !__kmp_hwloc_error)
            {
                // enables affinity according to KMP_AFFINITY_CAPABLE() macro
                KMP_AFFINITY_ENABLE(TRUE);
            } else {
                // indicate that hwloc didn't work and disable affinity
                __kmp_hwloc_error = TRUE;
                KMP_AFFINITY_DISABLE();
            }
# else
            __kmp_affinity_determine_capable(var);
# endif // KMP_USE_HWLOC
            if (! KMP_AFFINITY_CAPABLE()) {
                if (__kmp_affinity_verbose || (__kmp_affinity_warnings
                  && (__kmp_affinity_type != affinity_default)
                  && (__kmp_affinity_type != affinity_none)
                  && (__kmp_affinity_type != affinity_disabled))) {
                    KMP_WARNING(AffNotSupported, var);
                }
                __kmp_affinity_type = affinity_disabled;
                __kmp_affinity_respect_mask = 0;
                __kmp_affinity_gran = affinity_gran_fine;
            }
        }
# if OMP_40_ENABLED
        if (__kmp_affinity_type == affinity_disabled) {
            __kmp_nested_proc_bind.bind_types[0] =
      proc_bind_false;
        }
        else if (__kmp_nested_proc_bind.bind_types[0] ==
      proc_bind_true) {
            //
            // OMP_PROC_BIND=true maps to OMP_PROC_BIND=spread.
            //
            __kmp_nested_proc_bind.bind_types[0] =
      proc_bind_spread;
        }
# endif /* OMP_40_ENABLED */
        if (KMP_AFFINITY_CAPABLE()) {
# if KMP_GROUP_AFFINITY
            //
            // Handle the Win 64 group affinity stuff if there are multiple
            // processor groups, or if the user requested it, and OMP 4.0
            // affinity is not in effect.
            //
            if (((__kmp_num_proc_groups > 1)
              && (__kmp_affinity_type == affinity_default)
# if OMP_40_ENABLED
              && (__kmp_nested_proc_bind.bind_types[0] ==
      proc_bind_default))
# endif
              || (__kmp_affinity_top_method == affinity_top_method_group)) {
                if (__kmp_affinity_respect_mask == affinity_respect_mask_default) {
                    __kmp_affinity_respect_mask = FALSE;
                }
                if (__kmp_affinity_type == affinity_default) {
                    __kmp_affinity_type = affinity_compact;
# if OMP_40_ENABLED
                    __kmp_nested_proc_bind.bind_types[0] =
      proc_bind_intel;
# endif
                }
                if (__kmp_affinity_top_method == affinity_top_method_default) {
                    if (__kmp_affinity_gran == affinity_gran_default) {
                        __kmp_affinity_top_method = affinity_top_method_group;
                        __kmp_affinity_gran = affinity_gran_group;
                    }
                    else if (__kmp_affinity_gran == affinity_gran_group) {
                        __kmp_affinity_top_method = affinity_top_method_group;
                    }
                    else {
                        __kmp_affinity_top_method = affinity_top_method_all;
                    }
                }
                else if (__kmp_affinity_top_method == affinity_top_method_group) {
                    if (__kmp_affinity_gran == affinity_gran_default) {
                        __kmp_affinity_gran = affinity_gran_group;
                    }
                    else if ((__kmp_affinity_gran != affinity_gran_group)
                      && (__kmp_affinity_gran != affinity_gran_fine)
                      && (__kmp_affinity_gran != affinity_gran_thread)) {
                        const char *str = NULL;
                        switch (__kmp_affinity_gran) {
                            case affinity_gran_core: str = "core"; break;
                            case affinity_gran_package: str = "package"; break;
                            case affinity_gran_node: str = "node"; break;
                            default: KMP_DEBUG_ASSERT(0);
                        }
                        KMP_WARNING(AffGranTopGroup, var, str);
                        __kmp_affinity_gran = affinity_gran_fine;
                    }
                }
                else {
                    if (__kmp_affinity_gran == affinity_gran_default) {
                        __kmp_affinity_gran = affinity_gran_core;
                    }
                    else if (__kmp_affinity_gran == affinity_gran_group) {
                        const char *str = NULL;
                        switch (__kmp_affinity_type) {
                            case affinity_physical: str = "physical"; break;
                            case affinity_logical: str = "logical"; break;
                            case affinity_compact: str = "compact"; break;
                            case affinity_scatter: str = "scatter"; break;
                            case affinity_explicit: str = "explicit"; break;
                            // No MIC on windows, so no affinity_balanced case
                            default: KMP_DEBUG_ASSERT(0);
                        }
                        KMP_WARNING(AffGranGroupType, var, str);
                        __kmp_affinity_gran = affinity_gran_core;
                    }
                }
            }
            else
# endif /* KMP_GROUP_AFFINITY */
            {
                if (__kmp_affinity_respect_mask == affinity_respect_mask_default) {
# if KMP_GROUP_AFFINITY
                    if (__kmp_num_proc_groups > 1) {
                        __kmp_affinity_respect_mask = FALSE;
                    }
                    else
# endif /* KMP_GROUP_AFFINITY */
                    {
                        __kmp_affinity_respect_mask = TRUE;
                    }
                }
# if OMP_40_ENABLED
                if ((__kmp_nested_proc_bind.bind_types[0] !=
      proc_bind_intel)
                  && (__kmp_nested_proc_bind.bind_types[0] !=
      proc_bind_default)) {
                    if (__kmp_affinity_type == affinity_default) {
                        __kmp_affinity_type = affinity_compact;
                        __kmp_affinity_dups = FALSE;
                    }
                }
                else
# endif /* OMP_40_ENABLED */
                if (__kmp_affinity_type == affinity_default) {
#if OMP_40_ENABLED
#if KMP_ARCH_X86_64 && (KMP_OS_LINUX || KMP_OS_WINDOWS)
                    if(__kmp_mic_type != non_mic) {
                        __kmp_nested_proc_bind.bind_types[0] =
      proc_bind_intel;
                    } else
#endif
                    {
                        __kmp_nested_proc_bind.bind_types[0] =
      proc_bind_false;
                    }
#endif /* OMP_40_ENABLED */
#if KMP_ARCH_X86_64 && (KMP_OS_LINUX || KMP_OS_WINDOWS)
                    if(__kmp_mic_type != non_mic) {
                        __kmp_affinity_type = affinity_scatter;
                    } else
#endif
                    {
                        __kmp_affinity_type = affinity_none;
                    }
                }
                if ((__kmp_affinity_gran == affinity_gran_default)
                  && (__kmp_affinity_gran_levels < 0)) {
#if KMP_ARCH_X86_64 && (KMP_OS_LINUX || KMP_OS_WINDOWS)
                    if(__kmp_mic_type != non_mic) {
                        __kmp_affinity_gran = affinity_gran_fine;
                    } else
#endif
                    {
                        __kmp_affinity_gran = affinity_gran_core;
                    }
                }
                if (__kmp_affinity_top_method == affinity_top_method_default) {
                    __kmp_affinity_top_method = affinity_top_method_all;
                }
            }
        }
        K_DIAG(1, ("__kmp_affinity_type == %d\n", __kmp_affinity_type));
        K_DIAG(1, ("__kmp_affinity_compact == %d\n",
      __kmp_affinity_compact));
        K_DIAG(1, ("__kmp_affinity_offset == %d\n", __kmp_affinity_offset));
        K_DIAG(1, ("__kmp_affinity_verbose == %d\n", __kmp_affinity_verbose));
        K_DIAG(1, ("__kmp_affinity_warnings == %d\n", __kmp_affinity_warnings));
        K_DIAG(1, ("__kmp_affinity_respect_mask == %d\n", __kmp_affinity_respect_mask));
        K_DIAG(1, ("__kmp_affinity_gran == %d\n", __kmp_affinity_gran));
        KMP_DEBUG_ASSERT(__kmp_affinity_type != affinity_default);
# if OMP_40_ENABLED
        KMP_DEBUG_ASSERT(__kmp_nested_proc_bind.
      bind_types[0] != proc_bind_default);
# endif
    }
#endif /* KMP_AFFINITY_SUPPORTED */
    if (__kmp_version) {
        __kmp_print_version_1();
    }; // if
    // Post-initialization step: some env. vars need their value's further processing
    if (string != NULL) { // kmp_set_defaults() was called
        __kmp_aux_env_initialize(&block);
    }
    __kmp_env_blk_free(& block);
    KMP_MB();
} // __kmp_env_initialize
void __kmp_env_print ()
Definition at line 5400 of file kmp_settings.c.
Referenced by __kmp_aux_set_defaults(), and __kmp_do_serial_initialize().
                  {
    kmp_env_blk_t block;
    int i;
    kmp_str_buf_t buffer;
    __kmp_stg_init();
    __kmp_str_buf_init(& buffer);
    __kmp_env_blk_init(& block, NULL);
    __kmp_env_blk_sort(& block);
    // Print real environment values.
    __kmp_str_buf_print(& buffer, "\n%s\n\n", KMP_I18N_STR(UserSettings)
       );
    for (i = 0; i < block.count; ++ i) {
        char const * name = block.vars[ i ].name;
        char const * value = block.vars[ i ].value;
        if (
            (KMP_STRLEN(name) > 4 && strncmp(name, "KMP_", 4) == 0)
            || strncmp(name, "OMP_", 4) == 0
            #ifdef KMP_GOMP_COMPAT
                || strncmp(name, "GOMP_", 5) == 0
            #endif // KMP_GOMP_COMPAT
        ) {
            __kmp_str_buf_print(& buffer, " %s=%s\n", name, value);
        }; // if
    }; // for
    __kmp_str_buf_print(& buffer, "\n");
    // Print internal (effective) settings.
    __kmp_str_buf_print(& buffer, "%s\n\n", KMP_I18N_STR(EffectiveSettings
       ));
    for (int i = 0; i < __kmp_stg_count; ++ i) {
        if (__kmp_stg_table[ i ].print != NULL) {
            __kmp_stg_table[ i ].print(& buffer,
      __kmp_stg_table[ i ].name, __kmp_stg_table[ i ].
      data);
        }; // if
    }; // for
    __kmp_printf("%s", buffer.str);
    __kmp_env_blk_free(& block);
    __kmp_str_buf_free(& buffer);
    __kmp_printf("\n");
} // __kmp_env_print
void __kmp_env_print_2 ()
Definition at line 5449 of file kmp_settings.c.
Referenced by __kmp_do_serial_initialize().
                    {
    kmp_env_blk_t block;
    kmp_str_buf_t buffer;
    __kmp_env_format = 1;
    __kmp_stg_init();
    __kmp_str_buf_init(& buffer);
    __kmp_env_blk_init(& block, NULL);
    __kmp_env_blk_sort(& block);
    __kmp_str_buf_print(& buffer, "\n%s\n", KMP_I18N_STR(DisplayEnvBegin)
        );
    __kmp_str_buf_print(& buffer, " _OPENMP='%d'\n",
      __kmp_openmp_version);
    for (int i = 0; i < __kmp_stg_count; ++ i) {
        if (__kmp_stg_table[ i ].print != NULL &&
              ((__kmp_display_env && strncmp(__kmp_stg_table[
      i ].name, "OMP_", 4) == 0) || __kmp_display_env_verbose)) {
            __kmp_stg_table[ i ].print(& buffer,
      __kmp_stg_table[ i ].name, __kmp_stg_table[ i ].
      data);
        }; // if
    }; // for
    __kmp_str_buf_print(& buffer, "%s\n", KMP_I18N_STR(DisplayEnvEnd));
    __kmp_str_buf_print(& buffer, "\n");
    __kmp_printf("%s", buffer.str);
    __kmp_env_blk_free(& block);
    __kmp_str_buf_free(& buffer);
    __kmp_printf("\n");
} // __kmp_env_print_2
void __kmp_init_dflt_team_nth ()
int __kmp_initial_threads_capacity (int req_nproc)
Definition at line 513 of file kmp_settings.c.
Referenced by __kmp_do_serial_initialize(), and __kmp_env_initialize().
{
    int nth = 32;
    /* MIN(MAX(32, 4 * $OMP_NUM_THREADS, 4 * omp_get_num_procs()), __kmp_max_nth) */
    if (nth < (4 * req_nproc))
        nth = (4 * req_nproc);
    if (nth < (4 * __kmp_xproc))
        nth = (4 * __kmp_xproc);
    if (nth > __kmp_max_nth)
        nth = __kmp_max_nth;
    return nth;
}
void __kmp_reset_global_vars (void)