z_Linux_util.c File Reference
#include `kmp.h`
*
#include `kmp_wrapper_getpid.h`
*
#include `kmp_itt.h`
*
#include `kmp_str.h`
*
#include `kmp_i18n.h`
*
#include `kmp_io.h`
*
#include `kmp_stats.h`
*
#include `kmp_wait_release.h`
*
#include <alloca.h>
*
#include <unistd.h>
*
#include <math.h>
*
#include <sys/time.h>
*
#include <sys/times.h>
*
#include <sys/resource.h>
*
#include <sys/syscall.h>
*
#include <dirent.h>
*
#include <ctype.h>
*
#include <fcntl.h>
*
Classes
struct kmp_sys_timer
Macros
#define TS2NS(timespec) (((timespec).tv_sec * 1e9) + (timespec).tv_nsec)
Functions
void __kmp_terminate_thread (int gtid)
static kmp_int32 __kmp_set_stack_info (int gtid, kmp_info_t *th)
static void * __kmp_launch_worker (void *thr)
static void * __kmp_launch_monitor (void *thr)
void __kmp_create_worker (int gtid, kmp_info_t *th, size_t stack_size)
void __kmp_create_monitor (kmp_info_t *th)
void __kmp_exit_thread (int exit_status)
void __kmp_resume_monitor ()
void __kmp_reap_monitor (kmp_info_t *th)
void __kmp_reap_worker (kmp_info_t *th)
void __kmp_enable (int new_state)
void __kmp_disable (int *old_state)
static void __kmp_atfork_prepare (void)
static void __kmp_atfork_parent (void)
static void __kmp_atfork_child (void)
void __kmp_register_atfork (void)
void __kmp_suspend_initialize (void)
static void __kmp_suspend_initialize_thread (kmp_info_t *th)
void __kmp_suspend_uninitialize_thread (kmp_info_t *th)
template<class C >
static void __kmp_suspend_template (int th_gtid, C *flag)
void __kmp_suspend_32 (int th_gtid, kmp_flag_32 *flag)
void __kmp_suspend_64 (int th_gtid, kmp_flag_64 *flag)
void __kmp_suspend_oncore (int th_gtid, kmp_flag_oncore *flag)
template<class C >
static void __kmp_resume_template (int target_gtid, C *flag)
void __kmp_resume_32 (int target_gtid, kmp_flag_32 *flag)
void __kmp_resume_64 (int target_gtid, kmp_flag_64 *flag)
void __kmp_resume_oncore (int target_gtid, kmp_flag_oncore *flag)
void __kmp_yield (int cond)
void __kmp_gtid_set_specific (int gtid)
int __kmp_gtid_get_specific ()
double __kmp_read_cpu_time (void)
int __kmp_read_system_info (struct kmp_sys_info *info)
void __kmp_read_system_time (double *delta)
void __kmp_clear_system_time (void)
static int __kmp_get_xproc (void)
int __kmp_read_from_file (char const *path, char const *format,...)
void __kmp_runtime_initialize (void)
void __kmp_runtime_destroy (void)
void __kmp_thread_sleep (int millis)
void __kmp_elapsed (double *t)
void __kmp_elapsed_tick (double *t)
int __kmp_is_address_mapped (void *addr)
int __kmp_invoke_microtask (microtask_t pkfn, int gtid, int tid, int argc, void *p_argv[])
Variables
static struct kmp_sys_timer __kmp_sys_timer_data
static int __kmp_init_runtime = FALSE
static int __kmp_fork_count = 0
static pthread_condattr_t __kmp_suspend_cond_attr
static pthread_mutexattr_t __kmp_suspend_mutex_attr
static kmp_cond_align_t __kmp_wait_cv
static kmp_mutex_align_t __kmp_wait_mx
Macro Definition Documentation
#define TS2NS(timespec) (((timespec).tv_sec * 1e9) + (timespec).tv_nsec)
Definition at line 69 of file z_Linux_util.c.
Referenced by __kmp_read_system_time().
Function Documentation
static void __kmp_atfork_child (void) [static]
Definition at line 1528 of file z_Linux_util.c.
Referenced by __kmp_register_atfork().
{
    /* TODO make sure this is done right for nested/sibling */
    // ATT: Memory leaks are here? TODO: Check it and fix.
    /* KMP_ASSERT(0); */
    ++__kmp_fork_count;
    __kmp_init_runtime = FALSE;
    __kmp_init_monitor = 0;
    __kmp_init_parallel = FALSE;
    __kmp_init_middle = FALSE;
    __kmp_init_serial = FALSE;
    TCW_4(__kmp_init_gtid, FALSE);
    __kmp_init_common = FALSE;
    TCW_4(__kmp_init_user_locks, FALSE);
#if ! KMP_USE_DYNAMIC_LOCK
    __kmp_user_lock_table.used = 1;
    __kmp_user_lock_table.allocated = 0;
    __kmp_user_lock_table.table = NULL;
    __kmp_lock_blocks = NULL;
#endif
    __kmp_all_nth = 0;
    TCW_4(__kmp_nth, 0);
    /* Must actually zero all the *cache arguments passed to __kmpc_threadprivate here
       so threadprivate doesn't use stale data */
    KA_TRACE(10, ("__kmp_atfork_child: checking cache address list %p\n",
                 __kmp_threadpriv_cache_list));
    while (__kmp_threadpriv_cache_list != NULL) {
        if (*__kmp_threadpriv_cache_list -> addr != NULL) {
            KC_TRACE(50, ("__kmp_atfork_child: zeroing cache at address %p\n",
                        &(*__kmp_threadpriv_cache_list ->
      addr)));
            *__kmp_threadpriv_cache_list -> addr = NULL;
        }
        __kmp_threadpriv_cache_list =
      __kmp_threadpriv_cache_list -> next;
    }
    __kmp_init_runtime = FALSE;
    /* reset statically initialized locks */
    __kmp_init_bootstrap_lock(&__kmp_initz_lock);
    __kmp_init_bootstrap_lock(&__kmp_stdio_lock);
    __kmp_init_bootstrap_lock(&__kmp_console_lock);
    /* This is necessary to make sure no stale data is left around */
    /* AC: customers complain that we use unsafe routines in the atfork
       handler. Mathworks: dlsym() is unsafe. We call dlsym and dlopen
       in dynamic_link when check the presence of shared tbbmalloc library.
       Suggestion is to make the library initialization lazier, similar
       to what done for __kmpc_begin(). */
    // TODO: synchronize all static initializations with regular library
    // startup; look at kmp_global.c and etc.
    //__kmp_internal_begin ();
}
static void __kmp_atfork_parent (void) [static]
Definition at line 1517 of file z_Linux_util.c.
Referenced by __kmp_register_atfork().
{
    /* nothing to do */
}
static void __kmp_atfork_prepare (void) [static]
Definition at line 1511 of file z_Linux_util.c.
Referenced by __kmp_register_atfork().
{
    /* nothing to do */
}
void __kmp_clear_system_time (void)
Definition at line 1984 of file z_Linux_util.c.
{
    struct timeval tval;
    int status;
    status = gettimeofday(&tval, NULL);
    KMP_CHECK_SYSFAIL_ERRNO("gettimeofday", status);
    TIMEVAL_TO_TIMESPEC(&tval, &__kmp_sys_timer_data.start);
}
void __kmp_create_monitor (kmp_info_t * th)
Definition at line 1076 of file z_Linux_util.c.
{
    pthread_t handle;
    pthread_attr_t thread_attr;
    size_t size;
    int status;
    int auto_adj_size = FALSE;
    if(__kmp_dflt_blocktime == KMP_MAX_BLOCKTIME) {
        // We don't need monitor thread in case of MAX_BLOCKTIME
        KA_TRACE(10, ("__kmp_create_monitor: skipping monitor thread because of MAX blocktime\n")
       );
        th->th.th_info.ds.ds_tid = 0; // this makes reap_monitor no-op
        th->th.th_info.ds.ds_gtid = 0;
        return;
    }
    KA_TRACE(10, ("__kmp_create_monitor: try to create monitor\n"));
    KMP_MB(); /* Flush all pending memory write invalidates. */
    th->th.th_info.ds.ds_tid = KMP_GTID_MONITOR;
    th->th.th_info.ds.ds_gtid = KMP_GTID_MONITOR;
    #if KMP_REAL_TIME_FIX
        TCW_4(__kmp_global.g.g_time.dt.t_value, -1); // Will use it for synchronization
       a bit later.
    #else
        TCW_4(__kmp_global.g.g_time.dt.t_value, 0);
    #endif // KMP_REAL_TIME_FIX
    #ifdef KMP_THREAD_ATTR
        if (__kmp_monitor_stksize == 0) {
            __kmp_monitor_stksize =
      KMP_DEFAULT_MONITOR_STKSIZE;
            auto_adj_size = TRUE;
        }
        status = pthread_attr_init(&thread_attr);
        if (status != 0) {
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(CantInitThreadAttrs),
                KMP_ERR(status),
                __kmp_msg_null
            );
        }; // if
        status = pthread_attr_setdetachstate(& thread_attr, PTHREAD_CREATE_JOINABLE);
        if (status != 0) {
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(CantSetMonitorState),
                KMP_ERR(status),
                __kmp_msg_null
            );
        }; // if
        #ifdef _POSIX_THREAD_ATTR_STACKSIZE
            status = pthread_attr_getstacksize(& thread_attr, & size);
            KMP_CHECK_SYSFAIL("pthread_attr_getstacksize", status);
        #else
            size = __kmp_sys_min_stksize;
        #endif /* _POSIX_THREAD_ATTR_STACKSIZE */
    #endif /* KMP_THREAD_ATTR */
    if (__kmp_monitor_stksize == 0) {
        __kmp_monitor_stksize = KMP_DEFAULT_MONITOR_STKSIZE
      ;
    }
    if (__kmp_monitor_stksize < __kmp_sys_min_stksize) {
        __kmp_monitor_stksize = __kmp_sys_min_stksize;
    }
    KA_TRACE(10, ("__kmp_create_monitor: default stacksize = %lu bytes,"
                    "requested stacksize = %lu bytes\n",
                    size, __kmp_monitor_stksize));
    retry:
    /* Set stack size for this thread now. */
    #ifdef _POSIX_THREAD_ATTR_STACKSIZE
        KA_TRACE(10, ("__kmp_create_monitor: setting stacksize = %lu bytes,",
                        __kmp_monitor_stksize));
        status = pthread_attr_setstacksize(& thread_attr, __kmp_monitor_stksize);
        if (status != 0) {
            if (auto_adj_size) {
                __kmp_monitor_stksize *= 2;
                goto retry;
            }
            __kmp_msg(
                kmp_ms_warning, // should this be fatal? BB
                KMP_MSG(CantSetMonitorStackSize, (long int)
      __kmp_monitor_stksize),
                KMP_ERR(status),
                KMP_HNT(ChangeMonitorStackSize),
                __kmp_msg_null
            );
        }; // if
    #endif /* _POSIX_THREAD_ATTR_STACKSIZE */
    status = pthread_create(&handle, & thread_attr, __kmp_launch_monitor, (void *) th
      );
    if (status != 0) {
        #ifdef _POSIX_THREAD_ATTR_STACKSIZE
            if (status == EINVAL) {
                if (auto_adj_size && (__kmp_monitor_stksize < (size_t)0x40000000)) {
                    __kmp_monitor_stksize *= 2;
                    goto retry;
                }
                __kmp_msg(
                    kmp_ms_fatal,
                    KMP_MSG(CantSetMonitorStackSize, __kmp_monitor_stksize),
                    KMP_ERR(status),
                    KMP_HNT(IncreaseMonitorStackSize),
                    __kmp_msg_null
                );
            }; // if
            if (status == ENOMEM) {
                __kmp_msg(
                    kmp_ms_fatal,
                    KMP_MSG(CantSetMonitorStackSize, __kmp_monitor_stksize),
                    KMP_ERR(status),
                    KMP_HNT(DecreaseMonitorStackSize),
                    __kmp_msg_null
                );
            }; // if
        #endif /* _POSIX_THREAD_ATTR_STACKSIZE */
        if (status == EAGAIN) {
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(NoResourcesForMonitorThread),
                KMP_ERR(status),
                KMP_HNT(DecreaseNumberOfThreadsInUse),
                __kmp_msg_null
            );
        }; // if
        KMP_SYSFAIL("pthread_create", status);
    }; // if
    th->th.th_info.ds.ds_thread = handle;
    #if KMP_REAL_TIME_FIX
        // Wait for the monitor thread is really started and set its *priority*.
        KMP_DEBUG_ASSERT(sizeof(kmp_uint32) == sizeof(
      __kmp_global.g.g_time.dt.t_value));
        __kmp_wait_yield_4(
            (kmp_uint32 volatile *) & __kmp_global.g.g_time.dt.t_value, -1, &
      __kmp_neq_4, NULL
        );
    #endif // KMP_REAL_TIME_FIX
    #ifdef KMP_THREAD_ATTR
        status = pthread_attr_destroy(& thread_attr);
        if (status != 0) {
            __kmp_msg(//
                kmp_ms_warning,
                KMP_MSG(CantDestroyThreadAttrs),
                KMP_ERR(status),
                __kmp_msg_null
            );
        }; // if
    #endif
    KMP_MB(); /* Flush all pending memory write invalidates. */
    KA_TRACE(10, ("__kmp_create_monitor: monitor created %#.8lx\n", th->th.th_info.ds.ds_thread)
       );
} // __kmp_create_monitor
void __kmp_create_worker (int gtid, kmp_info_t * th, size_t stack_size)
Definition at line 954 of file z_Linux_util.c.
{
    pthread_t handle;
    pthread_attr_t thread_attr;
    int status;
    th->th.th_info.ds.ds_gtid = gtid;
#if KMP_STATS_ENABLED
    // sets up worker thread stats
    __kmp_acquire_tas_lock(&__kmp_stats_lock, gtid);
    // th->th.th_stats is used to transfer thread specific stats-pointer to __kmp_launch_worker
    // So when thread is created (goes into __kmp_launch_worker) it will
    // set it's __thread local pointer to th->th.th_stats
    th->th.th_stats = __kmp_stats_list.push_back(gtid);
    if(KMP_UBER_GTID(gtid)) {
        __kmp_stats_start_time = tsc_tick_count::now();
        __kmp_stats_thread_ptr = th->th.th_stats;
        __kmp_stats_init();
        KMP_START_EXPLICIT_TIMER(OMP_serial);
        KMP_START_EXPLICIT_TIMER(OMP_start_end);
    }
    __kmp_release_tas_lock(&__kmp_stats_lock, gtid);
#endif // KMP_STATS_ENABLED
    if (KMP_UBER_GTID(gtid)) {
        KA_TRACE(10, ("__kmp_create_worker: uber thread (%d)\n", gtid));
        th -> th.th_info.ds.ds_thread = pthread_self();
        __kmp_set_stack_info(gtid, th);
        __kmp_check_stack_overlap(th);
        return;
    }; // if
    KA_TRACE(10, ("__kmp_create_worker: try to create thread (%d)\n", gtid));
    KMP_MB(); /* Flush all pending memory write invalidates. */
#ifdef KMP_THREAD_ATTR
    status = pthread_attr_init(&thread_attr);
    if (status != 0) {
        __kmp_msg(kmp_ms_fatal, KMP_MSG(CantInitThreadAttrs),
      KMP_ERR(status), __kmp_msg_null);
    }; // if
    status = pthread_attr_setdetachstate(& thread_attr, PTHREAD_CREATE_JOINABLE);
    if (status != 0) {
        __kmp_msg(kmp_ms_fatal, KMP_MSG(CantSetWorkerState),
      KMP_ERR(status), __kmp_msg_null);
    }; // if
    /* Set stack size for this thread now.
     * The multiple of 2 is there because on some machines, requesting an unusual stacksize
     * causes the thread to have an offset before the dummy alloca() takes place to create the
     * offset. Since we want the user to have a sufficient stacksize AND support a stack offset, we
     * alloca() twice the offset so that the upcoming alloca() does not eliminate any premade
     * offset, and also gives the user the stack space they requested for all threads */
    stack_size += gtid * __kmp_stkoffset * 2;
    KA_TRACE(10, ("__kmp_create_worker: T#%d, default stacksize = %lu bytes, "
                    "__kmp_stksize = %lu bytes, final stacksize = %lu bytes\n",
                    gtid, KMP_DEFAULT_STKSIZE, __kmp_stksize, stack_size)
      );
# ifdef _POSIX_THREAD_ATTR_STACKSIZE
    status = pthread_attr_setstacksize(& thread_attr, stack_size);
# ifdef KMP_BACKUP_STKSIZE
    if (status != 0) {
        if (! __kmp_env_stksize) {
            stack_size = KMP_BACKUP_STKSIZE + gtid * __kmp_stkoffset;
            __kmp_stksize = KMP_BACKUP_STKSIZE;
            KA_TRACE(10, ("__kmp_create_worker: T#%d, default stacksize = %lu bytes, "
                           "__kmp_stksize = %lu bytes, (backup) final stacksize = %lu "
                           "bytes\n",
                           gtid, KMP_DEFAULT_STKSIZE,
      __kmp_stksize, stack_size)
                      );
            status = pthread_attr_setstacksize(&thread_attr, stack_size);
        }; // if
    }; // if
# endif /* KMP_BACKUP_STKSIZE */
    if (status != 0) {
        __kmp_msg(kmp_ms_fatal, KMP_MSG(CantSetWorkerStackSize, stack_size),
      KMP_ERR(status),
                  KMP_HNT(ChangeWorkerStackSize), __kmp_msg_null);
    }; // if
# endif /* _POSIX_THREAD_ATTR_STACKSIZE */
#endif /* KMP_THREAD_ATTR */
    status = pthread_create(& handle, & thread_attr, __kmp_launch_worker, (void *) th)
      ;
    if (status != 0 || ! handle) { // ??? Why do we check handle??
#ifdef _POSIX_THREAD_ATTR_STACKSIZE
        if (status == EINVAL) {
            __kmp_msg(kmp_ms_fatal, KMP_MSG(CantSetWorkerStackSize, stack_size
       ), KMP_ERR(status),
                      KMP_HNT(IncreaseWorkerStackSize), __kmp_msg_null);
        };
        if (status == ENOMEM) {
            __kmp_msg(kmp_ms_fatal, KMP_MSG(CantSetWorkerStackSize, stack_size
       ), KMP_ERR(status),
                      KMP_HNT(DecreaseWorkerStackSize), __kmp_msg_null);
        };
#endif /* _POSIX_THREAD_ATTR_STACKSIZE */
        if (status == EAGAIN) {
            __kmp_msg(kmp_ms_fatal, KMP_MSG(NoResourcesForWorkerThread),
      KMP_ERR(status),
                      KMP_HNT(Decrease_NUM_THREADS), __kmp_msg_null);
        }; // if
        KMP_SYSFAIL("pthread_create", status);
    }; // if
    th->th.th_info.ds.ds_thread = handle;
#ifdef KMP_THREAD_ATTR
    status = pthread_attr_destroy(& thread_attr);
    if (status) {
        __kmp_msg(kmp_ms_warning, KMP_MSG(CantDestroyThreadAttrs),
      KMP_ERR(status), __kmp_msg_null);
    }; // if
#endif /* KMP_THREAD_ATTR */
    KMP_MB(); /* Flush all pending memory write invalidates. */
    KA_TRACE(10, ("__kmp_create_worker: done creating thread (%d)\n", gtid));
} // __kmp_create_worker
void __kmp_disable (int * old_state)
Definition at line 1498 of file z_Linux_util.c.
{
    #ifdef KMP_CANCEL_THREADS
        int status;
        status = pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, old_state);
        KMP_CHECK_SYSFAIL("pthread_setcancelstate", status);
    #endif
}
void __kmp_elapsed (double * t)
Definition at line 2189 of file z_Linux_util.c.
{
    int status;
# ifdef FIX_SGI_CLOCK
    struct timespec ts;
    status = clock_gettime(CLOCK_PROCESS_CPUTIME_ID, &ts);
    KMP_CHECK_SYSFAIL_ERRNO("clock_gettime", status);
    *t = (double) ts.tv_nsec * (1.0 / (double) KMP_NSEC_PER_SEC) +
        (double) ts.tv_sec;
# else
    struct timeval tv;
    status = gettimeofday(& tv, NULL);
    KMP_CHECK_SYSFAIL_ERRNO("gettimeofday", status);
    *t = (double) tv.tv_usec * (1.0 / (double) KMP_USEC_PER_SEC) +
        (double) tv.tv_sec;
# endif
}
void __kmp_elapsed_tick (double * t)
Definition at line 2211 of file z_Linux_util.c.
{
    *t = 1 / (double) CLOCKS_PER_SEC;
}
void __kmp_enable (int new_state)
Definition at line 1487 of file z_Linux_util.c.
{
    #ifdef KMP_CANCEL_THREADS
        int status, old_state;
        status = pthread_setcancelstate(new_state, & old_state);
        KMP_CHECK_SYSFAIL("pthread_setcancelstate", status);
        KMP_DEBUG_ASSERT(old_state == PTHREAD_CANCEL_DISABLE);
    #endif
}
void __kmp_exit_thread (int exit_status)
Definition at line 1237 of file z_Linux_util.c.
  {
    pthread_exit((void *)(intptr_t) exit_status);
} // __kmp_exit_thread
static int __kmp_get_xproc (void) [static]
Definition at line 2025 of file z_Linux_util.c.
Referenced by __kmp_runtime_initialize().
                        {
    int r = 0;
    #if KMP_OS_LINUX || KMP_OS_FREEBSD || KMP_OS_NETBSD
        r = sysconf(_SC_NPROCESSORS_ONLN);
    #elif KMP_OS_DARWIN
        // Bug C77011 High "OpenMP Threads and number of active cores".
        // Find the number of available CPUs.
        kern_return_t rc;
        host_basic_info_data_t info;
        mach_msg_type_number_t num = HOST_BASIC_INFO_COUNT;
        rc = host_info(mach_host_self(), HOST_BASIC_INFO, (host_info_t) & info, & num);
        if (rc == 0 && num == HOST_BASIC_INFO_COUNT) {
            // Cannot use KA_TRACE() here because this code works before trace support is
            // initialized.
            r = info.avail_cpus;
        } else {
            KMP_WARNING(CantGetNumAvailCPU);
            KMP_INFORM(AssumedNumCPU);
        }; // if
    #else
        #error "Unknown or unsupported OS."
    #endif
    return r > 0 ? r : 2; /* guess value of 2 if OS told us 0 */
} // __kmp_get_xproc
int __kmp_gtid_get_specific (void)
Definition at line 1909 of file z_Linux_util.c.
{
    int gtid;
    if (!__kmp_init_runtime) {
        KA_TRACE(50, ("__kmp_get_specific: runtime shutdown, returning KMP_GTID_SHUTDOWN\n"));
        return KMP_GTID_SHUTDOWN;
    }
    gtid = (int)(size_t)pthread_getspecific(__kmp_gtid_threadprivate_key);
    if (gtid == 0) {
        gtid = KMP_GTID_DNE;
    }
    else {
        gtid--;
    }
    KA_TRACE(50, ("__kmp_gtid_get_specific: key:%d gtid:%d\n",
               __kmp_gtid_threadprivate_key, gtid));
    return gtid;
}
void __kmp_gtid_set_specific (int gtid)
Definition at line 1900 of file z_Linux_util.c.
Referenced by __kmp_launch_monitor(), and __kmp_launch_worker().
{
    int status;
    KMP_ASSERT(__kmp_init_runtime);
    status = pthread_setspecific(__kmp_gtid_threadprivate_key, (void*)(
      intptr_t)(gtid+1));
    KMP_CHECK_SYSFAIL("pthread_setspecific", status);
}
int __kmp_invoke_microtask (microtask_t pkfn, int gtid, int tid, int argc, void * p_argv[])
Definition at line 2567 of file z_Linux_util.c.
Referenced by __kmp_fork_call(), and __kmp_invoke_task_func().
{
#if OMPT_SUPPORT
  *exit_frame_ptr = __builtin_frame_address(0);
#endif
  switch (argc) {
  default:
    fprintf(stderr, "Too many args to microtask: %d!\n", argc);
    fflush(stderr);
    exit(-1);
  case 0:
    (*pkfn)(&gtid, &tid);
    break;
  case 1:
    (*pkfn)(&gtid, &tid, p_argv[0]);
    break;
  case 2:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1]);
    break;
  case 3:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2]);
    break;
  case 4:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3]);
    break;
  case 5:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4]);
    break;
  case 6:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5]);
    break;
  case 7:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5], p_argv[6]);
    break;
  case 8:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5], p_argv[6], p_argv[7]);
    break;
  case 9:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5], p_argv[6], p_argv[7], p_argv[8]);
    break;
  case 10:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5], p_argv[6], p_argv[7], p_argv[8], p_argv[9]);
    break;
  case 11:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5], p_argv[6], p_argv[7], p_argv[8], p_argv[9], p_argv[10]);
    break;
  case 12:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5], p_argv[6], p_argv[7], p_argv[8], p_argv[9], p_argv[10],
            p_argv[11]);
    break;
  case 13:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5], p_argv[6], p_argv[7], p_argv[8], p_argv[9], p_argv[10],
            p_argv[11], p_argv[12]);
    break;
  case 14:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5], p_argv[6], p_argv[7], p_argv[8], p_argv[9], p_argv[10],
            p_argv[11], p_argv[12], p_argv[13]);
    break;
  case 15:
    (*pkfn)(&gtid, &tid, p_argv[0], p_argv[1], p_argv[2], p_argv[3], p_argv[4],
            p_argv[5], p_argv[6], p_argv[7], p_argv[8], p_argv[9], p_argv[10],
            p_argv[11], p_argv[12], p_argv[13], p_argv[14]);
    break;
  }
#if OMPT_SUPPORT
  *exit_frame_ptr = 0;
#endif
  return 1;
}
int __kmp_is_address_mapped (void * addr)
Definition at line 2221 of file z_Linux_util.c.
                                       {
    int found = 0;
    int rc;
    #if KMP_OS_LINUX || KMP_OS_FREEBSD
        /*
            On Linux* OS, read the /proc/<pid>/maps pseudo-file to get all the address ranges mapped
            into the address space.
        */
        char * name = __kmp_str_format("/proc/%d/maps", getpid());
        FILE * file = NULL;
        file = fopen(name, "r");
        KMP_ASSERT(file != NULL);
        for (; ;) {
            void * beginning = NULL;
            void * ending = NULL;
            char perms[ 5 ];
            rc = fscanf(file, "%p-%p %4s %*[^\n]\n", & beginning, & ending, perms);
            if (rc == EOF) {
                break;
            }; // if
            KMP_ASSERT(rc == 3 && KMP_STRLEN(perms) == 4); // Make sure all fields
       are read.
            // Ending address is not included in the region, but beginning is.
            if ((addr >= beginning) && (addr < ending)) {
                perms[ 2 ] = 0; // 3th and 4th character does not matter.
                if (strcmp(perms, "rw") == 0) {
                    // Memory we are looking for should be readable and writable.
                    found = 1;
                }; // if
                break;
            }; // if
        }; // forever
        // Free resources.
        fclose(file);
        KMP_INTERNAL_FREE(name);
    #elif KMP_OS_DARWIN
        /*
            On OS X*, /proc pseudo filesystem is not available. Try to read memory using vm
            interface.
        */
        int buffer;
        vm_size_t count;
        rc =
            vm_read_overwrite(
                mach_task_self(), // Task to read memory of.
                (vm_address_t)(addr), // Address to read from.
                1, // Number of bytes to be read.
                (vm_address_t)(& buffer), // Address of buffer to save read bytes in.
                & count // Address of var to save number of read bytes in.
            );
        if (rc == 0) {
            // Memory successfully read.
            found = 1;
        }; // if
    #elif KMP_OS_FREEBSD || KMP_OS_NETBSD
        // FIXME(FreeBSD, NetBSD): Implement this
        found = 1;
    #else
        #error "Unknown or unsupported OS"
    #endif
    return found;
} // __kmp_is_address_mapped
static void* __kmp_launch_monitor (void * thr) [static]
Definition at line 759 of file z_Linux_util.c.
Referenced by __kmp_create_monitor().
{
    int status, old_type, old_state;
#ifdef KMP_BLOCK_SIGNALS
    sigset_t new_set;
#endif /* KMP_BLOCK_SIGNALS */
    struct timespec interval;
    int yield_count;
    int yield_cycles = 0;
    KMP_MB(); /* Flush all pending memory write invalidates. */
    KA_TRACE(10, ("__kmp_launch_monitor: #1 launched\n"));
    /* register us as the monitor thread */
    __kmp_gtid_set_specific(KMP_GTID_MONITOR);
#ifdef KMP_TDATA_GTID
    __kmp_gtid = KMP_GTID_MONITOR;
#endif
    KMP_MB();
#if USE_ITT_BUILD
    __kmp_itt_thread_ignore(); // Instruct Intel(R) Threading Tools to ignore monitor thread.
#endif /* USE_ITT_BUILD */
    __kmp_set_stack_info(((kmp_info_t*)thr)->th.th_info.ds.ds_gtid, (
      kmp_info_t*)thr);
    __kmp_check_stack_overlap((kmp_info_t*)thr);
#ifdef KMP_CANCEL_THREADS
    status = pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, & old_type);
    KMP_CHECK_SYSFAIL("pthread_setcanceltype", status);
    /* josh todo: isn't PTHREAD_CANCEL_ENABLE default for newly-created threads? */
    status = pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, & old_state);
    KMP_CHECK_SYSFAIL("pthread_setcancelstate", status);
#endif
    #if KMP_REAL_TIME_FIX
    // This is a potential fix which allows application with real-time scheduling policy work.
    // However, decision about the fix is not made yet, so it is disabled by default.
    { // Are program started with real-time scheduling policy?
        int sched = sched_getscheduler(0);
        if (sched == SCHED_FIFO || sched == SCHED_RR) {
            // Yes, we are a part of real-time application. Try to increase the priority of the
            // monitor.
            struct sched_param param;
            int max_priority = sched_get_priority_max(sched);
            int rc;
            KMP_WARNING(RealTimeSchedNotSupported);
            sched_getparam(0, & param);
            if (param.sched_priority < max_priority) {
                param.sched_priority += 1;
                rc = sched_setscheduler(0, sched, & param);
                if (rc != 0) {
                    int error = errno;
                  __kmp_msg(
                      kmp_ms_warning,
                      KMP_MSG(CantChangeMonitorPriority),
                      KMP_ERR(error),
                      KMP_MSG(MonitorWillStarve),
                      __kmp_msg_null
                  );
                }; // if
            } else {
                // We cannot abort here, because number of CPUs may be enough for all the threads,
                // including the monitor thread, so application could potentially work...
                __kmp_msg(
                    kmp_ms_warning,
                    KMP_MSG(RunningAtMaxPriority),
                    KMP_MSG(MonitorWillStarve),
                    KMP_HNT(RunningAtMaxPriority),
                    __kmp_msg_null
                );
            }; // if
        }; // if
        TCW_4(__kmp_global.g.g_time.dt.t_value, 0); // AC: free thread that waits for
       monitor started
    }
    #endif // KMP_REAL_TIME_FIX
    KMP_MB(); /* Flush all pending memory write invalidates. */
    if (__kmp_monitor_wakeups == 1) {
        interval.tv_sec = 1;
        interval.tv_nsec = 0;
    } else {
        interval.tv_sec = 0;
        interval.tv_nsec = (KMP_NSEC_PER_SEC /
      __kmp_monitor_wakeups);
    }
    KA_TRACE(10, ("__kmp_launch_monitor: #2 monitor\n"));
    if (__kmp_yield_cycle) {
        __kmp_yielding_on = 0; /* Start out with yielding shut off */
        yield_count = __kmp_yield_off_count;
    } else {
        __kmp_yielding_on = 1; /* Yielding is on permanently */
    }
    while(! TCR_4(__kmp_global.g.g_done)) {
        struct timespec now;
        struct timeval tval;
        /* This thread monitors the state of the system */
        KA_TRACE(15, ("__kmp_launch_monitor: update\n"));
        status = gettimeofday(&tval, NULL);
        KMP_CHECK_SYSFAIL_ERRNO("gettimeofday", status);
        TIMEVAL_TO_TIMESPEC(&tval, &now);
        now.tv_sec += interval.tv_sec;
        now.tv_nsec += interval.tv_nsec;
        if (now.tv_nsec >= KMP_NSEC_PER_SEC) {
            now.tv_sec += 1;
            now.tv_nsec -= KMP_NSEC_PER_SEC;
        }
        status = pthread_mutex_lock(& __kmp_wait_mx.m_mutex);
        KMP_CHECK_SYSFAIL("pthread_mutex_lock", status);
        // AC: the monitor should not fall asleep if g_done has been set
        if (!TCR_4(__kmp_global.g.g_done)) { // check once more under mutex
            status = pthread_cond_timedwait(&__kmp_wait_cv.c_cond, &
      __kmp_wait_mx.m_mutex, &now);
            if (status != 0) {
                if (status != ETIMEDOUT && status != EINTR) {
                    KMP_SYSFAIL("pthread_cond_timedwait", status);
                };
            };
        };
        status = pthread_mutex_unlock(& __kmp_wait_mx.m_mutex);
        KMP_CHECK_SYSFAIL("pthread_mutex_unlock", status);
        if (__kmp_yield_cycle) {
            yield_cycles++;
            if ((yield_cycles % yield_count) == 0) {
                if (__kmp_yielding_on) {
                    __kmp_yielding_on = 0; /* Turn it off now */
                    yield_count = __kmp_yield_off_count;
                } else {
                    __kmp_yielding_on = 1; /* Turn it on now */
                    yield_count = __kmp_yield_on_count;
                }
                yield_cycles = 0;
            }
        } else {
            __kmp_yielding_on = 1;
        }
        TCW_4(__kmp_global.g.g_time.dt.t_value,
          TCR_4(__kmp_global.g.g_time.dt.t_value) + 1);
        KMP_MB(); /* Flush all pending memory write invalidates. */
    }
    KA_TRACE(10, ("__kmp_launch_monitor: #3 cleanup\n"));
#ifdef KMP_BLOCK_SIGNALS
    status = sigfillset(& new_set);
    KMP_CHECK_SYSFAIL_ERRNO("sigfillset", status);
    status = pthread_sigmask(SIG_UNBLOCK, & new_set, NULL);
    KMP_CHECK_SYSFAIL("pthread_sigmask", status);
#endif /* KMP_BLOCK_SIGNALS */
    KA_TRACE(10, ("__kmp_launch_monitor: #4 finished\n"));
    if(__kmp_global.g.g_abort != 0) {
        /* now we need to terminate the worker threads */
        /* the value of t_abort is the signal we caught */
        int gtid;
        KA_TRACE(10, ("__kmp_launch_monitor: #5 terminate sig=%d\n",
      __kmp_global.g.g_abort));
        /* terminate the OpenMP worker threads */
        /* TODO this is not valid for sibling threads!!
         * the uber master might not be 0 anymore.. */
        for (gtid = 1; gtid < __kmp_threads_capacity; ++gtid)
            __kmp_terminate_thread(gtid);
        __kmp_cleanup();
        KA_TRACE(10, ("__kmp_launch_monitor: #6 raise sig=%d\n",
      __kmp_global.g.g_abort));
        if (__kmp_global.g.g_abort > 0)
            raise(__kmp_global.g.g_abort);
    }
    KA_TRACE(10, ("__kmp_launch_monitor: #7 exit\n"));
    return thr;
}
static void* __kmp_launch_worker (void * thr) [static]
Definition at line 680 of file z_Linux_util.c.
Referenced by __kmp_create_worker().
{
    int status, old_type, old_state;
#ifdef KMP_BLOCK_SIGNALS
    sigset_t new_set, old_set;
#endif /* KMP_BLOCK_SIGNALS */
    void *exit_val;
#if KMP_OS_LINUX || KMP_OS_FREEBSD || KMP_OS_NETBSD
    void * volatile padding = 0;
#endif
    int gtid;
    gtid = ((kmp_info_t*)thr) -> th.th_info.ds.ds_gtid;
    __kmp_gtid_set_specific(gtid);
#ifdef KMP_TDATA_GTID
    __kmp_gtid = gtid;
#endif
#if KMP_STATS_ENABLED
    // set __thread local index to point to thread-specific stats
    __kmp_stats_thread_ptr = ((kmp_info_t*)thr)->th.th_stats;
#endif
#if USE_ITT_BUILD
    __kmp_itt_thread_name(gtid);
#endif /* USE_ITT_BUILD */
#if KMP_AFFINITY_SUPPORTED
    __kmp_affinity_set_init_mask(gtid, FALSE);
#endif
#ifdef KMP_CANCEL_THREADS
    status = pthread_setcanceltype(PTHREAD_CANCEL_ASYNCHRONOUS, & old_type);
    KMP_CHECK_SYSFAIL("pthread_setcanceltype", status);
    /* josh todo: isn't PTHREAD_CANCEL_ENABLE default for newly-created threads? */
    status = pthread_setcancelstate(PTHREAD_CANCEL_ENABLE, & old_state);
    KMP_CHECK_SYSFAIL("pthread_setcancelstate", status);
#endif
#if KMP_ARCH_X86 || KMP_ARCH_X86_64
    //
    // Set the FP control regs to be a copy of
    // the parallel initialization thread's.
    //
    __kmp_clear_x87_fpu_status_word();
    __kmp_load_x87_fpu_control_word(&__kmp_init_x87_fpu_control_word);
    __kmp_load_mxcsr(&__kmp_init_mxcsr);
#endif /* KMP_ARCH_X86 || KMP_ARCH_X86_64 */
#ifdef KMP_BLOCK_SIGNALS
    status = sigfillset(& new_set);
    KMP_CHECK_SYSFAIL_ERRNO("sigfillset", status);
    status = pthread_sigmask(SIG_BLOCK, & new_set, & old_set);
    KMP_CHECK_SYSFAIL("pthread_sigmask", status);
#endif /* KMP_BLOCK_SIGNALS */
#if KMP_OS_LINUX || KMP_OS_FREEBSD || KMP_OS_NETBSD
    if (__kmp_stkoffset > 0 && gtid > 0) {
        padding = KMP_oALLOCA(gtid * __kmp_stkoffset);
    }
#endif
    KMP_MB();
    __kmp_set_stack_info(gtid, (kmp_info_t*)thr);
    __kmp_check_stack_overlap((kmp_info_t*)thr);
    exit_val = __kmp_launch_thread((kmp_info_t *) thr);
#ifdef KMP_BLOCK_SIGNALS
    status = pthread_sigmask(SIG_SETMASK, & old_set, NULL);
    KMP_CHECK_SYSFAIL("pthread_sigmask", status);
#endif /* KMP_BLOCK_SIGNALS */
    return exit_val;
}
double __kmp_read_cpu_time (void)
Definition at line 1932 of file z_Linux_util.c.
{
    /*clock_t t;*/
    struct tms buffer;
    /*t =*/ times(& buffer);
    return (buffer.tms_utime + buffer.tms_cutime) / (double) CLOCKS_PER_SEC;
}
int __kmp_read_from_file (char const * path, char const * format, ...)
Definition at line 2062 of file z_Linux_util.c.
{
    int result;
    va_list args;
    va_start(args, format);
    FILE *f = fopen(path, "rb");
    if (f == NULL)
        return 0;
    result = vfscanf(f, format, args);
    fclose(f);
    return result;
}
int __kmp_read_system_info (struct kmp_sys_info * info)
Definition at line 1943 of file z_Linux_util.c.
{
    int status;
    struct rusage r_usage;
    memset(info, 0, sizeof(*info));
    status = getrusage(RUSAGE_SELF, &r_usage);
    KMP_CHECK_SYSFAIL_ERRNO("getrusage", status);
    info->maxrss = r_usage.ru_maxrss; /* the maximum resident set size utilized (in kilobytes)
      */
    info->minflt = r_usage.ru_minflt; /* the number of page faults serviced without any I/O
      */
    info->majflt = r_usage.ru_majflt; /* the number of page faults serviced that required I/O
      */
    info->nswap = r_usage.ru_nswap; /* the number of times a process was "swapped" out of memory
      */
    info->inblock = r_usage.ru_inblock; /* the number of times the file system had to perform input
       */
    info->oublock = r_usage.ru_oublock; /* the number of times the file system had to perform output
       */
    info->nvcsw = r_usage.ru_nvcsw; /* the number of times a context switch was voluntarily
      */
    info->nivcsw = r_usage.ru_nivcsw; /* the number of times a context switch was forced
      */
    return (status != 0);
}
void __kmp_read_system_time (double * delta)
Definition at line 1969 of file z_Linux_util.c.
{
    double t_ns;
    struct timeval tval;
    struct timespec stop;
    int status;
    status = gettimeofday(&tval, NULL);
    KMP_CHECK_SYSFAIL_ERRNO("gettimeofday", status);
    TIMEVAL_TO_TIMESPEC(&tval, &stop);
    t_ns = TS2NS(stop) - TS2NS(__kmp_sys_timer_data.
      start);
    *delta = (t_ns * 1e-9);
}
void __kmp_reap_monitor (kmp_info_t * th)
Definition at line 1246 of file z_Linux_util.c.
{
    int status;
    void *exit_val;
    KA_TRACE(10, ("__kmp_reap_monitor: try to reap monitor thread with handle %#.8lx\n",
                   th->th.th_info.ds.ds_thread));
    // If monitor has been created, its tid and gtid should be KMP_GTID_MONITOR.
    // If both tid and gtid are 0, it means the monitor did not ever start.
    // If both tid and gtid are KMP_GTID_DNE, the monitor has been shut down.
    KMP_DEBUG_ASSERT(th->th.th_info.ds.ds_tid == th->th.th_info.ds.ds_gtid);
    if (th->th.th_info.ds.ds_gtid != KMP_GTID_MONITOR) {
        KA_TRACE(10, ("__kmp_reap_monitor: monitor did not start, returning\n"));
        return;
    }; // if
    KMP_MB(); /* Flush all pending memory write invalidates. */
    /* First, check to see whether the monitor thread exists. This could prevent a hang,
       but if the monitor dies after the pthread_kill call and before the pthread_join
       call, it will still hang. */
    status = pthread_kill(th->th.th_info.ds.ds_thread, 0);
    if (status == ESRCH) {
        KA_TRACE(10, ("__kmp_reap_monitor: monitor does not exist, returning\n"));
    } else
    {
        __kmp_resume_monitor(); // Wake up the monitor thread
        status = pthread_join(th->th.th_info.ds.ds_thread, & exit_val);
        if (exit_val != th) {
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(ReapMonitorError),
                KMP_ERR(status),
                __kmp_msg_null
            );
        }
    }
    th->th.th_info.ds.ds_tid = KMP_GTID_DNE;
    th->th.th_info.ds.ds_gtid = KMP_GTID_DNE;
    KA_TRACE(10, ("__kmp_reap_monitor: done reaping monitor thread with handle %#.8lx\n",
                   th->th.th_info.ds.ds_thread));
    KMP_MB(); /* Flush all pending memory write invalidates. */
}
void __kmp_reap_worker (kmp_info_t * th)
Definition at line 1300 of file z_Linux_util.c.
{
    int status;
    void *exit_val;
    KMP_MB(); /* Flush all pending memory write invalidates. */
    KA_TRACE(10, ("__kmp_reap_worker: try to reap T#%d\n", th->th.th_info.ds.ds_gtid));
    /* First, check to see whether the worker thread exists. This could prevent a hang,
       but if the worker dies after the pthread_kill call and before the pthread_join
       call, it will still hang. */
    status = pthread_kill(th->th.th_info.ds.ds_thread, 0);
    if (status == ESRCH) {
        KA_TRACE(10, ("__kmp_reap_worker: worker T#%d does not exist, returning\n", th->th.th_info
      .ds.ds_gtid));
    }
    else {
        KA_TRACE(10, ("__kmp_reap_worker: try to join with worker T#%d\n", th->th.th_info.ds.
      ds_gtid));
        status = pthread_join(th->th.th_info.ds.ds_thread, & exit_val);
#ifdef KMP_DEBUG
        /* Don't expose these to the user until we understand when they trigger */
        if (status != 0) {
            __kmp_msg(kmp_ms_fatal, KMP_MSG(ReapWorkerError),
      KMP_ERR(status), __kmp_msg_null);
        }
        if (exit_val != th) {
            KA_TRACE(10, ("__kmp_reap_worker: worker T#%d did not reap properly, exit_val = %p\n"
      ,
                            th->th.th_info.ds.ds_gtid, exit_val));
        }
#endif /* KMP_DEBUG */
    }
    KA_TRACE(10, ("__kmp_reap_worker: done reaping T#%d\n", th->th.th_info.ds.ds_gtid));
    KMP_MB(); /* Flush all pending memory write invalidates. */
}
void __kmp_register_atfork (void)
Definition at line 1591 of file z_Linux_util.c.
Referenced by __kmp_do_serial_initialize().
                            {
    if (__kmp_need_register_atfork) {
        int status = pthread_atfork(__kmp_atfork_prepare,
      __kmp_atfork_parent, __kmp_atfork_child);
        KMP_CHECK_SYSFAIL("pthread_atfork", status);
        __kmp_need_register_atfork = FALSE;
    }
}
void __kmp_resume_32 (int target_gtid, kmp_flag_32 * flag)
Definition at line 1848 of file z_Linux_util.c.
                                                         {
    __kmp_resume_template(target_gtid, flag);
}
void __kmp_resume_64 (int target_gtid, kmp_flag_64 * flag)
Definition at line 1851 of file z_Linux_util.c.
                                                         {
    __kmp_resume_template(target_gtid, flag);
}
void __kmp_resume_monitor ()
Definition at line 1859 of file z_Linux_util.c.
Referenced by __kmp_reap_monitor().
{
    int status;
#ifdef KMP_DEBUG
    int gtid = TCR_4(__kmp_init_gtid) ? __kmp_get_gtid() : -1;
    KF_TRACE(30, ("__kmp_resume_monitor: T#%d wants to wakeup T#%d enter\n",
                    gtid, KMP_GTID_MONITOR));
    KMP_DEBUG_ASSERT(gtid != KMP_GTID_MONITOR);
#endif
    status = pthread_mutex_lock(&__kmp_wait_mx.m_mutex);
    KMP_CHECK_SYSFAIL("pthread_mutex_lock", status);
#ifdef DEBUG_SUSPEND
    {
        char buffer[128];
        __kmp_print_cond(buffer, &__kmp_wait_cv.c_cond);
        __kmp_printf("__kmp_resume_monitor: T#%d resuming T#%d: %s\n", gtid,
      KMP_GTID_MONITOR, buffer);
    }
#endif
    status = pthread_cond_signal(&__kmp_wait_cv.c_cond);
    KMP_CHECK_SYSFAIL("pthread_cond_signal", status);
    status = pthread_mutex_unlock(&__kmp_wait_mx.m_mutex);
    KMP_CHECK_SYSFAIL("pthread_mutex_unlock", status);
    KF_TRACE(30, ("__kmp_resume_monitor: T#%d exiting after signaling wake up for T#%d\n",
                    gtid, KMP_GTID_MONITOR));
}
void __kmp_resume_oncore (int target_gtid, kmp_flag_oncore * flag)
Definition at line 1854 of file z_Linux_util.c.
                                                                 {
    __kmp_resume_template(target_gtid, flag);
}
template<class C > static void __kmp_resume_template (int target_gtid, C * flag) [inline], [static]
Definition at line 1785 of file z_Linux_util.c.
Referenced by __kmp_resume_32(), __kmp_resume_64(), and __kmp_resume_oncore().
{
    KMP_TIME_DEVELOPER_BLOCK(USER_resume);
    kmp_info_t *th = __kmp_threads[target_gtid];
    int status;
#ifdef KMP_DEBUG
    int gtid = TCR_4(__kmp_init_gtid) ? __kmp_get_gtid() : -1;
#endif
    KF_TRACE(30, ("__kmp_resume_template: T#%d wants to wakeup T#%d enter\n", gtid, target_gtid)
       );
    KMP_DEBUG_ASSERT(gtid != target_gtid);
    __kmp_suspend_initialize_thread(th);
    status = pthread_mutex_lock(&th->th.th_suspend_mx.m_mutex);
    KMP_CHECK_SYSFAIL("pthread_mutex_lock", status);
    if (!flag) { // coming from __kmp_null_resume_wrapper
        flag = (C *)th->th.th_sleep_loc;
    }
    // First, check if the flag is null or its type has changed. If so, someone else woke it up.
    if (!flag || flag->get_type() != flag->get_ptr_type()) { // get_ptr_type simply shows what flag was
       cast to
        KF_TRACE(5, ("__kmp_resume_template: T#%d exiting, thread T#%d already awake: flag(%p)\n"
      ,
                       gtid, target_gtid, NULL));
        status = pthread_mutex_unlock(&th->th.th_suspend_mx.m_mutex);
        KMP_CHECK_SYSFAIL("pthread_mutex_unlock", status);
        return;
    }
    else { // if multiple threads are sleeping, flag should be internally referring to a specific thread
       here
        typename C::flag_t old_spin = flag->unset_sleeping();
        if (! flag->is_sleeping_val(old_spin)) {
            KF_TRACE(5, ("__kmp_resume_template: T#%d exiting, thread T#%d already awake:
       flag(%p): "
                           "%u => %u\n",
                           gtid, target_gtid, flag->get(), old_spin, *flag->get()));
            status = pthread_mutex_unlock(&th->th.th_suspend_mx.m_mutex);
            KMP_CHECK_SYSFAIL("pthread_mutex_unlock", status);
            return;
        }
        KF_TRACE(5, ("__kmp_resume_template: T#%d about to wakeup T#%d, reset sleep bit for
       flag's loc(%p): "
                       "%u => %u\n",
                       gtid, target_gtid, flag->get(), old_spin, *flag->get()));
    }
    TCW_PTR(th->th.th_sleep_loc, NULL);
#ifdef DEBUG_SUSPEND
    {
        char buffer[128];
        __kmp_print_cond(buffer, &th->th.th_suspend_cv);
        __kmp_printf("__kmp_resume_template: T#%d resuming T#%d: %s\n", gtid, target_gtid,
      buffer);
    }
#endif
    status = pthread_cond_signal(&th->th.th_suspend_cv.c_cond);
    KMP_CHECK_SYSFAIL("pthread_cond_signal", status);
    status = pthread_mutex_unlock(&th->th.th_suspend_mx.m_mutex);
    KMP_CHECK_SYSFAIL("pthread_mutex_unlock", status);
    KF_TRACE(30, ("__kmp_resume_template: T#%d exiting after signaling wake up for T#%d\n",
                    gtid, target_gtid));
}
void __kmp_runtime_destroy (void)
Definition at line 2144 of file z_Linux_util.c.
{
    int status;
    if (! __kmp_init_runtime) {
        return; // Nothing to do.
    };
#if USE_ITT_BUILD
    __kmp_itt_destroy();
#endif /* USE_ITT_BUILD */
    status = pthread_key_delete(__kmp_gtid_threadprivate_key);
    KMP_CHECK_SYSFAIL("pthread_key_delete", status);
    #ifdef BUILD_TV
        status = pthread_key_delete(__kmp_tv_key);
        KMP_CHECK_SYSFAIL("pthread_key_delete", status);
    #endif
    status = pthread_mutex_destroy(& __kmp_wait_mx.m_mutex);
    if (status != 0 && status != EBUSY) {
        KMP_SYSFAIL("pthread_mutex_destroy", status);
    }
    status = pthread_cond_destroy(& __kmp_wait_cv.c_cond);
    if (status != 0 && status != EBUSY) {
        KMP_SYSFAIL("pthread_cond_destroy", status);
    }
    #if KMP_AFFINITY_SUPPORTED
        __kmp_affinity_uninitialize();
    #endif
    __kmp_init_runtime = FALSE;
}
void __kmp_runtime_initialize (void)
Definition at line 2078 of file z_Linux_util.c.
{
    int status;
    pthread_mutexattr_t mutex_attr;
    pthread_condattr_t cond_attr;
    if (__kmp_init_runtime) {
        return;
    }; // if
    #if (KMP_ARCH_X86 || KMP_ARCH_X86_64)
        if (! __kmp_cpuinfo.initialized) {
            __kmp_query_cpuid(&__kmp_cpuinfo);
        }; // if
    #endif /* KMP_ARCH_X86 || KMP_ARCH_X86_64 */
    __kmp_xproc = __kmp_get_xproc();
    if (sysconf(_SC_THREADS)) {
        /* Query the maximum number of threads */
        __kmp_sys_max_nth = sysconf(_SC_THREAD_THREADS_MAX);
        if (__kmp_sys_max_nth == -1) {
            /* Unlimited threads for NPTL */
            __kmp_sys_max_nth = INT_MAX;
        }
        else if (__kmp_sys_max_nth <= 1) {
            /* Can't tell, just use PTHREAD_THREADS_MAX */
            __kmp_sys_max_nth = KMP_MAX_NTH;
        }
        /* Query the minimum stack size */
        __kmp_sys_min_stksize = sysconf(_SC_THREAD_STACK_MIN);
        if (__kmp_sys_min_stksize <= 1) {
            __kmp_sys_min_stksize = KMP_MIN_STKSIZE;
        }
    }
    /* Set up minimum number of threads to switch to TLS gtid */
    __kmp_tls_gtid_min = KMP_TLS_GTID_MIN;
    #ifdef BUILD_TV
        {
            int rc = pthread_key_create(& __kmp_tv_key, 0);
            KMP_CHECK_SYSFAIL("pthread_key_create", rc);
        }
    #endif
    status = pthread_key_create(&__kmp_gtid_threadprivate_key,
      __kmp_internal_end_dest);
    KMP_CHECK_SYSFAIL("pthread_key_create", status);
    status = pthread_mutexattr_init(& mutex_attr);
    KMP_CHECK_SYSFAIL("pthread_mutexattr_init", status);
    status = pthread_mutex_init(& __kmp_wait_mx.m_mutex, & mutex_attr);
    KMP_CHECK_SYSFAIL("pthread_mutex_init", status);
    status = pthread_condattr_init(& cond_attr);
    KMP_CHECK_SYSFAIL("pthread_condattr_init", status);
    status = pthread_cond_init(& __kmp_wait_cv.c_cond, & cond_attr);
    KMP_CHECK_SYSFAIL("pthread_cond_init", status);
#if USE_ITT_BUILD
    __kmp_itt_initialize();
#endif /* USE_ITT_BUILD */
    __kmp_init_runtime = TRUE;
}
static kmp_int32 __kmp_set_stack_info (int gtid, kmp_info_t * th) [static]
Definition at line 629 of file z_Linux_util.c.
Referenced by __kmp_create_worker(), __kmp_launch_monitor(), and __kmp_launch_worker().
{
    int stack_data;
#if KMP_OS_LINUX || KMP_OS_FREEBSD || KMP_OS_NETBSD
    /* Linux* OS only -- no pthread_getattr_np support on OS X* */
    pthread_attr_t attr;
    int status;
    size_t size = 0;
    void * addr = 0;
    /* Always do incremental stack refinement for ubermaster threads since the initial
       thread stack range can be reduced by sibling thread creation so pthread_attr_getstack
       may cause thread gtid aliasing */
    if (! KMP_UBER_GTID(gtid)) {
        /* Fetch the real thread attributes */
        status = pthread_attr_init(&attr);
        KMP_CHECK_SYSFAIL("pthread_attr_init", status);
#if KMP_OS_FREEBSD || KMP_OS_NETBSD
        status = pthread_attr_get_np(pthread_self(), &attr);
        KMP_CHECK_SYSFAIL("pthread_attr_get_np", status);
#else
        status = pthread_getattr_np(pthread_self(), &attr);
        KMP_CHECK_SYSFAIL("pthread_getattr_np", status);
#endif
        status = pthread_attr_getstack(&attr, &addr, &size);
        KMP_CHECK_SYSFAIL("pthread_attr_getstack", status);
        KA_TRACE(60, ("__kmp_set_stack_info: T#%d pthread_attr_getstack returned size: %lu, "
                        "low addr: %p\n",
                        gtid, size, addr));
        status = pthread_attr_destroy(&attr);
        KMP_CHECK_SYSFAIL("pthread_attr_destroy", status);
    }
    if (size != 0 && addr != 0) { /* was stack parameter determination successful? */
        /* Store the correct base and size */
        TCW_PTR(th->th.th_info.ds.ds_stackbase, (((char *)addr) + size));
        TCW_PTR(th->th.th_info.ds.ds_stacksize, size);
        TCW_4(th->th.th_info.ds.ds_stackgrow, FALSE);
        return TRUE;
    }
#endif /* KMP_OS_LINUX || KMP_OS_FREEBSD || KMP_OS_NETBSD */
    /* Use incremental refinement starting from initial conservative estimate */
    TCW_PTR(th->th.th_info.ds.ds_stacksize, 0);
    TCW_PTR(th -> th.th_info.ds.ds_stackbase, &stack_data);
    TCW_4(th->th.th_info.ds.ds_stackgrow, TRUE);
    return FALSE;
}
void __kmp_suspend_32 (int th_gtid, kmp_flag_32 * flag)
Definition at line 1769 of file z_Linux_util.c.
                                                      {
    __kmp_suspend_template(th_gtid, flag);
}
void __kmp_suspend_64 (int th_gtid, kmp_flag_64 * flag)
Definition at line 1772 of file z_Linux_util.c.
                                                      {
    __kmp_suspend_template(th_gtid, flag);
}
void __kmp_suspend_initialize (void)
Definition at line 1600 of file z_Linux_util.c.
{
    int status;
    status = pthread_mutexattr_init(&__kmp_suspend_mutex_attr);
    KMP_CHECK_SYSFAIL("pthread_mutexattr_init", status);
    status = pthread_condattr_init(&__kmp_suspend_cond_attr);
    KMP_CHECK_SYSFAIL("pthread_condattr_init", status);
}
static void __kmp_suspend_initialize_thread (kmp_info_t * th) [static]
Definition at line 1610 of file z_Linux_util.c.
Referenced by __kmp_resume_template(), and __kmp_suspend_template().
{
    if (th->th.th_suspend_init_count <= __kmp_fork_count) {
        /* this means we haven't initialized the suspension pthread objects for this thread
           in this instance of the process */
        int status;
        status = pthread_cond_init(&th->th.th_suspend_cv.c_cond, &
      __kmp_suspend_cond_attr);
        KMP_CHECK_SYSFAIL("pthread_cond_init", status);
        status = pthread_mutex_init(&th->th.th_suspend_mx.m_mutex, &
      __kmp_suspend_mutex_attr);
        KMP_CHECK_SYSFAIL("pthread_mutex_init", status);
        *(volatile int*)&th->th.th_suspend_init_count = __kmp_fork_count + 1;
    };
}
void __kmp_suspend_oncore (int th_gtid, kmp_flag_oncore * flag)
Definition at line 1775 of file z_Linux_util.c.
                                                              {
    __kmp_suspend_template(th_gtid, flag);
}
template<class C > static void __kmp_suspend_template (int th_gtid, C * flag) [inline], [static]
Definition at line 1649 of file z_Linux_util.c.
Referenced by __kmp_suspend_32(), __kmp_suspend_64(), and __kmp_suspend_oncore().
{
    KMP_TIME_DEVELOPER_BLOCK(USER_suspend);
    kmp_info_t *th = __kmp_threads[th_gtid];
    int status;
    typename C::flag_t old_spin;
    KF_TRACE(30, ("__kmp_suspend_template: T#%d enter for flag = %p\n", th_gtid, flag->get()));
    __kmp_suspend_initialize_thread(th);
    status = pthread_mutex_lock(&th->th.th_suspend_mx.m_mutex);
    KMP_CHECK_SYSFAIL("pthread_mutex_lock", status);
    KF_TRACE(10, ("__kmp_suspend_template: T#%d setting sleep bit for spin(%p)\n",
                    th_gtid, flag->get()));
    /* TODO: shouldn't this use release semantics to ensure that __kmp_suspend_initialize_thread
       gets called first?
    */
    //hash: where else is the sleep bit used?
    old_spin = flag->set_sleeping();
    KF_TRACE(5, ("__kmp_suspend_template: T#%d set sleep bit for spin(%p)==%x, was %x\n",
                   th_gtid, flag->get(), *(flag->get()), old_spin));
    if (flag->done_check_val(old_spin)) {
        old_spin = flag->unset_sleeping();
        KF_TRACE(5, ("__kmp_suspend_template: T#%d false alarm, reset sleep bit for spin(%p)\n",
                       th_gtid, flag->get()));
    } else {
        /* Encapsulate in a loop as the documentation states that this may
         * "with low probability" return when the condition variable has
         * not been signaled or broadcast
         */
        int deactivated = FALSE;
        TCW_PTR(th->th.th_sleep_loc, (void *)flag);
        while (flag->is_sleeping()) {
#ifdef DEBUG_SUSPEND
            char buffer[128];
            __kmp_suspend_count++;
            __kmp_print_cond(buffer, &th->th.th_suspend_cv);
            __kmp_printf("__kmp_suspend_template: suspending T#%d: %s\n", th_gtid, buffer);
#endif
            // Mark the thread as no longer active (only in the first iteration of the loop).
            if (! deactivated) {
                th->th.th_active = FALSE;
                if (th->th.th_active_in_pool) {
                    th->th.th_active_in_pool = FALSE;
                    KMP_TEST_THEN_DEC32(
                      (kmp_int32 *) &__kmp_thread_pool_active_nth);
                    KMP_DEBUG_ASSERT(TCR_4(
      __kmp_thread_pool_active_nth) >= 0);
                }
                deactivated = TRUE;
            }
#if USE_SUSPEND_TIMEOUT
            struct timespec now;
            struct timeval tval;
            int msecs;
            status = gettimeofday(&tval, NULL);
            KMP_CHECK_SYSFAIL_ERRNO("gettimeofday", status);
            TIMEVAL_TO_TIMESPEC(&tval, &now);
            msecs = (4*__kmp_dflt_blocktime) + 200;
            now.tv_sec += msecs / 1000;
            now.tv_nsec += (msecs % 1000)*1000;
            KF_TRACE(15, ("__kmp_suspend_template: T#%d about to perform pthread_cond_timedwait\n
      ",
                            th_gtid));
            status = pthread_cond_timedwait(&th->th.th_suspend_cv.c_cond, &th->th.th_suspend_mx.m_mutex, &
       now);
#else
            KF_TRACE(15, ("__kmp_suspend_template: T#%d about to perform pthread_cond_wait\n",
                            th_gtid));
            status = pthread_cond_wait(&th->th.th_suspend_cv.c_cond, &th->th.th_suspend_mx.m_mutex);
#endif
            if ((status != 0) && (status != EINTR) && (status != ETIMEDOUT)) {
                KMP_SYSFAIL("pthread_cond_wait", status);
            }
#ifdef KMP_DEBUG
            if (status == ETIMEDOUT) {
                if (flag->is_sleeping()) {
                    KF_TRACE(100, ("__kmp_suspend_template: T#%d timeout wakeup\n", th_gtid));
                } else {
                    KF_TRACE(2, ("__kmp_suspend_template: T#%d timeout wakeup, sleep bit not set!
      \n",
                                   th_gtid));
                }
            } else if (flag->is_sleeping()) {
                KF_TRACE(100, ("__kmp_suspend_template: T#%d spurious wakeup\n", th_gtid));
            }
#endif
        } // while
        // Mark the thread as active again (if it was previous marked as inactive)
        if (deactivated) {
            th->th.th_active = TRUE;
            if (TCR_4(th->th.th_in_pool)) {
                KMP_TEST_THEN_INC32((kmp_int32 *) &
      __kmp_thread_pool_active_nth);
                th->th.th_active_in_pool = TRUE;
            }
        }
    }
#ifdef DEBUG_SUSPEND
    {
        char buffer[128];
        __kmp_print_cond(buffer, &th->th.th_suspend_cv);
        __kmp_printf("__kmp_suspend_template: T#%d has awakened: %s\n", th_gtid, buffer);
    }
#endif
    status = pthread_mutex_unlock(&th->th.th_suspend_mx.m_mutex);
    KMP_CHECK_SYSFAIL("pthread_mutex_unlock", status);
    KF_TRACE(30, ("__kmp_suspend_template: T#%d exit\n", th_gtid));
}
void __kmp_suspend_uninitialize_thread (kmp_info_t * th)
Definition at line 1625 of file z_Linux_util.c.
{
    if(th->th.th_suspend_init_count > __kmp_fork_count) {
        /* this means we have initialize the suspension pthread objects for this thread
           in this instance of the process */
        int status;
        status = pthread_cond_destroy(&th->th.th_suspend_cv.c_cond);
        if (status != 0 && status != EBUSY) {
            KMP_SYSFAIL("pthread_cond_destroy", status);
        };
        status = pthread_mutex_destroy(&th->th.th_suspend_mx.m_mutex);
        if (status != 0 && status != EBUSY) {
            KMP_SYSFAIL("pthread_mutex_destroy", status);
        };
        --th->th.th_suspend_init_count;
        KMP_DEBUG_ASSERT(th->th.th_suspend_init_count ==
      __kmp_fork_count);
    }
}
void __kmp_terminate_thread (int gtid)
Definition at line 592 of file z_Linux_util.c.
Referenced by __kmp_launch_monitor().
{
    int status;
    kmp_info_t *th = __kmp_threads[ gtid ];
    if (!th) return;
    #ifdef KMP_CANCEL_THREADS
        KA_TRACE(10, ("__kmp_terminate_thread: kill (%d)\n", gtid));
        status = pthread_cancel(th->th.th_info.ds.ds_thread);
        if (status != 0 && status != ESRCH) {
            __kmp_msg(
                kmp_ms_fatal,
                KMP_MSG(CantTerminateWorkerThread),
                KMP_ERR(status),
                __kmp_msg_null
            );
        }; // if
    #endif
    __kmp_yield(TRUE);
} //
void __kmp_thread_sleep (int millis)
Definition at line 2182 of file z_Linux_util.c.
{
    sleep((millis + 500) / 1000);
}
void __kmp_yield (int cond)
Definition at line 1889 of file z_Linux_util.c.
Referenced by __kmp_terminate_thread().
{
    if (cond && __kmp_yielding_on) {
        sched_yield();
    }
}
Variable Documentation
int __kmp_fork_count = 0 [static]
Definition at line 81 of file z_Linux_util.c.
Referenced by __kmp_atfork_child(), __kmp_suspend_initialize_thread(), and __kmp_suspend_uninitialize_thread().
int __kmp_init_runtime = FALSE [static]
Definition at line 79 of file z_Linux_util.c.
Referenced by __kmp_atfork_child(), __kmp_gtid_get_specific(), __kmp_gtid_set_specific(), __kmp_runtime_destroy(), and __kmp_runtime_initialize().
pthread_condattr_t __kmp_suspend_cond_attr [static]
Definition at line 83 of file z_Linux_util.c.
Referenced by __kmp_suspend_initialize(), and __kmp_suspend_initialize_thread().
pthread_mutexattr_t __kmp_suspend_mutex_attr [static]
Definition at line 84 of file z_Linux_util.c.
Referenced by __kmp_suspend_initialize(), and __kmp_suspend_initialize_thread().
struct kmp_sys_timer __kmp_sys_timer_data [static]
Definition at line 71 of file z_Linux_util.c.
Referenced by __kmp_clear_system_time(), and __kmp_read_system_time().
kmp_cond_align_t __kmp_wait_cv [static]
Definition at line 86 of file z_Linux_util.c.
Referenced by __kmp_launch_monitor(), __kmp_resume_monitor(), __kmp_runtime_destroy(), and __kmp_runtime_initialize().
kmp_mutex_align_t __kmp_wait_mx [static]
Definition at line 87 of file z_Linux_util.c.
Referenced by __kmp_launch_monitor(), __kmp_resume_monitor(), __kmp_runtime_destroy(), and __kmp_runtime_initialize().